# Generated by resources/tools/import_reference.py.
# GameFramework_EXCLUDE: reference compile units left out of the module target (tests, tools).
# GameFramework_NOT_IN_PDB: compiled, but the Shipping PDB attributes no function to them; verify in P2.7.
set(GameFramework_EXCLUDE
)
set(GameFramework_NOT_IN_PDB
  Src/DebugCameraController.cpp
  Src/GameMobile.cpp
  Src/GameMobileKismet.cpp
  Src/GameSpecialMoves.cpp
  Src/SecondaryViewportClient.cpp
)
