// AkAudio/src/akaudioclasses.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (103):
//   0x5f4d70  public: static void __cdecl UAkComponent::InitializePrivateStaticClassUAkComponent(void)
//   0x5f4d90  public: static void __cdecl UInterpTrackAkEvent::InitializePrivateStaticClassUInterpTrackAkEvent(void)
//   0x5f4db0  public: static void __cdecl UInterpTrackAkRTPC::InitializePrivateStaticClassUInterpTrackAkRTPC(void)
//   0x5f4dd0  public: static void __cdecl UInterpTrackInstAkEvent::InitializePrivateStaticClassUInterpTrackInstAkEvent(void)
//   0x5f4df0  public: static void __cdecl UInterpTrackInstAkRTPC::InitializePrivateStaticClassUInterpTrackInstAkRTPC(void)
//   0x5f4e10  public: static void __cdecl USeqAct_AkClearBanks::InitializePrivateStaticClassUSeqAct_AkClearBanks(void)
//   0x5f4e30  public: static void __cdecl USeqAct_AkPostTrigger::InitializePrivateStaticClassUSeqAct_AkPostTrigger(void)
//   0x5f4e50  public: static void __cdecl USeqAct_AkSetState::InitializePrivateStaticClassUSeqAct_AkSetState(void)
//   0x5f4e70  public: static void __cdecl USeqAct_AkSetSwitch::InitializePrivateStaticClassUSeqAct_AkSetSwitch(void)
//   0x5f4e90  public: static void __cdecl USeqAct_AkStopAll::InitializePrivateStaticClassUSeqAct_AkStopAll(void)
//   0x5f4eb0  public: static void __cdecl USeqAct_AkLoadBank::InitializePrivateStaticClassUSeqAct_AkLoadBank(void)
//   0x5f4ed0  public: static void __cdecl USeqAct_AkPostEvent::InitializePrivateStaticClassUSeqAct_AkPostEvent(void)
//   0x5f4ef0  public: static void __cdecl USeqAct_AkSetRTPCValue::InitializePrivateStaticClassUSeqAct_AkSetRTPCValue(void)
//   0x5f4f10  public: static void __cdecl AAkAmbientSound::InitializePrivateStaticClassAAkAmbientSound(void)
//   0x5f4f30  public: static void __cdecl UActorFactoryAkAmbientSound::InitializePrivateStaticClassUActorFactoryAkAmbientSound(void)
//   0x5f4f50  public: static void __cdecl USeqAct_AkStartAmbientSound::InitializePrivateStaticClassUSeqAct_AkStartAmbientSound(void)
//   0x5f4f70  public: static void __cdecl UInterpTrackAkEventKeyProperties::InitializePrivateStaticClassUInterpTrackAkEventKeyProperties(void)
//   0x5f4f90  AkBankCallback
//   0x5f4fb0  public: virtual unsigned int __thiscall USeqAct_AkLoadBank::UpdateOp(float)
//   0x5f4fd0  public: virtual void __thiscall USeqAct_AkLoadBank::BeginDestroy(void)
//   0x5f5000  AkCallback
//   0x5f5060  public: virtual void __thiscall USeqAct_AkPostEvent::GameSave(class FArchive &, enum ESaveLoadLocation)
//   0x5f50a0  AkAmbientSoundCallback
//   0x5f50d0  protected: virtual void __thiscall AAkAmbientSound::UpdateComponentsInternal(unsigned int)
//   0x5f50e0  public: void __thiscall AAkAmbientSound::StartPlayback(void)
//   0x5f5140  public: void __thiscall AAkAmbientSound::StopPlayback(void)
//   0x5f5170  public: virtual void __thiscall ADishonoredPawn::FinishDestroy(void)
//   0x5f5180  public: virtual unsigned int __thiscall AAkAmbientSound::IsSaveable(enum ESaveLoadLocation)const
//   0x5f51a0  public: virtual void __thiscall AAkAmbientSound::GameSave(class FArchive &, enum ESaveLoadLocation)
//   0x5f51f0  public: virtual void __thiscall AAkAmbientSound::GameLoad(class FArchive &, enum ESaveLoadLocation)
//   0x5f5240  public: virtual void __thiscall AAkAmbientSoundMovable::PostBeginPlay(void)
//   0x5f5d10  public: static class UClass * __cdecl UInterpTrackInstAkRTPC::GetPrivateStaticClassUInterpTrackInstAkRTPC(wchar_t const *)
//   0x5f5da0  public: static class UClass * __cdecl UInterpTrackAkEventKeyProperties::GetPrivateStaticClassUInterpTrackAkEventKeyProperties(wchar_t const *)
//   0x5f5e30  public: virtual void __thiscall UInterpTrackInstAkEvent::InitTrackInst(class UInterpTrack *)
//   0x5f5e50  public: virtual void __thiscall USeqAct_AkPostEvent::FinishDestroy(void)
//   0x5f5ea0  public: virtual void __thiscall USeqAct_AkSetState::Activated(void)
//   0x5f5f10  public: virtual class AActor * __thiscall UActorFactoryAkAmbientSound::CreateActor(class FVector const * const, class FRotator const * const, class USeqAct_ActorFactory const * const)
//   0x5f5f70  public: virtual unsigned int __thiscall UActorFactoryAkAmbientSound::CanCreateActor(class FString &, unsigned int)
//   0x5f6520  public: static class UClass * __cdecl UInterpTrackInstAkRTPC::StaticClassNoInline(void)
//   0x5f6550  public: static class UClass * __cdecl UInterpTrackAkEventKeyProperties::StaticClassNoInline(void)
//   0x5f6580  public: virtual unsigned int __thiscall UInterpTrackAIControl::GetClosestSnapPosition(float, class TArray<int, class FDefaultAllocator> &, float &)
//   0x5f66c0  public: struct FAkEventTrackKey & __thiscall UInterpTrackAkEvent::GetAkEventKeyAtPosition(float)
//   0x5f6780  public: virtual class UObject * __thiscall UInterpTrackAkEvent::GetKeyProperties(int)
//   0x5f67d0  public: virtual void __thiscall UInterpTrackInstAkEvent::TermTrackInst(class UInterpTrack *)
//   0x5f6840  public: virtual void __thiscall USeqAct_AkLoadBank::Activated(void)
//   0x5f6970  public: virtual void __thiscall USeqAct_AkSetRTPCValue::Activated(void)
//   0x5f6f10  public: static class UClass * __cdecl UActorFactoryAkAmbientSound::GetPrivateStaticClassUActorFactoryAkAmbientSound(wchar_t const *)
//   0x5f6fa0  public: void __thiscall UAkComponent::Stop(void)
//   0x5f7060  public: virtual void __thiscall UInterpTrackAkEvent::PostLoad(void)
//   0x5f7160  public: virtual int __thiscall UInterpTrackAkEvent::AddKeyframe(float, class UInterpTrackInst *, enum EInterpCurveMode)
//   0x5f72b0  public: virtual int __thiscall UInterpTrackAkRTPC::AddKeyframe(float, class UInterpTrackInst *, enum EInterpCurveMode)
//   0x5f7350  public: virtual void __thiscall UActorFactoryAkAmbientSound::AutoFillFields(class USelection *)
//   0x5f7380  public: virtual class FString __thiscall UActorFactoryAkAmbientSound::GetMenuName(void)
//   0x5f7900  public: static class UClass * __cdecl UInterpTrackInstAkEvent::GetPrivateStaticClassUInterpTrackInstAkEvent(wchar_t const *)
//   0x5f7990  public: static class UClass * __cdecl UActorFactoryAkAmbientSound::StaticClassNoInline(void)
//   0x5f7d20  public: static class UClass * __cdecl UAkComponent::GetPrivateStaticClassUAkComponent(wchar_t const *)
//   0x5f7db0  public: static class UClass * __cdecl UInterpTrackInstAkEvent::StaticClassNoInline(void)
//   0x5f7fd0  public: static class UClass * __cdecl UAkComponent::StaticClassNoInline(void)
//   0x5f8000  public: static class UClass * __cdecl AAkAmbientSound::GetPrivateStaticClassAAkAmbientSound(wchar_t const *)
//   0x5f8090  public: static class UClass * __cdecl AAkAmbientSoundMovable::GetPrivateStaticClassAAkAmbientSoundMovable(wchar_t const *)
//   0x5f8120  public: virtual void __thiscall USeqAct_AkClearBanks::Activated(void)
//   0x5f85e0  public: static class UClass * __cdecl AAkAmbientSound::StaticClassNoInline(void)
//   0x5f8610  public: static void __cdecl AAkAmbientSoundMovable::InitializePrivateStaticClassAAkAmbientSoundMovable(void)
//   0x5f8b40  public: static class UClass * __cdecl UInterpTrackAkEvent::GetPrivateStaticClassUInterpTrackAkEvent(wchar_t const *)
//   0x5f8bd0  public: static class UClass * __cdecl UInterpTrackAkRTPC::GetPrivateStaticClassUInterpTrackAkRTPC(wchar_t const *)
//   0x5f8c60  public: static class UClass * __cdecl AAkAmbientSoundMovable::StaticClassNoInline(void)
//   0x5f8c90  public: virtual void __thiscall UAkComponent::Detach(unsigned int)
//   0x5f8cf0  public: virtual void __thiscall UAkComponent::FinishDestroy(void)
//   0x5f8dc0  public: virtual void __thiscall UAkComponent::ShutdownAfterError(void)
//   0x5f9b20  public: static class UClass * __cdecl UInterpTrackAkEvent::StaticClassNoInline(void)
//   0x5f9b50  public: static class UClass * __cdecl UInterpTrackAkRTPC::StaticClassNoInline(void)
//   0x5f9b80  public: virtual void __thiscall UAkComponent::Attach(void)
//   0x5f9bd0  public: virtual void __thiscall USeqAct_AkStartAmbientSound::Activated(void)
//   0x5f9f50  public: void __thiscall AAkAmbientSound::StopEvent(void)
//   0x5fa610  public: static class UClass * __cdecl USeqAct_AkClearBanks::GetPrivateStaticClassUSeqAct_AkClearBanks(wchar_t const *)
//   0x5fa6a0  public: static class UClass * __cdecl USeqAct_AkPostTrigger::GetPrivateStaticClassUSeqAct_AkPostTrigger(wchar_t const *)
//   0x5fa730  public: static class UClass * __cdecl USeqAct_AkSetState::GetPrivateStaticClassUSeqAct_AkSetState(wchar_t const *)
//   0x5fa7c0  public: static class UClass * __cdecl USeqAct_AkSetSwitch::GetPrivateStaticClassUSeqAct_AkSetSwitch(wchar_t const *)
//   0x5fa850  public: static class UClass * __cdecl USeqAct_AkStopAll::GetPrivateStaticClassUSeqAct_AkStopAll(wchar_t const *)
//   0x5fa8e0  public: static class UClass * __cdecl USeqAct_AkLoadBank::GetPrivateStaticClassUSeqAct_AkLoadBank(wchar_t const *)
//   0x5fa970  public: static class UClass * __cdecl USeqAct_AkPostEvent::GetPrivateStaticClassUSeqAct_AkPostEvent(wchar_t const *)
//   0x5faa00  public: static class UClass * __cdecl USeqAct_AkSetRTPCValue::GetPrivateStaticClassUSeqAct_AkSetRTPCValue(wchar_t const *)
//   0x5faa90  public: static class UClass * __cdecl USeqAct_AkStartAmbientSound::GetPrivateStaticClassUSeqAct_AkStartAmbientSound(wchar_t const *)
//   0x5fab20  public: virtual void __thiscall UInterpTrackAkRTPC::UpdateTrack(float, class UInterpTrackInst *, unsigned int)
//   0x5fabf0  public: virtual void __thiscall USeqAct_AkPostTrigger::Activated(void)
//   0x5fad80  private: void __thiscall USeqAct_AkSetRTPCValue::SetRTPCValue(void)
//   0x5faf70  public: virtual void __thiscall USeqAct_AkSetSwitch::Activated(void)
//   0x5fb170  public: virtual void __thiscall USeqAct_AkStopAll::Activated(void)
//   0x5fb840  public: static class UClass * __cdecl USeqAct_AkClearBanks::StaticClassNoInline(void)
//   0x5fb870  public: static class UClass * __cdecl USeqAct_AkPostTrigger::StaticClassNoInline(void)
//   0x5fb8a0  public: static class UClass * __cdecl USeqAct_AkSetState::StaticClassNoInline(void)
//   0x5fb8d0  public: static class UClass * __cdecl USeqAct_AkSetSwitch::StaticClassNoInline(void)
//   0x5fb900  public: static class UClass * __cdecl USeqAct_AkStopAll::StaticClassNoInline(void)
//   0x5fb930  public: static class UClass * __cdecl USeqAct_AkLoadBank::StaticClassNoInline(void)
//   0x5fb960  public: static class UClass * __cdecl USeqAct_AkPostEvent::StaticClassNoInline(void)
//   0x5fb990  public: static class UClass * __cdecl USeqAct_AkSetRTPCValue::StaticClassNoInline(void)
//   0x5fb9c0  public: static class UClass * __cdecl USeqAct_AkStartAmbientSound::StaticClassNoInline(void)
//   0x5fb9f0  public: virtual void __thiscall UInterpTrackInstAkEvent::UpdateTrackInst(float, unsigned int)
//   0x5fbc40  private: void __thiscall USeqAct_AkPostEvent::PlayEventOnTargets(void)
//   0x5fbdf0  public: virtual unsigned int __thiscall USeqAct_AkSetRTPCValue::UpdateOp(float)
//   0x5fbe60  public: void __thiscall AAkAmbientSound::StartEvent(void)
//   0x5fc0e0  public: virtual void __thiscall USeqAct_AkPostEvent::Activated(void)
//   0x5fc130  public: virtual unsigned int __thiscall USeqAct_AkPostEvent::UpdateOp(float)
