// AkAudioNativeStubs.cpp - exec bodies of the retail AkAudio natives, not ported yet: every one consumes its
// parameters, zeroes its result and warns once (DISHONORED_NATIVE_STUB, Core/Inc/DishonoredNativeStub.h; -strictnatives aborts).
// Generated by resources/tools/symbols/gen_classes_header.py --sdk. Port a native by moving its body into the module's own
// source (and removing it here); the generator skips natives listed in <Module>NativeStubs.ported.txt.
#include "AkAudio.h"
#include "DishonoredNativeStub.h"

