// AkAudio/src/akaudiodevice.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (43):
//   0x5f53f0  void * __cdecl FxAllocateUE3(unsigned int)
//   0x5f5410  void __cdecl AK::FreeHook(void *)
//   0x5f5420  void * __cdecl AK::VirtualAllocHook(void *, unsigned int, unsigned long, unsigned long)
//   0x5f5440  void __cdecl AK::VirtualFreeHook(void *, unsigned int, unsigned long)
//   0x5f5460  public: static void __cdecl UAkAudioDevice::InitializePrivateStaticClassUAkAudioDevice(void)
//   0x5f5480  public: virtual void __thiscall UAkAudioDevice::Update(unsigned int)
//   0x5f54b0  public: void __thiscall UAkAudioDevice::SetListener(int, class FVector const &, class FVector const &, class FVector const &, class FVector const &)
//   0x5f5560  public: enum AKRESULT __thiscall UAkAudioDevice::PrepareEvent(enum AK::SoundEngine::PreparationType, unsigned long, void (__cdecl *)(unsigned long, enum AKRESULT, long, void *), void *)
//   0x5f5590  public: enum AKRESULT __thiscall UAkAudioDevice::UnloadBank(wchar_t const *, long *)
//   0x5f55b0  public: enum AKRESULT __thiscall UAkAudioDevice::UnloadBank(wchar_t const *, void (__cdecl *)(unsigned long, enum AKRESULT, long, void *), void *)
//   0x5f55d0  public: enum AKRESULT __thiscall UAkAudioDevice::SetState(wchar_t const *, wchar_t const *)
//   0x5f55f0  public: static class UAkAudioDevice * __cdecl UAkAudioDevice::Get(void)
//   0x5f5620  wchar_t const * __cdecl AkGetLanguage(wchar_t const *)
//   0x5f6ad0  protected: void __thiscall UAkAudioDevice::SetBankDirectory(void)
//   0x5f79c0  public: enum AKRESULT __thiscall UAkAudioDevice::UnloadFilePackage(unsigned long)
//   0x5f7de0  public: enum AKRESULT __thiscall UAkAudioDevice::ClearBanks(void)
//   0x5f7e20  public: enum AKRESULT __thiscall UAkAudioDevice::LoadFilePackage(wchar_t const *, unsigned long &)
//   0x5f8630  protected: bool __thiscall UAkAudioDevice::EnsureInitialized(int)
//   0x5f8960  public: virtual unsigned int __thiscall UAkAudioDevice::Init(void)
//   0x5f8970  public: enum AKRESULT __thiscall UAkAudioDevice::PrepareBank(enum AK::SoundEngine::PreparationType, wchar_t const *, enum AK::SoundEngine::AkBankContent)
//   0x5f89a0  public: enum AKRESULT __thiscall UAkAudioDevice::LoadBank(wchar_t const *, long, unsigned long &)
//   0x5f89d0  public: enum AKRESULT __thiscall UAkAudioDevice::LoadBank(wchar_t const *, void (__cdecl *)(unsigned long, enum AKRESULT, long, void *), void *, long, unsigned long &)
//   0x5f8a00  public: void __thiscall UAkAudioDevice::LoadAllReferencedBanks(void)
//   0x5f8e10  public: void __thiscall UAkAudioDevice::RegisterComponent(class UAkComponent *)
//   0x5f8e40  public: class UAkComponent * __thiscall UAkAudioDevice::GetAkComponent(class AActor *, class FName, bool)
//   0x5f8fa0  public: void __thiscall UAkAudioDevice::Flush(class FSceneInterface *)
//   0x5f9fb0  protected: void __thiscall UAkAudioDevice::Teardown(void)
//   0x5fa020  public: void __thiscall UAkAudioDevice::AddBaseDirectory(class FString const &, class TArray<class FString, class FDefaultAllocator> const &)
//   0x5fa1c0  public: virtual void __thiscall UAkAudioDevice::FinishDestroy(void)
//   0x5fa1e0  public: virtual void __thiscall UAkAudioDevice::ShutdownAfterError(void)
//   0x5fa200  public: void __thiscall UAkAudioDevice::StopAllSounds(unsigned int)
//   0x5fa220  public: enum AKRESULT __thiscall UAkAudioDevice::SeekOnEvent(class FString const &, class AActor *, class FName, long)
//   0x5fa2a0  public: unsigned long __thiscall UAkAudioDevice::PostEvent(unsigned long, float const &, class AActor *, class FName, unsigned long, void (__cdecl *)(enum AkCallbackType, struct AkCallbackInfo *), void *, bool)
//   0x5fa3a0  public: enum AKRESULT __thiscall UAkAudioDevice::PostTrigger(wchar_t const *, class AActor *, class FName)
//   0x5fa3e0  public: enum AKRESULT __thiscall UAkAudioDevice::SetRTPCValue(wchar_t const *, float, class AActor *, class FName)
//   0x5fa430  public: enum AKRESULT __thiscall UAkAudioDevice::SetSwitch(wchar_t const *, wchar_t const *, class AActor *, class FName)
//   0x5fb1b0  public: static class UClass * __cdecl UAkAudioDevice::GetPrivateStaticClassUAkAudioDevice(wchar_t const *)
//   0x5fb240  public: void __thiscall UAkAudioDevice::RemoveAllAdditionalDirectories(void)
//   0x5fb250  public: unsigned long __thiscall UAkAudioDevice::PostEvent(class UAkEvent *, class AActor *, class FName, unsigned long, void (__cdecl *)(enum AkCallbackType, struct AkCallbackInfo *), void *, bool)
//   0x5fb2b0  public: unsigned long __thiscall UAkAudioDevice::PostEvent(class FString const &, float const &, class AActor *, class FName, unsigned long, void (__cdecl *)(enum AkCallbackType, struct AkCallbackInfo *), void *, bool)
//   0x5fbf10  public: static class UClass * __cdecl UAkAudioDevice::StaticClassNoInline(void)
//   0x5fc220  public: void __thiscall UAkAudioDevice::ApplyGameSettings(class ArkSettingsParameters const &, enum IArkSettingsListenerInterface::EChangeReason)
//   0xba2fa0  _dynamic_initializer_for__g_lowLevelIO__
