// DishonoredGame/src/disaisubstate.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (30):
//   0x765250  public: static void __cdecl UDisAISubState::InitializePrivateStaticClassUDisAISubState(void)
//   0x765270  public: static void __cdecl UDisTweaks_AISubState::InitializePrivateStaticClassUDisTweaks_AISubState(void)
//   0x768420  public: __thiscall FDisAISubState_Param::FDisAISubState_Param(void)
//   0x768440  public: virtual void __thiscall FDisAISubState_Param::OnPending(class UDishonoredNativeState *, class UObject *)
//   0x768470  public: unsigned int __thiscall UDisAISubState::ArePreconditionsMet(struct FDisNativeStateParam &)
//   0x7684a0  public: virtual void __thiscall UDisAISubState::TickState(float)
//   0x768530  protected: virtual void __thiscall UDisAISubState::RequestStateExit_Derived(void)
//   0x768560  public: void __thiscall UDisAISubState::OnOwningBehaviorResume(struct FDisBodyIntention const &)
//   0x7685b0  public: void __thiscall UDisAISubState::OnOwningBehaviorPause(unsigned int)
//   0x768600  public: virtual void __thiscall UDisAISubState::RefreshSubState(float)
//   0x768640  protected: virtual void __thiscall UDisAISubState::PostGameLoad(enum ESaveLoadLocation)
//   0x770750  public: void __thiscall UDisAISubState::RegisterDelegate_OnEnterCallback(class UObject *, class FString const &)
//   0x770830  public: void __thiscall UDisAISubState::RegisterDelegate_TickCallback(class UObject *, class FString const &)
//   0x770910  public: void __thiscall UDisAISubState::RegisterDelegate_OnExitCallback(class UObject *, class FString const &)
//   0x7709f0  public: void __thiscall UDisAISubState::RegisterDelegate_OnResetCallback(class UObject *, class FString const &)
//   0x7731a0  public: static class UClass * __cdecl UDisAISubState::GetPrivateStaticClassUDisAISubState(wchar_t const *)
//   0x773230  public: void __thiscall UDisAISubState::RegisterDelegate_RefreshCallback(class UDishonoredAIBehavior * const)
//   0x773370  public: void __thiscall UDisAISubState::RegisterDelegate_RequestStateExitCallback(class UDishonoredAIBehavior * const)
//   0x7734b0  private: virtual void __thiscall UDisAISubState::GameSave(class FArchive &, enum ESaveLoadLocation)
//   0x7734e0  private: virtual void __thiscall UDisAISubState::GameLoad(class FArchive &, enum ESaveLoadLocation)
//   0x7750a0  public: static class UClass * __cdecl UDisAISubState::StaticClassNoInline(void)
//   0x7750d0  public: void __thiscall UDisAISubState::InitSubState(class UDishonoredAIBehavior * const, class UDisTweaks_AISubState * const)
//   0x777300  protected: void __thiscall UDisAISubState::SetActionTargetProxy(struct FDisAttentionProxy)
//   0x777390  public: virtual void __thiscall UDisAISubState::BeginDestroy(void)
//   0x7773d0  protected: void __thiscall UDisAISubState::ClearActionTargetProxy(void)
//   0x77b5f0  public: virtual void __thiscall UDisAISubState::OnEnterState(class UDishonoredNativeState *)
//   0x77b6a0  public: virtual void __thiscall UDisAISubState::OnExitState(class UDishonoredNativeState *)
//   0x77b810  public: virtual unsigned int __thiscall UDisAISubState::OnResetState(void)
//   0x782f60  public: static class UClass * __cdecl UDisTweaks_AISubState::GetPrivateStaticClassUDisTweaks_AISubState(wchar_t const *)
//   0x7844d0  public: static class UClass * __cdecl UDisTweaks_AISubState::StaticClassNoInline(void)
