// DishonoredGame/src/disbehaviorcombatratswarmeliteguard.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (13):
//   0x745cc0  public: virtual unsigned char const * __thiscall UDisBehaviorCombatRatSwarmEliteGuard::BuildFilterStimMask(void)const
//   0x74d5b0  public: virtual unsigned char const * __thiscall UDisBehaviorCombatRatSwarmEliteGuard::BuildBehaviorFilterStimMasks(unsigned char const * &, unsigned char const * &)const
//   0x74fbb0  public: virtual void __thiscall UDisBehaviorCombatRatSwarmEliteGuard::InitBehavior(class UDishonoredAIBrain * const)
//   0x757890  public: static class UClass * __cdecl UDisBehaviorCombatRatSwarmEliteGuard::GetPrivateStaticClassUDisBehaviorCombatRatSwarmEliteGuard(wchar_t const *)
//   0x759e10  public: static void __cdecl UDisBehaviorCombatRatSwarmEliteGuard::InitializePrivateStaticClassUDisBehaviorCombatRatSwarmEliteGuard(void)
//   0x75b570  public: static class UClass * __cdecl UDisBehaviorCombatRatSwarmEliteGuard::StaticClassNoInline(void)
//   0x75b5a0  public: static class UClass * __cdecl UDisTweaks_AIBehavior_CombatRatSwarmEliteGuard::GetPrivateStaticClassUDisTweaks_AIBehavior_CombatRatSwarmEliteGuard(wchar_t const *)
//   0x75c370  public: static void __cdecl UDisTweaks_AIBehavior_CombatRatSwarmEliteGuard::InitializePrivateStaticClassUDisTweaks_AIBehavior_CombatRatSwarmEliteGuard(void)
//   0x75c8a0  public: static class UClass * __cdecl UDisTweaks_AIBehavior_CombatRatSwarmEliteGuard::StaticClassNoInline(void)
//   0x7600d0  private: unsigned int __thiscall UDisBehaviorCombatRatSwarmEliteGuard::WantsToUseGun(void)const
//   0x7601c0  public: virtual void __thiscall UDisBehaviorCombatRatSwarmEliteGuard::RefreshCallback_TakeActorPosition(class UDisAISubState *, float)
//   0x761c20  public: virtual class DisDelegate<unsigned int, struct FAIStimStruct> __thiscall UDisBehaviorCombatRatSwarmEliteGuard::GetFilterStimDelegate(enum EAIStimID)
//   0x761ca0  public: virtual void __thiscall UDisBehaviorCombatRatSwarmEliteGuard::RequestStateExitCallback_FirePistol(class UDishonoredNativeState *)

#include "DishonoredGame.h"

// ---- natives whose retail body is trivial (generated by build/agentAC_work/gen_trivial.py from the 2013 vtables) ----

// DISHONORED(written): 2013 rva 0x5f61b0; the retail UDisBehaviorCombatRatSwarmEliteGuard vtable slot +448 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x59d10) and no retail subclass overrides it
void UDisBehaviorCombatRatSwarmEliteGuard::execRequestStateExitCallback_FirePistol( FFrame& Stack, RESULT_DECL )
{
	P_GET_OBJECT(UDishonoredNativeState, _pThisState);
	P_FINISH;
}

// ---- end of trivial natives ----
