// DishonoredGame/src/disdebugnpccontroller.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (4):
//   0x7aafe0  public: static void __cdecl ADisDebugNPCController::InitializePrivateStaticClassADisDebugNPCController(void)
//   0x7bf230  public: static class UClass * __cdecl ADisDebugNPCController::GetPrivateStaticClassADisDebugNPCController(wchar_t const *)
//   0x7bfcb0  public: static class UClass * __cdecl ADisDebugNPCController::StaticClassNoInline(void)
//   0x7c8cc0  public: virtual void __thiscall ADisDebugNPCController::HandleWalking(float)

#include "DishonoredGame.h"

// ---- natives whose retail body is trivial (generated by build/agentAC_work/gen_trivial.py from the 2013 vtables) ----

// DISHONORED(written): 2013 rva 0x5edbf0; the retail ADisDebugNPCController vtable slot +1268 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x59d10) and no retail subclass overrides it
void ADisDebugNPCController::execDis_StartPower( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
}

// DISHONORED(written): 2013 rva 0x5f3cf0; the retail ADisDebugNPCController vtable slot +1264 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x59d10) and no retail subclass overrides it
void ADisDebugNPCController::execDis_StartFire( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
}

// ---- end of trivial natives ----
