// DishonoredGame/src/disdesirestructs.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (57):
//   0x8f8d80  public: static void __cdecl UDisDesireStructs::InitializePrivateStaticClassUDisDesireStructs(void)
//   0x8f8da0  public: __thiscall FDisLookAtInfluence::FDisLookAtInfluence(float, float, unsigned int)
//   0x8f8dd0  public: unsigned int __thiscall FDisLookAtInfluence::operator!=(struct FDisLookAtInfluence const &)const
//   0x8f8e20  private: void __thiscall FDisFaceToRequest::SetParams(unsigned int, int, float, unsigned int, enum EDisDesireRequestStatus &)
//   0x8f8ea0  private: void __thiscall FDisFaceToRequest::StopRequest(void)
//   0x8f8ec0  private: void __thiscall FDisLocoRequest::SetParams(int, float, float, unsigned int, unsigned int, unsigned int, float, float, enum EDisDesireRequestStatus &)
//   0x8f8fa0  private: void __thiscall FDisLocoRequest::StopRequest(void)
//   0x8f8fc0  private: void __thiscall FDisLookAtRequest::SetParams(unsigned int, unsigned int, int, struct FDisLookAtInfluence const &, float, enum EDisDesireRequestStatus &)
//   0x8f9070  public: unsigned int __thiscall FDisBodyIntentionRequest::RequestBodyIntention(enum eDisNPCBodyStance, class UClass *, class UClass *)
//   0x8f90f0  unsigned int __cdecl DisDesireStructs::ResolveProxyTarget(struct FDisAttentionProxy const &, class FVector &)
//   0x8f9ec0  protected: unsigned int __thiscall FDisDesireRequest::ReferencesActor(class AActor const &)const
//   0x8f9f20  private: void __thiscall FDisFaceToRequest::DoRequest(enum EDisDesireRequestStatus)
//   0x8fa170  private: void __thiscall FDisLocoRequest::DoRequest(enum EDisDesireRequestStatus)
//   0x8fa3d0  public: void __thiscall FDisLookAtRequest::ClearRequest(void)
//   0x8fa430  public: void __thiscall FDisLookAtRequest::OnActorTerminated(class AActor const &)
//   0x8fa450  private: void __thiscall FDisLookAtRequest::DoRequest(enum EDisDesireRequestStatus)
//   0x8fcbb0  public: static class UClass * __cdecl UDisDesireStructs::GetPrivateStaticClassUDisDesireStructs(wchar_t const *)
//   0x8fcc40  public: void __thiscall FDisFaceToRequest::PauseRequest(void)
//   0x8fccb0  public: void __thiscall FDisFaceToRequest::ClearRequest(void)
//   0x8fcd30  public: void __thiscall FDisLocoRequest::PauseRequest(void)
//   0x8fcdc0  public: void __thiscall FDisLocoRequest::ClearRequest(void)
//   0x8fce80  public: void __thiscall FDisLookAtRequest::Finalize(void)
//   0x8ffaf0  public: static class UClass * __cdecl UDisDesireStructs::StaticClassNoInline(void)
//   0x8ffb20  public: void __thiscall FDisDesireRequest::OnOtherActorTerminatedEvent(class FArkGameEvent const &)
//   0x8ffb90  public: void __thiscall FDisLookAtRequest::Initialize(class FArkComponentLookat &, class UObject &, enum EDisLookAtPriority)
//   0x8ffbd0  public: void __thiscall FDisBodyIntentionRequest::Initialize(class ADishonoredNPCPawn &, enum EDisBodyIntentionPriority)
//   0x900390  protected: void __thiscall FDisDesireRequest::RegisterToActorTerminationIfNeeded(void)
//   0x900400  public: __thiscall FDisDesireRequest::~FDisDesireRequest(void)
//   0x900450  protected: enum EDisDesireRequestStatus __thiscall FDisDesireRequest::ClearTarget(void)
//   0x9004b0  private: enum EDisDesireRequestStatus __thiscall FDisDesireRequest::GetRequestStatus(class AActor *, unsigned int, class FVector const &)
//   0x900830  public: void __thiscall FDisFaceToRequest::Initialize(class FArkComponentFaceTo &, class UObject &, enum EDisFaceToPriority, void (__thiscall UObject::*const &)(enum EArkCpntFaceToEvent))
//   0x900880  public: void __thiscall FDisLocoRequest::Initialize(class FArkComponentLocomotion &, class UObject &, enum EDisLocoPriority, void (__thiscall UObject::*const &)(int, enum EArkCpntLocoEvent))
//   0x9008d0  private: void __thiscall FDisLookAtRequest::SyncRequest(void)
//   0x901cc0  protected: enum EDisDesireRequestStatus __thiscall FDisDesireRequest::SetProxyTarget(struct FDisAttentionProxy const &)
//   0x901d50  protected: enum EDisDesireRequestStatus __thiscall FDisDesireRequest::SetLookAtTarget(class IDisLookAtInterface &)
//   0x901dd0  protected: enum EDisDesireRequestStatus __thiscall FDisDesireRequest::SetActorTarget(class AActor &)
//   0x901e30  protected: enum EDisDesireRequestStatus __thiscall FDisDesireRequest::SetLocationTarget(class FVector const &)
//   0x901ed0  public: void __thiscall FDisFaceToRequest::RequestProxyTarget(struct FDisAttentionProxy const &, float, unsigned int)
//   0x901f50  public: void __thiscall FDisFaceToRequest::RequestActorTarget(class AActor &, float, unsigned int)
//   0x901fd0  public: void __thiscall FDisFaceToRequest::RequestLocationTarget(class FVector const &, float, unsigned int)
//   0x902050  public: void __thiscall FDisFaceToRequest::RequestYawTarget(int, float, unsigned int)
//   0x902100  private: void __thiscall FDisFaceToRequest::UpdateRequest(void)
//   0x902160  public: void __thiscall FDisLocoRequest::RequestProxyTarget(struct FDisAttentionProxy const &, int, float, float, unsigned int, unsigned int)
//   0x902210  public: void __thiscall FDisLocoRequest::RequestActorTarget(class AActor &, int, float, float, unsigned int, unsigned int)
//   0x9022c0  public: void __thiscall FDisLocoRequest::RequestFollowTarget(class AActor &, int, float, float, unsigned int, unsigned int, unsigned int, float, float)
//   0x902380  public: void __thiscall FDisLocoRequest::RequestLocationTarget(class FVector const &, int, float, float, unsigned int, unsigned int)
//   0x902430  private: void __thiscall FDisLocoRequest::UpdateRequest(void)
//   0x9024b0  public: void __thiscall FDisLookAtRequest::RequestProxyTarget(struct FDisAttentionProxy const &, struct FDisLookAtInfluence const &, float)
//   0x902500  public: void __thiscall FDisLookAtRequest::RequestActorTarget(class AActor &, struct FDisLookAtInfluence const &, float)
//   0x902580  public: void __thiscall FDisLookAtRequest::RequestActorAimTarget(class AActor &, struct FDisLookAtInfluence const &, float)
//   0x902600  public: void __thiscall FDisLookAtRequest::RequestProceduralLookAt(enum EDisLookAtProceduralPattern, struct FDisLookAtInfluence const &, float)
//   0x905b10  public: void __thiscall FDisLookAtRequest::TickRequest(float)
//   0x905b80  public: void __thiscall FDisLookAtRequest::PostGameLoad(class FArkComponentLookat &, class UObject &)
//   0xbaae80  _dynamic_initializer_for__FDisLookAtInfluence::Eyes__
//   0xbaae90  _dynamic_initializer_for__FDisLookAtInfluence::Head__
//   0xbaaea0  _dynamic_initializer_for__FDisLookAtInfluence::Torso__
//   0xbaaeb0  _dynamic_initializer_for__FDisLookAtInfluence::TorsoSpeedIndependent__
