// DishonoredGame/src/disdesiresinterface.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (37):
//   0x8f8d50  public: static void __cdecl UDisDesiresInterface::InitializePrivateStaticClassUDisDesiresInterface(void)
//   0x8f8d70  private: virtual void (__thiscall UObject::*const & __thiscall IDisDesiresInterface::GetDesiresLocoEventCallback(void)const)(int, enum EArkCpntLocoEvent)
//   0x8f9df0  public: class FVector __thiscall IDisDesiresInterface::GetLocoDesireDestination(void)const
//   0x8f9e90  public: unsigned int __thiscall IDisDesiresInterface::SetBodyIntentionDesire(enum eDisNPCBodyStance, class UClass *, class UClass *)
//   0x8fca00  public: static class UClass * __cdecl UDisDesiresInterface::GetPrivateStaticClassUDisDesiresInterface(wchar_t const *)
//   0x8fca90  public: enum ETransitSpeed __thiscall IDisDesiresInterface::GetLocoDesireTransitSpeed(void)const
//   0x8fcb50  public: void __thiscall IDisDesiresInterface::ClearLookAtDesire(void)
//   0x8fcb70  public: void __thiscall IDisDesiresInterface::ClearBodyIntentionDesire(void)
//   0x8ffa00  public: static class UClass * __cdecl UDisDesiresInterface::StaticClassNoInline(void)
//   0x8ffa30  public: void __thiscall IDisDesiresInterface::StopDesires(void)
//   0x8ffab0  public: void __thiscall IDisDesiresInterface::ClearFaceToDesire(void)
//   0x8ffad0  public: void __thiscall IDisDesiresInterface::ClearLocoDesire(void)
//   0x9002d0  public: void __thiscall IDisDesiresInterface::FinalizeDesires(void)
//   0x901a10  public: void __thiscall IDisDesiresInterface::HandleFaceToEvent(enum EArkCpntFaceToEvent)
//   0x901b10  public: void __thiscall IDisDesiresInterface::HandleLocoEvent(enum EArkCpntLocoEvent)
//   0x905330  public: void __thiscall IDisDesiresInterface::InitializeDesires(void)
//   0x9054a0  public: void __thiscall IDisDesiresInterface::PauseDesires(void)
//   0x905530  public: void __thiscall IDisDesiresInterface::SetFaceToProxyDesire(struct FDisAttentionProxy const &, float, int)
//   0x905560  public: void __thiscall IDisDesiresInterface::SetFaceToActorDesire(class AActor &, float, int)
//   0x905590  public: void __thiscall IDisDesiresInterface::SetFaceToLocationDesire(class FVector const &, float, int)
//   0x9055c0  public: void __thiscall IDisDesiresInterface::SetFaceToYawDesire(int, float, int)
//   0x9055f0  public: void __thiscall IDisDesiresInterface::SetLocoProxyDesire(struct FDisAttentionProxy const &, enum ETransitSpeed, float, float, unsigned int, unsigned int)
//   0x905680  public: void __thiscall IDisDesiresInterface::SetLocoActorDesire(class AActor &, enum ETransitSpeed, float, float, unsigned int, unsigned int)
//   0x905710  public: void __thiscall IDisDesiresInterface::SetLocoFollowDesire(class AActor &, enum ETransitSpeed, float, float)
//   0x9057b0  public: void __thiscall IDisDesiresInterface::SetLocoLocationDesire(class FVector const &, enum ETransitSpeed, float, float, unsigned int, unsigned int)
//   0x905840  public: void __thiscall IDisDesiresInterface::SetLookAtProxyDesire(struct FDisAttentionProxy const &, struct FDisLookAtInfluence const &, float)
//   0x9058a0  public: void __thiscall IDisDesiresInterface::SetLookAtTargetDesire(class IDisLookAtInterface &, struct FDisLookAtInfluence const &, float)
//   0x905900  public: void __thiscall IDisDesiresInterface::SetLookAtActorDesire(class AActor &, struct FDisLookAtInfluence const &, float)
//   0x905930  public: void __thiscall IDisDesiresInterface::SetLookAtLocationDesire(class FVector const &, struct FDisLookAtInfluence const &, float)
//   0x905990  public: void __thiscall IDisDesiresInterface::SetAimAtProxyDesire(struct FDisAttentionProxy const &, struct FDisLookAtInfluence const &, float)
//   0x9059f0  public: void __thiscall IDisDesiresInterface::SetAimAtActorDesire(class AActor &, struct FDisLookAtInfluence const &, float)
//   0x905a20  public: void __thiscall IDisDesiresInterface::SetLookAtProceduralDesire(enum EDisLookAtProceduralPattern, struct FDisLookAtInfluence const &, float)
//   0x905a50  public: void __thiscall IDisDesiresInterface::SetLookAtProceduralProxyDesire(struct FDisAttentionProxy const &, enum EDisLookAtProceduralPattern, struct FDisLookAtInfluence const &, float)
//   0x905ab0  public: void __thiscall IDisDesiresInterface::SetLookAtProceduralLocationDesire(class FVector const &, enum EDisLookAtProceduralPattern, struct FDisLookAtInfluence const &, float)
//   0x907ee0  public: void __thiscall IDisDesiresInterface::ResumeDesires(struct FDisBodyIntention const &)
//   0x908010  public: void __thiscall IDisDesiresInterface::TickDesires(float)
//   0x908070  public: void __thiscall IDisDesiresInterface::PostGameLoad_Desires(void)
