// DishonoredGame/src/disemittercameralenseffect_looping.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (7):
//   0x630280  public: static void __cdecl ADisEmitterCameraLensEffect_Looping::InitializePrivateStaticClassADisEmitterCameraLensEffect_Looping(void)
//   0x6302a0  public: virtual unsigned int __thiscall ADisEmitterCameraLensEffect_Looping::Tick(float, enum ELevelTick)
//   0x6303b0  public: void __thiscall ADisEmitterCameraLensEffect_Looping::EnableLoopingEffect(float)
//   0x630430  public: void __thiscall ADisEmitterCameraLensEffect_Looping::DisableLoopingEffect(float)
//   0x630490  public: virtual void __thiscall ADisEmitterCameraLensEffect_Looping::NotifyRetriggered(void)
//   0x651800  public: static class UClass * __cdecl ADisEmitterCameraLensEffect_Looping::GetPrivateStaticClassADisEmitterCameraLensEffect_Looping(wchar_t const *)
//   0x653930  public: static class UClass * __cdecl ADisEmitterCameraLensEffect_Looping::StaticClassNoInline(void)

#include "DishonoredGame.h"

// ---- natives whose retail body is trivial (generated by build/agentAC_work/gen_trivial.py from the 2013 vtables) ----

// DISHONORED(written): 2013 rva 0x5f6340; the retail ADisEmitterCameraLensEffect_Looping vtable slot +944 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x59d10) and no retail subclass overrides it
void ADisEmitterCameraLensEffect_Looping::execEnabledFromScript( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
}

// ---- end of trivial natives ----
