// DishonoredGame/src/disgfxmovieplayerpausemenu.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (28):
//   0x822a90  public: static void __cdecl UDisGFxMoviePlayerPauseMenu::InitializePrivateStaticClassUDisGFxMoviePlayerPauseMenu(void)
//   0x822ab0  public: static void __cdecl UDisTweaks_GFxMoviePlayerPauseMenu::InitializePrivateStaticClassUDisTweaks_GFxMoviePlayerPauseMenu(void)
//   0x822ad0  public: static void __cdecl UDEPRECATED_DisTweaks_GFxMoviePlayerGameOver::InitializePrivateStaticClassUDEPRECATED_DisTweaks_GFxMoviePlayerGameOver(void)
//   0x822af0  protected: virtual void __thiscall UDisGFxMoviePlayerMissionStats::OnCompleteMoviePackageLoading(void)
//   0x822b20  public: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::OnResumeGameClicked(void)
//   0x822b30  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnLoadGameClicked(void)
//   0x822b40  public: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::OnOptionsClicked(void)
//   0x822b50  public: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::OnMenuClosed(void)
//   0x825230  private: virtual unsigned int __thiscall UDisGFxMoviePlayerPauseMenu::FilterButtonInput(int, class FName, unsigned char, unsigned int &)
//   0x825280  public: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::OnQuitGameConfirm(void)
//   0x828f30  public: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::OnSaveGameConfirm(int)
//   0x828fe0  public: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::OnDeleteSaveConfirm(unsigned int, int)
//   0x829090  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnQuitGameConfirm(void)
//   0x830280  private: void __thiscall UDisGFxMoviePlayerPauseMenu::CreateGFxSaveGameList(class GFxValue *)
//   0x835d50  private: void __thiscall UDisGFxMoviePlayerPauseMenu::FillSaveGameMenu(void)
//   0x835e60  private: void __thiscall UDisGFxMoviePlayerPauseMenu::RefreshSaveGameMenu(void)
//   0x835f70  public: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::OnSaveGameClicked(void)
//   0x8395d0  private: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::PreAdvance(float)
//   0x840310  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerPauseMenu::GetPrivateStaticClassUDisTweaks_GFxMoviePlayerPauseMenu(wchar_t const *)
//   0x8403a0  public: static class UClass * __cdecl UDEPRECATED_DisTweaks_GFxMoviePlayerGameOver::GetPrivateStaticClassUDEPRECATED_DisTweaks_GFxMoviePlayerGameOver(wchar_t const *)
//   0x840860  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerPauseMenu::StaticClassNoInline(void)
//   0x840890  public: static class UClass * __cdecl UDEPRECATED_DisTweaks_GFxMoviePlayerGameOver::StaticClassNoInline(void)
//   0x8428b0  private: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::PostFirstAdvance(void)
//   0x842c70  public: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::OnTutorialsClicked(void)
//   0x842fb0  public: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::OnTutorialReadRequest(int)
//   0x8443f0  public: unsigned int __thiscall UDisGFxMoviePlayerPauseMenu::OpenPauseMenuAsync(unsigned int, class FString const *)
//   0x846070  public: static class UClass * __cdecl UDisGFxMoviePlayerPauseMenu::GetPrivateStaticClassUDisGFxMoviePlayerPauseMenu(wchar_t const *)
//   0x847670  public: static class UClass * __cdecl UDisGFxMoviePlayerPauseMenu::StaticClassNoInline(void)
