// DishonoredGame/src/disgfxmovieplayerpowerwheel.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (44):
//   0x822b70  public: static void __cdecl UDisGFxMoviePlayerPowerWheel::InitializePrivateStaticClassUDisGFxMoviePlayerPowerWheel(void)
//   0x822b90  public: static void __cdecl UDisTweaks_GFxMoviePlayerPowerWheel::InitializePrivateStaticClassUDisTweaks_GFxMoviePlayerPowerWheel(void)
//   0x822bb0  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::UpdateLastSelectedShortcutIndex(int)
//   0x822c10  public: virtual void __thiscall UDisGFxMoviePlayerPowerWheel::GameLoad(class FArchive &, enum ESaveLoadLocation)
//   0x822ca0  public: unsigned int __thiscall UDisGFxMoviePlayerPowerWheel::IsActive(int)const
//   0x822cd0  public: unsigned int __thiscall UDisGFxMoviePlayerPowerWheel::IsVisible(int)const
//   0x822d00  protected: virtual unsigned int __thiscall UDisGFxMoviePlayerPowerWheel::IsUsingGamepad(void)const
//   0x825340  public: void __thiscall UDisGFxMoviePlayerPowerWheel::UseShortcut(int)
//   0x8253a0  protected: int __thiscall UDisGFxMoviePlayerPowerWheel::TranslateShortcutOffset(int)
//   0x825430  public: void __thiscall UDisGFxMoviePlayerPowerWheel::UseRelativeShortcut(int)
//   0x825480  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::CloseWheelForAS(void)
//   0x825500  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::CloseShortcutsForAS(void)
//   0x825580  public: virtual void __thiscall UDisGFxMoviePlayerPowerWheel::ConsumeHealthPotion(void)
//   0x8255a0  public: virtual void __thiscall UDisGFxMoviePlayerPowerWheel::ConsumeManaPotion(void)
//   0x8255c0  public: virtual void __thiscall UDisGFxMoviePlayerPowerWheel::OnWheelClosed(void)
//   0x825620  public: virtual void __thiscall UDisGFxMoviePlayerPowerWheel::OnShortcutsClosed(void)
//   0x825680  public: virtual void __thiscall UDisGFxMoviePlayerPowerWheel::OnQuickPotionClosed(void)
//   0x829170  public: void __thiscall UDisGFxMoviePlayerPowerWheel::AssignShortcut(int)
//   0x829350  public: void __thiscall UDisGFxMoviePlayerPowerWheel::SelectShortcut(int)
//   0x829430  public: void __thiscall UDisGFxMoviePlayerPowerWheel::SelectRelativeShortcut(int)
//   0x829500  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::AddToItemList(class GFxValue &, unsigned char, int, unsigned int)
//   0x829670  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::UpdateItemInfo(unsigned char, unsigned char)
//   0x829830  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::UpdateHeartInfo(void)
//   0x8299e0  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::UpdatePotionCount(void)
//   0x829b10  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::EquipItem(unsigned char, unsigned char)
//   0x829c00  public: void __thiscall UDisGFxMoviePlayerPowerWheel::OnPotionConsumed(enum EElixirType)
//   0x8307e0  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::EquipItem(unsigned char)
//   0x839710  protected: static void __cdecl UDisGFxMoviePlayerPowerWheel::FindAvailableItems(struct TMemStackArray<unsigned char> &)
//   0x83f9e0  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::UpdatePowerInfo(unsigned char)
//   0x840450  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerPowerWheel::GetPrivateStaticClassUDisTweaks_GFxMoviePlayerPowerWheel(wchar_t const *)
//   0x8408c0  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerPowerWheel::StaticClassNoInline(void)
//   0x843080  public: void __thiscall UDisGFxMoviePlayerPowerWheel::CloseWheel(unsigned int, unsigned int)
//   0x8432e0  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::AutoAssignShortcuts(struct TMemStackArray<unsigned char> const &)
//   0x8437d0  protected: virtual unsigned int __thiscall UDisGFxMoviePlayerPowerWheel::FilterButtonInput(int, class FName, unsigned char, unsigned int &)
//   0x8438f0  protected: struct FVector2D __thiscall UDisGFxMoviePlayerPowerWheel::GetGamepadDirection(void)
//   0x8439e0  protected: struct FVector2D __thiscall UDisGFxMoviePlayerPowerWheel::GetMouseDirection(void)
//   0x843b80  public: virtual void __thiscall UDisGFxMoviePlayerPowerWheel::OnSelectionChanged(int)
//   0x844510  public: static class UClass * __cdecl UDisGFxMoviePlayerPowerWheel::GetPrivateStaticClassUDisGFxMoviePlayerPowerWheel(wchar_t const *)
//   0x8445a0  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::UpdateShortcuts(struct TMemStackArray<unsigned char> const &)
//   0x844750  protected: virtual void __thiscall UDisGFxMoviePlayerPowerWheel::UpdateAnalogInputForAS(float)
//   0x846100  public: static class UClass * __cdecl UDisGFxMoviePlayerPowerWheel::StaticClassNoInline(void)
//   0x846130  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::OpenWheelForAS(void)
//   0x846480  protected: void __thiscall UDisGFxMoviePlayerPowerWheel::OpenShortcutsForAS(void)
//   0x8476a0  public: void __thiscall UDisGFxMoviePlayerPowerWheel::OpenWheel(int, int, unsigned int)
