// DishonoredGame/src/disgfxmovieplayermenubase.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (41):
//   0x7f4b50  public: static void __cdecl UDisTweaks_GFxMoviePlayerMenuBase::InitializePrivateStaticClassUDisTweaks_GFxMoviePlayerMenuBase(void)
//   0x7f4b70  public: virtual void __thiscall UDisGFxMoviePlayerMenuBase::OnKeyListening(int)
//   0x7f7120  protected: void __thiscall UDisGFxMoviePlayerMenuBase::FindSaveImagePath(struct FDisSaveGame const *, class FString &, unsigned int)const
//   0x7f71c0  private: void __thiscall UDisGFxMoviePlayerMenuBase::CloseOptions(void)
//   0x7f7290  public: virtual void __thiscall UDisGFxMoviePlayerMenuBase::OnApplyVideoSettings(void)
//   0x7f72c0  public: void __thiscall UDisGFxMoviePlayerGamma::CloseGammaMenu(void)
//   0x7f73d0  public: virtual void __thiscall UDisGFxMoviePlayerGamma::OnGammaImageClosed(void)
//   0x800ec0  public: virtual void __thiscall UDisGFxMoviePlayerMenuBase::OnLoadGameConfirm(int)
//   0x800f40  public: virtual void __thiscall UDisGFxMoviePlayerMenuBase::OnDeleteSaveConfirm(unsigned int, int)
//   0x800fc0  public: virtual void __thiscall UDisGFxMoviePlayerMenuBase::Req_GamepadMappingScreen(int)
//   0x801340  public: virtual void __thiscall UDisGFxMoviePlayerMenuBase::CloseGammaImage(void)
//   0x806880  protected: void __thiscall UDisGFxMoviePlayerMenuBase::FormatSaveDate(struct FDisSaveGame const *, class FString &)const
//   0x806b10  public: virtual void __thiscall UDisGFxMoviePlayerMenuBase::OnSettingChange(int, float)
//   0x806de0  public: virtual void __thiscall UDisGFxMoviePlayerMenuBase::OnLeaveOptions(void)
//   0x80f920  private: void __thiscall UDisGFxMoviePlayerMenuBase::CreateGFxSetting(struct FDisSetting const &, class GFxValue *)
//   0x8103b0  private: void __thiscall UDisGFxMoviePlayerMenuBase::TryBindKey(class FName)
//   0x810590  public: virtual void __thiscall UDisGFxMoviePlayerMenuBase::Req_VideoSettingsScreen(void)
//   0x813790  protected: virtual unsigned int __thiscall UDisGFxMoviePlayerMenuBase::FilterButtonInput(int, class FName, unsigned char, unsigned int &)
//   0x8137f0  protected: void __thiscall UDisGFxMoviePlayerMenuBase::FindSaveName(struct FDisSaveGame const *, class FString &)const
//   0x813930  private: void __thiscall UDisGFxMoviePlayerMenuBase::CreateGFxLoadGameList(class GFxValue *)
//   0x813db0  private: void __thiscall UDisGFxMoviePlayerMenuBase::CreateGFxSubCategory(struct FDisSettingsSubCategory const &, class GFxValue *)
//   0x815830  protected: void __thiscall UDisGFxMoviePlayerMenuBase::FillLoadGameMenu(void)
//   0x815940  private: void __thiscall UDisGFxMoviePlayerMenuBase::RefreshLoadGameMenu(void)
//   0x815a50  private: void __thiscall UDisGFxMoviePlayerMenuBase::CreateGFxCategory(struct FDisSettingsCategory const &, class GFxValue *)
//   0x817160  protected: virtual void __thiscall UDisGFxMoviePlayerMenuBase::PreAdvance(float)
//   0x817250  private: void __thiscall UDisGFxMoviePlayerMenuBase::ShowSettingsCategoryList(class TArray<struct FDisSettingsCategory, class FDefaultAllocator> const &)
//   0x817400  private: void __thiscall UDisGFxMoviePlayerMenuBase::RefreshSettingsCategory(struct FDisSettingsCategory const &)
//   0x817510  public: virtual void __thiscall UDisGFxMoviePlayerMenuBase::OnResetOptions(int, int)
//   0x818270  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerMenuBase::GetPrivateStaticClassUDisTweaks_GFxMoviePlayerMenuBase(wchar_t const *)
//   0x81adc0  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerMenuBase::StaticClassNoInline(void)
//   0x81ba20  private: void __thiscall UDisGFxMoviePlayerMenuBase::FillSettingsCategoryList(unsigned int, class TArray<struct FDisSettingsCategory, class FDefaultAllocator> &)
//   0x81da70  protected: void __thiscall UDisGFxMoviePlayerMenuBase::FillOptionsMenu(unsigned int)
//   0x81daf0  public: void __thiscall UDisGFxMoviePlayerGamma::OpenGammaMenu(void)
//   0x81dcf0  private: virtual void __thiscall UDisGFxMoviePlayerGamma::OnCompleteMoviePackageLoading(void)
//   0x820420  public: static class UClass * __cdecl UDisGFxMoviePlayerMenuBase::GetPrivateStaticClassUDisGFxMoviePlayerMenuBase(wchar_t const *)
//   0x8204b0  public: static class UClass * __cdecl UDisGFxMoviePlayerGamma::GetPrivateStaticClassUDisGFxMoviePlayerGamma(wchar_t const *)
//   0x821050  public: static void __cdecl UDisGFxMoviePlayerMenuBase::InitializePrivateStaticClassUDisGFxMoviePlayerMenuBase(void)
//   0x821070  public: static void __cdecl UDisGFxMoviePlayerGamma::InitializePrivateStaticClassUDisGFxMoviePlayerGamma(void)
//   0x822790  public: static class UClass * __cdecl UDisGFxMoviePlayerMenuBase::StaticClassNoInline(void)
//   0x8227c0  public: static class UClass * __cdecl UDisGFxMoviePlayerGamma::StaticClassNoInline(void)
//   0x822980  public: virtual void __thiscall UDisGFxMoviePlayerMenuBase::OpenGammaImage(void)
