// DishonoredGame/src/disgfxmovieplayerjournal.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (73):
//   0x7f4a20  public: static void __cdecl UDisSeqAct_OpenJournal::InitializePrivateStaticClassUDisSeqAct_OpenJournal(void)
//   0x7f4a40  public: static void __cdecl UDisSeqEvent_JournalViewed::InitializePrivateStaticClassUDisSeqEvent_JournalViewed(void)
//   0x7f6d20  public: void __thiscall UDisGFxMoviePlayerJournal::RequestCloseJournal(void)
//   0x7f6e00  public: unsigned int __thiscall UDisGFxMoviePlayerJournal::PlayerHasBoneCharms(void)const
//   0x7f6e20  private: virtual unsigned int __thiscall UDisGFxMoviePlayerJournal::FilterButtonInput(int, class FName, unsigned char, unsigned int &)
//   0x7f6e60  private: struct FDisJournalPowerSlot const * __thiscall UDisGFxMoviePlayerJournal::FindPowerConfig(class FString const &, unsigned int, unsigned int)const
//   0x7f6ee0  private: unsigned char __thiscall UDisGFxMoviePlayerJournal::FindActivePowerType(class FString const &)const
//   0x7f6f20  private: unsigned char __thiscall UDisGFxMoviePlayerJournal::FindPassivePowerType(class FString const &)const
//   0x7f6f60  public: virtual void __thiscall UDisGFxMoviePlayerJournal::OnPowerInfosRequest(class FString const &)
//   0x7f6fd0  public: virtual void __thiscall UDisGFxMoviePlayerJournal::EquipBoneCharm(int)
//   0x7f7000  public: virtual void __thiscall UDisGFxMoviePlayerJournal::RemoveBoneCharm(int)
//   0x7ff730  public: unsigned int __thiscall UDisGFxMoviePlayerJournal::PlayerHasPowersOrRunes(void)const
//   0x7ff7a0  private: void __thiscall UDisGFxMoviePlayerJournal::ShowHUDMarkers(int, unsigned int)
//   0x7ff910  private: void __thiscall UDisGFxMoviePlayerJournal::ShowChapterInfo(void)
//   0x7ffcf0  private: void __thiscall UDisGFxMoviePlayerJournal::ShowRuneCount(int)
//   0x7ffe00  public: virtual int __thiscall UDisGFxMoviePlayerJournal::Req_FlashingTabsBitfield(void)
//   0x7ffe90  public: virtual void __thiscall UDisGFxMoviePlayerJournal::OnToggleHUDMarker(int)
//   0x800090  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_PowerDetails(class FString const &)
//   0x8006b0  private: unsigned int __thiscall UDisGFxMoviePlayerJournal::IsAudioLogPlaying(int)
//   0x8007a0  public: virtual void __thiscall UDisGFxMoviePlayerJournal::PlayAudioLog(int)
//   0x800880  public: virtual void __thiscall UDisGFxMoviePlayerJournal::StopAudioLog(int)
//   0x8008e0  private: void __thiscall UDisGFxMoviePlayerJournal::CheckAudioLogEnd(void)
//   0x800b20  protected: virtual void __thiscall UDisGFxMoviePlayerJournal::PreAdvance(float)
//   0x805110  public: static class UDishonoredActivePowerComponent const * __cdecl UDisGFxMoviePlayerJournal::FindActivePower(unsigned char, unsigned int *)
//   0x8051e0  public: static struct FDishonoredPower const * __cdecl UDisGFxMoviePlayerJournal::FindPassivePower(unsigned char, unsigned int *)
//   0x8052b0  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_PowersTabContent(void)
//   0x805cb0  public: virtual void __thiscall UDisGFxMoviePlayerJournal::PowerBuy(class FString const &, int)
//   0x805f60  public: virtual void __thiscall UDisGFxMoviePlayerJournal::ReadNote(int)
//   0x80a3a0  private: void __thiscall UDisGFxMoviePlayerJournal::ShowObjectives(void)
//   0x80b060  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_ObjectivesList(void)
//   0x80b070  public: virtual void __thiscall UDisGFxMoviePlayerJournal::OnToggleObjectivesListHistory(void)
//   0x80dc80  public: void __thiscall FDisJournalItem::GetAbstractItemDesc(struct TMemStackArray<class FString> &)const
//   0x80dd80  public: static void __cdecl UDisGFxMoviePlayerJournal::FindPlayerAbstractItems(enum EDisJournalItemSection, struct TMemStackArray<struct FDisJournalItem> &)
//   0x80deb0  public: static void __cdecl UDisGFxMoviePlayerJournal::FindPlayerMissionItems(struct TMemStackArray<struct FDisJournalItem> &)
//   0x80e050  public: static void __cdecl UDisGFxMoviePlayerJournal::FindPlayerKeys(struct TMemStackArray<struct FDisJournalItem> &)
//   0x80e2e0  public: static void __cdecl UDisGFxMoviePlayerJournal::FindPlayerGadgets(struct TMemStackArray<struct FDisJournalItem> &)
//   0x80e4a0  public: void __thiscall UDisGFxMoviePlayerJournal::FindPlayerAmmo(struct TMemStackArray<struct FDisJournalItem> &)
//   0x80e710  public: static void __cdecl UDisGFxMoviePlayerJournal::FindPlayerUpgrades(struct TMemStackArray<struct FDisJournalItem> &)
//   0x80e8f0  private: void __thiscall UDisGFxMoviePlayerJournal::ShowItems(struct TMemStackArray<struct FDisJournalItem> &, enum EDisJournalTab)
//   0x80f1b0  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_MissionItems(void)
//   0x80f290  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_Inventory_Key_Ring(void)
//   0x80f370  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_Inventory_Gadgets(void)
//   0x80f450  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_Inventory_Ammo(void)
//   0x80f530  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_Inventory_Upgrades(void)
//   0x80f610  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_Logs_All(void)
//   0x80f700  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_Logs_Audio(void)
//   0x80f7e0  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_Logs_Notes(void)
//   0x812700  private: void __thiscall UDisGFxMoviePlayerJournal::FillItemInfo(struct FDisJournalItem *, class GFxValue &)
//   0x812b60  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_ChapterNotes(void)
//   0x813140  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_MissionItemInfo(int)
//   0x8132a0  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_InventoryItemInfo(int)
//   0x813400  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_LogInfo(int)
//   0x813630  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_CharmsListDetails(int)
//   0x818150  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerJournal::GetPrivateStaticClassUDisTweaks_GFxMoviePlayerJournal(wchar_t const *)
//   0x81ad80  public: static void __cdecl UDisTweaks_GFxMoviePlayerJournal::InitializePrivateStaticClassUDisTweaks_GFxMoviePlayerJournal(void)
//   0x81b8a0  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerJournal::StaticClassNoInline(void)
//   0x81b8d0  public: static class UClass * __cdecl UDisSeqAct_OpenJournal::GetPrivateStaticClassUDisSeqAct_OpenJournal(wchar_t const *)
//   0x81b960  public: static class UClass * __cdecl UDisSeqEvent_JournalViewed::GetPrivateStaticClassUDisSeqEvent_JournalViewed(wchar_t const *)
//   0x81d930  public: static class UClass * __cdecl UDisSeqAct_OpenJournal::StaticClassNoInline(void)
//   0x81d960  public: static class UClass * __cdecl UDisSeqEvent_JournalViewed::StaticClassNoInline(void)
//   0x81d990  public: unsigned int __thiscall UDisGFxMoviePlayerJournal::OpenJournalAsync(enum EDisJournalTab)
//   0x81da30  public: virtual void __thiscall UDisSeqAct_OpenJournal::Activated(void)
//   0x81f280  public: static class UClass * __cdecl UDisGFxMoviePlayerJournal::GetPrivateStaticClassUDisGFxMoviePlayerJournal(wchar_t const *)
//   0x81f310  public: unsigned int __thiscall UDisGFxMoviePlayerJournal::OpenJournal(enum EDisJournalTab)
//   0x81f750  public: void __thiscall UDisGFxMoviePlayerJournal::FindPlayerResources(struct TMemStackArray<struct FDisJournalItem> &)
//   0x81f9f0  public: void __thiscall UDisGFxMoviePlayerJournal::FindPlayerBoneCharms(struct TMemStackArray<struct FDisJournalItem> &)
//   0x81fc10  private: virtual void __thiscall UDisGFxMoviePlayerJournal::OnCompleteMoviePackageLoading(void)
//   0x81fc40  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_Inventory_All(void)
//   0x81fd50  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_Inventory_Resources(void)
//   0x81fe30  public: virtual void __thiscall UDisGFxMoviePlayerJournal::Req_CharmsTabContent(void)
//   0x81ff20  public: virtual void __thiscall UDisGFxMoviePlayerJournal::CloseJournal(void)
//   0x820de0  public: static void __cdecl UDisGFxMoviePlayerJournal::InitializePrivateStaticClassUDisGFxMoviePlayerJournal(void)
//   0x821dd0  public: static class UClass * __cdecl UDisGFxMoviePlayerJournal::StaticClassNoInline(void)
