// DishonoredGame/src/disgfxmovieplayerglobal.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (29):
//   0x7f4620  public: unsigned int __thiscall UDisGFxMoviePlayerGlobal::HasSavingUI(void)const
//   0x7f4640  protected: virtual void __thiscall UDisGFxMoviePlayerGlobal::PostStart(void)
//   0x7f46b0  protected: virtual unsigned int __thiscall UDisGFxMoviePlayerGlobal::FilterButtonInput(int, class FName, unsigned char, unsigned int &)
//   0x7f6070  protected: void __thiscall UDisGFxMoviePlayerGlobal::ConditionalShowMouseCursor(void)
//   0x7f61a0  protected: void __thiscall UDisGFxMoviePlayerGlobal::MoveMouseCursor(struct FVector2D)
//   0x7f6200  protected: void __thiscall UDisGFxMoviePlayerGlobal::HideCurrentMessageBox(void)
//   0x7f6290  protected: void __thiscall UDisGFxMoviePlayerGlobal::UpdateInputCapture(void)
//   0x7fa640  public: void __thiscall UDisGFxMoviePlayerGlobal::AddMessageBoxTimer(int, float)
//   0x7fa780  protected: void __thiscall UDisGFxMoviePlayerGlobal::ConditionalHideMouseCursor(void)
//   0x7fa880  protected: void __thiscall UDisGFxMoviePlayerGlobal::ShowMessageBox(struct FDisMsgBoxInfo const &)
//   0x7faaf0  protected: void __thiscall UDisGFxMoviePlayerGlobal::ShowSaveIcon(unsigned int)
//   0x7fac20  protected: void __thiscall UDisGFxMoviePlayerGlobal::ShowCheckpointText(unsigned int)
//   0x802c50  public: void __thiscall UDisGFxMoviePlayerGlobal::PreCommitMapChange(void)
//   0x802c60  public: void __thiscall UDisGFxMoviePlayerGlobal::PreRender(class FViewport *)
//   0x802d30  public: void __thiscall UDisGFxMoviePlayerGlobal::ShowProfileSaveUI(unsigned int)
//   0x802db0  public: void __thiscall UDisGFxMoviePlayerGlobal::ShowGameSaveUI(unsigned int)
//   0x802e60  protected: virtual void __thiscall UDisGFxMoviePlayerGlobal::PreClose(unsigned int)
//   0x802ed0  protected: virtual void __thiscall UDisGFxMoviePlayerGlobal::PreAdvance(float)
//   0x802f80  public: virtual void __thiscall UDisGFxMoviePlayerGlobal::OnWriteProfileSettingsComplete(unsigned char, unsigned int)
//   0x808b00  public: void __thiscall UDisGFxMoviePlayerGlobal::AddMessageBox(struct FDisMsgBoxInfo const &, int &, unsigned int)
//   0x808c40  public: virtual void __thiscall UDisGFxMoviePlayerGlobal::OnControllerDisconnected(unsigned char)
//   0x80bda0  public: void __thiscall UDisGFxMoviePlayerGlobal::RemoveMessageBox(int)
//   0x80bec0  public: virtual void __thiscall UDisGFxMoviePlayerGlobal::OnMessageBoxConfirm(int)
//   0x818030  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerGlobal::GetPrivateStaticClassUDisTweaks_GFxMoviePlayerGlobal(wchar_t const *)
//   0x81ad40  public: static void __cdecl UDisTweaks_GFxMoviePlayerGlobal::InitializePrivateStaticClassUDisTweaks_GFxMoviePlayerGlobal(void)
//   0x81b570  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerGlobal::StaticClassNoInline(void)
//   0x81ebf0  public: static class UClass * __cdecl UDisGFxMoviePlayerGlobal::GetPrivateStaticClassUDisGFxMoviePlayerGlobal(wchar_t const *)
//   0x820d80  public: static void __cdecl UDisGFxMoviePlayerGlobal::InitializePrivateStaticClassUDisGFxMoviePlayerGlobal(void)
//   0x821d40  public: static class UClass * __cdecl UDisGFxMoviePlayerGlobal::StaticClassNoInline(void)
