// DishonoredGame/src/disgfxmovieplayermainmenu.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (28):
//   0x7f4a60  public: void __thiscall UDisGFxMoviePlayerMainMenu::PreCommitMapChange(void)
//   0x7f4a70  protected: void __thiscall UDisGFxMoviePlayerMainMenu::SelectController(int)
//   0x7f4b20  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnCampaignTabSelected(void)
//   0x7f4b30  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnDLCTabSelected(void)
//   0x7f4b40  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnDLCClicked(void)
//   0x7f7030  protected: virtual void __thiscall UDisGFxMoviePlayerMainMenu::PreClose(unsigned int)
//   0x800b30  protected: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnMessageBoxResult(class FArkGameEvent const &)
//   0x800b50  public: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::OnLoadLastSaveClicked(void)
//   0x800b80  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnMissionSelected(int)
//   0x800cb0  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::Req_SaveSlotInfos(int)
//   0x806090  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnMissionsClicked(void)
//   0x8181e0  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerMainMenu::GetPrivateStaticClassUDisTweaks_GFxMoviePlayerMainMenu(wchar_t const *)
//   0x81ada0  public: static void __cdecl UDisTweaks_GFxMoviePlayerMainMenu::InitializePrivateStaticClassUDisTweaks_GFxMoviePlayerMainMenu(void)
//   0x81b9f0  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerMainMenu::StaticClassNoInline(void)
//   0x81ffe0  public: static class UClass * __cdecl UDisGFxMoviePlayerMainMenu::GetPrivateStaticClassUDisGFxMoviePlayerMainMenu(wchar_t const *)
//   0x820070  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnOptionsClicked(void)
//   0x820080  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnNewGameConfirm(int)
//   0x820100  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OpenMissionStats(int)
//   0x8201f0  protected: void __thiscall UDisGFxMoviePlayerMainMenu::StartTrailerTimer(void)
//   0x820250  protected: void __thiscall UDisGFxMoviePlayerMainMenu::ShowTrailer(void)
//   0x820330  protected: void __thiscall UDisGFxMoviePlayerMainMenu::HideTrailer(void)
//   0x820e00  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::BackToStartScreen(void)
//   0x820f80  protected: void __thiscall UDisGFxMoviePlayerMainMenu::UpdateTrailer(float)
//   0x821e00  protected: virtual void __thiscall UDisGFxMoviePlayerMainMenu::PostStart(void)
//   0x822280  protected: virtual void __thiscall UDisGFxMoviePlayerMainMenu::PreAdvance(float)
//   0x822590  protected: virtual unsigned int __thiscall UDisGFxMoviePlayerMainMenu::FilterButtonInput(int, class FName, unsigned char, unsigned int &)
//   0x822960  public: static void __cdecl UDisGFxMoviePlayerMainMenu::InitializePrivateStaticClassUDisGFxMoviePlayerMainMenu(void)
//   0x8229e0  public: static class UClass * __cdecl UDisGFxMoviePlayerMainMenu::StaticClassNoInline(void)
