// DishonoredGame/src/disgfxmovieplayerhud.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (157):
//   0x7f46f0  public: static void __cdecl UDisSeqAct_ShowHUDMessage::InitializePrivateStaticClassUDisSeqAct_ShowHUDMessage(void)
//   0x7f4710  public: static void __cdecl UDisSeqAct_SetTutorialMessage::InitializePrivateStaticClassUDisSeqAct_SetTutorialMessage(void)
//   0x7f4730  public: static void __cdecl UDisSeqAct_EnableSystemicTutorials::InitializePrivateStaticClassUDisSeqAct_EnableSystemicTutorials(void)
//   0x7f4750  public: static void __cdecl UDisSeqAct_ShowLocationDiscovery::InitializePrivateStaticClassUDisSeqAct_ShowLocationDiscovery(void)
//   0x7f4770  public: static void __cdecl UDisSeqAct_ShowTargetNotification::InitializePrivateStaticClassUDisSeqAct_ShowTargetNotification(void)
//   0x7f4790  public: unsigned int __thiscall FDisPlayerStatus_Equipment::operator!=(struct FDisPlayerStatus_Equipment const &)const
//   0x7f47f0  public: __thiscall FDisUIInteraction::FDisUIInteraction(void)
//   0x7f4810  public: __thiscall FDisUIInteraction::FDisUIInteraction(enum EDisUIInteraction, class FString const *, unsigned int)
//   0x7f4830  public: void __thiscall FDisUIInteractionGroup::Add(struct FDisUIInteraction const &)
//   0x7f48b0  public: void __thiscall FDisUIInteractionContext::Add(struct FDisUIInteraction const &)
//   0x7f48e0  public: unsigned int __thiscall FDisUIInteractionContext::HasGroupChanged(enum EDisUIInteractionGroup, struct FDisUIInteractionContext const &)const
//   0x7f4950  public: __thiscall FDisHUDDamageInfo::FDisHUDDamageInfo(int, class FVector const &, class AActor *, class ADishonoredPawn *)
//   0x7f4980  public: void __thiscall UDisGFxMoviePlayerHUD::CloseHUD(void)
//   0x7f49b0  public: unsigned int __thiscall UDisGFxMoviePlayerHUD::IsHighlightEnabled(void)const
//   0x7f49c0  public: void __thiscall UDisGFxMoviePlayerHUD::HandleObjectiveEvents(unsigned int)
//   0x7f49e0  public: void __thiscall UDisGFxMoviePlayerHUD::ShowDamage(struct FDisHUDDamageInfo const &)
//   0x7f6330  public: __thiscall FDisUIInteraction::FDisUIInteraction(enum EDisUIInteraction, unsigned int)
//   0x7f6430  public: unsigned int __thiscall FDisUIInteractionProbe::CheckMantle(void)
//   0x7f64a0  public: void __thiscall FDisUIInteractionProbe::FillUIInteractions(struct FDisUIInteractionContext &)const
//   0x7f6570  public: void __thiscall UDisGFxMoviePlayerHUD::StartHUD(void)
//   0x7f65b0  public: unsigned int __thiscall UDisGFxMoviePlayerHUD::ShouldAlwaysShowPlayerInfo(void)const
//   0x7f6610  public: void __thiscall UDisGFxMoviePlayerHUD::OnElixirConsumed(enum EElixirType)
//   0x7f66e0  public: void __thiscall UDisGFxMoviePlayerHUD::ShowKeyhole(void)
//   0x7f6780  public: void __thiscall UDisGFxMoviePlayerHUD::PreHideKeyhole(void)
//   0x7f6820  public: void __thiscall UDisGFxMoviePlayerHUD::HideKeyhole(void)
//   0x7f68c0  public: void __thiscall UDisGFxMoviePlayerHUD::HideChoiceSelection(void)
//   0x7f6990  public: virtual void __thiscall UDisGFxMoviePlayerHUD::OnPlayerChoiceConfirm(int)
//   0x7f69d0  protected: void __thiscall UDisGFxMoviePlayerHUD::UpdateStealthShroud(unsigned int)
//   0x7f6a80  protected: void __thiscall UDisGFxMoviePlayerHUD::MoveCrosshairInteractions(class AActor const *, class UCanvas *)
//   0x7f6bf0  protected: void __thiscall UDisGFxMoviePlayerHUD::HideTutorialWindow(void)
//   0x7f6c90  public: float __thiscall FDisHUDMarkerVariation::ComputeValue(float)const
//   0x7fad50  public: __thiscall FDisTutorialInfo::~FDisTutorialInfo(void)
//   0x7fad80  public: void __thiscall UDisGFxMoviePlayerHUD::HideGauge(enum EDisGaugeType, unsigned int)
//   0x7faed0  public: void __thiscall UDisGFxMoviePlayerHUD::UpdateGauge(enum EDisGaugeType, float)
//   0x7fb080  public: void __thiscall UDisGFxMoviePlayerHUD::ShowLocationDiscovery(class FString const &, unsigned int)
//   0x7fb230  public: void __thiscall UDisGFxMoviePlayerHUD::OnRemoveAwarenessOverride(class ADishonoredNPCPawn const *)
//   0x7fb2b0  public: void __thiscall UDisGFxMoviePlayerHUD::AddGrenadeMarker(class AActor const *)
//   0x7fb360  public: void __thiscall UDisGFxMoviePlayerHUD::AddHeartMarker(class ADisPickup_Base const *)
//   0x7fb450  protected: virtual void __thiscall UDisGFxMoviePlayerHUD::PostStart(void)
//   0x7fbd50  protected: void __thiscall UDisGFxMoviePlayerHUD::Tick_PlayerState(int)
//   0x7fbed0  protected: void __thiscall UDisGFxMoviePlayerHUD::Tick_Stealth(int)
//   0x7fbf60  protected: void __thiscall UDisGFxMoviePlayerHUD::Tick_Cinematic(void)
//   0x7fc0d0  protected: void __thiscall UDisGFxMoviePlayerHUD::PreRender_Layout(class UCanvas *)
//   0x7fccf0  protected: void __thiscall UDisGFxMoviePlayerHUD::PreRender_Damage(class UCanvas *)
//   0x7fd720  protected: void __thiscall UDisGFxMoviePlayerHUD::PreRender_Keyhole(void)
//   0x7fd940  protected: void __thiscall UDisGFxMoviePlayerHUD::UpdateHealthGauge(struct FDisPlayerStatus_Health const &)
//   0x7fdb80  protected: void __thiscall UDisGFxMoviePlayerHUD::UpdateManaGauge(struct FDisPlayerStatus_Mana const &)
//   0x7fddf0  protected: void __thiscall UDisGFxMoviePlayerHUD::UpdateEquipmentInfo(struct FDisPlayerStatus_Equipment const &)
//   0x7fe040  protected: void __thiscall UDisGFxMoviePlayerHUD::UpdateCrosshairFocusText(class FString const &)
//   0x7fe180  protected: void __thiscall UDisGFxMoviePlayerHUD::AddPickupLogItem(class FString const &, int, class FString const &)
//   0x7fe430  protected: int __thiscall UDisGFxMoviePlayerHUD::FindTutorial(int)const
//   0x7fe4b0  protected: void __thiscall UDisGFxMoviePlayerHUD::SetTutorialMessage(class FString const &)
//   0x7fe620  protected: void __thiscall UDisGFxMoviePlayerHUD::ClearTutorialMessage(void)
//   0x7fe700  protected: void __thiscall UDisGFxMoviePlayerHUD::ShowTutorialWindow(struct FDisTutorialInfo const &)
//   0x7fe8b0  protected: void __thiscall UDisGFxMoviePlayerHUD::ShowObjectivePopup(struct FDisObjectivePopupInfo const &)
//   0x7fef30  protected: void __thiscall UDisGFxMoviePlayerHUD::ShowTargetNotification(class UDisSeqAct_ShowTargetNotification const *)
//   0x7ff2e0  protected: void __thiscall UDisGFxMoviePlayerHUD::SortMarkers(struct FDisHUDMarkerPosInfo *, unsigned int)
//   0x7ff4f0  protected: void __thiscall UDisGFxMoviePlayerHUD::ShowSubtitleText(wchar_t const *, int)
//   0x7ff6a0  public: virtual void __thiscall UDisSeqAct_EnableSystemicTutorials::Activated(void)
//   0x7ff700  public: virtual void __thiscall UDisSeqAct_ShowLocationDiscovery::Activated(void)
//   0x802fd0  public: void __thiscall FDisObjectivePopupInfo::AddTask(struct FDisTaskPopupInfo const &)
//   0x803040  public: void __thiscall UDisGFxMoviePlayerHUD::OnAmmoPickedUp(enum eDisAmmoType, int)
//   0x803140  public: void __thiscall UDisGFxMoviePlayerHUD::OnKeyPickedUp(class FString const &, class UDisTweaks_Key const *)
//   0x803160  public: void __thiscall UDisGFxMoviePlayerHUD::OnUpgradePickedUp(class UDisTweaks_Upgrade const *)
//   0x803180  public: struct FDisTutorialInfo * __thiscall UDisGFxMoviePlayerHUD::FindTutorialInfo(int)
//   0x8031e0  public: unsigned int __thiscall UDisGFxMoviePlayerHUD::HasTutorialWindow(void)const
//   0x803250  public: void __thiscall UDisGFxMoviePlayerHUD::RemoveGrenadeMarker(class AActor const *)
//   0x803360  public: void __thiscall UDisGFxMoviePlayerHUD::RemoveGrenadeMarkers(void)
//   0x803400  public: void __thiscall UDisGFxMoviePlayerHUD::RemoveHeartMarkers(void)
//   0x8034a0  public: void __thiscall UDisGFxMoviePlayerHUD::ShowNextMainSubtitlePart(int)
//   0x803560  public: void __thiscall UDisGFxMoviePlayerHUD::ShowNextSecondarySubtitlePart(int)
//   0x803620  public: void __thiscall UDisGFxMoviePlayerHUD::ShowChoiceSelection(class FString const &, struct TMemStackArray<struct FDisPlayerChoiceInfo> &)
//   0x803950  protected: void __thiscall UDisGFxMoviePlayerHUD::Tick_PlayerStatus(int)
//   0x803f70  protected: void __thiscall UDisGFxMoviePlayerHUD::Tick_Subtitles(int)
//   0x804080  protected: void __thiscall UDisGFxMoviePlayerHUD::PreRender_Crosshair(class UCanvas *)
//   0x8049d0  protected: void __thiscall UDisGFxMoviePlayerHUD::PreRender_Markers(class UCanvas *)
//   0x804ef0  protected: void __thiscall UDisGFxMoviePlayerHUD::RemoveMarkerInstance(class FDisHUDMarker *)
//   0x804f70  protected: void __thiscall UDisGFxMoviePlayerHUD::ClearMarkerInstances(void)
//   0x805080  public: static struct FDisNoteParams * __cdecl FDisNoteParams::CreateNoteParams(unsigned char)
//   0x808d20  public: unsigned int __thiscall FDisUIInteractionProbe::CheckAssassinate(void)
//   0x808e50  public: unsigned int __thiscall FDisUIInteractionProbe::CheckDropAssassinate(void)
//   0x809010  public: unsigned int __thiscall FDisUIInteractionProbe::CheckAdrenalineKill(void)
//   0x809140  class FArchive & __cdecl operator<<(class FArchive &, struct FDisTutorialInfo &)
//   0x809220  public: void __thiscall UDisGFxMoviePlayerHUD::PreRender(class UCanvas *)
//   0x809370  public: virtual void __thiscall UDisGFxMoviePlayerHUD::GameSave(class FArchive &, enum ESaveLoadLocation)
//   0x809470  public: void __thiscall UDisGFxMoviePlayerHUD::ShowGauge(enum EDisGaugeType)
//   0x809690  public: void __thiscall UDisGFxMoviePlayerHUD::OnActorTerminated(class AActor const *)
//   0x809750  public: void __thiscall UDisGFxMoviePlayerHUD::AddHeartMarkers(class TArray<class ADisPickup_Base *, class FDefaultAllocator> const &)
//   0x8097d0  protected: void __thiscall UDisGFxMoviePlayerHUD::UpdateCrosshairInteractions(class FString const &, struct FDisUIInteractionGroup const &)
//   0x809a40  protected: void __thiscall UDisGFxMoviePlayerHUD::UpdateContextInteractions(struct FDisUIInteractionGroup const &)
//   0x809c10  protected: void __thiscall UDisGFxMoviePlayerHUD::UpdateSpecialInteractions(struct FDisUIInteractionGroup const &)
//   0x80a000  protected: int __thiscall UDisGFxMoviePlayerHUD::InsertTutorial(struct FDisTutorialInfo const &)
//   0x80a240  protected: unsigned int __thiscall UDisGFxMoviePlayerHUD::IsBrainEligibleForAwarenessMarker(class UDishonoredAIBrain const *, enum EDisAttentionLevel)const
//   0x80c000  public: void __thiscall FDisUIInteractionProbe::Tick(float)
//   0x80c0f0  public: virtual void __thiscall UDisGFxMoviePlayerHUD::GameLoad(class FArchive &, enum ESaveLoadLocation)
//   0x80c2b0  public: void __thiscall UDisGFxMoviePlayerHUD::ClearInteractions(void)
//   0x80c3c0  public: void __thiscall UDisGFxMoviePlayerHUD::HideTutorial(int)
//   0x80c3f0  public: void __thiscall UDisGFxMoviePlayerHUD::HideAdrenalineTutorialMessage(void)
//   0x80c430  protected: virtual void __thiscall UDisGFxMoviePlayerHUD::BeginDestroy(void)
//   0x80c450  protected: void __thiscall UDisGFxMoviePlayerHUD::Tick_Interaction(class IDisInteractableInterface const *)
//   0x80c6b0  protected: void __thiscall UDisGFxMoviePlayerHUD::Tick_Tutorials(float, int)
//   0x80caa0  protected: void __thiscall UDisGFxMoviePlayerHUD::ResolveMarkupString(class FString &)const
//   0x80ccf0  protected: void __thiscall UDisGFxMoviePlayerHUD::RemoveTutorials(void)
//   0x80cd40  protected: void __thiscall UDisGFxMoviePlayerHUD::UpdateTaskMarkerInstances(void)
//   0x80d120  protected: void __thiscall UDisGFxMoviePlayerHUD::UpdateAwarenessMarkerInstances(void)
//   0x80d770  protected: void __thiscall UDisGFxMoviePlayerHUD::SplitSubtitleText(wchar_t const *, class TArray<class FString, class FDefaultAllocator> &, class TArray<float, class FDefaultAllocator> &)
//   0x811620  public: virtual void __thiscall UDisGFxMoviePlayerHUD::ApplyGameSettings(class ArkSettingsParameters const &, enum IArkSettingsListenerInterface::EChangeReason)
//   0x8117c0  public: void __thiscall UDisGFxMoviePlayerHUD::OnCrosshairActorSet(class IDisInteractableInterface *)
//   0x811810  public: int __thiscall UDisGFxMoviePlayerHUD::ShowTutorial(class FString const &, float, unsigned int, unsigned int, unsigned int, unsigned int)
//   0x811990  public: int __thiscall UDisGFxMoviePlayerHUD::ShowTutorialWindow(class FString const &, enum EDisTutorialType, float, unsigned int, enum EDisUINoteType, struct FDisNoteParams *, unsigned int, enum EDisJournalTab)
//   0x811b20  public: void __thiscall UDisGFxMoviePlayerHUD::ShowAdrenalineTutorialMessage(void)
//   0x811bf0  public: void __thiscall UDisGFxMoviePlayerHUD::OnMainSubtitleChanged(wchar_t const *, class TArray<float, class FDefaultAllocator> *)
//   0x811d00  public: void __thiscall UDisGFxMoviePlayerHUD::OnSecondarySubtitleChanged(wchar_t const *, class TArray<float, class FDefaultAllocator> *)
//   0x811e40  protected: virtual void __thiscall UDisGFxMoviePlayerHUD::PreClose(unsigned int)
//   0x812080  protected: void __thiscall UDisGFxMoviePlayerHUD::Tick_ObjectivePopup(float)
//   0x8122c0  protected: void __thiscall UDisGFxMoviePlayerHUD::Tick_Markers(float)
//   0x812340  protected: void __thiscall UDisGFxMoviePlayerHUD::SetGameMessage(class FString const &, float)const
//   0x8124f0  public: virtual void __thiscall UDisSeqAct_SetTutorialMessage::PostLoad(void)
//   0x8125a0  public: virtual void __thiscall UDisSeqAct_SetTutorialMessage::Activated(void)
//   0x814ce0  public: virtual void __thiscall UDisGFxMoviePlayerHUD::PreAdvance(float)
//   0x814e80  public: void __thiscall UDisGFxMoviePlayerHUD::OnAbstractItemAdded(class UDisAbstractItem const *, int, unsigned int)
//   0x814ec0  public: void __thiscall UDisGFxMoviePlayerHUD::AddGameMessage(class FString const &)
//   0x814ef0  public: void __thiscall UDisGFxMoviePlayerHUD::AddUseMessage(class FString const &)
//   0x814f20  public: void __thiscall UDisGFxMoviePlayerHUD::AddInteractionMessage(class FString const &)
//   0x814f50  public: void __thiscall UDisGFxMoviePlayerHUD::OnObjectiveAdded(class UDishonoredObjective *)
//   0x814fd0  public: void __thiscall UDisGFxMoviePlayerHUD::OnObjectiveCompleted(class UDishonoredObjective *)
//   0x815130  public: void __thiscall UDisGFxMoviePlayerHUD::OnObjectiveFailed(class UDishonoredObjective *)
//   0x815290  public: void __thiscall UDisGFxMoviePlayerHUD::OnTaskAdded(class UDishonoredTask_Base *)
//   0x8153b0  public: void __thiscall UDisGFxMoviePlayerHUD::OnTaskUpdated(class UDishonoredTask_Base *)
//   0x8154d0  public: void __thiscall UDisGFxMoviePlayerHUD::OnTaskCompleted(class UDishonoredTask_Base *)
//   0x8155f0  public: void __thiscall UDisGFxMoviePlayerHUD::OnTaskFailed(class UDishonoredTask_Base *)
//   0x815720  public: void __thiscall UDisGFxMoviePlayerHUD::QueueTargetNotification(class UDisSeqAct_ShowTargetNotification *)
//   0x815790  public: virtual void __thiscall UDisSeqAct_ShowHUDMessage::Activated(void)
//   0x815800  public: virtual void __thiscall UDisSeqAct_ShowTargetNotification::Activated(void)
//   0x816e60  public: void __thiscall UDisGFxMoviePlayerHUD::OnAbstractItemPickedUp(class UDisAbstractItem const *, int)
//   0x8180c0  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerHUD::GetPrivateStaticClassUDisTweaks_GFxMoviePlayerHUD(wchar_t const *)
//   0x81ad60  public: static void __cdecl UDisTweaks_GFxMoviePlayerHUD::InitializePrivateStaticClassUDisTweaks_GFxMoviePlayerHUD(void)
//   0x81b5a0  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerHUD::StaticClassNoInline(void)
//   0x81b5d0  public: static class UClass * __cdecl UDisSeqAct_ShowHUDMessage::GetPrivateStaticClassUDisSeqAct_ShowHUDMessage(wchar_t const *)
//   0x81b660  public: static class UClass * __cdecl UDisSeqAct_SetTutorialMessage::GetPrivateStaticClassUDisSeqAct_SetTutorialMessage(wchar_t const *)
//   0x81b6f0  public: static class UClass * __cdecl UDisSeqAct_EnableSystemicTutorials::GetPrivateStaticClassUDisSeqAct_EnableSystemicTutorials(wchar_t const *)
//   0x81b780  public: static class UClass * __cdecl UDisSeqAct_ShowLocationDiscovery::GetPrivateStaticClassUDisSeqAct_ShowLocationDiscovery(wchar_t const *)
//   0x81b810  public: static class UClass * __cdecl UDisSeqAct_ShowTargetNotification::GetPrivateStaticClassUDisSeqAct_ShowTargetNotification(wchar_t const *)
//   0x81d840  public: static class UClass * __cdecl UDisSeqAct_ShowHUDMessage::StaticClassNoInline(void)
//   0x81d870  public: static class UClass * __cdecl UDisSeqAct_SetTutorialMessage::StaticClassNoInline(void)
//   0x81d8a0  public: static class UClass * __cdecl UDisSeqAct_EnableSystemicTutorials::StaticClassNoInline(void)
//   0x81d8d0  public: static class UClass * __cdecl UDisSeqAct_ShowLocationDiscovery::StaticClassNoInline(void)
//   0x81d900  public: static class UClass * __cdecl UDisSeqAct_ShowTargetNotification::StaticClassNoInline(void)
//   0x81ec80  public: static class UClass * __cdecl UDisGFxMoviePlayerHUD::GetPrivateStaticClassUDisGFxMoviePlayerHUD(wchar_t const *)
//   0x81ed10  public: static class UClass * __cdecl UDisGFxMoviePlayerHUDFX::GetPrivateStaticClassUDisGFxMoviePlayerHUDFX(wchar_t const *)
//   0x81eda0  public: void __thiscall UDisGFxMoviePlayerHUD::OnBoneCharmPickedUp(struct FDisCollectedWhaleBoneCharm const *)
//   0x81f060  public: void __thiscall UDisGFxMoviePlayerHUD::OnElixirPickedUp(enum EElixirType)
//   0x81f130  public: unsigned int __thiscall UDisGFxMoviePlayerHUD::UseTutorialWindow(void)
//   0x820da0  public: static void __cdecl UDisGFxMoviePlayerHUD::InitializePrivateStaticClassUDisGFxMoviePlayerHUD(void)
//   0x820dc0  public: static void __cdecl UDisGFxMoviePlayerHUDFX::InitializePrivateStaticClassUDisGFxMoviePlayerHUDFX(void)
//   0x821d70  public: static class UClass * __cdecl UDisGFxMoviePlayerHUD::StaticClassNoInline(void)
//   0x821da0  public: static class UClass * __cdecl UDisGFxMoviePlayerHUDFX::StaticClassNoInline(void)
