// DishonoredGame/src/disgfxmovieplayermainmenu.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (28):
//   0x7f4a60  public: void __thiscall UDisGFxMoviePlayerMainMenu::PreCommitMapChange(void)
//   0x7f4a70  protected: void __thiscall UDisGFxMoviePlayerMainMenu::SelectController(int)
//   0x7f4b20  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnCampaignTabSelected(void)
//   0x7f4b30  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnDLCTabSelected(void)
//   0x7f4b40  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnDLCClicked(void)
//   0x7f7030  protected: virtual void __thiscall UDisGFxMoviePlayerMainMenu::PreClose(unsigned int)
//   0x800b30  protected: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnMessageBoxResult(class FArkGameEvent const &)
//   0x800b50  public: virtual void __thiscall UDisGFxMoviePlayerPauseMenu::OnLoadLastSaveClicked(void)
//   0x800b80  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnMissionSelected(int)
//   0x800cb0  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::Req_SaveSlotInfos(int)
//   0x806090  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnMissionsClicked(void)
//   0x8181e0  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerMainMenu::GetPrivateStaticClassUDisTweaks_GFxMoviePlayerMainMenu(wchar_t const *)
//   0x81ada0  public: static void __cdecl UDisTweaks_GFxMoviePlayerMainMenu::InitializePrivateStaticClassUDisTweaks_GFxMoviePlayerMainMenu(void)
//   0x81b9f0  public: static class UClass * __cdecl UDisTweaks_GFxMoviePlayerMainMenu::StaticClassNoInline(void)
//   0x81ffe0  public: static class UClass * __cdecl UDisGFxMoviePlayerMainMenu::GetPrivateStaticClassUDisGFxMoviePlayerMainMenu(wchar_t const *)
//   0x820070  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnOptionsClicked(void)
//   0x820080  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OnNewGameConfirm(int)
//   0x820100  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::OpenMissionStats(int)
//   0x8201f0  protected: void __thiscall UDisGFxMoviePlayerMainMenu::StartTrailerTimer(void)
//   0x820250  protected: void __thiscall UDisGFxMoviePlayerMainMenu::ShowTrailer(void)
//   0x820330  protected: void __thiscall UDisGFxMoviePlayerMainMenu::HideTrailer(void)
//   0x820e00  public: virtual void __thiscall UDisGFxMoviePlayerMainMenu::BackToStartScreen(void)
//   0x820f80  protected: void __thiscall UDisGFxMoviePlayerMainMenu::UpdateTrailer(float)
//   0x821e00  protected: virtual void __thiscall UDisGFxMoviePlayerMainMenu::PostStart(void)
//   0x822280  protected: virtual void __thiscall UDisGFxMoviePlayerMainMenu::PreAdvance(float)
//   0x822590  protected: virtual unsigned int __thiscall UDisGFxMoviePlayerMainMenu::FilterButtonInput(int, class FName, unsigned char, unsigned int &)
//   0x822960  public: static void __cdecl UDisGFxMoviePlayerMainMenu::InitializePrivateStaticClassUDisGFxMoviePlayerMainMenu(void)
//   0x8229e0  public: static class UClass * __cdecl UDisGFxMoviePlayerMainMenu::StaticClassNoInline(void)

#include "DishonoredGame.h"

// DISHONORED(written): exec 2013 rva 0x5f0f80 (2012 0x63daf0) -> vtable +612 = 2013 rva 0x7b9a00 (`m_bDLCTabSelected = FALSE`)
void UDisGFxMoviePlayerMainMenu::execOnCampaignTabSelected( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	m_bDLCTabSelected = FALSE;
}

// DISHONORED(written): exec 2013 rva 0x5f7e10 -> vtable +616 = 2013 rva 0x7b9a10 (`m_bDLCTabSelected = TRUE`)
void UDisGFxMoviePlayerMainMenu::execOnDLCTabSelected( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	m_bDLCTabSelected = TRUE;
}

// DISHONORED(written): exec 2013 rva 0x5f1030 -> vtable +628 = 2013 rva 0x7b9a20 (`m_bIsInMissionsMenu = FALSE`)
void UDisGFxMoviePlayerMainMenu::execOnMissionsMenuClosed( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	m_bIsInMissionsMenu = FALSE;
}

// DISHONORED(written): exec 2013 rva 0x5f7f50 -> vtable +640 = 2013 rva 0x7b9a30 (returns the m_bEnablePSStoreAccess bit)
void UDisGFxMoviePlayerMainMenu::execReq_PSStoreEnabled( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	*(INT*)Result = m_bEnablePSStoreAccess;
}

// ---- natives whose retail body is trivial (generated by build/agentAC_work/gen_trivial.py from the 2013 vtables) ----

// DISHONORED(written): 2013 rva 0x5f8030; the retail UDisGFxMoviePlayerMainMenu vtable slot +656 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x59d10) and no retail subclass overrides it
void UDisGFxMoviePlayerMainMenu::execOnDLCListClosed( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
}

// DISHONORED(written): 2013 rva 0x5f7d00; the retail UDisGFxMoviePlayerMainMenu vtable slot +592 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x1cb0c0) and no retail subclass overrides it
void UDisGFxMoviePlayerMainMenu::execOnDeviceSelectionComplete( FFrame& Stack, RESULT_DECL )
{
	P_GET_UBOOL(_bWasSuccessful);
	P_FINISH;
}

// DISHONORED(written): 2013 rva 0x5f0e90; the retail UDisGFxMoviePlayerMainMenu vtable slot +588 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x59d10) and no retail subclass overrides it
void UDisGFxMoviePlayerMainMenu::execOnLoginCancelled( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
}

// DISHONORED(written): 2013 rva 0x5f7ca0; the retail UDisGFxMoviePlayerMainMenu vtable slot +584 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x1cb0c0) and no retail subclass overrides it
void UDisGFxMoviePlayerMainMenu::execOnLoginChange( FFrame& Stack, RESULT_DECL )
{
	P_GET_BYTE(_ControllerId);
	P_FINISH;
}

// ---- end of trivial natives ----

/*-----------------------------------------------------------------------------
	Agent BE (PHASE8.md package BE): the 12 remaining UDisGFxMoviePlayerMainMenu
	natives, and PostStart - the function that actually opens the main menu.

	Agent AW measured the whole C++ contribution of the New Game button as two calls
	(gfx_decision.md 2.4): SetDifficulty, then one console command whose text is
	UDisTweaks_GFxMoviePlayerMainMenu::m_NewGameCommand = "ce ChangeLvl_StartNewGame",
	which is exactly what agent AF's -newgame already issues. Both are here, so the
	button and the switch now go down the same path.
-----------------------------------------------------------------------------*/

#include "gfxui_gfx3.h"
#include "dishonoredutilities.h"
#include "dishonoredutilities_saveload.h"

/** the movie view, or NULL when no movie is open */
static GFxMovieView* DisMainMenuView( UDisGFxMoviePlayerMainMenu* Menu )
{
	FGFxMovie* Movie = Menu->GetMovie();
	return Movie ? Movie->pView.GetPtr() : NULL;
}

/** the main menu's own tweaks; retail takes GetTweaks_Derived and falls back to the class default object */
static UDisTweaks_GFxMoviePlayerMainMenu* DisMainMenuTweaks()
{
	return (UDisTweaks_GFxMoviePlayerMainMenu*)UDisTweaks_GFxMoviePlayerMainMenu::StaticClass()->GetDefaultObject();
}

/** issue one console command on the local player controller, the way every menu command leaves C++ */
static void DisMenuConsoleCommand( const FString& Command )
{
	if( Command.Len() == 0 )
	{
		return;
	}
	if( ADishonoredPlayerController::s_pInstance )
	{
		ADishonoredPlayerController::s_pInstance->ConsoleCommand( Command, TRUE );
	}
}

/** _root.<name>_mc.<Method>() with no arguments - the shape every main-menu screen change has */
static void DisInvokeOnMovieClip( GFxMovieView* View, const char* Path, const char* Method )
{
	if( View == NULL )
	{
		return;
	}
	GFxValue Clip;
	if( View->GetVariable( &Clip, Path ) )
	{
		GFxValue Unused;
		Clip.Invoke( Method, &Unused );
		Unused.ReleaseManaged();
	}
	Clip.ReleaseManaged();
}

// DISHONORED(port): 2013 rva 0x7c1ff0 (agent AF; 2012 body 0x820080). The two calls, in retail's order.
void UDisGFxMoviePlayerMainMenu::execOnNewGameConfirm( FFrame& Stack, RESULT_DECL )
{
	P_GET_INT(_Difficulty);
	P_FINISH;

	ADishonoredGameInfo* GameInfo = DisGetGameInfo();
	if( GameInfo )
	{
		// DISHONORED(port): ADishonoredGameInfo::SetDifficulty writes this member; the setter itself is not
		// declared in this tree, and the member is the whole of what it does.
		GameInfo->m_Difficulty = (BYTE)_Difficulty;
	}
	m_bStartingNewGame = TRUE;
	debugf( TEXT("DISHONORED(bringup): OnNewGameConfirm(difficulty %d): '%s'"), _Difficulty,
		*DisMainMenuTweaks()->m_NewGameCommand );
	DisMenuConsoleCommand( DisMainMenuTweaks()->m_NewGameCommand );
}

// DISHONORED(port): 2013 rva 0x5f8190 exec. Clicking New Game only asks the question; the difficulty choice
// and the confirmation come back as OnNewGameConfirm.
void UDisGFxMoviePlayerMainMenu::execOnNewGameClicked( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	m_Screen = 3;
	// DISHONORED(bringup): with a save present retail first raises the overwrite message box through
	// UDisGlobalUIManager::ShowMessageBox, which is not declared in this tree; the asset's own confirm
	// screen still calls OnNewGameConfirm.
}

// DISHONORED(port): 2013 rva 0x5f81d0 exec, new in 2013 (the 2012 build has only the exec temp). Continue is
// "load the most recent save", which is the load path with the slot chosen for the player.
void UDisGFxMoviePlayerMainMenu::execOnContinueClicked( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	// DISHONORED(port): agent CF - the save list is sorted newest first (2013 rva 0x6086f0 compares m_Time
	// descending), so Continue is row 0. The body behind retail's exec is a vtable slot with no PDB name in
	// either build; the row-0 choice is what the newest-first sort exists for and it is flagged as inferred
	// in resources/docs/agents/agentCF.md.
	UDishonoredEngine* Engine = Cast<UDishonoredEngine>( GEngine );
	FDisSaveGame* SaveGame = Engine ? Engine->GetSaveGame( 0 ) : NULL;
	if( SaveGame == NULL )
	{
		return;
	}
	m_bLoadingGame = TRUE;
	Engine->Dis_Load( SaveGame->m_Slot );
}

// DISHONORED(port): 2012 rva 0x829090 - one console command, m_QuitGameCommand of the menu-base tweaks
void UDisGFxMoviePlayerMainMenu::execOnQuitGameConfirm( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	debugf( TEXT("DISHONORED(bringup): OnQuitGameConfirm: '%s'"),
		m_pMenuBaseTweaks ? *m_pMenuBaseTweaks->m_QuitGameCommand : TEXT("<no menu-base tweaks>") );
	if( m_pMenuBaseTweaks )
	{
		DisMenuConsoleCommand( m_pMenuBaseTweaks->m_QuitGameCommand );
	}
}

// DISHONORED(port): 2012 rva 0x820e00. Back from any screen to the start screen: cancel the trailer timer,
// drop the message box, close mainMenu_mc if it is the screen we are on, then open startScreen_mc.
// m_Screen 1 is the start screen, 3 is the main menu (the values the asset and FilterButtonInput share).
void UDisGFxMoviePlayerMainMenu::execBackToStartScreen( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;

	if( m_MsgBoxID )
	{
		// DISHONORED(port, agent EI): DisGetGlobalUIManager()->HideMessageBox(m_MsgBoxID), 2013 0x83dc50
		HideMessageBox();
	}
	m_fTrailerTimer = 0.f;

	if( m_Screen != 1 )
	{
		GFxMovieView* View = DisMainMenuView( this );
		if( m_Screen == 3 )
		{
			DisInvokeOnMovieClip( View, "_root.mainMenu_mc", "Close" );
		}
		DisInvokeOnMovieClip( View, "_root.startScreen_mc", "Open" );
	}
	m_LoginStep = 1;
	m_Screen = 1;
}

// DISHONORED(port): 2012 rva 0x806090 - the missions screen. The list itself is per-mission profile data.
void UDisGFxMoviePlayerMainMenu::execOnMissionsClicked( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	m_bIsInMissionsMenu = TRUE;
	// DISHONORED(bringup): retail builds the mission list from UArkProfileSettings::GetMissionData and the
	// m_MissionStatsTweaks array and invokes _root.missions_mc.Open with it; UArkProfileSettings has no
	// accessors in this tree.
}

// DISHONORED(port): 2012 rva 0x800b80 - picking a mission runs that mission's console command out of
// m_DLCCommands, skipping the entries with no command
void UDisGFxMoviePlayerMainMenu::execOnMissionSelected( FFrame& Stack, RESULT_DECL )
{
	P_GET_INT(_MissionIdx);
	P_FINISH;

	if( !m_bIsInMissionsMenu )
	{
		return;
	}
	INT Selectable = 0;
	for( INT Index = 0; Index < ARRAY_COUNT(m_DLCCommands); Index++ )
	{
		if( m_DLCCommands[Index].m_MissionNumber == 0 )
		{
			continue;
		}
		if( Selectable++ == _MissionIdx )
		{
			DisMenuConsoleCommand( m_DLCCommands[Index].m_Command );
			return;
		}
	}
}

// DISHONORED(port): 2012 rva 0x820100 - the per-mission stats screen is its own movie player, opened by
// UDisGlobalUIManager once the matching UDisTweaks_MissionStats is found
void UDisGFxMoviePlayerMainMenu::execOpenMissionStats( FFrame& Stack, RESULT_DECL )
{
	P_GET_INT(_MissionIdx);
	P_FINISH;
	// DISHONORED(bringup): UArkProfileSettings::GetMissionData(_MissionIdx) picks the setup index, the
	// matching UDisTweaks_MissionStats is looked up in the main-menu tweaks, and
	// DisGetGlobalUIManager() opens UDisGFxMoviePlayerMissionStats with it. Neither accessor is declared.
}

// DISHONORED(port): 2012 rva 0x7f4b40 - the DLC screen; the enumeration is the platform's
void UDisGFxMoviePlayerMainMenu::execOnDLCClicked( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	m_bListingDLCs = TRUE;
	m_fDLCListingTimer = 0.f;
	// DISHONORED(bringup): the list comes from UDisGlobalDLCManager / UDownloadableContentEnumerator
	// (PC retail enumerates nothing), which is why this screen is empty on PC anyway.
}

// DISHONORED(port): 2013 rva 0x5f7fd0 exec - deleting downloadable content is the enumerator's job
void UDisGFxMoviePlayerMainMenu::execDeleteDLC( FFrame& Stack, RESULT_DECL )
{
	P_GET_INT(_DLCIdx);
	P_FINISH;
	m_bDeletingDLC = TRUE;
	// DISHONORED(bringup): UDownloadableContentEnumerator::DeleteDLC (2012 0xea8a0) by name; the DLC manager
	// is not wired up in this tree.
}

// DISHONORED(port): 2013 rva 0x5f1160 exec - "is the downloadable content on the hard disk"; on PC retail
// answers from the DLC manager, and with none present the answer is no
void UDisGFxMoviePlayerMainMenu::execReq_DLConHDD( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	// DISHONORED(bringup): UDisGlobalDLCManager's HDD query; not declared in this tree.
}

// DISHONORED(port): 2013 rva 0x5f80b0 exec - the DLC06 (Knife of Dunwall) progression carry-over, chosen
// from the same list the missions screen shows
void UDisGFxMoviePlayerMainMenu::execUseDLC06Progression( FFrame& Stack, RESULT_DECL )
{
	P_GET_INT(_ListIdx);
	P_FINISH;
	// DISHONORED(bringup): retail copies the selected DLC06 save's story flags into the new game through
	// UDishonoredEngine's save list; blocked on the same FDisSaveGame declaration.
}

/*-----------------------------------------------------------------------------
	PostStart - what opens the menu. Agent AW's decompile of 2012 0x821e00 shows it
	does nothing but drive ActionScript, and this is that, verbatim in shape: close or
	open the start screen, then open mainMenu_mc with the four booleans the asset lays
	the buttons out from.
-----------------------------------------------------------------------------*/

void DisMainMenuPostStart( UDisGFxMoviePlayerMainMenu* Menu )
{
	GFxMovieView* View = DisMainMenuView( Menu );
	if( View == NULL )
	{
		return;
	}
	UDishonoredEngine* Engine = Cast<UDishonoredEngine>( GEngine );
	const UBOOL bSaveLoadEnabled = Engine && Engine->m_bSaveLoadEnabled;
	// DISHONORED(port): agent CF - retail's PostStart (2012 rva 0x821e00) computes exactly
	// !Engine || Engine->HasSaveGame(0), i.e. a missing engine reads as "there is a save"
	const UBOOL bHasSaveGame = ( Engine == NULL ) || Engine->HasSaveGame( 0 );

	if( Menu->m_Screen == 1 )
	{
		DisInvokeOnMovieClip( View, "_root.startScreen_mc", "Open" );
		return;
	}

	DisInvokeOnMovieClip( View, "_root.startScreen_mc", "Close" );

	GFxValue MainMenu;
	if( View->GetVariable( &MainMenu, "_root.mainMenu_mc" ) )
	{
		AutoGFxValueArray( Args, 4 );
		Args(0).SetBoolean( bHasSaveGame ? true : false );
		Args(1).SetBoolean( bHasSaveGame ? true : false );
		Args(2).SetBoolean( true );
		Args(3).SetBoolean( bSaveLoadEnabled ? true : false );
		GFxValue Unused;
		MainMenu.Invoke( "Open", &Unused, Args, 4 );
		Unused.ReleaseManaged();
	}
	MainMenu.ReleaseManaged();
	// DISHONORED(bringup): retail then starts the map-image package loading through
	// UDisGlobalUIManager::LoadTexturePackageAsync(m_MapLargeImagePackage); not declared in this tree.
}
// ------ DG tail ------


/*-----------------------------------------------------------------------------
	The main menu's own state machine. Agent DG.

	Three retail bodies, and between them they are what turns the asset from "every screen drawn on
	top of every other" into a menu:

	  PostStart         2012 0x821e00  opens startScreen_mc or mainMenu_mc, depending on the local
	                                   player's m_bShowTitleScreen bit
	  FilterButtonInput 2012 0x822590  on the start screen, any key press closes it and moves to
	                                   login step 7
	  PreAdvance        2012 0x822280  at login step 7, once the profile and the save list are ready,
	                                   closes the start screen and opens mainMenu_mc with the four
	                                   booleans the asset's Open() takes

	m_Screen is the enum the two share: 1 = start screen, 2 = in transit, 3 = the menu proper.
-----------------------------------------------------------------------------*/

/** the two bodies of disgfxmovieplayerbase.cpp this unit's seam installs */
void DisGFxMoviePlayerInitTexts( UDisGFxMoviePlayerBase* Player );
// agent EK (PHASE11 EK): the HUD's two seam bodies, disgfxmovieplayerhud.cpp
void DisGFxMoviePlayerHUDPostStart( UDisGFxMoviePlayerHUD* HUD );
void DisGFxMoviePlayerHUDPreAdvance( UDisGFxMoviePlayerHUD* HUD, FLOAT DeltaTime );
UBOOL DisGFxMoviePlayerFilterButtonInput( UDisGFxMoviePlayerBase* Player, INT ControllerId,
	FName Key, BYTE Event, UBOOL& bHandled );

/** `_root.<clip>.<method>(args)` - the GetVariable + ObjectInterface::Invoke pair every one of the
    three bodies uses, which GFxMovieView::Invoke resolves from the same path in one call */
static void DisMainMenuInvoke( UDisGFxMoviePlayerMainMenu* Menu, const char* Path,
	const GFxValue* Args, UINT NumArgs )
{
	GFxMovieView* View = DisMainMenuView( Menu );
	if( View == NULL )
	{
		return;
	}
	GFxValue Result;
	const UBOOL bOk = View->Invoke( Path, &Result, Args, NumArgs );
	debugf( TEXT("DISHONORED(bringup): main menu: %s(%d) -> %s"), ANSI_TO_TCHAR( Path ), NumArgs,
		bOk ? TEXT("ok") : TEXT("NOT FOUND") );
}

/** mainMenu_mc.Open(bCanContinue, bCanLoad, bCanNewGame, bSaveLoadEnabled) - the four booleans of
    both retail call sites, in their order */
static void DisMainMenuOpenMenu( UDisGFxMoviePlayerMainMenu* Menu )
{
	UDishonoredEngine* Engine = Cast<UDishonoredEngine>( GEngine );
	// DISHONORED(bringup): retail asks UDishonoredEngine::HasSaveGame(0) and IsSaveLoadEnabled();
	// neither is ported, and retail's own `!Engine || ...` shape means a missing engine answers TRUE,
	// which is the conservative arm - the menu offers Continue and Load and the entry reports back.
	const UBOOL bHasSave = TRUE;
	const UBOOL bSaveLoadEnabled = TRUE;
	(void)Engine;
	GFxValue Args[4];
	Args[0].SetBoolean( bHasSave ? true : false );
	Args[1].SetBoolean( bHasSave ? true : false );
	Args[2].SetBoolean( true );
	Args[3].SetBoolean( bSaveLoadEnabled ? true : false );
	DisMainMenuInvoke( Menu, "_root.mainMenu_mc.Open", Args, 4 );
	Menu->m_Screen = 3;
}

static void DisMainMenuCloseScreen( UDisGFxMoviePlayerMainMenu* Menu, BYTE Screen )
{
	if( Screen == 1 )
	{
		DisMainMenuInvoke( Menu, "_root.startScreen_mc.Close", NULL, 0 );
	}
	else if( Screen == 3 )
	{
		DisMainMenuInvoke( Menu, "_root.mainMenu_mc.Close", NULL, 0 );
	}
}

// DISHONORED(port): 2012 rva 0x821e00
void DisGFxMoviePlayerMainMenuPostStart( UDisGFxMoviePlayerMainMenu* Menu )
{
	Menu->m_LoginStep = 0;
	Menu->m_Screen = 0;
	Menu->m_DelegatesControllerId = -1;
	Menu->Advance( 0.f );

	// DISHONORED(bringup): retail also calls RegisterCommonDelegates through ProcessEvent here; the
	// UnrealScript that implements it is the online-subsystem login flow and nothing in this build
	// has a profile to sign in with.
	UDisLocalPlayer* LocalPlayer = DisGetLocalPlayer();
	const UBOOL bTitleScreen = GIsEditor || ( LocalPlayer != NULL && LocalPlayer->m_bShowTitleScreen );
	Menu->m_fTrailerTimer = 0.f;
	if( bTitleScreen )
	{
		if( Menu->m_Screen != 1 )
		{
			DisMainMenuCloseScreen( Menu, Menu->m_Screen );
			DisMainMenuInvoke( Menu, "_root.startScreen_mc.Open", NULL, 0 );
		}
		Menu->m_LoginStep = 1;
		Menu->m_Screen = 1;
	}
	else
	{
		if( Menu->m_Screen != 3 )
		{
			DisMainMenuCloseScreen( Menu, Menu->m_Screen );
			DisMainMenuOpenMenu( Menu );
		}
		Menu->m_LoginStep = 8;
		Menu->m_Screen = 3;
	}
}

// DISHONORED(port): 2012 rva 0x822280
void DisGFxMoviePlayerMainMenuPreAdvance( UDisGFxMoviePlayerMainMenu* Menu, FLOAT DeltaTime )
{
	if( Menu->m_LoginStep != 7 )
	{
		return;
	}
	// DISHONORED(bringup): retail waits for the profile read (AsyncState 0 or 3) and for
	// UDishonoredEngine::IsSaveGameListReady. Neither the profile read nor the save list exists in
	// this build, and retail's own shape answers "ready" when the engine cast fails, so the step
	// completes on the next advance.
	DisMainMenuCloseScreen( Menu, Menu->m_Screen );
	DisMainMenuOpenMenu( Menu );
	Menu->m_LoginStep = 8;
	Menu->m_Screen = 3;
}

// DISHONORED(port): 2012 rva 0x822590. On the start screen a key press - any key, on press rather
// than on release - closes it and moves to login step 7, which is where PreAdvance takes over.
UBOOL DisGFxMoviePlayerMainMenuFilterButtonInput( UDisGFxMoviePlayerMainMenu* Menu, INT ControllerId,
	FName Key, BYTE Event, UBOOL& bHandled )
{
	if( Menu->m_LoginStep == 1 )
	{
		if( Event == IE_Pressed )
		{
			Menu->m_fTrailerTimer = 0.f;
			if( Menu->m_Screen != 2 )
			{
				DisMainMenuCloseScreen( Menu, Menu->m_Screen );
			}
			Menu->m_LoginStep = 7;
			Menu->m_Screen = 2;
			debugf( TEXT("DISHONORED(bringup): main menu: start screen dismissed by %s"), *Key.ToString() );
		}
		bHandled = TRUE;
		return TRUE;
	}
	return FALSE;
}


// DISHONORED(port): 2012 0x7fa4c0. The init call, which is the only one this bring-up makes: there
// is no gamepad state to change later. Retail compares against the cached bit and early-outs; with
// bInit set it always runs.
static void DisGFxMoviePlayerUpdateGamepadUseForAS( UDisGFxMoviePlayerBase* Base )
{
	FGFxMovie* Movie = Base->GetMovie();
	GFxMovieView* View = Movie ? Movie->pView.GetPtr() : NULL;
	if( View == NULL )
	{
		return;
	}
	// IsUsingGamepad is a script virtual this build does not reach; the PC default is the mouse.
	const UBOOL bUsingGamepad = FALSE;
	GFxValue Flag;
	Flag.SetBoolean( bUsingGamepad ? true : false );
	View->SetMouseCursorCount( bUsingGamepad ? 0 : 1 );
	View->SetVariable( "_global.bUsingGamepad", Flag, GFxMovie::SV_Sticky );

	GFxValue UIBase;
	if( View->GetVariable( &UIBase, "_root.UIBase" ) && UIBase.IsObject() )
	{
		GFxValue Result;
		UIBase.Invoke( "UpdateControllerButtonsInstances", &Result, NULL, 0 );
	}
}

/*-----------------------------------------------------------------------------
	The seam. gfxuiengine.h says why these arrive as hooks rather than as the virtual overrides
	retail has; the bodies and the call sites are retail's.
-----------------------------------------------------------------------------*/

static void DisGFxMoviePlayerPreLoaded( UGFxMoviePlayer* Player )
{
	if( UDisGFxMoviePlayerBase* Base = Cast<UDisGFxMoviePlayerBase>( Player ) )
	{
		// DISHONORED(port): 2012 0x822820, the three calls retail makes after UGFxMoviePlayer::PreLoad,
		// in retail's order. PlatformName is read by the content before anything else - the start
		// screen chooses t_PressAnyKey or t_PressStart on it.
		FGFxMovie* Movie = Base->GetMovie();
		GFxMovieView* View = Movie ? Movie->pView.GetPtr() : NULL;
		if( View != NULL )
		{
			GFxValue Platform;
			Platform.SetStringW( TEXT("PC") );
			View->SetVariable( "_global.PlatformName", Platform, GFxMovie::SV_Sticky );
		}
		DisGFxMoviePlayerInitTexts( Base );
		DisGFxMoviePlayerUpdateGamepadUseForAS( Base );
	}
}

static void DisGFxMoviePlayerStarted( UGFxMoviePlayer* Player )
{
	// DISHONORED(bringup): UDisGlobalUIManager::OnMovieStackChanged (the movie stack's focus and
	// pause bookkeeping) runs between the two in retail; UDisGlobalUIManager has no movie stack in
	// this build because nothing but the bring-up switch opens a movie.
	if( UDisGFxMoviePlayerMainMenu* Menu = Cast<UDisGFxMoviePlayerMainMenu>( Player ) )
	{
		DisGFxMoviePlayerMainMenuPostStart( Menu );
	}
	// agent EK: UDisGFxMoviePlayerHUD::PostStart, retail vtable slot 117 (2013 rva 0x795650)
	else if( UDisGFxMoviePlayerHUD* HUD = Cast<UDisGFxMoviePlayerHUD>( Player ) )
	{
		DisGFxMoviePlayerHUDPostStart( HUD );
	}
}

static void DisGFxMoviePlayerPreAdvance( UGFxMoviePlayer* Player, FLOAT DeltaTime )
{
	if( UDisGFxMoviePlayerMainMenu* Menu = Cast<UDisGFxMoviePlayerMainMenu>( Player ) )
	{
		DisGFxMoviePlayerMainMenuPreAdvance( Menu, DeltaTime );
	}
	// agent EK: UDisGFxMoviePlayerHUD::PreAdvance, retail vtable slot 119 (2013 rva 0x7b2280)
	else if( UDisGFxMoviePlayerHUD* HUD = Cast<UDisGFxMoviePlayerHUD>( Player ) )
	{
		DisGFxMoviePlayerHUDPreAdvance( HUD, DeltaTime );
	}
}

static UBOOL DisGFxMoviePlayerFilterButton( UGFxMoviePlayer* Player, INT ControllerId, FName Key,
	BYTE Event, UBOOL& bHandled )
{
	UDisGFxMoviePlayerBase* Base = Cast<UDisGFxMoviePlayerBase>( Player );
	if( Base == NULL )
	{
		return FALSE;
	}
	if( UDisGFxMoviePlayerMainMenu* Menu = Cast<UDisGFxMoviePlayerMainMenu>( Base ) )
	{
		if( DisGFxMoviePlayerMainMenuFilterButtonInput( Menu, ControllerId, Key, Event, bHandled ) )
		{
			return TRUE;
		}
	}
	return DisGFxMoviePlayerFilterButtonInput( Base, ControllerId, Key, Event, bHandled );
}

/** installs the four bodies above. A file-scope constructor is safe here and only here: it writes a
    zero-initialised pointer in another translation unit, which is ordered by the standard, and it
    reads nothing - in particular not appCmdLine(), which is what PHASE9.md's rule is about. */
static struct FDisGFxMoviePlayerSeam
{
	FDisGFxMoviePlayerSeam()
	{
		GGFxMoviePlayerPreLoadedHook = &DisGFxMoviePlayerPreLoaded;
		GGFxMoviePlayerStartedHook = &DisGFxMoviePlayerStarted;
		GGFxMoviePlayerPreAdvanceHook = &DisGFxMoviePlayerPreAdvance;
		GGFxMoviePlayerFilterButtonHook = &DisGFxMoviePlayerFilterButton;
	}
} GDisGFxMoviePlayerSeam;
