// DishonoredGame/src/dishonoredhud.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (24):
//   0x62fc60  public: static void __cdecl ADishonoredHUD::InitializePrivateStaticClassADishonoredHUD(void)
//   0x62fc80  public: virtual void __thiscall ADishonoredHUD::BeginDestroy(void)
//   0x62fcb0  public: void __thiscall ADishonoredHUD::SerializeForGameSave(class FArchive &, enum ESaveLoadLocation)
//   0x62fcd0  public: virtual void __thiscall ADishonoredHUD::DebugOnly(class FName, class FName, class FName, class FName, class FName)
//   0x62fce0  public: void __thiscall ADishonoredHUD::EnableHUDElements(enum eDisHUDMaskLevel, int)
//   0x62fd00  public: void __thiscall ADishonoredHUD::DisableHUDElements(enum eDisHUDMaskLevel, int)
//   0x62fd20  public: unsigned int __thiscall ADishonoredHUD::IsHUDElementEnabled(enum eDisHUDMaskLevel, int)const
//   0x62fd40  public: unsigned int __thiscall ADishonoredHUD::IsHUDElementEnabledByAll(int)const
//   0x62fd70  public: unsigned int __thiscall ADishonoredHUD::IsHUDElementEnabledOnce(int)const
//   0x62fda0  public: void __thiscall ADishonoredHUD::RequestPlayerInfoDisplay(unsigned int)
//   0x62fdf0  public: void __thiscall ADishonoredHUD::UpdatePlayerInfoDisplay(float, unsigned int)
//   0x6402f0  public: virtual void __thiscall ADishonoredHUD::PostBeginPlay(void)
//   0x640330  public: void __thiscall ADishonoredHUD::SerializeForGameLoad(class FArchive &, enum ESaveLoadLocation)
//   0x640370  public: virtual void __thiscall ADishonoredHUD::DrawHUD_UIBlackStripes(void)
//   0x6405b0  public: virtual void __thiscall ADishonoredHUD::PlayerDisplayDebug_Native(float &, float &)
//   0x643370  public: void __thiscall ADishonoredHUD::AddPostRenderedActor(class AActor *, unsigned int)
//   0x643560  public: void __thiscall ADishonoredHUD::RemovePostRenderedActor(class AActor *)
//   0x643600  protected: void __thiscall ADishonoredHUD::TickHUD_Powers(float)
//   0x6487e0  public: virtual unsigned int __thiscall ADishonoredHUD::Tick(float, enum ELevelTick)
//   0x64b610  public: virtual void __thiscall ADishonoredHUD::DrawHUD_Native(void)
//   0x64b650  public: virtual void __thiscall ADishonoredHUD::DebugClear(void)
//   0x653500  public: __thiscall ADishonoredHUD::ADishonoredHUD(void)
//   0x654ea0  public: static class UClass * __cdecl ADishonoredHUD::GetPrivateStaticClassADishonoredHUD(wchar_t const *)
//   0x655f20  public: static class UClass * __cdecl ADishonoredHUD::StaticClassNoInline(void)

#include "DishonoredGame.h"

// DISHONORED(written): 2013 rva 0x605f10 (2012 0x64b610). The first call is GEngine->RenderDebugMenu(Canvas) (UEngine vtable +388),
// which UDishonoredEngine leaves at the empty base body (2013 rva 0x1cb0c0): the debug menu is compiled out.
void ADishonoredHUD::DrawHUD_Native()
{
	if( PlayerOwner->Pawn )
	{
		m_PowerMenu->Render( Canvas );
	}
}

// DISHONORED(written): 2013 rva 0x5fa730 (2012 0x6405b0, same bytes)
void ADishonoredHUD::PlayerDisplayDebug_Native( FLOAT& OutYL, FLOAT& OutYPos )
{
	ADishonoredPlayerPawn::s_pInstance->eventDisplayDebug_Script( this, OutYL, OutYPos );
}

// DISHONORED(written): 2013 rva 0x605f50 (2012 0x64b650)
void ADishonoredHUD::DebugClear()
{
	DebugDisplay.Empty();
}

// DISHONORED(written): 2013 rva 0x5f6340 = AAutoTestManager::execDoSentinelActionPerLoadedLevel_Native (vtable +944)
void ADishonoredHUD::execDrawHUD_Native( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	DrawHUD_Native();
}

// DISHONORED(written): 2013 rva 0x5f8400 (2012 0x63e120) (vtable +948)
void ADishonoredHUD::execPlayerDisplayDebug_Native( FFrame& Stack, RESULT_DECL )
{
	P_GET_FLOAT_REF(out_YL);
	P_GET_FLOAT_REF(out_YPos);
	P_FINISH;
	PlayerDisplayDebug_Native( out_YL, out_YPos );
}

// DISHONORED(written): 2013 rva 0x5f26f0 = ASplineActor::execBreakAllConnectionsFrom (vtable +964)
void ADishonoredHUD::execDebugClear( FFrame& Stack, RESULT_DECL )
{
	P_FINISH;
	DebugClear();
}

// DISHONORED(written): 2013 rva 0x5f8390 (2012 0x63e0b0, same bytes): the retail exec reads its two parameters and does nothing
void ADishonoredHUD::execRenderNonHUD_Native( FFrame& Stack, RESULT_DECL )
{
	P_GET_STRUCT(FVector, ViewPoint);
	P_GET_STRUCT(FRotator, ViewRot);
	P_FINISH;
}

// ---- natives whose retail body is trivial (generated by build/agentAC_work/gen_trivial.py from the 2013 vtables) ----

// DISHONORED(written): 2013 rva 0x5f86e0; the retail ADishonoredHUD vtable slot +968 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x5ea090) and no retail subclass overrides it
void ADishonoredHUD::execDebugOnly( FFrame& Stack, RESULT_DECL )
{
	P_GET_NAME_OPTX(DebugType1, NAME_None);
	P_GET_NAME_OPTX(DebugType2, NAME_None);
	P_GET_NAME_OPTX(DebugType3, NAME_None);
	P_GET_NAME_OPTX(DebugType4, NAME_None);
	P_GET_NAME_OPTX(DebugType5, NAME_None);
	P_FINISH;
}

// DISHONORED(written): 2013 rva 0x5f8660; the retail ADishonoredHUD vtable slot +960 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x128ad0) and no retail subclass overrides it
void ADishonoredHUD::execDebugDisable( FFrame& Stack, RESULT_DECL )
{
	P_GET_NAME_OPTX(DebugType, NAME_None);
	P_FINISH;
}

// DISHONORED(written): 2013 rva 0x5f85e0; the retail ADishonoredHUD vtable slot +956 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x128ad0) and no retail subclass overrides it
void ADishonoredHUD::execDebugEnable( FFrame& Stack, RESULT_DECL )
{
	P_GET_NAME_OPTX(DebugType, NAME_None);
	P_FINISH;
}

// DISHONORED(written): 2013 rva 0x5f84f0; the retail ADishonoredHUD vtable slot +952 it dispatches to is an empty body (or a jump to one; DisGetGameInfo() calls have no side effect)
// (2013 rva 0x128ad0) and no retail subclass overrides it
void ADishonoredHUD::execShowDebugInfo_Native( FFrame& Stack, RESULT_DECL )
{
	P_GET_FLOAT_REF(out_YL);
	P_GET_FLOAT_REF(out_YPos);
	P_FINISH;
}

// ---- end of trivial natives ----
