// DishonoredGame/src/dishonoreddamagetype.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (147):
//   0x630a10  public: static void __cdecl UDishonoredDamageType::InitializePrivateStaticClassUDishonoredDamageType(void)
//   0x630a30  public: static void __cdecl UDisDamageType_RagdollImpact::InitializePrivateStaticClassUDisDamageType_RagdollImpact(void)
//   0x644870  public: static class UClass * __cdecl UDishonoredDamageType::GetPrivateStaticClassUDishonoredDamageType(wchar_t const *)
//   0x644900  public: static class UClass * __cdecl UDisDamageType_Assassination::GetPrivateStaticClassUDisDamageType_Assassination(wchar_t const *)
//   0x644990  public: static class UClass * __cdecl UDishonoredDamageType_Bash::GetPrivateStaticClassUDishonoredDamageType_Bash(wchar_t const *)
//   0x644a20  public: static class UClass * __cdecl UDishonoredDamageType_Bite::GetPrivateStaticClassUDishonoredDamageType_Bite(wchar_t const *)
//   0x644ab0  public: static class UClass * __cdecl UDisDamageType_BlinkPush::GetPrivateStaticClassUDisDamageType_BlinkPush(wchar_t const *)
//   0x644b40  public: static class UClass * __cdecl UDisDamageType_BlinkKnockdown::GetPrivateStaticClassUDisDamageType_BlinkKnockdown(wchar_t const *)
//   0x644bd0  public: static class UClass * __cdecl UDishonoredDamageType_Bullet::GetPrivateStaticClassUDishonoredDamageType_Bullet(wchar_t const *)
//   0x644c60  public: static class UClass * __cdecl UDishonoredDamageType_BulletMedium::GetPrivateStaticClassUDishonoredDamageType_BulletMedium(wchar_t const *)
//   0x644cf0  public: static class UClass * __cdecl UDishonoredDamageType_BulletFar::GetPrivateStaticClassUDishonoredDamageType_BulletFar(wchar_t const *)
//   0x644d80  public: static class UClass * __cdecl UDishonoredDamageType_BulletBlast::GetPrivateStaticClassUDishonoredDamageType_BulletBlast(wchar_t const *)
//   0x644e10  public: static class UClass * __cdecl UDisDamageType_Choke::GetPrivateStaticClassUDisDamageType_Choke(wchar_t const *)
//   0x644ea0  public: static class UClass * __cdecl UDisDamageType_CrushPush::GetPrivateStaticClassUDisDamageType_CrushPush(wchar_t const *)
//   0x644f30  public: static class UClass * __cdecl UDisDamageType_CrushKnockdown::GetPrivateStaticClassUDisDamageType_CrushKnockdown(wchar_t const *)
//   0x644fc0  public: static class UClass * __cdecl UDishonoredDamageType_Electricity::GetPrivateStaticClassUDishonoredDamageType_Electricity(wchar_t const *)
//   0x645050  public: static class UClass * __cdecl UDishonoredDamageType_Explosion::GetPrivateStaticClassUDishonoredDamageType_Explosion(wchar_t const *)
//   0x6450e0  public: static class UClass * __cdecl UDishonoredDamageType_FastHit::GetPrivateStaticClassUDishonoredDamageType_FastHit(wchar_t const *)
//   0x645170  public: static class UClass * __cdecl UDisDamageType_FastHit_Left::GetPrivateStaticClassUDisDamageType_FastHit_Left(wchar_t const *)
//   0x645200  public: static class UClass * __cdecl UDisDamageType_FastHit_Right::GetPrivateStaticClassUDisDamageType_FastHit_Right(wchar_t const *)
//   0x645290  public: static class UClass * __cdecl UDisDamageType_FastHit_Up::GetPrivateStaticClassUDisDamageType_FastHit_Up(wchar_t const *)
//   0x645320  public: static class UClass * __cdecl UDisDamageType_FastHit_Up_Left::GetPrivateStaticClassUDisDamageType_FastHit_Up_Left(wchar_t const *)
//   0x6453b0  public: static class UClass * __cdecl UDisDamageType_FastHit_Up_Right::GetPrivateStaticClassUDisDamageType_FastHit_Up_Right(wchar_t const *)
//   0x645440  public: static class UClass * __cdecl UDisDamageType_GenericSleep::GetPrivateStaticClassUDisDamageType_GenericSleep(wchar_t const *)
//   0x6454d0  public: static class UClass * __cdecl UDisDamageType_ImpactHit::GetPrivateStaticClassUDisDamageType_ImpactHit(wchar_t const *)
//   0x645560  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Left::GetPrivateStaticClassUDisDamageType_ImpactHit_Left(wchar_t const *)
//   0x6455f0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Right::GetPrivateStaticClassUDisDamageType_ImpactHit_Right(wchar_t const *)
//   0x645680  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Up::GetPrivateStaticClassUDisDamageType_ImpactHit_Up(wchar_t const *)
//   0x645710  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Up_Left::GetPrivateStaticClassUDisDamageType_ImpactHit_Up_Left(wchar_t const *)
//   0x6457a0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Up_Right::GetPrivateStaticClassUDisDamageType_ImpactHit_Up_Right(wchar_t const *)
//   0x645830  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline::GetPrivateStaticClassUDisDamageType_ImpactHit_Adrenaline(wchar_t const *)
//   0x6458c0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Left::GetPrivateStaticClassUDisDamageType_ImpactHit_Adrenaline_Left(wchar_t const *)
//   0x645950  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Right::GetPrivateStaticClassUDisDamageType_ImpactHit_Adrenaline_Right(wchar_t const *)
//   0x6459e0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Up::GetPrivateStaticClassUDisDamageType_ImpactHit_Adrenaline_Up(wchar_t const *)
//   0x645a70  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Up_Left::GetPrivateStaticClassUDisDamageType_ImpactHit_Adrenaline_Up_Left(wchar_t const *)
//   0x645b00  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Up_Right::GetPrivateStaticClassUDisDamageType_ImpactHit_Adrenaline_Up_Right(wchar_t const *)
//   0x645b90  public: static class UClass * __cdecl UDisDamageType_InstantSleep::GetPrivateStaticClassUDisDamageType_InstantSleep(wchar_t const *)
//   0x645c20  public: static class UClass * __cdecl UDishonoredDamageType_FrontalImpale::GetPrivateStaticClassUDishonoredDamageType_FrontalImpale(wchar_t const *)
//   0x645cb0  public: static class UClass * __cdecl UDishonoredDamageType_Knockdown::GetPrivateStaticClassUDishonoredDamageType_Knockdown(wchar_t const *)
//   0x645d40  public: static class UClass * __cdecl UDisDamageType_Musical::GetPrivateStaticClassUDisDamageType_Musical(wchar_t const *)
//   0x645dd0  public: static class UClass * __cdecl UDishonoredDamageType_Plague::GetPrivateStaticClassUDishonoredDamageType_Plague(wchar_t const *)
//   0x645e60  public: static class UClass * __cdecl UDishonoredDamageType_Projectile::GetPrivateStaticClassUDishonoredDamageType_Projectile(wchar_t const *)
//   0x645ef0  public: static class UClass * __cdecl UDishonoredDamageType_Projectile_Stealth::GetPrivateStaticClassUDishonoredDamageType_Projectile_Stealth(wchar_t const *)
//   0x645f80  public: static class UClass * __cdecl UDisDamageType_RagdollImpact::GetPrivateStaticClassUDisDamageType_RagdollImpact(wchar_t const *)
//   0x646010  public: static class UClass * __cdecl UDisDamageType_Sleep_Deferred::GetPrivateStaticClassUDisDamageType_Sleep_Deferred(wchar_t const *)
//   0x6460a0  public: static class UClass * __cdecl UDisDamageType_Slide::GetPrivateStaticClassUDisDamageType_Slide(wchar_t const *)
//   0x646130  public: static class UClass * __cdecl UDishonoredDamageType_SpawnRatSwarm::GetPrivateStaticClassUDishonoredDamageType_SpawnRatSwarm(wchar_t const *)
//   0x6461c0  public: static class UClass * __cdecl UDisDamageType_SpringRazorPlaced::GetPrivateStaticClassUDisDamageType_SpringRazorPlaced(wchar_t const *)
//   0x646250  public: static class UClass * __cdecl UDishonoredDamageType_Stomped::GetPrivateStaticClassUDishonoredDamageType_Stomped(wchar_t const *)
//   0x6462e0  public: static class UClass * __cdecl UDisDamageType_Water::GetPrivateStaticClassUDisDamageType_Water(wchar_t const *)
//   0x646370  public: static class UClass * __cdecl UDisDamageType_WindBlast::GetPrivateStaticClassUDisDamageType_WindBlast(wchar_t const *)
//   0x6499f0  public: static class UClass * __cdecl UDishonoredDamageType::StaticClassNoInline(void)
//   0x649a20  public: static void __cdecl UDisDamageType_Assassination::InitializePrivateStaticClassUDisDamageType_Assassination(void)
//   0x649a40  public: static void __cdecl UDishonoredDamageType_Bash::InitializePrivateStaticClassUDishonoredDamageType_Bash(void)
//   0x649a60  public: static void __cdecl UDishonoredDamageType_Bite::InitializePrivateStaticClassUDishonoredDamageType_Bite(void)
//   0x649a80  public: static void __cdecl UDisDamageType_BlinkPush::InitializePrivateStaticClassUDisDamageType_BlinkPush(void)
//   0x649aa0  public: static void __cdecl UDisDamageType_BlinkKnockdown::InitializePrivateStaticClassUDisDamageType_BlinkKnockdown(void)
//   0x649ac0  public: static void __cdecl UDisDamageType_Choke::InitializePrivateStaticClassUDisDamageType_Choke(void)
//   0x649ae0  public: static void __cdecl UDisDamageType_CrushPush::InitializePrivateStaticClassUDisDamageType_CrushPush(void)
//   0x649b00  public: static void __cdecl UDisDamageType_CrushKnockdown::InitializePrivateStaticClassUDisDamageType_CrushKnockdown(void)
//   0x649b20  public: static void __cdecl UDishonoredDamageType_Electricity::InitializePrivateStaticClassUDishonoredDamageType_Electricity(void)
//   0x649b40  public: static void __cdecl UDishonoredDamageType_Explosion::InitializePrivateStaticClassUDishonoredDamageType_Explosion(void)
//   0x649b60  public: static void __cdecl UDishonoredDamageType_FastHit::InitializePrivateStaticClassUDishonoredDamageType_FastHit(void)
//   0x649b80  public: static void __cdecl UDisDamageType_GenericSleep::InitializePrivateStaticClassUDisDamageType_GenericSleep(void)
//   0x649ba0  public: static void __cdecl UDishonoredDamageType_FrontalImpale::InitializePrivateStaticClassUDishonoredDamageType_FrontalImpale(void)
//   0x649bc0  public: static void __cdecl UDishonoredDamageType_Knockdown::InitializePrivateStaticClassUDishonoredDamageType_Knockdown(void)
//   0x649be0  public: static void __cdecl UDisDamageType_Musical::InitializePrivateStaticClassUDisDamageType_Musical(void)
//   0x649c00  public: static void __cdecl UDishonoredDamageType_Plague::InitializePrivateStaticClassUDishonoredDamageType_Plague(void)
//   0x649c20  public: static void __cdecl UDishonoredDamageType_Projectile::InitializePrivateStaticClassUDishonoredDamageType_Projectile(void)
//   0x649c40  public: static class UClass * __cdecl UDisDamageType_RagdollImpact::StaticClassNoInline(void)
//   0x649c70  public: static void __cdecl UDisDamageType_Sleep_Deferred::InitializePrivateStaticClassUDisDamageType_Sleep_Deferred(void)
//   0x649c90  public: static void __cdecl UDishonoredDamageType_SpawnRatSwarm::InitializePrivateStaticClassUDishonoredDamageType_SpawnRatSwarm(void)
//   0x649cb0  public: static void __cdecl UDisDamageType_SpringRazorPlaced::InitializePrivateStaticClassUDisDamageType_SpringRazorPlaced(void)
//   0x649cd0  public: static void __cdecl UDishonoredDamageType_Stomped::InitializePrivateStaticClassUDishonoredDamageType_Stomped(void)
//   0x649cf0  public: static void __cdecl UDisDamageType_Water::InitializePrivateStaticClassUDisDamageType_Water(void)
//   0x649d10  public: static void __cdecl UDisDamageType_WindBlast::InitializePrivateStaticClassUDisDamageType_WindBlast(void)
//   0x64c130  public: static class UClass * __cdecl UDisDamageType_Assassination::StaticClassNoInline(void)
//   0x64c160  public: static class UClass * __cdecl UDishonoredDamageType_Bash::StaticClassNoInline(void)
//   0x64c190  public: static class UClass * __cdecl UDishonoredDamageType_Bite::StaticClassNoInline(void)
//   0x64c1c0  public: static class UClass * __cdecl UDisDamageType_BlinkPush::StaticClassNoInline(void)
//   0x64c1f0  public: static class UClass * __cdecl UDisDamageType_BlinkKnockdown::StaticClassNoInline(void)
//   0x64c220  public: static class UClass * __cdecl UDisDamageType_Choke::StaticClassNoInline(void)
//   0x64c250  public: static class UClass * __cdecl UDisDamageType_CrushPush::StaticClassNoInline(void)
//   0x64c280  public: static class UClass * __cdecl UDisDamageType_CrushKnockdown::StaticClassNoInline(void)
//   0x64c2b0  public: static class UClass * __cdecl UDishonoredDamageType_Electricity::StaticClassNoInline(void)
//   0x64c2e0  public: static class UClass * __cdecl UDishonoredDamageType_Explosion::StaticClassNoInline(void)
//   0x64c310  public: static class UClass * __cdecl UDishonoredDamageType_FastHit::StaticClassNoInline(void)
//   0x64c340  public: static void __cdecl UDisDamageType_FastHit_Left::InitializePrivateStaticClassUDisDamageType_FastHit_Left(void)
//   0x64c360  public: static void __cdecl UDisDamageType_FastHit_Right::InitializePrivateStaticClassUDisDamageType_FastHit_Right(void)
//   0x64c380  public: static void __cdecl UDisDamageType_FastHit_Up::InitializePrivateStaticClassUDisDamageType_FastHit_Up(void)
//   0x64c3a0  public: static class UClass * __cdecl UDisDamageType_GenericSleep::StaticClassNoInline(void)
//   0x64c3d0  public: static void __cdecl UDisDamageType_ImpactHit::InitializePrivateStaticClassUDisDamageType_ImpactHit(void)
//   0x64c3f0  public: static void __cdecl UDisDamageType_ImpactHit_Adrenaline::InitializePrivateStaticClassUDisDamageType_ImpactHit_Adrenaline(void)
//   0x64c410  public: static void __cdecl UDisDamageType_InstantSleep::InitializePrivateStaticClassUDisDamageType_InstantSleep(void)
//   0x64c430  public: static class UClass * __cdecl UDishonoredDamageType_FrontalImpale::StaticClassNoInline(void)
//   0x64c460  public: static class UClass * __cdecl UDishonoredDamageType_Knockdown::StaticClassNoInline(void)
//   0x64c490  public: static class UClass * __cdecl UDisDamageType_Musical::StaticClassNoInline(void)
//   0x64c4c0  public: static class UClass * __cdecl UDishonoredDamageType_Plague::StaticClassNoInline(void)
//   0x64c4f0  public: static class UClass * __cdecl UDishonoredDamageType_Projectile::StaticClassNoInline(void)
//   0x64c520  public: static void __cdecl UDishonoredDamageType_Projectile_Stealth::InitializePrivateStaticClassUDishonoredDamageType_Projectile_Stealth(void)
//   0x64c540  public: static class UClass * __cdecl UDisDamageType_Sleep_Deferred::StaticClassNoInline(void)
//   0x64c570  public: static void __cdecl UDisDamageType_Slide::InitializePrivateStaticClassUDisDamageType_Slide(void)
//   0x64c590  public: static class UClass * __cdecl UDishonoredDamageType_SpawnRatSwarm::StaticClassNoInline(void)
//   0x64c5c0  public: static class UClass * __cdecl UDisDamageType_SpringRazorPlaced::StaticClassNoInline(void)
//   0x64c5f0  public: static class UClass * __cdecl UDishonoredDamageType_Stomped::StaticClassNoInline(void)
//   0x64c620  public: static class UClass * __cdecl UDisDamageType_Water::StaticClassNoInline(void)
//   0x64c650  public: static class UClass * __cdecl UDisDamageType_WindBlast::StaticClassNoInline(void)
//   0x64d470  public: static void __cdecl UDishonoredDamageType_Bullet::InitializePrivateStaticClassUDishonoredDamageType_Bullet(void)
//   0x64d490  public: static class UClass * __cdecl UDisDamageType_FastHit_Left::StaticClassNoInline(void)
//   0x64d4c0  public: static class UClass * __cdecl UDisDamageType_FastHit_Right::StaticClassNoInline(void)
//   0x64d4f0  public: static class UClass * __cdecl UDisDamageType_FastHit_Up::StaticClassNoInline(void)
//   0x64d520  public: static void __cdecl UDisDamageType_FastHit_Up_Left::InitializePrivateStaticClassUDisDamageType_FastHit_Up_Left(void)
//   0x64d540  public: static void __cdecl UDisDamageType_FastHit_Up_Right::InitializePrivateStaticClassUDisDamageType_FastHit_Up_Right(void)
//   0x64d560  public: static class UClass * __cdecl UDisDamageType_ImpactHit::StaticClassNoInline(void)
//   0x64d590  public: static void __cdecl UDisDamageType_ImpactHit_Left::InitializePrivateStaticClassUDisDamageType_ImpactHit_Left(void)
//   0x64d5b0  public: static void __cdecl UDisDamageType_ImpactHit_Right::InitializePrivateStaticClassUDisDamageType_ImpactHit_Right(void)
//   0x64d5d0  public: static void __cdecl UDisDamageType_ImpactHit_Up::InitializePrivateStaticClassUDisDamageType_ImpactHit_Up(void)
//   0x64d5f0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline::StaticClassNoInline(void)
//   0x64d620  public: static void __cdecl UDisDamageType_ImpactHit_Adrenaline_Left::InitializePrivateStaticClassUDisDamageType_ImpactHit_Adrenaline_Left(void)
//   0x64d640  public: static void __cdecl UDisDamageType_ImpactHit_Adrenaline_Right::InitializePrivateStaticClassUDisDamageType_ImpactHit_Adrenaline_Right(void)
//   0x64d660  public: static void __cdecl UDisDamageType_ImpactHit_Adrenaline_Up::InitializePrivateStaticClassUDisDamageType_ImpactHit_Adrenaline_Up(void)
//   0x64d680  public: static class UClass * __cdecl UDisDamageType_InstantSleep::StaticClassNoInline(void)
//   0x64d6b0  public: static class UClass * __cdecl UDishonoredDamageType_Projectile_Stealth::StaticClassNoInline(void)
//   0x64d6e0  public: static class UClass * __cdecl UDisDamageType_Slide::StaticClassNoInline(void)
//   0x650100  public: static class UClass * __cdecl UDishonoredDamageType_Bullet::StaticClassNoInline(void)
//   0x650130  public: static void __cdecl UDishonoredDamageType_BulletMedium::InitializePrivateStaticClassUDishonoredDamageType_BulletMedium(void)
//   0x650150  public: static void __cdecl UDishonoredDamageType_BulletFar::InitializePrivateStaticClassUDishonoredDamageType_BulletFar(void)
//   0x650170  public: static void __cdecl UDishonoredDamageType_BulletBlast::InitializePrivateStaticClassUDishonoredDamageType_BulletBlast(void)
//   0x650190  public: static class UClass * __cdecl UDisDamageType_FastHit_Up_Left::StaticClassNoInline(void)
//   0x6501c0  public: static class UClass * __cdecl UDisDamageType_FastHit_Up_Right::StaticClassNoInline(void)
//   0x6501f0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Left::StaticClassNoInline(void)
//   0x650220  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Right::StaticClassNoInline(void)
//   0x650250  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Up::StaticClassNoInline(void)
//   0x650280  public: static void __cdecl UDisDamageType_ImpactHit_Up_Left::InitializePrivateStaticClassUDisDamageType_ImpactHit_Up_Left(void)
//   0x6502a0  public: static void __cdecl UDisDamageType_ImpactHit_Up_Right::InitializePrivateStaticClassUDisDamageType_ImpactHit_Up_Right(void)
//   0x6502c0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Left::StaticClassNoInline(void)
//   0x6502f0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Right::StaticClassNoInline(void)
//   0x650320  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Up::StaticClassNoInline(void)
//   0x650350  public: static void __cdecl UDisDamageType_ImpactHit_Adrenaline_Up_Left::InitializePrivateStaticClassUDisDamageType_ImpactHit_Adrenaline_Up_Left(void)
//   0x650370  public: static void __cdecl UDisDamageType_ImpactHit_Adrenaline_Up_Right::InitializePrivateStaticClassUDisDamageType_ImpactHit_Adrenaline_Up_Right(void)
//   0x651c10  public: static class UClass * __cdecl UDishonoredDamageType_BulletMedium::StaticClassNoInline(void)
//   0x651c40  public: static class UClass * __cdecl UDishonoredDamageType_BulletFar::StaticClassNoInline(void)
//   0x651c70  public: static class UClass * __cdecl UDishonoredDamageType_BulletBlast::StaticClassNoInline(void)
//   0x651ca0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Up_Left::StaticClassNoInline(void)
//   0x651cd0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Up_Right::StaticClassNoInline(void)
//   0x651d00  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Up_Left::StaticClassNoInline(void)
//   0x651d30  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Up_Right::StaticClassNoInline(void)
