// DishonoredGame/src/dishonoredutilities_accessors.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (41):
//   0x823980  float __cdecl DisGetAppropriateWorldTime(class AActor const * const)
//   0x8239b0  class FVector const __cdecl DisGetPawnFeet(class APawn const *)
//   0x823a10  class FVector const __cdecl DisGetPawnTop(class APawn const *)
//   0x827020  class UDishonoredMapInfo * __cdecl DishonoredGetMapInfo(void)
//   0x827040  class ADishonoredGameInfo * __cdecl DisGetGameInfo(void)
//   0x827060  class UDishonoredContactSystem * __cdecl DisGetContactSystem(void)
//   0x827090  class UDisPostProcessManager & __cdecl DisGetPpManager(void)
//   0x8270c0  unsigned int __cdecl DisIsBendTimeOn(void)
//   0x8270f0  unsigned int __cdecl DisIsBendTimeFrozen(void)
//   0x827120  unsigned int __cdecl DisIsActorAffectedByBendTimePower(class AActor const * const)
//   0x827170  unsigned int __cdecl DisIsActorFrozenByBendTimePower(class AActor const * const)
//   0x8271c0  class UDishonoredAudioSystem * __cdecl DisGetAudioSystem(void)
//   0x8271e0  class UDisConvGlobalMan * __cdecl DisGetConvGlobalMan(void)
//   0x8271f0  class UStatePlayerCarryCorpseIdle * __cdecl DisGetCarryCorpseState(void)
//   0x827220  class UDisWaterVolumeManager * __cdecl DisGetWaterVolumeManager(void)
//   0x827250  class AActor * __cdecl DisGetActorUnderCrosshair(void)
//   0x827380  class UDisGlobalCombatManager * __cdecl DisGetGlobalCombatManager(void)
//   0x8273b0  class UDisGameCrowdPopulationManager * __cdecl DisGetGameCrowdPopulationManager(void)
//   0x8273d0  class UDisRatSwarmGlobalManager * __cdecl DisGetRatSwarmGlobalManager(void)
//   0x827400  class UDisGlobalAIDangerManager * __cdecl DisGetGlobalAIDangerManager(void)
//   0x827430  class UDisNPCTravelManager * __cdecl DisGetNPCTravelManager(void)
//   0x827460  class UDisGlobalUIManager * __cdecl DisGetGlobalUIManager(void)
//   0x827490  class UDisGFxMoviePlayerHUD * __cdecl DisGetGFxHUD(void)
//   0x8274d0  class UDisGFxMoviePlayerPowerWheel * __cdecl DisGetPowerWheel(void)
//   0x82d7e0  class UDisLocalPlayer * __cdecl DisGetLocalPlayer(void)
//   0x82d840  class UArkPpNode * __cdecl DisGetArkPpNode(class FName const &)
//   0x82d900  class UArkPpNodeMaterial * __cdecl DisGetArkPpNodeMaterial(class FName const &, unsigned int)
//   0x82d990  class UDisDistractionGlobalManager * __cdecl DisGetDistractionGlobalManagerUnchecked(void)
//   0x82d9d0  class UDisAlarmGlobalManager * __cdecl DisGetAlarmGlobalManager(void)
//   0x82da00  class UDisAmbushGlobalManager * __cdecl DisGetAmbushGlobalManager(void)
//   0x82da30  class UStatePlayerMasterMantle * __cdecl DisGetMantleState(class UAnimNodeSequence *)
//   0x82da80  class FVector const __cdecl DisGetDamageCenter(class AActor const *)
//   0x82db30  class UDisTweaks_PlayerVisSettings const & __cdecl DisGetGlobalVisSettings(void)
//   0x82dc00  class UDisGlobalAIAttentionManager * __cdecl DisGetGlobalAIAttentionManager(void)
//   0x82dc30  class UDisGlobalProjectileManager * __cdecl DisGetGlobalProjectileManager(void)
//   0x832240  class UDishonoredGlobalAIManager * __cdecl DisGetGlobalAIManagerUnchecked(void)
//   0x832270  class UDisAIBlackboard * __cdecl DisGetGlobalAIBlackboard(void)
//   0x8322a0  class UDisAINoiseManager * __cdecl DisGetAINoiseManagerUnchecked(void)
//   0x8322d0  class UDisTweaks_PlayerVisSettings const & __cdecl DisGetPlayerVisSettings(void)
//   0x839fd0  class UDisContactPhysicalMaterial * __cdecl DisGetPhysicalMaterial(class AActor const *, class FVector const &, class FVector const &, int, struct FCheckResult *)
//   0x83a090  class UClass * __cdecl DisGetContactType(class UPhysicalMaterial const *, class AActor const *)
