// DishonoredGame/src/dishonoredutilities_math.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (40):
//   0x823b90  unsigned int __cdecl DisSphereLineIntersect(struct FCheckResult &, class FVector const &, float, class FVector const &, class FVector const &)
//   0x823fc0  int __cdecl DisAngleDiff(int, int)
//   0x823fe0  int __cdecl DisLerpAngle(int, int, float)
//   0x824050  unsigned int __cdecl DisIsPointInCone(class FVector const &, class FVector const &, float, float, float, class FVector const &)
//   0x824150  class FVector __cdecl DisNearestPointOnBox(class FBox const &, class FVector const &)
//   0x8241d0  unsigned int __cdecl DisLineSegBoxIntersect(class FBox const &, class FVector const &, class FVector const &, float *, float *)
//   0x824320  void __cdecl DisTimer_Unset(float &)
//   0x824340  void __cdecl DisTimer_Set(float &, float)
//   0x824360  unsigned int __cdecl DisTimer_IsElapsed(float const &)
//   0x824390  unsigned int __cdecl DisTimer_IsSet(float const &)
//   0x8243d0  float __cdecl DisInterpolateBySpeedWithDif(float, float, float, float, float)
//   0x827590  unsigned int __cdecl DisTeleportPlayer(class FVector const &, class FRotator const &)
//   0x827610  unsigned int __cdecl DisVectorsAreFacing(class FVector const &, class FVector const &, float, unsigned int, unsigned int)
//   0x827730  unsigned int __cdecl DisPawnsAreFacing(class APawn const *, class APawn const *, float, unsigned int, unsigned int)
//   0x8277c0  unsigned int __cdecl DisPawnYawIsFacing(class APawn const *, class FVector const &, float)
//   0x827890  float __cdecl DisAngleDiffRad(float, float)
//   0x8278e0  unsigned int __cdecl DisClampDirection(class FVector const &, class FVector *, float)
//   0x827b10  unsigned int __cdecl DisClampYaw(class FVector const &, class FVector *, float)
//   0x827cc0  class FVector __cdecl DisFindExtentInDirection(class FVector const &, class FVector const &)
//   0x827e40  unsigned int __cdecl DisCloseEnough(class FVector const &, class FVector const &, float)
//   0x827ea0  unsigned int __cdecl DisCloseEnough2D(class FVector const &, class FVector const &, float, float)
//   0x827f00  unsigned int __cdecl DisWithinRange(class FVector const &, class FVector const &, float, float)
//   0x827f70  unsigned int __cdecl DisWithinRange2D(class FVector const &, class FVector const &, float, float, float)
//   0x827fe0  unsigned int __cdecl DisIsPointInCylinder(class FVector, class FVector, float, class FVector)
//   0x8280c0  unsigned int __cdecl DisIsCrouchObstructed(class ADishonoredPawn *)
//   0x828230  void __cdecl DisTimer_Decrease(float &, float)
//   0x82ddc0  public: unsigned int __thiscall FMaskedProbeFunctor_Interact::CheckDisTraceFlags(class AActor const * const, struct FCheckResult const * const, int, int)
//   0x82e070  public: unsigned int __thiscall FMaskedProbeFunctor_GenericMask::CheckDisTraceFlags(class AActor const * const, struct FCheckResult const * const, int, int)
//   0x83ac10  unsigned int __cdecl MaskedLineProbeShared<class FMaskedProbeFunctor_Generic, class TArray<class AActor const *, class FDefaultAllocator>>(class AActor const *, struct FDisLineProbeResult &, struct TMemStackArray<struct FDisLineProbeResult> *, class FVector const &, class FVector const &, int, int, int, class FVector, unsigned int, class TArray<class AActor const *, class FDefaultAllocator> const *, class FMaskedProbeFunctor_Generic &)
//   0x83b5f0  unsigned int __cdecl MaskedLineProbeShared<class FMaskedProbeFunctor_Interact, class TArray<class AActor const *, class FDefaultAllocator>>(class AActor const *, struct FDisLineProbeResult &, struct TMemStackArray<struct FDisLineProbeResult> *, class FVector const &, class FVector const &, int, int, int, class FVector, unsigned int, class TArray<class AActor const *, class FDefaultAllocator> const *, class FMaskedProbeFunctor_Interact &)
//   0x83bfe0  unsigned int __cdecl MaskedLineProbeShared<class FMaskedProbeFunctor_GenericMask, class TArray<class AActor const *, class FDefaultAllocator>>(class AActor const *, struct FDisLineProbeResult &, struct TMemStackArray<struct FDisLineProbeResult> *, class FVector const &, class FVector const &, int, int, int, class FVector, unsigned int, class TArray<class AActor const *, class FDefaultAllocator> const *, class FMaskedProbeFunctor_GenericMask &)
//   0x83d3b0  unsigned int __cdecl DisLineProbe(class AActor const *, struct FDisLineProbeResult &, class FVector const &, class FVector const &, int, int, class FVector, unsigned int)
//   0x83d410  unsigned int __cdecl DisLineProbe(class AActor const *, class TArray<class AActor const *, class FDefaultAllocator> const &, struct FDisLineProbeResult &, class FVector const &, class FVector const &, int, int, class FVector, unsigned int)
//   0x83d470  unsigned int __cdecl DisLineProbeMulti(class AActor const *, struct TMemStackArray<struct FDisLineProbeResult> &, class FVector const &, class FVector const &, int, int, class FVector, unsigned int, struct TMemStackArray<class AActor const *> const *)
//   0x83d530  unsigned int __cdecl DisLineProbe_Interact(class AActor const *, struct FDisLineProbeResult &, class FVector const &, class FVector const &, int, int, int, class FVector, unsigned int, class TArray<class AActor const *, class FDefaultAllocator> const *)
//   0x83d590  unsigned int __cdecl DisLineProbeMulti_Interact(class AActor const *, struct TMemStackArray<struct FDisLineProbeResult> &, class FVector const &, class FVector const &, int, int, int, class FVector, unsigned int, class TArray<class AActor const *, class FDefaultAllocator> const *)
//   0x83d650  unsigned int __cdecl DisLineProbe_Masked(class AActor const *, struct FDisLineProbeResult &, class FVector const &, class FVector const &, int, int, int, class FVector, unsigned int)
//   0x83d6b0  unsigned int __cdecl DisLineProbe_Masked(class AActor const *, class TArray<class AActor const *, class FDefaultAllocator> const &, struct FDisLineProbeResult &, class FVector const &, class FVector const &, int, int, int, class FVector, unsigned int)
//   0x83d710  unsigned int __cdecl DisLineProbeMulti_Masked(class AActor const *, struct TMemStackArray<struct FDisLineProbeResult> &, class FVector const &, class FVector const &, int, int, int, class FVector, unsigned int)
//   0x83d7d0  unsigned int __cdecl DisLineProbeMulti_Masked(class AActor const *, class TArray<class AActor const *, class FDefaultAllocator> const &, struct TMemStackArray<struct FDisLineProbeResult> &, class FVector const &, class FVector const &, int, int, int, class FVector, unsigned int)
