// DishonoredGame/src/dishonoredcheatmanager.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (81):
//   0x7c9b50  public: static void __cdecl UDishonoredCheatManager::InitializePrivateStaticClassUDishonoredCheatManager(void)
//   0x7c9b70  public: virtual void __thiscall UDishonoredCheatManager::InitCheatManager_Native(void)
//   0x7c9b80  public: virtual void __thiscall UDishonoredCheatManager::BeginDestroy(void)
//   0x7c9b90  public: virtual void __thiscall UDishonoredCheatManager::DebugMenuLeft(void)
//   0x7c9bb0  public: virtual void __thiscall UDishonoredCheatManager::DebugMenuRight(void)
//   0x7c9bd0  public: virtual void __thiscall UDishonoredCheatManager::DebugToggleVerbose(void)
//   0x7c9bf0  public: virtual void __thiscall UDishonoredCheatManager::BendTimeDisplay(void)
//   0x7c9c10  public: virtual void __thiscall UDishonoredCheatManager::DebugDialog(void)
//   0x7c9c30  public: virtual void __thiscall UDishonoredCheatManager::DialogSkipGlobalRules(void)
//   0x7c9c50  public: virtual void __thiscall UDishonoredCheatManager::ListComponents(void)
//   0x7c9c70  public: virtual void __thiscall UDishonoredCheatManager::DisNoteToggle(void)
//   0x7c9ca0  public: virtual void __thiscall UDishonoredCheatManager::ListActorTickTime(void)
//   0x7c9cb0  public: virtual void __thiscall UDishonoredCheatManager::KillAllRats(void)
//   0x7c9cd0  public: virtual void __thiscall UDishonoredCheatManager::SpawnRandomRatSwarm(void)
//   0x7c9ce0  public: virtual void __thiscall UDishonoredCheatManager::ToggleRatProbingForGround(void)
//   0x7c9d00  public: virtual void __thiscall UDishonoredCheatManager::DormantDebugToggle(void)
//   0x7c9d20  public: virtual void __thiscall UDishonoredCheatManager::DormantDebugEnable(unsigned int)
//   0x7c9d40  public: virtual void __thiscall UDishonoredCheatManager::ToggleUsableHighlight(void)
//   0x7c9d60  public: virtual void __thiscall UDishonoredCheatManager::DoorPoltergeistMode(int)
//   0x7c9db0  public: virtual void __thiscall UDishonoredCheatManager::SetDifficulty(int)
//   0x7c9de0  public: virtual void __thiscall UDishonoredCheatManager::GetDifficulty(void)
//   0x7c9df0  public: virtual void __thiscall UDishonoredCheatManager::StartVisSettingsMode(void)
//   0x7c9e00  public: virtual void __thiscall UDishonoredCheatManager::StopVisSettingsMode(void)
//   0x7c9e10  public: virtual void __thiscall UDishonoredCheatManager::DisSlomoFull(float, float)
//   0x7c9e50  public: virtual void __thiscall UDishonoredCheatManager::ForceCorpseDropTypeOff(void)
//   0x7c9e60  public: virtual void __thiscall UDishonoredCheatManager::DisSlomo(float)
//   0x7c9e90  public: virtual void __thiscall UDishonoredCheatManager::NPCToggleSteeringAvoidable(void)
//   0x7c9ec0  public: virtual void __thiscall UDishonoredCheatManager::NPCToggleSteeringDanger(void)
//   0x7c9ee0  public: virtual void __thiscall UDishonoredCheatManager::NPCToggleSteeringCombat(void)
//   0x7c9f00  public: virtual void __thiscall UDishonoredCheatManager::NPCToggleSteeringEnemyPush(void)
//   0x7c9f20  public: virtual void __thiscall UDishonoredCheatManager::NPCToggleSteeringWall(void)
//   0x7c9f40  public: virtual void __thiscall UDishonoredCheatManager::GoreEnable(unsigned int)
//   0x7cc5d0  public: virtual void __thiscall UDishonoredCheatManager::DebugMenuEnter(void)
//   0x7cc610  public: virtual void __thiscall UDishonoredCheatManager::DebugMenuUp(void)
//   0x7cc650  public: virtual void __thiscall UDishonoredCheatManager::DebugMenuDown(void)
//   0x7cc690  public: virtual void __thiscall UDishonoredCheatManager::DebugRats(void)
//   0x7cc6f0  public: virtual void __thiscall UDishonoredCheatManager::DebugDarkness(void)
//   0x7cc740  public: virtual void __thiscall UDishonoredCheatManager::GiveBoneCharm(void)
//   0x7cc750  public: virtual void __thiscall UDishonoredCheatManager::SetVisSettingsHighVis(void)
//   0x7cc790  public: virtual void __thiscall UDishonoredCheatManager::SetVisSettingsLowVis(void)
//   0x7cc7d0  public: virtual void __thiscall UDishonoredCheatManager::NormalStepMantleEdgeFinder(void)
//   0x7cc800  public: virtual void __thiscall UDishonoredCheatManager::SetDebugMantleCheckTime(float)
//   0x7cc830  public: virtual void __thiscall UDishonoredCheatManager::SetDebugMantleStepSize(float)
//   0x7cc860  public: virtual void __thiscall UDishonoredCheatManager::ShowPowerMenu(void)
//   0x7cc880  public: virtual void __thiscall UDishonoredCheatManager::GiveRunes(int)
//   0x7cc8c0  public: virtual void __thiscall UDishonoredCheatManager::GameSave(class FArchive &, enum ESaveLoadLocation)
//   0x7ccd20  public: virtual void __thiscall UDishonoredCheatManager::GameLoad(class FArchive &, enum ESaveLoadLocation)
//   0x7cea50  public: virtual void __thiscall UDishonoredCheatManager::SetTargetedActor(class AActor *)
//   0x7cea80  public: virtual void __thiscall UDishonoredCheatManager::AddMod(class FName, class FName, unsigned char, float, float)
//   0x7ceaf0  public: virtual void __thiscall UDishonoredCheatManager::RemoveMod(class FName, class FName)
//   0x7ceb40  public: virtual void __thiscall UDishonoredCheatManager::AddPower(class FName, int)
//   0x7ceb90  public: virtual void __thiscall UDishonoredCheatManager::AddAttribute(class FName, float)
//   0x7cebf0  public: virtual void __thiscall UDishonoredCheatManager::RemovePower(class FName)
//   0x7cec40  public: virtual void __thiscall UDishonoredCheatManager::MaxPowers(void)
//   0x7ced90  public: virtual void __thiscall UDishonoredCheatManager::MinPowers(void)
//   0x7cedd0  public: virtual void __thiscall UDishonoredCheatManager::DebugRat(void)
//   0x7cf0b0  public: virtual void __thiscall UDishonoredCheatManager::AddDarkness(int)
//   0x7cf0f0  public: virtual void __thiscall UDishonoredCheatManager::AddUpgrade(class FString const &)
//   0x7cf230  public: virtual void __thiscall UDishonoredCheatManager::RemoveUpgrade(class FString const &)
//   0x7cf370  public: virtual void __thiscall UDishonoredCheatManager::MaxUpgrades(void)
//   0x7cf410  public: virtual void __thiscall UDishonoredCheatManager::MinUpgrades(void)
//   0x7cf4b0  public: virtual void __thiscall UDishonoredCheatManager::SingleStepMantleEdgeFinder(void)
//   0x7cf540  public: virtual void __thiscall UDishonoredCheatManager::GiveMoney(int)
//   0x7cf5a0  public: virtual void __thiscall UDishonoredCheatManager::ForceCorpseDropType(unsigned char)
//   0x7cf5f0  public: virtual void __thiscall UDishonoredCheatManager::BlinkShowRange(float)
//   0x7cfaa0  public: virtual void __thiscall UDishonoredCheatManager::SwitchDLCLock(int)
//   0x7cfb90  public: virtual void __thiscall UDishonoredCheatManager::ShowStorePage(class FString const &)
//   0x7d4f60  public: virtual void __thiscall UDishonoredCheatManager::BendTimeReport(void)
//   0x7d4fc0  public: virtual void __thiscall UDishonoredCheatManager::TestNailing(void)
//   0x7d5330  ToggleLightEnvironmentsInList
//   0x7d53f0  public: virtual void __thiscall UDishonoredCheatManager::ToggleActorLightEnvironment(void)
//   0x7d5470  public: virtual void __thiscall UDishonoredCheatManager::DisSlomoCommand(class FName)
//   0x7d58d0  public: virtual void __thiscall UDishonoredCheatManager::GiveAllUsableRequiredItems(void)
//   0x7d8420  public: virtual void __thiscall UDishonoredCheatManager::SingleStep_Native(void)
//   0x7d84c0  public: virtual void __thiscall UDishonoredCheatManager::ListTickableActors(void)
//   0x7dac90  public: virtual void __thiscall UDishonoredCheatManager::DisNoteShow(unsigned int)
//   0x7dace0  public: virtual void __thiscall UDishonoredCheatManager::LogAnimSequences(void)
//   0x7db730  public: virtual void __thiscall UDishonoredCheatManager::LogDuplicateAnimSequences(void)
//   0x7dbbe0  public: virtual void __thiscall UDishonoredCheatManager::BlinkShowRangeFull(float)
//   0x7de440  public: static class UClass * __cdecl UDishonoredCheatManager::GetPrivateStaticClassUDishonoredCheatManager(wchar_t const *)
//   0x7df250  public: static class UClass * __cdecl UDishonoredCheatManager::StaticClassNoInline(void)
