// DishonoredGame/src/dishonoredcontactsystem.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (130):
//   0x8232d0  public: static void __cdecl UDishonoredContactSystem::InitializePrivateStaticClassUDishonoredContactSystem(void)
//   0x8232f0  public: static void __cdecl UDisContactPhysicalMaterial::InitializePrivateStaticClassUDisContactPhysicalMaterial(void)
//   0x823310  public: static void __cdecl UDisContactType::InitializePrivateStaticClassUDisContactType(void)
//   0x82bbe0  public: static class UClass * __cdecl UDisContactPhysicalMaterial::GetPrivateStaticClassUDisContactPhysicalMaterial(wchar_t const *)
//   0x82bc70  protected: unsigned int __thiscall UDishonoredContactSystem::FixupSubIntersections(struct FDisContactIntersection &)
//   0x831fe0  public: static class UClass * __cdecl UDisContactPhysicalMaterial::StaticClassNoInline(void)
//   0x837d40  public: static class UClass * __cdecl UDisContactType::GetPrivateStaticClassUDisContactType(wchar_t const *)
//   0x837dd0  public: static class UClass * __cdecl UDisContactType_Environment::GetPrivateStaticClassUDisContactType_Environment(wchar_t const *)
//   0x837e60  public: static class UClass * __cdecl UDisContactType_Env_DeepWater::GetPrivateStaticClassUDisContactType_Env_DeepWater(wchar_t const *)
//   0x837ef0  public: static class UClass * __cdecl UDisContactType_Env_Foliage::GetPrivateStaticClassUDisContactType_Env_Foliage(wchar_t const *)
//   0x837f80  public: static class UClass * __cdecl UDisContactType_Weapon::GetPrivateStaticClassUDisContactType_Weapon(wchar_t const *)
//   0x838010  public: static class UClass * __cdecl UDisContactType_PistolBlast::GetPrivateStaticClassUDisContactType_PistolBlast(wchar_t const *)
//   0x8380a0  public: static class UClass * __cdecl UDisContactType_Windblast::GetPrivateStaticClassUDisContactType_Windblast(wchar_t const *)
//   0x838130  public: static class UClass * __cdecl UDisContactType_Windblast_Ceil::GetPrivateStaticClassUDisContactType_Windblast_Ceil(wchar_t const *)
//   0x8381c0  public: static class UClass * __cdecl UDisContactType_Windblast_Floor::GetPrivateStaticClassUDisContactType_Windblast_Floor(wchar_t const *)
//   0x838250  public: static class UClass * __cdecl UDisContactType_Windblast_Ground::GetPrivateStaticClassUDisContactType_Windblast_Ground(wchar_t const *)
//   0x8382e0  public: static class UClass * __cdecl UDisContactType_Windblast_Wall::GetPrivateStaticClassUDisContactType_Windblast_Wall(wchar_t const *)
//   0x838370  public: static class UClass * __cdecl UDisContactType_Projectile::GetPrivateStaticClassUDisContactType_Projectile(wchar_t const *)
//   0x838400  public: static class UClass * __cdecl UDisContactType_Body::GetPrivateStaticClassUDisContactType_Body(wchar_t const *)
//   0x838490  public: static class UClass * __cdecl UDisContactType_Body_Head::GetPrivateStaticClassUDisContactType_Body_Head(wchar_t const *)
//   0x838520  public: static class UClass * __cdecl UDisContactType_ProtectedNPC::GetPrivateStaticClassUDisContactType_ProtectedNPC(wchar_t const *)
//   0x8385b0  public: static class UClass * __cdecl UDisContactType_Corpse::GetPrivateStaticClassUDisContactType_Corpse(wchar_t const *)
//   0x838640  public: static class UClass * __cdecl UDisContactType_SleepingBody::GetPrivateStaticClassUDisContactType_SleepingBody(wchar_t const *)
//   0x8386d0  public: static class UClass * __cdecl UDisContactType_Player::GetPrivateStaticClassUDisContactType_Player(wchar_t const *)
//   0x838760  public: static class UClass * __cdecl UDisContactType_BreakingBones::GetPrivateStaticClassUDisContactType_BreakingBones(wchar_t const *)
//   0x8387f0  public: static class UClass * __cdecl UDisContactType_BreakingBones_Player::GetPrivateStaticClassUDisContactType_BreakingBones_Player(wchar_t const *)
//   0x838880  public: static class UClass * __cdecl UDisContactType_RiverKrustFlesh::GetPrivateStaticClassUDisContactType_RiverKrustFlesh(wchar_t const *)
//   0x838910  public: static class UClass * __cdecl UDisContactType_SpawnRatSwarm::GetPrivateStaticClassUDisContactType_SpawnRatSwarm(wchar_t const *)
//   0x8389a0  public: static class UClass * __cdecl UDisContactType_Footfall::GetPrivateStaticClassUDisContactType_Footfall(wchar_t const *)
//   0x838a30  public: static class UClass * __cdecl UDisContactType_Footfall_Tallboy::GetPrivateStaticClassUDisContactType_Footfall_Tallboy(wchar_t const *)
//   0x838ac0  public: static class UClass * __cdecl UDisContactType_Footfall_Wolfhound::GetPrivateStaticClassUDisContactType_Footfall_Wolfhound(wchar_t const *)
//   0x838b50  public: static class UClass * __cdecl UDisContactType_Footfall_Wolfhound_Run::GetPrivateStaticClassUDisContactType_Footfall_Wolfhound_Run(wchar_t const *)
//   0x838be0  public: static class UClass * __cdecl UDisContactType_Footfall_Run::GetPrivateStaticClassUDisContactType_Footfall_Run(wchar_t const *)
//   0x838c70  public: static class UClass * __cdecl UDisContactType_Footfall_Sneak::GetPrivateStaticClassUDisContactType_Footfall_Sneak(wchar_t const *)
//   0x838d00  public: static class UClass * __cdecl UDisContactType_Footfall_Sprint::GetPrivateStaticClassUDisContactType_Footfall_Sprint(wchar_t const *)
//   0x838d90  public: static class UClass * __cdecl UDisContactType_Footfall_Run_Player::GetPrivateStaticClassUDisContactType_Footfall_Run_Player(wchar_t const *)
//   0x838e20  public: static class UClass * __cdecl UDisContactType_Footfall_Run_Player_Silent::GetPrivateStaticClassUDisContactType_Footfall_Run_Player_Silent(wchar_t const *)
//   0x838eb0  public: static class UClass * __cdecl UDisContactType_Footfall_Sneak_Player::GetPrivateStaticClassUDisContactType_Footfall_Sneak_Player(wchar_t const *)
//   0x838f40  public: static class UClass * __cdecl UDisContactType_Footfall_Sprint_Player::GetPrivateStaticClassUDisContactType_Footfall_Sprint_Player(wchar_t const *)
//   0x838fd0  public: static class UClass * __cdecl UDisContactType_JumpLand::GetPrivateStaticClassUDisContactType_JumpLand(wchar_t const *)
//   0x839060  public: static class UClass * __cdecl UDisContactType_JumpLand_Stealth::GetPrivateStaticClassUDisContactType_JumpLand_Stealth(wchar_t const *)
//   0x8390f0  public: static class UClass * __cdecl UDisContactType_JumpLand_Big::GetPrivateStaticClassUDisContactType_JumpLand_Big(wchar_t const *)
//   0x839180  public: static class UClass * __cdecl UDisContactType_Slide::GetPrivateStaticClassUDisContactType_Slide(wchar_t const *)
//   0x839210  public: static class UClass * __cdecl UDisContactType_SlideImpact::GetPrivateStaticClassUDisContactType_SlideImpact(wchar_t const *)
//   0x8392a0  public: void __thiscall UDishonoredContactSystem::TickContactSystem(void)
//   0x839cb0  public: static class UClass * __cdecl UDisContactType::StaticClassNoInline(void)
//   0x839ce0  public: static void __cdecl UDisContactType_Environment::InitializePrivateStaticClassUDisContactType_Environment(void)
//   0x839d00  public: static void __cdecl UDisContactType_Weapon::InitializePrivateStaticClassUDisContactType_Weapon(void)
//   0x839d20  public: static void __cdecl UDisContactType_Windblast::InitializePrivateStaticClassUDisContactType_Windblast(void)
//   0x839d40  public: static void __cdecl UDisContactType_Projectile::InitializePrivateStaticClassUDisContactType_Projectile(void)
//   0x839d60  public: static void __cdecl UDisContactType_Body::InitializePrivateStaticClassUDisContactType_Body(void)
//   0x839d80  public: static void __cdecl UDisContactType_SpawnRatSwarm::InitializePrivateStaticClassUDisContactType_SpawnRatSwarm(void)
//   0x839da0  public: static void __cdecl UDisContactType_Slide::InitializePrivateStaticClassUDisContactType_Slide(void)
//   0x839dc0  public: static void __cdecl UDisContactType_SlideImpact::InitializePrivateStaticClassUDisContactType_SlideImpact(void)
//   0x83cfb0  public: static class UClass * __cdecl UDisContactType_Environment::StaticClassNoInline(void)
//   0x83cfe0  public: static void __cdecl UDisContactType_Env_DeepWater::InitializePrivateStaticClassUDisContactType_Env_DeepWater(void)
//   0x83d000  public: static void __cdecl UDisContactType_Env_Foliage::InitializePrivateStaticClassUDisContactType_Env_Foliage(void)
//   0x83d020  public: static class UClass * __cdecl UDisContactType_Weapon::StaticClassNoInline(void)
//   0x83d050  public: static void __cdecl UDisContactType_PistolBlast::InitializePrivateStaticClassUDisContactType_PistolBlast(void)
//   0x83d070  public: static class UClass * __cdecl UDisContactType_Windblast::StaticClassNoInline(void)
//   0x83d0a0  public: static void __cdecl UDisContactType_Windblast_Ceil::InitializePrivateStaticClassUDisContactType_Windblast_Ceil(void)
//   0x83d0c0  public: static void __cdecl UDisContactType_Windblast_Floor::InitializePrivateStaticClassUDisContactType_Windblast_Floor(void)
//   0x83d0e0  public: static void __cdecl UDisContactType_Windblast_Ground::InitializePrivateStaticClassUDisContactType_Windblast_Ground(void)
//   0x83d100  public: static void __cdecl UDisContactType_Windblast_Wall::InitializePrivateStaticClassUDisContactType_Windblast_Wall(void)
//   0x83d120  public: static class UClass * __cdecl UDisContactType_Projectile::StaticClassNoInline(void)
//   0x83d150  public: static class UClass * __cdecl UDisContactType_Body::StaticClassNoInline(void)
//   0x83d180  public: static void __cdecl UDisContactType_Body_Head::InitializePrivateStaticClassUDisContactType_Body_Head(void)
//   0x83d1a0  public: static void __cdecl UDisContactType_ProtectedNPC::InitializePrivateStaticClassUDisContactType_ProtectedNPC(void)
//   0x83d1c0  public: static void __cdecl UDisContactType_Corpse::InitializePrivateStaticClassUDisContactType_Corpse(void)
//   0x83d1e0  public: static void __cdecl UDisContactType_Player::InitializePrivateStaticClassUDisContactType_Player(void)
//   0x83d200  public: static void __cdecl UDisContactType_BreakingBones::InitializePrivateStaticClassUDisContactType_BreakingBones(void)
//   0x83d220  public: static void __cdecl UDisContactType_RiverKrustFlesh::InitializePrivateStaticClassUDisContactType_RiverKrustFlesh(void)
//   0x83d240  public: static class UClass * __cdecl UDisContactType_SpawnRatSwarm::StaticClassNoInline(void)
//   0x83d270  public: static void __cdecl UDisContactType_Footfall::InitializePrivateStaticClassUDisContactType_Footfall(void)
//   0x83d290  public: static void __cdecl UDisContactType_JumpLand::InitializePrivateStaticClassUDisContactType_JumpLand(void)
//   0x83d2b0  public: static class UClass * __cdecl UDisContactType_Slide::StaticClassNoInline(void)
//   0x83d2e0  public: static class UClass * __cdecl UDisContactType_SlideImpact::StaticClassNoInline(void)
//   0x83eb80  public: static class UClass * __cdecl UDisContactType_Env_DeepWater::StaticClassNoInline(void)
//   0x83ebb0  public: static class UClass * __cdecl UDisContactType_Env_Foliage::StaticClassNoInline(void)
//   0x83ebe0  public: static class UClass * __cdecl UDisContactType_PistolBlast::StaticClassNoInline(void)
//   0x83ec10  public: static class UClass * __cdecl UDisContactType_Windblast_Ceil::StaticClassNoInline(void)
//   0x83ec40  public: static class UClass * __cdecl UDisContactType_Windblast_Floor::StaticClassNoInline(void)
//   0x83ec70  public: static class UClass * __cdecl UDisContactType_Windblast_Ground::StaticClassNoInline(void)
//   0x83eca0  public: static class UClass * __cdecl UDisContactType_Windblast_Wall::StaticClassNoInline(void)
//   0x83ecd0  public: static class UClass * __cdecl UDisContactType_Body_Head::StaticClassNoInline(void)
//   0x83ed00  public: static class UClass * __cdecl UDisContactType_ProtectedNPC::StaticClassNoInline(void)
//   0x83ed30  public: static class UClass * __cdecl UDisContactType_Corpse::StaticClassNoInline(void)
//   0x83ed60  public: static void __cdecl UDisContactType_SleepingBody::InitializePrivateStaticClassUDisContactType_SleepingBody(void)
//   0x83ed80  public: static class UClass * __cdecl UDisContactType_Player::StaticClassNoInline(void)
//   0x83edb0  public: static class UClass * __cdecl UDisContactType_BreakingBones::StaticClassNoInline(void)
//   0x83ede0  public: static void __cdecl UDisContactType_BreakingBones_Player::InitializePrivateStaticClassUDisContactType_BreakingBones_Player(void)
//   0x83ee00  public: static class UClass * __cdecl UDisContactType_RiverKrustFlesh::StaticClassNoInline(void)
//   0x83ee30  public: static class UClass * __cdecl UDisContactType_Footfall::StaticClassNoInline(void)
//   0x83ee60  public: static void __cdecl UDisContactType_Footfall_Tallboy::InitializePrivateStaticClassUDisContactType_Footfall_Tallboy(void)
//   0x83ee80  public: static void __cdecl UDisContactType_Footfall_Wolfhound::InitializePrivateStaticClassUDisContactType_Footfall_Wolfhound(void)
//   0x83eea0  public: static void __cdecl UDisContactType_Footfall_Wolfhound_Run::InitializePrivateStaticClassUDisContactType_Footfall_Wolfhound_Run(void)
//   0x83eec0  public: static void __cdecl UDisContactType_Footfall_Run::InitializePrivateStaticClassUDisContactType_Footfall_Run(void)
//   0x83eee0  public: static void __cdecl UDisContactType_Footfall_Sneak::InitializePrivateStaticClassUDisContactType_Footfall_Sneak(void)
//   0x83ef00  public: static void __cdecl UDisContactType_Footfall_Sprint::InitializePrivateStaticClassUDisContactType_Footfall_Sprint(void)
//   0x83ef20  public: static void __cdecl UDisContactType_Footfall_Run_Player_Silent::InitializePrivateStaticClassUDisContactType_Footfall_Run_Player_Silent(void)
//   0x83ef40  public: static class UClass * __cdecl UDisContactType_JumpLand::StaticClassNoInline(void)
//   0x83ef70  public: static void __cdecl UDisContactType_JumpLand_Stealth::InitializePrivateStaticClassUDisContactType_JumpLand_Stealth(void)
//   0x83ef90  public: static void __cdecl UDisContactType_JumpLand_Big::InitializePrivateStaticClassUDisContactType_JumpLand_Big(void)
//   0x83fd80  public: static class UClass * __cdecl UDisContactType_SleepingBody::StaticClassNoInline(void)
//   0x83fdb0  public: static class UClass * __cdecl UDisContactType_BreakingBones_Player::StaticClassNoInline(void)
//   0x83fde0  public: static class UClass * __cdecl UDisContactType_Footfall_Tallboy::StaticClassNoInline(void)
//   0x83fe10  public: static class UClass * __cdecl UDisContactType_Footfall_Wolfhound::StaticClassNoInline(void)
//   0x83fe40  public: static class UClass * __cdecl UDisContactType_Footfall_Wolfhound_Run::StaticClassNoInline(void)
//   0x83fe70  public: static class UClass * __cdecl UDisContactType_Footfall_Run::StaticClassNoInline(void)
//   0x83fea0  public: static class UClass * __cdecl UDisContactType_Footfall_Sneak::StaticClassNoInline(void)
//   0x83fed0  public: static class UClass * __cdecl UDisContactType_Footfall_Sprint::StaticClassNoInline(void)
//   0x83ff00  public: static void __cdecl UDisContactType_Footfall_Run_Player::InitializePrivateStaticClassUDisContactType_Footfall_Run_Player(void)
//   0x83ff20  public: static class UClass * __cdecl UDisContactType_Footfall_Run_Player_Silent::StaticClassNoInline(void)
//   0x83ff50  public: static void __cdecl UDisContactType_Footfall_Sneak_Player::InitializePrivateStaticClassUDisContactType_Footfall_Sneak_Player(void)
//   0x83ff70  public: static void __cdecl UDisContactType_Footfall_Sprint_Player::InitializePrivateStaticClassUDisContactType_Footfall_Sprint_Player(void)
//   0x83ff90  public: static class UClass * __cdecl UDisContactType_JumpLand_Stealth::StaticClassNoInline(void)
//   0x83ffc0  public: static class UClass * __cdecl UDisContactType_JumpLand_Big::StaticClassNoInline(void)
//   0x8404e0  public: static class UClass * __cdecl UDisContactType_Footfall_Run_Player::StaticClassNoInline(void)
//   0x840510  public: static class UClass * __cdecl UDisContactType_Footfall_Sneak_Player::StaticClassNoInline(void)
//   0x840540  public: static class UClass * __cdecl UDisContactType_Footfall_Sprint_Player::StaticClassNoInline(void)
//   0x8408f0  protected: struct FDisContactListHead * __thiscall UDishonoredContactSystem::FindListHead(class UClass *)
//   0x840a00  public: struct FDisContactIntersection * __thiscall UDishonoredContactSystem::FindIntersection(class UClass *, class UClass *, unsigned int)
//   0x840ad0  public: struct FDisContactIntersection * __thiscall UDishonoredContactSystem::FindClosestIntersection(class UClass *, class UClass *, int, class UClass * *, class UClass * *)
//   0x840bd0  protected: void __thiscall UDishonoredContactSystem::FlattenSubIntersections(struct FDisContactIntersection &)
//   0x840ec0  protected: void __thiscall UDishonoredContactSystem::UpdateLinkedLists(void)
//   0x8410f0  public: void __thiscall UDishonoredContactSystem::ApplyContact(class UClass *, class UClass *, class AActor *, struct FImpactInfo &, class FVector const *, class UDisItemContext *)
//   0x8412a0  protected: void __thiscall UDishonoredContactSystem::FlattenIntersections(void)
//   0x843cb0  public: static class UClass * __cdecl UDishonoredContactSystem::GetPrivateStaticClassUDishonoredContactSystem(wchar_t const *)
//   0x843d40  public: unsigned int __thiscall UDishonoredContactSystem::PostBeginPlay_Contacts(void)
//   0x844ac0  public: static class UClass * __cdecl UDishonoredContactSystem::StaticClassNoInline(void)
