// DishonoredGame/src/dishonoredcheatmanager_ai.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (105):
//   0x7c9f60  public: virtual void __thiscall UDishonoredCheatManager::AIClearDebug(void)
//   0x7c9f70  public: virtual void __thiscall UDishonoredCheatManager::AIEnable(unsigned int)
//   0x7c9f90  public: virtual void __thiscall UDishonoredCheatManager::AIToggle(void)
//   0x7c9fc0  public: virtual void __thiscall UDishonoredCheatManager::AIDontAttack(void)
//   0x7c9fe0  public: virtual void __thiscall UDishonoredCheatManager::AITestGuns(void)
//   0x7ca000  public: virtual void __thiscall UDishonoredCheatManager::AIToggleMagic(void)
//   0x7ca020  public: virtual void __thiscall UDishonoredCheatManager::GodNPC(void)
//   0x7ca040  public: virtual void __thiscall UDishonoredCheatManager::AIForcePanic(void)
//   0x7ca060  public: virtual void __thiscall UDishonoredCheatManager::NPCDodgeEverything(void)
//   0x7ca080  public: virtual void __thiscall UDishonoredCheatManager::NPCDodgeNothing(void)
//   0x7ca0a0  public: virtual void __thiscall UDishonoredCheatManager::NPCTestParry(void)
//   0x7ca0c0  public: virtual void __thiscall UDishonoredCheatManager::NPCTestVersus(void)
//   0x7ca0e0  public: virtual void __thiscall UDishonoredCheatManager::NPCSetDamage(float)
//   0x7ca100  public: virtual void __thiscall UDishonoredCheatManager::NPCToggleSlopeOffset(void)
//   0x7ca120  public: virtual void __thiscall UDishonoredCheatManager::NPCSlowDeath(void)
//   0x7ca140  public: virtual void __thiscall UDishonoredCheatManager::AIForceTransitSpeed(int)
//   0x7ca170  public: virtual void __thiscall UDishonoredCheatManager::AIDontRotate(void)
//   0x7ca190  public: virtual void __thiscall UDishonoredCheatManager::AINeverRingAlarm(void)
//   0x7ca1b0  public: virtual void __thiscall UDishonoredCheatManager::AIAlwaysRingAlarm(void)
//   0x7ca1d0  public: virtual void __thiscall UDishonoredCheatManager::AIBeepWhenSeePlayer(void)
//   0x7ca1f0  public: virtual void __thiscall UDishonoredCheatManager::AISetBeepWhenSeePlayer(unsigned int)
//   0x7ca220  public: virtual void __thiscall UDishonoredCheatManager::LocoDontRotate(void)
//   0x7ca230  public: virtual void __thiscall UDishonoredCheatManager::LocoForceIdleAnim(void)
//   0x7ca250  public: virtual void __thiscall UDishonoredCheatManager::LocoDisableStartAnims(void)
//   0x7ca270  public: virtual void __thiscall UDishonoredCheatManager::AIGoToReset(void)
//   0x7ca290  public: virtual void __thiscall UDishonoredCheatManager::NPCFreeze(void)
//   0x7ca2b0  public: virtual void __thiscall UDishonoredCheatManager::NPCSetFreeze(unsigned int)
//   0x7ca2e0  public: virtual void __thiscall UDishonoredCheatManager::NPCTogglePrediction(void)
//   0x7ca300  public: virtual void __thiscall UDishonoredCheatManager::NPCActionSpineBendingToggle(void)
//   0x7ca320  public: virtual void __thiscall UDishonoredCheatManager::AIPauseOnPathFailure(void)
//   0x7ca340  public: virtual void __thiscall UDishonoredCheatManager::AIForceAttentionLevelOff(void)
//   0x7ca350  public: virtual void __thiscall UDishonoredCheatManager::AIDumbToPlayer(void)
//   0x7ca370  public: virtual void __thiscall UDishonoredCheatManager::AISetDumbToPlayer(unsigned int)
//   0x7ca390  public: virtual void __thiscall UDishonoredCheatManager::AIBlindToPlayer(void)
//   0x7ca3b0  public: virtual void __thiscall UDishonoredCheatManager::AISetBlindToPlayer(unsigned int)
//   0x7ca3d0  public: virtual void __thiscall UDishonoredCheatManager::AIDeafToPlayer(void)
//   0x7ca3f0  public: virtual void __thiscall UDishonoredCheatManager::AISetDeafToPlayer(unsigned int)
//   0x7ca410  public: virtual void __thiscall UDishonoredCheatManager::AINumbToPlayer(void)
//   0x7ca430  public: virtual void __thiscall UDishonoredCheatManager::AISetNumbToPlayer(unsigned int)
//   0x7ca450  public: virtual void __thiscall UDishonoredCheatManager::AIDumbToAIs(void)
//   0x7ca470  public: virtual void __thiscall UDishonoredCheatManager::AISetDumbToAIs(unsigned int)
//   0x7ca490  public: virtual void __thiscall UDishonoredCheatManager::AIBlindToAIs(void)
//   0x7ca4b0  public: virtual void __thiscall UDishonoredCheatManager::AISetBlindToAIs(unsigned int)
//   0x7ca4d0  public: virtual void __thiscall UDishonoredCheatManager::AIDeafToAIs(void)
//   0x7ca4f0  public: virtual void __thiscall UDishonoredCheatManager::AISetDeafToAIs(unsigned int)
//   0x7ca510  public: virtual void __thiscall UDishonoredCheatManager::AINumbToAIs(void)
//   0x7ca530  public: virtual void __thiscall UDishonoredCheatManager::AISetNumbToAIs(unsigned int)
//   0x7ca550  public: virtual void __thiscall UDishonoredCheatManager::DestroyActor(void)
//   0x7ca590  public: virtual void __thiscall UDishonoredCheatManager::NPCForceFatality(void)
//   0x7ca5b0  public: virtual void __thiscall UDishonoredCheatManager::NPCEasyDismemberment(void)
//   0x7ca5d0  public: virtual void __thiscall UDishonoredCheatManager::AIShowThoughts(float)
//   0x7ca620  public: virtual void __thiscall UDishonoredCheatManager::AIUseSimpleAttentionForPlayer(void)
//   0x7ca640  public: virtual void __thiscall UDishonoredCheatManager::NPCToggleLODSystem(void)
//   0x7ca660  public: virtual void __thiscall UDishonoredCheatManager::AttentionSetIgnoreType(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
//   0x7ca6a0  public: virtual void __thiscall UDishonoredCheatManager::AttentionSetExclusiveType(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
//   0x7cd020  public: virtual void __thiscall UDishonoredCheatManager::NPCDestroyNonVisible(void)
//   0x7cd090  public: virtual void __thiscall UDishonoredCheatManager::LocoForceLookAtMode(int)
//   0x7cd0e0  public: virtual void __thiscall UDishonoredCheatManager::LocoForceModifier(int)
//   0x7cd130  public: virtual void __thiscall UDishonoredCheatManager::LocoNewAvoidance(void)
//   0x7cd160  public: virtual void __thiscall UDishonoredCheatManager::LocoNewIK(void)
//   0x7cd1b0  public: virtual void __thiscall UDishonoredCheatManager::LocoNewPhysWalking(void)
//   0x7cd1e0  public: virtual void __thiscall UDishonoredCheatManager::LocoTeleport(void)
//   0x7cd340  public: virtual void __thiscall UDishonoredCheatManager::AIGoToCrosshair(void)
//   0x7cd4c0  public: virtual void __thiscall UDishonoredCheatManager::AISetLocoDebug(void)
//   0x7cd5b0  public: virtual void __thiscall UDishonoredCheatManager::NPCDelayTravel(float)
//   0x7cd5d0  public: virtual void __thiscall UDishonoredCheatManager::AIForceAttentionLevel(unsigned char)
//   0x7cfc20  public: class ADishonoredNPCPawn * __thiscall UDishonoredCheatManager::GetIntendedNPC(unsigned int, unsigned int)const
//   0x7cfe00  public: virtual void __thiscall UDishonoredCheatManager::AISetDebug(void)
//   0x7cfea0  public: virtual void __thiscall UDishonoredCheatManager::AICycleDebug(void)
//   0x7cff80  public: virtual void __thiscall UDishonoredCheatManager::NPCDestroy(void)
//   0x7cffd0  public: virtual void __thiscall UDishonoredCheatManager::NPCDestroyNonSelected(void)
//   0x7d0050  public: virtual void __thiscall UDishonoredCheatManager::AIDeaf(unsigned int)
//   0x7d00d0  public: virtual void __thiscall UDishonoredCheatManager::AIBlind(unsigned int)
//   0x7d0150  public: virtual void __thiscall UDishonoredCheatManager::AINumb(unsigned int)
//   0x7d01d0  public: virtual void __thiscall UDishonoredCheatManager::AIDumb(unsigned int)
//   0x7d0270  public: virtual void __thiscall UDishonoredCheatManager::AIForget(void)
//   0x7d02f0  public: virtual void __thiscall UDishonoredCheatManager::AIForcePanicNow(void)
//   0x7d0340  public: virtual void __thiscall UDishonoredCheatManager::NPCSlap(float)
//   0x7d0430  public: virtual void __thiscall UDishonoredCheatManager::NPCKnockdown(void)
//   0x7d0530  public: virtual void __thiscall UDishonoredCheatManager::NPCImpulse(float, float)
//   0x7d06d0  public: virtual void __thiscall UDishonoredCheatManager::AIVerbosePathDebug(void)
//   0x7d0710  public: virtual void __thiscall UDishonoredCheatManager::NavMeshCheck(void)
//   0x7d08e0  public: virtual void __thiscall UDishonoredCheatManager::AIDebugHideout(void)
//   0x7d09f0  public: virtual void __thiscall UDishonoredCheatManager::NPCForceSkelMeshLOD(int)
//   0x7d0a40  class FString const __cdecl GetNPCForceRenderString(enum eDisLodRenderState)
//   0x7d0ac0  public: virtual void __thiscall UDishonoredCheatManager::NPCClearForcedLOD(void)
//   0x7d59a0  public: virtual void __thiscall UDishonoredCheatManager::AISetSuspicion(int)
//   0x7d5b30  public: virtual void __thiscall UDishonoredCheatManager::NPCForceLOD(unsigned char, int, int)
//   0x7d5c90  public: virtual void __thiscall UDishonoredCheatManager::NPCForceLODForAll(unsigned char, int, int)
//   0x7d5e30  class FString __cdecl DishonoredCheatManager::MakeAttentionEnumTypeList(class TArray<unsigned char, class FDefaultAllocator> const &)
//   0x7d5f90  public: virtual unsigned int __thiscall UDishonoredCheatManager::IsAttentionTypeAllowed(unsigned char)
//   0x7d8640  public: virtual void __thiscall UDishonoredCheatManager::AIEnableAllBehaviors(void)
//   0x7d8680  public: virtual void __thiscall UInput::FlushPressedKeys(void)
//   0x7d86c0  public: virtual void __thiscall UDishonoredCheatManager::AttentionAddIgnoreType(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
//   0x7d87b0  public: virtual void __thiscall UDishonoredCheatManager::AttentionClearIgnoreType(void)
//   0x7d87f0  public: virtual void __thiscall UDishonoredCheatManager::AttentionAddExclusiveType(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
//   0x7d88e0  public: virtual void __thiscall UDishonoredCheatManager::AttentionClearExclusiveType(void)
//   0x7dc3a0  public: virtual void __thiscall UDishonoredCheatManager::AIRegisterAllHideouts(void)
//   0x7dc410  public: virtual void __thiscall UDishonoredCheatManager::AIClearAttention(void)
//   0x7dc600  public: virtual void __thiscall UDishonoredCheatManager::AIEnableBehavior(class FString const &)
//   0x7dc740  public: virtual void __thiscall UDishonoredCheatManager::AIDisableBehavior(class FString const &)
//   0x7dca70  public: virtual void __thiscall UDishonoredCheatManager::AIEnableSubState(class FString const &)
//   0x7dcbb0  public: virtual void __thiscall UDishonoredCheatManager::AIDisableSubState(class FString const &)
//   0x7f1d70  public: virtual void __thiscall UDishonoredCheatManager::AIFuck(void)
//   0x7f1f10  public: virtual void __thiscall UDishonoredCheatManager::NPCSpawn(class FName)
