// DishonoredGame/src/dishonoredanimnotifies.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (192):
//   0x6d0310  public: static void __cdecl UDishonoredNotify_CameraPitchTarget::InitializePrivateStaticClassUDishonoredNotify_CameraPitchTarget(void)
//   0x6d0330  public: static void __cdecl UDishonoredNotify_ShowEquippedInvItem::InitializePrivateStaticClassUDishonoredNotify_ShowEquippedInvItem(void)
//   0x6d0350  public: static void __cdecl UDishonoredNotify_AnimStateAdvance::InitializePrivateStaticClassUDishonoredNotify_AnimStateAdvance(void)
//   0x6d0370  public: static void __cdecl UDishonoredNotify_AnimStateExit::InitializePrivateStaticClassUDishonoredNotify_AnimStateExit(void)
//   0x6d0390  public: static void __cdecl UDishonoredNotify_ChainExit::InitializePrivateStaticClassUDishonoredNotify_ChainExit(void)
//   0x6d03b0  public: static void __cdecl UDishonoredNotify_ChainStart::InitializePrivateStaticClassUDishonoredNotify_ChainStart(void)
//   0x6d03d0  public: static void __cdecl UDishonoredNotify_ChainInput::InitializePrivateStaticClassUDishonoredNotify_ChainInput(void)
//   0x6d03f0  public: static void __cdecl UDishonoredNotify_Ragdoll::InitializePrivateStaticClassUDishonoredNotify_Ragdoll(void)
//   0x6d0410  public: static void __cdecl UDishonoredNotify_AllowRagdoll::InitializePrivateStaticClassUDishonoredNotify_AllowRagdoll(void)
//   0x6d0430  public: static void __cdecl UDishonoredNotify_SetBodyMode::InitializePrivateStaticClassUDishonoredNotify_SetBodyMode(void)
//   0x6d0450  public: static void __cdecl UDishonoredNotify_UsableObjectActivate::InitializePrivateStaticClassUDishonoredNotify_UsableObjectActivate(void)
//   0x6d0470  public: static void __cdecl UDishonoredNotify_AllowMantleEnd::InitializePrivateStaticClassUDishonoredNotify_AllowMantleEnd(void)
//   0x6d0490  public: static void __cdecl UDishonoredNotify_AttachEquippedItem::InitializePrivateStaticClassUDishonoredNotify_AttachEquippedItem(void)
//   0x6d04b0  public: static void __cdecl UDisNotify_DropItem::InitializePrivateStaticClassUDisNotify_DropItem(void)
//   0x6d04d0  public: static void __cdecl UDishonoredNotify_AllowMantleCancel::InitializePrivateStaticClassUDishonoredNotify_AllowMantleCancel(void)
//   0x6d04f0  public: static void __cdecl UDishonoredNotify_Stunned::InitializePrivateStaticClassUDishonoredNotify_Stunned(void)
//   0x6d0510  public: static void __cdecl UDishonoredNotify_AnimStateSyncEnd::InitializePrivateStaticClassUDishonoredNotify_AnimStateSyncEnd(void)
//   0x6d0530  public: static void __cdecl UDishonoredNotify_Footfall::InitializePrivateStaticClassUDishonoredNotify_Footfall(void)
//   0x6d0550  public: static void __cdecl UDishonoredNotify_ReleaseCorpse::InitializePrivateStaticClassUDishonoredNotify_ReleaseCorpse(void)
//   0x6d0570  public: static void __cdecl UDishonoredNotify_EndDropCorpse::InitializePrivateStaticClassUDishonoredNotify_EndDropCorpse(void)
//   0x6d0590  public: static void __cdecl UDishonoredNotify_SeverLimb::InitializePrivateStaticClassUDishonoredNotify_SeverLimb(void)
//   0x6d05b0  public: static void __cdecl UDishonoredNotify_PlayerMeleeWeaponHitFlesh::InitializePrivateStaticClassUDishonoredNotify_PlayerMeleeWeaponHitFlesh(void)
//   0x6d05d0  public: static void __cdecl UDishonoredNotify_FireProjectile::InitializePrivateStaticClassUDishonoredNotify_FireProjectile(void)
//   0x6d05f0  public: static void __cdecl UDisNotify_ReloadAmmo::InitializePrivateStaticClassUDisNotify_ReloadAmmo(void)
//   0x6d0610  public: static void __cdecl UDisNotify_PlaceSpringRazor::InitializePrivateStaticClassUDisNotify_PlaceSpringRazor(void)
//   0x6d0630  public: static void __cdecl UDisNotify_Destroy::InitializePrivateStaticClassUDisNotify_Destroy(void)
//   0x6d0650  public: static void __cdecl UDisNotify_SetLightningTarget::InitializePrivateStaticClassUDisNotify_SetLightningTarget(void)
//   0x6d0670  public: static void __cdecl UDisNotify_VulnerablePlayer::InitializePrivateStaticClassUDisNotify_VulnerablePlayer(void)
//   0x6d0690  public: static void __cdecl UDisNotify_MakeAINoise::InitializePrivateStaticClassUDisNotify_MakeAINoise(void)
//   0x6d06b0  public: static void __cdecl UDisNotify_SwimStroke::InitializePrivateStaticClassUDisNotify_SwimStroke(void)
//   0x6d06d0  public: static void __cdecl UDisNotify_ShowBullet::InitializePrivateStaticClassUDisNotify_ShowBullet(void)
//   0x6d06f0  public: static void __cdecl UDisNotify_WindBlast::InitializePrivateStaticClassUDisNotify_WindBlast(void)
//   0x6d0710  public: static void __cdecl UDisNotify_DevouringSwarm::InitializePrivateStaticClassUDisNotify_DevouringSwarm(void)
//   0x6d0730  public: static void __cdecl UDisNotify_PowerShake::InitializePrivateStaticClassUDisNotify_PowerShake(void)
//   0x6d0750  public: static void __cdecl UDisNotify_PowerRumble::InitializePrivateStaticClassUDisNotify_PowerRumble(void)
//   0x6d0770  public: static void __cdecl UDisNotify_EnableLocomotion::InitializePrivateStaticClassUDisNotify_EnableLocomotion(void)
//   0x6d0790  public: static void __cdecl UDisNotify_BendTime::InitializePrivateStaticClassUDisNotify_BendTime(void)
//   0x6d07b0  public: static void __cdecl UDisNotify_Possession::InitializePrivateStaticClassUDisNotify_Possession(void)
//   0x6d6200  public: virtual class FColor __thiscall UDishonoredNotify_AnimStateAdvance::GetEditorColor(void)
//   0x6d6220  public: virtual class FColor __thiscall UDishonoredNotify_AnimStateExit::GetEditorColor(void)
//   0x6d6240  public: virtual class FColor __thiscall UDishonoredNotify_ChainInput::GetEditorColor(void)
//   0x6d6260  public: virtual class FColor __thiscall UDishonoredNotify_AllowRagdoll::GetEditorColor(void)
//   0x6d6280  public: virtual class FColor __thiscall UDishonoredNotify_ShowEquippedInvItem::GetEditorColor(void)
//   0x6d62a0  public: virtual class FColor __thiscall UDishonoredNotify_UsableObjectActivate::GetEditorColor(void)
//   0x6d62c0  public: virtual void __thiscall UDishonoredNotify_AllowMantleEnd::Notify(class UAnimNodeSequence *)
//   0x6d62e0  public: virtual void __thiscall UDishonoredNotify_AllowMantleCancel::Notify(class UAnimNodeSequence *)
//   0x6d6300  public: virtual void __thiscall UDishonoredNotify_AllowMantleCancel::Notify_EndRange(class UAnimNodeSequence *)
//   0x6d6320  public: virtual void __thiscall UDishonoredNotify_ReleaseCorpse::Notify(class UAnimNodeSequence *)
//   0x6d6340  public: virtual class FColor __thiscall UDishonoredNotify_FireProjectile::GetEditorColor(void)
//   0x6d6360  public: virtual class FColor __thiscall UDisNotify_ReloadAmmo::GetEditorColor(void)
//   0x6d6380  public: virtual class FColor __thiscall UDisNotify_BendTime::GetEditorColor(void)
//   0x6d68d0  public: virtual class FColor __thiscall UDisNotify_DropItem::GetEditorColor(void)
//   0x6db070  public: static class UClass * __cdecl UDishonoredNotify_CameraPitchTarget::GetPrivateStaticClassUDishonoredNotify_CameraPitchTarget(wchar_t const *)
//   0x6db100  public: static class UClass * __cdecl UDishonoredNotify_ShowEquippedInvItem::GetPrivateStaticClassUDishonoredNotify_ShowEquippedInvItem(wchar_t const *)
//   0x6db190  public: virtual void __thiscall UDishonoredNotify_ShowEquippedInvItem::Notify(class UAnimNodeSequence *)
//   0x6db1f0  public: static class UClass * __cdecl UDishonoredNotify_AnimStateAdvance::GetPrivateStaticClassUDishonoredNotify_AnimStateAdvance(wchar_t const *)
//   0x6db280  public: static class UClass * __cdecl UDishonoredNotify_AnimStateExit::GetPrivateStaticClassUDishonoredNotify_AnimStateExit(wchar_t const *)
//   0x6db310  public: static class UClass * __cdecl UDishonoredNotify_ChainExit::GetPrivateStaticClassUDishonoredNotify_ChainExit(wchar_t const *)
//   0x6db3a0  public: static class UClass * __cdecl UDishonoredNotify_ChainStart::GetPrivateStaticClassUDishonoredNotify_ChainStart(wchar_t const *)
//   0x6db430  public: static class UClass * __cdecl UDishonoredNotify_ChainInput::GetPrivateStaticClassUDishonoredNotify_ChainInput(wchar_t const *)
//   0x6db4c0  public: virtual void __thiscall UDishonoredNotify_ChainInput::Notify(class UAnimNodeSequence *)
//   0x6db510  public: virtual void __thiscall UDishonoredNotify_ChainInput::Notify_EndRange(class UAnimNodeSequence *)
//   0x6db560  public: virtual class FString __thiscall UDishonoredNotify_ChainInput::GetEditorComment(void)
//   0x6db590  public: static class UClass * __cdecl UDishonoredNotify_Ragdoll::GetPrivateStaticClassUDishonoredNotify_Ragdoll(wchar_t const *)
//   0x6db620  public: virtual void __thiscall UDishonoredNotify_Ragdoll::Notify(class UAnimNodeSequence *)
//   0x6db6f0  public: virtual class FString __thiscall UDishonoredNotify_Ragdoll::GetEditorComment(void)
//   0x6db720  public: static class UClass * __cdecl UDishonoredNotify_AllowRagdoll::GetPrivateStaticClassUDishonoredNotify_AllowRagdoll(wchar_t const *)
//   0x6db7b0  public: virtual void __thiscall UDishonoredNotify_AllowRagdoll::Notify(class UAnimNodeSequence *)
//   0x6db7e0  public: virtual class FString __thiscall UDishonoredNotify_AllowRagdoll::GetEditorComment(void)
//   0x6db810  public: static class UClass * __cdecl UDishonoredNotify_SetBodyMode::GetPrivateStaticClassUDishonoredNotify_SetBodyMode(wchar_t const *)
//   0x6db8a0  public: virtual void __thiscall UDishonoredNotify_SetBodyMode::Notify(class UAnimNodeSequence *)
//   0x6db8e0  public: virtual class FString __thiscall UDishonoredNotify_SetBodyMode::GetEditorComment(void)
//   0x6db960  public: static class UClass * __cdecl UDishonoredNotify_UsableObjectActivate::GetPrivateStaticClassUDishonoredNotify_UsableObjectActivate(wchar_t const *)
//   0x6db9f0  public: virtual void __thiscall UDishonoredNotify_UsableObjectActivate::Notify(class UAnimNodeSequence *)
//   0x6dba40  public: virtual class FString __thiscall UDishonoredNotify_UsableObjectActivate::GetEditorComment(void)
//   0x6dba70  public: static class UClass * __cdecl UDishonoredNotify_AllowMantleEnd::GetPrivateStaticClassUDishonoredNotify_AllowMantleEnd(wchar_t const *)
//   0x6dbb00  public: virtual class FString __thiscall UDishonoredNotify_AllowMantleEnd::GetEditorComment(void)
//   0x6dbb30  public: static class UClass * __cdecl UDishonoredNotify_AttachEquippedItem::GetPrivateStaticClassUDishonoredNotify_AttachEquippedItem(wchar_t const *)
//   0x6dbbc0  public: virtual void __thiscall UDishonoredNotify_AttachEquippedItem::Notify(class UAnimNodeSequence *)
//   0x6dbc20  public: virtual class FString __thiscall UDishonoredNotify_AttachEquippedItem::GetEditorComment(void)
//   0x6dbcf0  public: static class UClass * __cdecl UDisNotify_DropItem::GetPrivateStaticClassUDisNotify_DropItem(wchar_t const *)
//   0x6dbd80  public: virtual void __thiscall UDisNotify_DropItem::Notify(class UAnimNodeSequence *)
//   0x6dbf40  public: static class UClass * __cdecl UDishonoredNotify_AllowMantleCancel::GetPrivateStaticClassUDishonoredNotify_AllowMantleCancel(wchar_t const *)
//   0x6dbfd0  public: virtual class FString __thiscall UDishonoredNotify_AllowMantleCancel::GetEditorComment(void)
//   0x6dc000  public: static class UClass * __cdecl UDishonoredNotify_Stunned::GetPrivateStaticClassUDishonoredNotify_Stunned(wchar_t const *)
//   0x6dc090  public: static class UClass * __cdecl UDishonoredNotify_AnimStateSyncEnd::GetPrivateStaticClassUDishonoredNotify_AnimStateSyncEnd(wchar_t const *)
//   0x6dc120  public: static class UClass * __cdecl UDishonoredNotify_Footfall::GetPrivateStaticClassUDishonoredNotify_Footfall(wchar_t const *)
//   0x6dc1b0  public: virtual void __thiscall UDishonoredNotify_Footfall::Notify(class UAnimNodeSequence *)
//   0x6dc1e0  public: virtual class FString __thiscall UDishonoredNotify_Footfall::GetEditorComment(void)
//   0x6dc210  public: static class UClass * __cdecl UDishonoredNotify_ReleaseCorpse::GetPrivateStaticClassUDishonoredNotify_ReleaseCorpse(wchar_t const *)
//   0x6dc2a0  public: virtual class FString __thiscall UDishonoredNotify_ReleaseCorpse::GetEditorComment(void)
//   0x6dc2d0  public: static class UClass * __cdecl UDishonoredNotify_EndDropCorpse::GetPrivateStaticClassUDishonoredNotify_EndDropCorpse(wchar_t const *)
//   0x6dc360  public: virtual void __thiscall UDishonoredNotify_EndDropCorpse::Notify(class UAnimNodeSequence *)
//   0x6dc3c0  public: virtual class FString __thiscall UDishonoredNotify_EndDropCorpse::GetEditorComment(void)
//   0x6dc3f0  public: static class UClass * __cdecl UDishonoredNotify_SeverLimb::GetPrivateStaticClassUDishonoredNotify_SeverLimb(wchar_t const *)
//   0x6dc480  public: virtual void __thiscall UDishonoredNotify_SeverLimb::Notify(class UAnimNodeSequence *)
//   0x6dc5a0  public: static class UClass * __cdecl UDishonoredNotify_PlayerMeleeWeaponHitFlesh::GetPrivateStaticClassUDishonoredNotify_PlayerMeleeWeaponHitFlesh(wchar_t const *)
//   0x6dc630  public: virtual void __thiscall UDishonoredNotify_PlayerMeleeWeaponHitFlesh::Notify(class UAnimNodeSequence *)
//   0x6dc6d0  public: virtual class FString __thiscall UDishonoredNotify_PlayerMeleeWeaponHitFlesh::GetEditorComment(void)
//   0x6dc700  public: static class UClass * __cdecl UDishonoredNotify_FireProjectile::GetPrivateStaticClassUDishonoredNotify_FireProjectile(wchar_t const *)
//   0x6dc790  public: virtual void __thiscall UDishonoredNotify_FireProjectile::Notify(class UAnimNodeSequence *)
//   0x6dc850  public: virtual class FString __thiscall UDishonoredNotify_FireProjectile::GetEditorComment(void)
//   0x6dc880  public: static class UClass * __cdecl UDisNotify_ReloadAmmo::GetPrivateStaticClassUDisNotify_ReloadAmmo(wchar_t const *)
//   0x6dc910  public: virtual void __thiscall UDisNotify_ReloadAmmo::Notify(class UAnimNodeSequence *)
//   0x6dc950  public: virtual class FString __thiscall UDisNotify_ReloadAmmo::GetEditorComment(void)
//   0x6dc980  public: static class UClass * __cdecl UDisNotify_PlaceSpringRazor::GetPrivateStaticClassUDisNotify_PlaceSpringRazor(wchar_t const *)
//   0x6dca10  public: virtual void __thiscall UDisNotify_PlaceSpringRazor::Notify(class UAnimNodeSequence *)
//   0x6dca80  public: virtual class FString __thiscall UDisNotify_PlaceSpringRazor::GetEditorComment(void)
//   0x6dcab0  public: static class UClass * __cdecl UDisNotify_Destroy::GetPrivateStaticClassUDisNotify_Destroy(wchar_t const *)
//   0x6dcb40  public: virtual void __thiscall UDisNotify_Destroy::Notify(class UAnimNodeSequence *)
//   0x6dcb80  public: virtual class FString __thiscall UDisNotify_Destroy::GetEditorComment(void)
//   0x6dcbb0  public: static class UClass * __cdecl UDisNotify_SetLightningTarget::GetPrivateStaticClassUDisNotify_SetLightningTarget(wchar_t const *)
//   0x6dcc40  public: virtual void __thiscall UDisNotify_SetLightningTarget::Notify(class UAnimNodeSequence *)
//   0x6dcd70  public: static class UClass * __cdecl UDisNotify_VulnerablePlayer::GetPrivateStaticClassUDisNotify_VulnerablePlayer(wchar_t const *)
//   0x6dce00  public: virtual void __thiscall UDisNotify_VulnerablePlayer::Notify(class UAnimNodeSequence *)
//   0x6dce80  public: static class UClass * __cdecl UDisNotify_MakeAINoise::GetPrivateStaticClassUDisNotify_MakeAINoise(wchar_t const *)
//   0x6dcf10  public: virtual void __thiscall UDisNotify_MakeAINoise::Notify(class UAnimNodeSequence *)
//   0x6dcfb0  public: static class UClass * __cdecl UDisNotify_SwimStroke::GetPrivateStaticClassUDisNotify_SwimStroke(wchar_t const *)
//   0x6dd040  public: virtual void __thiscall UDisNotify_SwimStroke::Notify(class UAnimNodeSequence *)
//   0x6dd080  public: static class UClass * __cdecl UDisNotify_ShowBullet::GetPrivateStaticClassUDisNotify_ShowBullet(wchar_t const *)
//   0x6dd110  public: virtual void __thiscall UDisNotify_ShowBullet::Notify(class UAnimNodeSequence *)
//   0x6dd150  public: static class UClass * __cdecl UDisNotify_WindBlast::GetPrivateStaticClassUDisNotify_WindBlast(wchar_t const *)
//   0x6dd1e0  public: virtual void __thiscall UDisNotify_WindBlast::Notify(class UAnimNodeSequence *)
//   0x6dd250  public: virtual class FString __thiscall UDisNotify_WindBlast::GetEditorComment(void)
//   0x6dd280  public: static class UClass * __cdecl UDisNotify_DevouringSwarm::GetPrivateStaticClassUDisNotify_DevouringSwarm(wchar_t const *)
//   0x6dd310  public: virtual void __thiscall UDisNotify_DevouringSwarm::Notify(class UAnimNodeSequence *)
//   0x6dd380  public: virtual class FString __thiscall UDisNotify_DevouringSwarm::GetEditorComment(void)
//   0x6dd3b0  public: static class UClass * __cdecl UDisNotify_PowerShake::GetPrivateStaticClassUDisNotify_PowerShake(wchar_t const *)
//   0x6dd440  public: virtual void __thiscall UDisNotify_PowerShake::Notify(class UAnimNodeSequence *)
//   0x6dd4b0  public: virtual class FString __thiscall UDisNotify_PowerShake::GetEditorComment(void)
//   0x6dd4e0  public: static class UClass * __cdecl UDisNotify_PowerRumble::GetPrivateStaticClassUDisNotify_PowerRumble(wchar_t const *)
//   0x6dd570  public: virtual void __thiscall UDisNotify_PowerRumble::Notify(class UAnimNodeSequence *)
//   0x6dd5e0  public: virtual class FString __thiscall UDisNotify_PowerRumble::GetEditorComment(void)
//   0x6dd610  public: static class UClass * __cdecl UDisNotify_EnableLocomotion::GetPrivateStaticClassUDisNotify_EnableLocomotion(wchar_t const *)
//   0x6dd6a0  public: virtual void __thiscall UDisNotify_EnableLocomotion::Notify(class UAnimNodeSequence *)
//   0x6dd6e0  public: static class UClass * __cdecl UDisNotify_BendTime::GetPrivateStaticClassUDisNotify_BendTime(wchar_t const *)
//   0x6dd770  public: virtual void __thiscall UDisNotify_BendTime::Notify(class UAnimNodeSequence *)
//   0x6dd7e0  public: virtual class FString __thiscall UDisNotify_BendTime::GetEditorComment(void)
//   0x6dd810  public: static class UClass * __cdecl UDisNotify_Possession::GetPrivateStaticClassUDisNotify_Possession(wchar_t const *)
//   0x6dd8a0  public: virtual void __thiscall UDisNotify_Possession::Notify(class UAnimNodeSequence *)
//   0x6dd910  public: virtual class FString __thiscall UDisNotify_Possession::GetEditorComment(void)
//   0x6e9210  public: static class UClass * __cdecl UDishonoredNotify_CameraPitchTarget::StaticClassNoInline(void)
//   0x6e9240  public: static class UClass * __cdecl UDishonoredNotify_ShowEquippedInvItem::StaticClassNoInline(void)
//   0x6e9270  public: virtual class FString __thiscall UDishonoredNotify_ShowEquippedInvItem::GetEditorComment(void)
//   0x6e92a0  public: static class UClass * __cdecl UDishonoredNotify_AnimStateAdvance::StaticClassNoInline(void)
//   0x6e92d0  public: virtual class FString __thiscall UDishonoredNotify_AnimStateAdvance::GetEditorComment(void)
//   0x6e9300  public: static class UClass * __cdecl UDishonoredNotify_AnimStateExit::StaticClassNoInline(void)
//   0x6e9330  public: virtual class FString __thiscall UDishonoredNotify_AnimStateExit::GetEditorComment(void)
//   0x6e9360  public: static class UClass * __cdecl UDishonoredNotify_ChainExit::StaticClassNoInline(void)
//   0x6e9390  public: virtual class FString __thiscall UDishonoredNotify_ChainExit::GetEditorComment(void)
//   0x6e93c0  public: static class UClass * __cdecl UDishonoredNotify_ChainStart::StaticClassNoInline(void)
//   0x6e93f0  public: virtual class FString __thiscall UDishonoredNotify_ChainStart::GetEditorComment(void)
//   0x6e9420  public: static class UClass * __cdecl UDishonoredNotify_ChainInput::StaticClassNoInline(void)
//   0x6e9450  public: static class UClass * __cdecl UDishonoredNotify_Ragdoll::StaticClassNoInline(void)
//   0x6e9480  public: static class UClass * __cdecl UDishonoredNotify_AllowRagdoll::StaticClassNoInline(void)
//   0x6e94b0  public: static class UClass * __cdecl UDishonoredNotify_SetBodyMode::StaticClassNoInline(void)
//   0x6e94e0  public: static class UClass * __cdecl UDishonoredNotify_UsableObjectActivate::StaticClassNoInline(void)
//   0x6e9510  public: static class UClass * __cdecl UDishonoredNotify_AllowMantleEnd::StaticClassNoInline(void)
//   0x6e9540  public: static class UClass * __cdecl UDishonoredNotify_AttachEquippedItem::StaticClassNoInline(void)
//   0x6e9570  public: static class UClass * __cdecl UDisNotify_DropItem::StaticClassNoInline(void)
//   0x6e95a0  public: virtual class FString __thiscall UDisNotify_DropItem::GetEditorComment(void)
//   0x6e96d0  public: static class UClass * __cdecl UDishonoredNotify_AllowMantleCancel::StaticClassNoInline(void)
//   0x6e9700  public: static class UClass * __cdecl UDishonoredNotify_Stunned::StaticClassNoInline(void)
//   0x6e9730  public: static class UClass * __cdecl UDishonoredNotify_AnimStateSyncEnd::StaticClassNoInline(void)
//   0x6e9760  public: static class UClass * __cdecl UDishonoredNotify_Footfall::StaticClassNoInline(void)
//   0x6e9790  public: static class UClass * __cdecl UDishonoredNotify_ReleaseCorpse::StaticClassNoInline(void)
//   0x6e97c0  public: static class UClass * __cdecl UDishonoredNotify_EndDropCorpse::StaticClassNoInline(void)
//   0x6e97f0  public: static class UClass * __cdecl UDishonoredNotify_SeverLimb::StaticClassNoInline(void)
//   0x6e9820  public: virtual class FString __thiscall UDishonoredNotify_SeverLimb::GetEditorComment(void)
//   0x6e98c0  public: static class UClass * __cdecl UDishonoredNotify_PlayerMeleeWeaponHitFlesh::StaticClassNoInline(void)
//   0x6e98f0  public: static class UClass * __cdecl UDishonoredNotify_FireProjectile::StaticClassNoInline(void)
//   0x6e9920  public: static class UClass * __cdecl UDisNotify_ReloadAmmo::StaticClassNoInline(void)
//   0x6e9950  public: static class UClass * __cdecl UDisNotify_PlaceSpringRazor::StaticClassNoInline(void)
//   0x6e9980  public: static class UClass * __cdecl UDisNotify_Destroy::StaticClassNoInline(void)
//   0x6e99b0  public: static class UClass * __cdecl UDisNotify_SetLightningTarget::StaticClassNoInline(void)
//   0x6e99e0  public: virtual class FString __thiscall UDisNotify_SetLightningTarget::GetEditorComment(void)
//   0x6e9ae0  public: static class UClass * __cdecl UDisNotify_VulnerablePlayer::StaticClassNoInline(void)
//   0x6e9b10  public: static class UClass * __cdecl UDisNotify_MakeAINoise::StaticClassNoInline(void)
//   0x6e9b40  public: static class UClass * __cdecl UDisNotify_SwimStroke::StaticClassNoInline(void)
//   0x6e9b70  public: static class UClass * __cdecl UDisNotify_ShowBullet::StaticClassNoInline(void)
//   0x6e9ba0  public: static class UClass * __cdecl UDisNotify_WindBlast::StaticClassNoInline(void)
//   0x6e9bd0  public: static class UClass * __cdecl UDisNotify_DevouringSwarm::StaticClassNoInline(void)
//   0x6e9c00  public: static class UClass * __cdecl UDisNotify_PowerShake::StaticClassNoInline(void)
//   0x6e9c30  public: static class UClass * __cdecl UDisNotify_PowerRumble::StaticClassNoInline(void)
//   0x6e9c60  public: static class UClass * __cdecl UDisNotify_EnableLocomotion::StaticClassNoInline(void)
//   0x6e9c90  public: static class UClass * __cdecl UDisNotify_BendTime::StaticClassNoInline(void)
//   0x6e9cc0  public: static class UClass * __cdecl UDisNotify_Possession::StaticClassNoInline(void)
//   0x6f6440  public: virtual void __thiscall UDishonoredNotify_AnimStateAdvance::Notify(class UAnimNodeSequence *)
//   0x6f6500  public: virtual void __thiscall UDishonoredNotify_AnimStateExit::Notify(class UAnimNodeSequence *)
//   0x6f65f0  public: virtual void __thiscall UDishonoredNotify_ChainExit::Notify(class UAnimNodeSequence *)
//   0x6f6680  public: virtual void __thiscall UDishonoredNotify_Stunned::Notify(class UAnimNodeSequence *)
//   0x6f6720  public: virtual void __thiscall UDishonoredNotify_AnimStateSyncEnd::Notify(class UAnimNodeSequence *)
