// DishonoredGame/src/dishonoredcheatmanager_player.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (59):
//   0x7ca6e0  public: virtual void __thiscall UDishonoredCheatManager::idkfa(void)
//   0x7ca6f0  public: virtual void __thiscall UDishonoredCheatManager::PlayerTestChain(void)
//   0x7ca710  public: virtual void __thiscall UDishonoredCheatManager::PlayerDodgeEverything(void)
//   0x7ca730  public: virtual void __thiscall UDishonoredCheatManager::PlayerDodgeNothing(void)
//   0x7ca750  public: virtual void __thiscall UDishonoredCheatManager::PlayerSetDamage(float)
//   0x7ca770  public: virtual void __thiscall UDishonoredCheatManager::PlayerForceReadyStance(void)
//   0x7ca790  public: virtual void __thiscall UDishonoredCheatManager::PlayerDisableFatality(void)
//   0x7ca7b0  public: virtual void __thiscall UDishonoredCheatManager::PlayerDisableAssassinate(void)
//   0x7ca7d0  public: virtual void __thiscall UDishonoredCheatManager::PlayerDisableMeleeAssist(void)
//   0x7ca7f0  public: virtual void __thiscall UDishonoredCheatManager::PlayerForceFastFinishers(void)
//   0x7ca800  public: virtual void __thiscall UDishonoredCheatManager::PlayerForceLongFinishers(void)
//   0x7ca810  public: virtual void __thiscall UDishonoredCheatManager::ManaEnable(unsigned int)
//   0x7ca830  public: virtual void __thiscall UDishonoredCheatManager::ManaToggle(void)
//   0x7ca850  public: virtual void __thiscall UDishonoredCheatManager::Buddha(void)
//   0x7ca870  public: virtual void __thiscall UDishonoredCheatManager::PlayerEnableTakeDamage(void)
//   0x7ca880  public: virtual void __thiscall UDishonoredCheatManager::PlayerDisableTakeDamage(void)
//   0x7ca890  public: virtual void __thiscall UDishonoredCheatManager::PlayerEnableStrongHitReaction(void)
//   0x7ca8a0  public: virtual void __thiscall UDishonoredCheatManager::PlayerDisableStrongHitReaction(void)
//   0x7ca8b0  public: virtual void __thiscall UDishonoredCheatManager::PlayerEnableKnockdown(void)
//   0x7ca8c0  public: virtual void __thiscall UDishonoredCheatManager::PlayerDisableKnockdown(void)
//   0x7ca8d0  public: virtual void __thiscall UDishonoredCheatManager::PlayerToggleAdrenalineCooldown(void)
//   0x7ca8f0  public: virtual void __thiscall UDishonoredCheatManager::PlayerShowNavMeshStatus(unsigned int)
//   0x7ca910  public: virtual void __thiscall UDishonoredCheatManager::PlayerToggleAimAssist(void)
//   0x7ca930  public: virtual void __thiscall UDishonoredCheatManager::PlayerToggleHomingArrow(void)
//   0x7ca950  public: virtual void __thiscall UDishonoredCheatManager::PlayerForceKillCam(void)
//   0x7ca970  public: virtual void __thiscall UDishonoredCheatManager::PlayerForceDramaticFatalities(void)
//   0x7ca990  public: virtual void __thiscall UDishonoredCheatManager::EnableIronSight(void)
//   0x7cd600  public: virtual void __thiscall UDishonoredCheatManager::PlayerArmsToggle(void)
//   0x7cd630  public: virtual void __thiscall UDishonoredCheatManager::PlayerArmsEnable(unsigned int)
//   0x7cd660  public: virtual void __thiscall UDishonoredCheatManager::PlayerTestAnim(class FString const &, unsigned int)
//   0x7cd690  public: virtual void __thiscall UDishonoredCheatManager::ManaAdd(int)
//   0x7cd6b0  public: virtual void __thiscall UDishonoredCheatManager::HealthAdd(int)
//   0x7cd780  public: void __thiscall UDishonoredCheatManager::DoPlayerDamage(class UClass *, int, float, float)
//   0x7cd890  public: virtual void __thiscall UDishonoredCheatManager::PlayerInfiniteAdrenaline(void)
//   0x7cd8f0  public: virtual void __thiscall UDishonoredCheatManager::PlayerFillAdrenaline(void)
//   0x7cd940  public: virtual void __thiscall UDishonoredCheatManager::PlayerGhostChestView(unsigned int)
//   0x7d0b30  public: virtual void __thiscall UDishonoredCheatManager::TogglePlayerBodyMode_Native(class APawn *)
//   0x7d0b70  public: virtual void __thiscall UDishonoredCheatManager::SetCameraBob_Native(class APawn *, float, float)
//   0x7d0c20  public: virtual void __thiscall UDishonoredCheatManager::GivePlayerItem(class FString const &)
//   0x7d0d40  public: virtual void __thiscall UDishonoredCheatManager::PlayerForceVisible(void)
//   0x7d0d70  public: virtual void __thiscall UDishonoredCheatManager::AddObjective(class FString const &)
//   0x7d0e00  public: virtual void __thiscall UDishonoredCheatManager::RemoveObjective(class FString const &)
//   0x7d0e90  public: virtual void __thiscall UDishonoredCheatManager::ClearObjectives(void)
//   0x7d0ec0  public: virtual void __thiscall UDishonoredCheatManager::PlayerDamage(int, float, float)
//   0x7d0f00  public: virtual void __thiscall UDishonoredCheatManager::PlayerDamageBash(int, float, float)
//   0x7d0f40  public: virtual void __thiscall UDishonoredCheatManager::PlayerDamageBullet(int, float, float)
//   0x7d0f80  public: virtual void __thiscall UDishonoredCheatManager::PlayerDamageElectricity(int, float, float)
//   0x7d0fc0  public: virtual void __thiscall UDishonoredCheatManager::PlayerDamageFastHit(int, float, float)
//   0x7d1000  public: virtual void __thiscall UDishonoredCheatManager::PlayerDamageImpact(int, float, float)
//   0x7d1040  public: virtual void __thiscall UDishonoredCheatManager::PlayerDamageKnockdown(int, float, float)
//   0x7d1080  public: virtual void __thiscall UDishonoredCheatManager::PlayerDamageProjectile(int, float, float)
//   0x7d10c0  public: virtual void __thiscall UDishonoredCheatManager::PlayerDamageProjectile_Stealth(int, float, float)
//   0x7d1100  public: virtual void __thiscall UDishonoredCheatManager::DoLineCheckStressTest(int, int)
//   0x7d1330  public: virtual void __thiscall UDishonoredCheatManager::PlayerTestCamRumble(float, float, float)
//   0x7d5fe0  public: virtual void __thiscall UDishonoredCheatManager::PlayerSetFixedFatality(void)
//   0x7d6010  public: virtual void __thiscall UDishonoredCheatManager::PlayerForceDeathDir(void)
//   0x7d6040  public: virtual void __thiscall UDishonoredCheatManager::PlayerInfiniteAmmo(void)
//   0x7d6090  public: virtual void __thiscall UDishonoredCheatManager::AbstractInventoryList(void)
//   0x7dcee0  public: virtual void __thiscall UDishonoredCheatManager::MaxItems(void)
