// DishonoredGame/src/disitemcontext_npctunes.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (47):
//   0x886480  public: static void __cdecl UDisItemContext_NPCTune::InitializePrivateStaticClassUDisItemContext_NPCTune(void)
//   0x8864a0  public: static void __cdecl UDisTweaks_NPCTune::InitializePrivateStaticClassUDisTweaks_NPCTune(void)
//   0x8864c0  public: static void __cdecl UDisTweaks_Tune::InitializePrivateStaticClassUDisTweaks_Tune(void)
//   0x8864e0  protected: virtual enum eDisItemContextStatus __thiscall UDisItemContext_NPCTune::DoContext_Derived(void)
//   0x886500  protected: virtual enum eDisItemContextStatus __thiscall UDisItemContext_NPCTune::DoContext_Derived_UseNPC(struct FDisItemContextParam_UseNPC const &)
//   0x886510  protected: virtual void __thiscall UDisItemContext_NPCTune::EndItemContext_Derived(enum eDisItemContextStatus)
//   0x886520  public: virtual unsigned int __thiscall UDisItemContext_NPCTune_Combat::CanDoContext_Derived_UseNPC(struct FDisItemContextParam_UseNPC const &)const
//   0x888cb0  protected: void __thiscall UDisItemContext_NPCTune_Protection::OnNpcHActionEnded(class FArkGameEvent const &)
//   0x888cd0  protected: virtual unsigned int __thiscall UDisItemContext_NPCTune_Combat::StartTune(void)
//   0x888d20  public: unsigned int __thiscall UDisItemContext_NPCTune_Combat::IsTimerSet(float const &)const
//   0x888d60  public: virtual unsigned int __thiscall UDisTweaks_Tune_Protection::EditConditionAskObj_IsConditionMet(class FEditPropertyChain *, wchar_t const *)
//   0x88bf40  public: static class UClass * __cdecl UDisItemContext_NPCTune::GetPrivateStaticClassUDisItemContext_NPCTune(wchar_t const *)
//   0x88bfd0  public: static class UClass * __cdecl UDisItemContext_NPCTune_Protection::GetPrivateStaticClassUDisItemContext_NPCTune_Protection(wchar_t const *)
//   0x88c060  public: static class UClass * __cdecl UDisItemContext_NPCTune_Combat::GetPrivateStaticClassUDisItemContext_NPCTune_Combat(wchar_t const *)
//   0x88c0f0  public: virtual void __thiscall UDisItemContext_NPCTune_Combat::EndItemContext_Derived(enum eDisItemContextStatus)
//   0x891790  public: static class UClass * __cdecl UDisItemContext_NPCTune::StaticClassNoInline(void)
//   0x8917c0  public: static void __cdecl UDisItemContext_NPCTune_Protection::InitializePrivateStaticClassUDisItemContext_NPCTune_Protection(void)
//   0x8917e0  public: static void __cdecl UDisItemContext_NPCTune_Combat::InitializePrivateStaticClassUDisItemContext_NPCTune_Combat(void)
//   0x891800  public: virtual void __thiscall UDisItemContext_NPCTune_Combat::TickContext(float)
//   0x8939b0  public: static class UClass * __cdecl UDisItemContext_NPCTune_Protection::StaticClassNoInline(void)
//   0x8939e0  public: static class UClass * __cdecl UDisItemContext_NPCTune_Combat::StaticClassNoInline(void)
//   0x893a10  protected: virtual void __thiscall UDisItemContext_NPCTune_Protection::StopTune(void)
//   0x893a50  public: virtual unsigned int __thiscall UDisItemContext_NPCTune_Combat::IsActorInRange(class AActor const *)const
//   0x893ab0  public: void __thiscall UDisItemContext_NPCTune_Combat::OnOtherActorTerminatedEvent(class FArkGameEvent const &)
//   0x893b00  public: virtual void __thiscall UDisItemContext_NPCTune_Combat::BeginDestroy(void)
//   0x893b50  protected: virtual void __thiscall UDisItemContext_NPCTune_Combat::StopTune(void)
//   0x894d30  public: virtual void __thiscall UDisItemContext_NPCTune_Protection::InitContext(class UDishonoredInventoryItem *)
//   0x894d70  public: virtual void __thiscall UDisItemContext_NPCTune_Combat::InitContext(class UDishonoredInventoryItem *)
//   0x894db0  public: virtual enum eDisItemContextStatus __thiscall UDisItemContext_NPCTune_Combat::DoContext_Derived_UseNPC(struct FDisItemContextParam_UseNPC const &)
//   0x894e40  public: virtual void __thiscall UDisTweaks_NPCTune::GatherTweakChildren_Derived(struct TMemStackArray<struct FDisTweakChildInfo> &)const
//   0x899090  public: virtual void __thiscall UDisItemContext_NPCTune_Combat::ItemActionEnded_Derived(class UStateSharedActionBase *)
//   0x89cb10  public: static class UClass * __cdecl UDisTweaks_NPCTune::GetPrivateStaticClassUDisTweaks_NPCTune(wchar_t const *)
//   0x89cba0  public: static class UClass * __cdecl UDisTweaks_NPCTune_Protection::GetPrivateStaticClassUDisTweaks_NPCTune_Protection(wchar_t const *)
//   0x89cc30  public: static class UClass * __cdecl UDisTweaks_NPCTune_Combat::GetPrivateStaticClassUDisTweaks_NPCTune_Combat(wchar_t const *)
//   0x89ccc0  public: static class UClass * __cdecl UDisTweaks_Tune::GetPrivateStaticClassUDisTweaks_Tune(wchar_t const *)
//   0x89cd50  public: static class UClass * __cdecl UDisTweaks_Tune_Protection::GetPrivateStaticClassUDisTweaks_Tune_Protection(wchar_t const *)
//   0x89f000  public: static class UClass * __cdecl UDisTweaks_NPCTune::StaticClassNoInline(void)
//   0x89f030  public: static void __cdecl UDisTweaks_NPCTune_Protection::InitializePrivateStaticClassUDisTweaks_NPCTune_Protection(void)
//   0x89f050  public: static void __cdecl UDisTweaks_NPCTune_Combat::InitializePrivateStaticClassUDisTweaks_NPCTune_Combat(void)
//   0x89f070  public: static class UClass * __cdecl UDisTweaks_Tune::StaticClassNoInline(void)
//   0x89f0a0  public: static void __cdecl UDisTweaks_Tune_Protection::InitializePrivateStaticClassUDisTweaks_Tune_Protection(void)
//   0x8a0050  public: static class UClass * __cdecl UDisTweaks_NPCTune_Protection::StaticClassNoInline(void)
//   0x8a0080  public: static class UClass * __cdecl UDisTweaks_NPCTune_Combat::StaticClassNoInline(void)
//   0x8a00b0  public: static class UClass * __cdecl UDisTweaks_Tune_Protection::StaticClassNoInline(void)
//   0x8a00e0  public: virtual void __thiscall UDisItemContext_NPCTune_Protection::TerminateContext_Derived(void)
//   0x8a0130  protected: virtual unsigned int __thiscall UDisItemContext_NPCTune_Protection::StartTune(void)
//   0x8a01a0  protected: virtual void __thiscall UDisItemContext_NPCTune_Protection::EndItemContext_Derived(enum eDisItemContextStatus)
