// DishonoredGame/src/disnpctravelmanager.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (42):
//   0x6fbaa0  public: static void __cdecl UDisNPCTravelManager::InitializePrivateStaticClassUDisNPCTravelManager(void)
//   0x6ffc90  void __cdecl DisNPCTravelManager::ReturnHome(class ADishonoredNPCPawn &, unsigned int)
//   0x708720  private: void __thiscall UDisNPCTravelManager::SpawnTraveler(int, struct FDisNPCTravelInfo &)
//   0x708790  int __cdecl DisNPCTravelManager::GetMaterialIndex(class USkeletalMesh *, class UMaterialInterface *)
//   0x7087f0  int __cdecl DisNPCTravelManager::GetVariationIndex(struct FDisBodyMaterialVariation const &, class UMaterialInterface *)
//   0x708850  unsigned int __cdecl DisNPCTravelManager::HasExternalMaterials(struct FDisMaterialsOverride const &, class USkeletalMesh *, struct FDisMeshMaterialVariationList const &)
//   0x7088f0  unsigned int __cdecl DisNPCTravelManager::HasExternalMaterials(class ADishonoredNPCPawn const *)
//   0x708a20  void __cdecl DisNPCTravelManager::RestoreMaterialVariations(struct FDisMaterialIndexesOverride const &, struct FDisMaterialsOverride &, class USkeletalMesh *, struct FDisMeshMaterialVariationList const &)
//   0x708b80  class UClass * __cdecl DisNPCTravelManager::RestoreInventoryItem(class ADishonoredNPCPawn &, enum EDisEquipUsage, int)
//   0x708c90  float __cdecl DisNPCTravelManager::CalculateTimeToSpawn(class ADishonoredNPCPawn const &, class FVector const &, unsigned int)
//   0x70daa0  private: unsigned int __thiscall UDisNPCTravelManager::NPCCanContinueTravel(class ADishonoredNPCPawn const &)const
//   0x70db20  void __cdecl DisNPCTravelManager::StoreArmor(struct FDisNPCTravelInfo &)
//   0x70dc40  void __cdecl DisNPCTravelManager::StoreInventory(struct FDisNPCTravelInfo &)
//   0x70dd70  void __cdecl DisNPCTravelManager::RestoreInventory(struct FDisNPCTravelInfo &)
//   0x710280  private: unsigned int __thiscall UDisNPCTravelManager::NPCCanBeginTravel(class ADishonoredNPCPawn const &, unsigned int, unsigned int &)const
//   0x7103c0  void __cdecl DisNPCTravelManager::StoreMaterialVariations(struct FDisMaterialsOverride const &, struct FDisMaterialIndexesOverride &, class USkeletalMesh *, struct FDisMeshMaterialVariationList const &)
//   0x710510  void __cdecl DisNPCTravelManager::StoreAppearance(struct FDisNPCTravelInfo &)
//   0x710670  void __cdecl DisNPCTravelManager::RestoreAppearance(struct FDisNPCTravelInfo const &)
//   0x716ef0  public: virtual void __thiscall UDisNPCTravelManager::OnSpawnFailed(int)
//   0x716f40  void __cdecl DisNPCTravelManager::RestoreArmor(struct FDisNPCTravelInfo const &)
//   0x717030  void __cdecl DisNPCTravelManager::RestoreRelationships(struct FDisNPCTravelInfo const &)
//   0x718530  void __cdecl DisNPCTravelManager::RestoreNPCInfo(struct FDisNPCTravelInfo &)
//   0x71afa0  void __cdecl DisNPCTravelManager::StoreRelationships(struct FDisNPCTravelInfo &)
//   0x71b260  public: void __thiscall FDisNPCTravelInfo::GameSave(class FArchive &)
//   0x71b700  public: void __thiscall FDisNPCTravelInfo::GameLoad(class FArchive &)
//   0x71c480  public: void __thiscall UDisNPCTravelManager::AddTravelSpawner(class ADisTravelSpawner &)
//   0x71c6b0  public: virtual void __thiscall UDisNPCTravelManager::GameSave(class FArchive &, enum ESaveLoadLocation)
//   0x71c980  public: __thiscall FDisNPCTravelInfo::FDisNPCTravelInfo(void)
//   0x71ca70  public: __thiscall FDisNPCTravelInfo::FDisNPCTravelInfo(int, class FName const &, class ADishonoredNPCPawn &)
//   0x71d520  void __cdecl DisNPCTravelManager::PrepareForDeparture(struct FDisNPCTravelInfo &)
//   0x71ded0  public: void __thiscall UDisNPCTravelManager::OnReturnTravelComplete(class ADishonoredNPCPawn &)
//   0x7204d0  public: void __thiscall UDisNPCTravelManager::DiscardNPCsFromLevel(class FName const &)
//   0x720600  public: void __thiscall UDisNPCTravelManager::PrepareForDepartures(void)
//   0x720bc0  public: void __thiscall UDisNPCTravelManager::OnPawnShutDown(class ADishonoredNPCPawn const &)
//   0x720c20  public: virtual void __thiscall UDisNPCTravelManager::GameLoad(class FArchive &, enum ESaveLoadLocation)
//   0x720e70  private: void __thiscall UDisNPCTravelManager::HandleArrival(struct FDisNPCTravelInfo &, unsigned int)
//   0x721070  public: void __thiscall UDisNPCTravelManager::PrepareForArrivals(void)
//   0x7215f0  public: virtual void __thiscall UDisNPCTravelManager::OnPawnSpawned(class ADishonoredNPCPawn *)
//   0x721680  private: void __thiscall UDisNPCTravelManager::RevealTraveler(struct FDisNPCTravelInfo &)
//   0x721880  public: void __thiscall UDisNPCTravelManager::TickNPCTravelManager(float)
//   0x721ab0  public: static class UClass * __cdecl UDisNPCTravelManager::GetPrivateStaticClassUDisNPCTravelManager(wchar_t const *)
//   0x721b40  public: static class UClass * __cdecl UDisNPCTravelManager::StaticClassNoInline(void)
