"""Cross-check our compiled layouts (LayoutProbe output) against the retail SDK dump
(retail_sdk_layout.json from parse_codered_sdk.py): member offsets of every reflected property and the
class span (our sizeof must reach the end of the last retail property).

This is the retail counterpart of `gen_layout_probe.py compare` (which can only check offsets where the
2012 PDB layout still applies): every script-visible member of every probed class/struct is checked
against the offset the RETAIL exe computed at runtime.

Usage: python resources/tools/sdk/xcheck_sdk_layout.py build/<dir>/layout_probe.txt
Writes resources/docs/types/retail_sdk_delta.md; exit 1 when a contract type mismatches.
"""
import csv
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
TYPES = REPO / "resources" / "docs" / "types"
sys.path.insert(0, str(REPO / "resources" / "tools" / "symbols"))
from gen_layout_probe import CONTRACT  # noqa: E402


def load_probe(path: Path):
    sizes, offsets = {}, {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if "," not in line:
            continue
        key, val = line.rsplit(",", 1)
        if "." in key:
            if val.strip() != "MISSING":
                t, m = key.split(".", 1)
                offsets[(t, m)] = int(val)
        else:
            sizes[key] = int(val)
    return sizes, offsets


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 2
    probe = REPO / argv[1] if not Path(argv[1]).is_absolute() else Path(argv[1])
    sdk = json.loads((TYPES / "retail_sdk_layout.json").read_text(encoding="utf-8"))
    retail_sizes = {}
    with (TYPES / "native_class_sizes.csv").open(newline="", encoding="utf-8") as f:
        retail_sizes = {r["class"]: int(r["size_2013"]) for r in csv.DictReader(f) if r.get("size_2013")}
    sizes, offsets = load_probe(probe)
    rows = []
    for name in sorted(sizes):
        t = sdk["classes"].get(name) or sdk["structs"].get(name)
        if t is None:
            continue
        bad, checked, unseen = [], 0, []
        for m in t["members"]:
            got = offsets.get((name, m["name"]))
            if got is None:
                unseen.append(m["name"])
                continue
            checked += 1
            if got != m["offset"]:
                bad.append((m["name"], m["offset"], got))
        span_end = t.get("span_end")
        too_small = span_end is not None and sizes[name] < span_end
        rows.append({"name": name, "kind": "class" if name in sdk["classes"] else "struct", "ours": sizes[name], "span_end": span_end,
                     "retail": retail_sizes.get(name), "checked": checked, "bad": bad, "unseen": unseen, "too_small": too_small})
    mismatching = [r for r in rows if r["bad"] or r["too_small"]]
    contract_bad = [r for r in mismatching if r["name"] in CONTRACT]
    exact = [r for r in rows if not r["bad"] and not r["too_small"] and r["checked"]]
    out = TYPES / "retail_sdk_delta.md"
    with out.open("w", encoding="utf-8") as f:
        f.write("# Compiled layout vs retail SDK dump (runtime property offsets of the 2013 exe)\n\n")
        f.write(f"Generated by `xcheck_sdk_layout.py` from `{probe.name}` and `retail_sdk_layout.json`. "
                f"{len(rows)} probed types exist in the dump; {len(exact)} have every probed reflected member at the retail offset "
                f"and reach the retail span; {len(mismatching)} differ ({len(contract_bad)} contract types).\n\n")
        f.write("`Span end` = end of the last reflected retail property (the C++ sizeof, `Retail sizeof`, may be larger: native-only tail members). "
                "`Checked` = members present in both the probe and the dump; members the probe does not report (bitfields, members our header lacks) are listed under `Unseen`.\n\n")
        f.write("## Contract types\n\n| Type | Ours | Span end | Retail sizeof | Checked | Offset mismatches (member: retail→ours) | Unseen |\n|---|---:|---:|---:|---:|---|---|\n")
        for r in rows:
            if r["name"] not in CONTRACT:
                continue
            flag = " **too small**" if r["too_small"] else ""
            f.write(f"| {r['name']} | {r['ours']}{flag} | {r['span_end'] or ''} | {r['retail'] or ''} | {r['checked']} | "
                    f"{', '.join(f'{m}: {a}→{b}' for m, a, b in r['bad'][:8])} | {', '.join(r['unseen'][:6])} |\n")
        f.write("\n## All other probed types with differences\n\n| Type | Ours | Span end | Retail sizeof | Checked | First mismatches (member: retail→ours) |\n|---|---:|---:|---:|---:|---|\n")
        for r in mismatching:
            if r["name"] in CONTRACT:
                continue
            flag = " **too small**" if r["too_small"] else ""
            f.write(f"| {r['name']} | {r['ours']}{flag} | {r['span_end'] or ''} | {r['retail'] or ''} | {r['checked']} | "
                    f"{', '.join(f'{m}: {a}→{b}' for m, a, b in r['bad'][:4])} |\n")
    print(f"types={len(rows)} exact={len(exact)} mismatching={len(mismatching)} contract_mismatches={len(contract_bad)} -> {out.relative_to(REPO)}")
    return 1 if contract_bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
