// OnlineSubsystemSteamworksNativeStubs.cpp - exec bodies of the retail OnlineSubsystemSteamworks natives, not ported yet: every one aborts with its name.
// Generated by resources/tools/symbols/gen_classes_header.py --sdk. Port a native by moving its body into the module's own
// source (and removing it here); the generator skips natives listed in <Module>NativeStubs.ported.txt.
#include "OnlineSubsystemSteamworks.h"

void UOnlineSubsystemSteamworks::execInt64ToUniqueNetId( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execInt64ToUniqueNetId"));
}
void UOnlineSubsystemSteamworks::execUniqueNetIdToInt64( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execUniqueNetIdToInt64"));
}
void UOnlineSubsystemSteamworks::execShowProfileUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowProfileUI"));
}
void UOnlineSubsystemSteamworks::execUniqueNetIdToPlayerName( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execUniqueNetIdToPlayerName"));
}
void UOnlineSubsystemSteamworks::execDisplayAchievementProgress( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execDisplayAchievementProgress"));
}
void UOnlineSubsystemSteamworks::execEnumerateFilesOnRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execEnumerateFilesOnRemoteStorage"));
}
void UOnlineSubsystemSteamworks::execDeleteFileFromRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execDeleteFileFromRemoteStorage"));
}
void UOnlineSubsystemSteamworks::execReadBytesFromRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execReadBytesFromRemoteStorage"));
}
void UOnlineSubsystemSteamworks::execReadStringFromRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execReadStringFromRemoteStorage"));
}
void UOnlineSubsystemSteamworks::execWriteBytesToRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execWriteBytesToRemoteStorage"));
}
void UOnlineSubsystemSteamworks::execWriteStringToRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execWriteStringToRemoteStorage"));
}
void UOnlineSubsystemSteamworks::execGetSteamClanData( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execGetSteamClanData"));
}
void UOnlineSubsystemSteamworks::execReadOnlineAvatar( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execReadOnlineAvatar"));
}
void UOnlineSubsystemSteamworks::execShowCustomPlayersUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowCustomPlayersUI"));
}
void UOnlineSubsystemSteamworks::execGetAchievements( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execGetAchievements"));
}
void UOnlineSubsystemSteamworks::execReadAchievements( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execReadAchievements"));
}
void UOnlineSubsystemSteamworks::execShowPlayersUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowPlayersUI"));
}
void UOnlineSubsystemSteamworks::execShowFriendsInviteUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowFriendsInviteUI"));
}
void UOnlineSubsystemSteamworks::execShowFriendsUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowFriendsUI"));
}
void UOnlineSubsystemSteamworks::execUnlockGamerPicture( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execUnlockGamerPicture"));
}
void UOnlineSubsystemSteamworks::execUnlockAchievement( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execUnlockAchievement"));
}
void UOnlineSubsystemSteamworks::execIsDeviceValid( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execIsDeviceValid"));
}
void UOnlineSubsystemSteamworks::execGetDeviceSelectionResults( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execGetDeviceSelectionResults"));
}
void UOnlineSubsystemSteamworks::execShowDeviceSelectionUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowDeviceSelectionUI"));
}
void UOnlineSubsystemSteamworks::execShowMembershipMarketplaceUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowMembershipMarketplaceUI"));
}
void UOnlineSubsystemSteamworks::execShowContentMarketplaceUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowContentMarketplaceUI"));
}
void UOnlineSubsystemSteamworks::execShowInviteUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowInviteUI"));
}
void UOnlineSubsystemSteamworks::execShowAchievementsUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowAchievementsUI"));
}
void UOnlineSubsystemSteamworks::execShowMessagesUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowMessagesUI"));
}
void UOnlineSubsystemSteamworks::execShowGamerCardUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowGamerCardUI"));
}
void UOnlineSubsystemSteamworks::execShowFeedbackUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowFeedbackUI"));
}
void UOnlineSubsystemSteamworks::execShowKeyboardUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowKeyboardUI"));
}
void UOnlineSubsystemSteamworks::execSetOnlineStatus( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execSetOnlineStatus"));
}
void UOnlineSubsystemSteamworks::execCreateOnlineAccount( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execCreateOnlineAccount"));
}
void UOnlineSubsystemSteamworks::execGetTitleFileContents( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execGetTitleFileContents"));
}
void UOnlineSubsystemSteamworks::execReadTitleFile( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execReadTitleFile"));
}
void UOnlineSubsystemSteamworks::execGetNATType( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execGetNATType"));
}
void UOnlineSubsystemSteamworks::execIsControllerConnected( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execIsControllerConnected"));
}
void UOnlineSubsystemSteamworks::execSetNetworkNotificationPosition( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execSetNetworkNotificationPosition"));
}
void UOnlineSubsystemSteamworks::execHasLinkConnection( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execHasLinkConnection"));
}
void UOnlineSubsystemSteamworks::execGetFriendsList( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execGetFriendsList"));
}
void UOnlineSubsystemSteamworks::execReadFriendsList( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execReadFriendsList"));
}
void UOnlineSubsystemSteamworks::execWriteProfileSettingsCompleted( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execWriteProfileSettingsCompleted"));
}
void UOnlineSubsystemSteamworks::execWriteProfileSettings( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execWriteProfileSettings"));
}
void UOnlineSubsystemSteamworks::execReadProfileSettingsCompleted( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execReadProfileSettingsCompleted"));
}
void UOnlineSubsystemSteamworks::execReadProfileSettings( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execReadProfileSettings"));
}
void UOnlineSubsystemSteamworks::execAreAnyFriends( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execAreAnyFriends"));
}
void UOnlineSubsystemSteamworks::execIsFriend( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execIsFriend"));
}
void UOnlineSubsystemSteamworks::execGetLoginStatus( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execGetLoginStatus"));
}
void UOnlineSubsystemSteamworks::execLogout( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execLogout"));
}
void UOnlineSubsystemSteamworks::execAutoLogin( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execAutoLogin"));
}
void UOnlineSubsystemSteamworks::execLogin( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execLogin"));
}
void UOnlineSubsystemSteamworks::execShowLoginUI( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execShowLoginUI"));
}
void UOnlineSubsystemSteamworks::execExit( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execExit"));
}
void UOnlineSubsystemSteamworks::execInit( FFrame& Stack, RESULT_DECL )
{
	appErrorf(TEXT("OnlineSubsystemSteamworks native not ported: %s"), TEXT("UOnlineSubsystemSteamworks::execInit"));
}
