// OnlineSubsystemSteamworksNativeStubs.cpp - exec bodies of the retail OnlineSubsystemSteamworks natives, not ported yet: every one consumes its
// parameters, zeroes its result and warns once (DISHONORED_NATIVE_STUB, Core/Inc/DishonoredNativeStub.h; -strictnatives aborts).
// Generated by resources/tools/symbols/gen_classes_header.py --sdk. Port a native by moving its body into the module's own
// source (and removing it here); the generator skips natives listed in <Module>NativeStubs.ported.txt.
#include "OnlineSubsystemSteamworks.h"
#include "DishonoredNativeStub.h"

void UOnlineSubsystemSteamworks::execInt64ToUniqueNetId( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execInt64ToUniqueNetId);
}
void UOnlineSubsystemSteamworks::execUniqueNetIdToInt64( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execUniqueNetIdToInt64);
}
void UOnlineSubsystemSteamworks::execShowProfileUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowProfileUI);
}
void UOnlineSubsystemSteamworks::execUniqueNetIdToPlayerName( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execUniqueNetIdToPlayerName);
}
void UOnlineSubsystemSteamworks::execDisplayAchievementProgress( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execDisplayAchievementProgress);
}
void UOnlineSubsystemSteamworks::execEnumerateFilesOnRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execEnumerateFilesOnRemoteStorage);
}
void UOnlineSubsystemSteamworks::execDeleteFileFromRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execDeleteFileFromRemoteStorage);
}
void UOnlineSubsystemSteamworks::execReadBytesFromRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execReadBytesFromRemoteStorage);
}
void UOnlineSubsystemSteamworks::execReadStringFromRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execReadStringFromRemoteStorage);
}
void UOnlineSubsystemSteamworks::execWriteBytesToRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execWriteBytesToRemoteStorage);
}
void UOnlineSubsystemSteamworks::execWriteStringToRemoteStorage( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execWriteStringToRemoteStorage);
}
void UOnlineSubsystemSteamworks::execGetSteamClanData( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execGetSteamClanData);
}
void UOnlineSubsystemSteamworks::execReadOnlineAvatar( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execReadOnlineAvatar);
}
void UOnlineSubsystemSteamworks::execShowCustomPlayersUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowCustomPlayersUI);
}
void UOnlineSubsystemSteamworks::execGetAchievements( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execGetAchievements);
}
void UOnlineSubsystemSteamworks::execReadAchievements( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execReadAchievements);
}
void UOnlineSubsystemSteamworks::execShowPlayersUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowPlayersUI);
}
void UOnlineSubsystemSteamworks::execShowFriendsInviteUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowFriendsInviteUI);
}
void UOnlineSubsystemSteamworks::execShowFriendsUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowFriendsUI);
}
void UOnlineSubsystemSteamworks::execUnlockGamerPicture( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execUnlockGamerPicture);
}
void UOnlineSubsystemSteamworks::execUnlockAchievement( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execUnlockAchievement);
}
void UOnlineSubsystemSteamworks::execIsDeviceValid( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execIsDeviceValid);
}
void UOnlineSubsystemSteamworks::execGetDeviceSelectionResults( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execGetDeviceSelectionResults);
}
void UOnlineSubsystemSteamworks::execShowDeviceSelectionUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowDeviceSelectionUI);
}
void UOnlineSubsystemSteamworks::execShowMembershipMarketplaceUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowMembershipMarketplaceUI);
}
void UOnlineSubsystemSteamworks::execShowContentMarketplaceUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowContentMarketplaceUI);
}
void UOnlineSubsystemSteamworks::execShowInviteUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowInviteUI);
}
void UOnlineSubsystemSteamworks::execShowAchievementsUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowAchievementsUI);
}
void UOnlineSubsystemSteamworks::execShowMessagesUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowMessagesUI);
}
void UOnlineSubsystemSteamworks::execShowGamerCardUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowGamerCardUI);
}
void UOnlineSubsystemSteamworks::execShowFeedbackUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowFeedbackUI);
}
void UOnlineSubsystemSteamworks::execShowKeyboardUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowKeyboardUI);
}
void UOnlineSubsystemSteamworks::execSetOnlineStatus( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execSetOnlineStatus);
}
void UOnlineSubsystemSteamworks::execCreateOnlineAccount( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execCreateOnlineAccount);
}
void UOnlineSubsystemSteamworks::execGetTitleFileContents( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execGetTitleFileContents);
}
void UOnlineSubsystemSteamworks::execReadTitleFile( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execReadTitleFile);
}
void UOnlineSubsystemSteamworks::execGetNATType( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execGetNATType);
}
void UOnlineSubsystemSteamworks::execIsControllerConnected( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execIsControllerConnected);
}
void UOnlineSubsystemSteamworks::execSetNetworkNotificationPosition( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execSetNetworkNotificationPosition);
}
void UOnlineSubsystemSteamworks::execHasLinkConnection( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execHasLinkConnection);
}
void UOnlineSubsystemSteamworks::execGetFriendsList( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execGetFriendsList);
}
void UOnlineSubsystemSteamworks::execReadFriendsList( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execReadFriendsList);
}
void UOnlineSubsystemSteamworks::execWriteProfileSettingsCompleted( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execWriteProfileSettingsCompleted);
}
void UOnlineSubsystemSteamworks::execWriteProfileSettings( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execWriteProfileSettings);
}
void UOnlineSubsystemSteamworks::execReadProfileSettingsCompleted( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execReadProfileSettingsCompleted);
}
void UOnlineSubsystemSteamworks::execReadProfileSettings( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execReadProfileSettings);
}
void UOnlineSubsystemSteamworks::execAreAnyFriends( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execAreAnyFriends);
}
void UOnlineSubsystemSteamworks::execIsFriend( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execIsFriend);
}
void UOnlineSubsystemSteamworks::execGetLoginStatus( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execGetLoginStatus);
}
void UOnlineSubsystemSteamworks::execLogout( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execLogout);
}
void UOnlineSubsystemSteamworks::execAutoLogin( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execAutoLogin);
}
void UOnlineSubsystemSteamworks::execLogin( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execLogin);
}
void UOnlineSubsystemSteamworks::execShowLoginUI( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execShowLoginUI);
}
void UOnlineSubsystemSteamworks::execExit( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execExit);
}
void UOnlineSubsystemSteamworks::execInit( FFrame& Stack, RESULT_DECL )
{
	DISHONORED_NATIVE_STUB(OnlineSubsystemSteamworks, UOnlineSubsystemSteamworks, execInit);
}
