// Engine/src/arkppnodes.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (50):
//   0x549fb0  public: static void __cdecl UArkPpNode::InitializePrivateStaticClassUArkPpNode(void)
//   0x549fd0  public: static void __cdecl UArkPpSettings::InitializePrivateStaticClassUArkPpSettings(void)
//   0x549ff0  public: static void __cdecl UArkPpNodeController::InitializePrivateStaticClassUArkPpNodeController(void)
//   0x54a010  public: virtual unsigned int __thiscall FArkPpNodeSceneColorProxy::GetSurfaceSizeX(void)
//   0x54a020  public: virtual unsigned int __thiscall FArkPpNodeSceneColorProxy::GetSurfaceSizeY(void)
//   0x54a030  public: virtual unsigned int __thiscall FArkPpNodeTargetProxy::GetSurfaceSizeX(void)
//   0x54a050  public: virtual unsigned int __thiscall FArkPpNodeTargetProxy::GetSurfaceSizeY(void)
//   0x54a070  public: virtual unsigned int __thiscall UArkPpNodeTarget::IsValid(struct FArkPpIsValidData &)
//   0x54a080  public: __thiscall FArkPpNodeCommonTargetProxy::FArkPpNodeCommonTargetProxy(struct FArkPpCreateProxyConfig &, class UArkPpNodeCommonTarget *)
//   0x54a0d0  public: virtual unsigned int __thiscall FArkPpNodeCommonTargetProxy::GetSurfaceSizeX(void)
//   0x54a110  public: virtual unsigned int __thiscall FArkPpNodeCommonTargetProxy::GetSurfaceSizeY(void)
//   0x54a150  public: virtual unsigned int __thiscall UArkPpNodeSwitch::LinkInput(unsigned int, class UArkPpNode *)
//   0x54a180  public: virtual unsigned int __thiscall UArkPpNodeSwitch::UnlinkInput(class UArkPpNode *)
//   0x54a1c0  public: virtual unsigned int __thiscall UArkPpNodeSwitch::UnlinkInput(unsigned int)
//   0x54a200  public: virtual class FArkPpNodeProxy * __thiscall UArkPpNodeSwitch::CreateSceneProxy(struct FArkPpCreateProxyConfig &)
//   0x54bcd0  public: static class UClass * __cdecl UArkPpNodeController::GetPrivateStaticClassUArkPpNodeController(wchar_t const *)
//   0x54bd60  public: virtual class TDynamicRHIResourceReference<12> const __thiscall FArkPpNodeSceneColorProxy::GetSurface(class FViewInfo const &)
//   0x54bdb0  public: virtual class TDynamicRHIResourceReference<14> const __thiscall FArkPpNodeSceneColorProxy::GetTexture(class FViewInfo const &)
//   0x54be00  public: virtual class TDynamicRHIResourceReference<12> const __thiscall FArkPpNodeTargetProxy::GetSurface(class FViewInfo const &)
//   0x54bed0  public: virtual unsigned int __thiscall FArkPpNodeTargetProxy::Render(class FScene const *, class FViewInfo &, struct FArkPpRenderConfig)
//   0x54c040  public: virtual class TDynamicRHIResourceReference<12> const __thiscall FArkPpNodeCommonTargetProxy::GetSurface(class FViewInfo const &)
//   0x54c0e0  public: virtual class TDynamicRHIResourceReference<14> const __thiscall FArkPpNodeCommonTargetProxy::GetTexture(class FViewInfo const &)
//   0x54c180  public: virtual unsigned int __thiscall FArkPpNodeCommonTargetProxy::Render(class FScene const *, class FViewInfo &, struct FArkPpRenderConfig)
//   0x54fce0  public: static class UClass * __cdecl UArkPpSettings::GetPrivateStaticClassUArkPpSettings(wchar_t const *)
//   0x54fd70  public: static class UClass * __cdecl UArkPpNodeController::StaticClassNoInline(void)
//   0x54fda0  public: virtual class FString __thiscall UArkPpNode::InputName(unsigned int)const
//   0x54fdd0  public: virtual class FString __thiscall UArkPpNodeSceneColor::InputName(unsigned int)const
//   0x54fe00  public: virtual class TDynamicRHIResourceReference<14> const __thiscall FArkPpNodeTargetProxy::GetTexture(class FViewInfo const &)
//   0x54ff10  public: virtual class FString __thiscall UArkPpNodeTarget::InputName(unsigned int)const
//   0x54ff40  public: virtual class FString __thiscall UArkPpNodeCommonTarget::InputName(unsigned int)const
//   0x54ff70  public: virtual class FString __thiscall UArkPpNodeSwitch::InputName(unsigned int)const
//   0x555ca0  public: static class UClass * __cdecl UArkPpSettings::StaticClassNoInline(void)
//   0x55d860  public: static class UClass * __cdecl UArkPpNode::GetPrivateStaticClassUArkPpNode(wchar_t const *)
//   0x55d8f0  public: static class UClass * __cdecl UArkPpNodeTarget::GetPrivateStaticClassUArkPpNodeTarget(wchar_t const *)
//   0x55d980  public: static class UClass * __cdecl UArkPpNodeCommonTarget::GetPrivateStaticClassUArkPpNodeCommonTarget(wchar_t const *)
//   0x55da10  public: static class UClass * __cdecl UArkPpNodeSceneColor::GetPrivateStaticClassUArkPpNodeSceneColor(wchar_t const *)
//   0x55daa0  public: static class UClass * __cdecl UArkPpNodeSwitch::GetPrivateStaticClassUArkPpNodeSwitch(wchar_t const *)
//   0x55e920  public: static class UClass * __cdecl UArkPpNode::StaticClassNoInline(void)
//   0x55e950  public: static void __cdecl UArkPpNodeTarget::InitializePrivateStaticClassUArkPpNodeTarget(void)
//   0x55e970  public: static void __cdecl UArkPpNodeCommonTarget::InitializePrivateStaticClassUArkPpNodeCommonTarget(void)
//   0x55e990  public: static void __cdecl UArkPpNodeSceneColor::InitializePrivateStaticClassUArkPpNodeSceneColor(void)
//   0x55e9b0  public: static void __cdecl UArkPpNodeSwitch::InitializePrivateStaticClassUArkPpNodeSwitch(void)
//   0x55fc40  public: static class UClass * __cdecl UArkPpNodeTarget::StaticClassNoInline(void)
//   0x55fc70  public: static class UClass * __cdecl UArkPpNodeCommonTarget::StaticClassNoInline(void)
//   0x55fca0  public: static class UClass * __cdecl UArkPpNodeSceneColor::StaticClassNoInline(void)
//   0x55fcd0  public: static class UClass * __cdecl UArkPpNodeSwitch::StaticClassNoInline(void)
//   0x5659e0  public: virtual class FArkPpNodeProxy * __thiscall UArkPpNodeSceneColor::CreateSceneProxy(struct FArkPpCreateProxyConfig &)
//   0x565a70  public: virtual class FArkPpNodeProxy * __thiscall UArkPpNodeTarget::CreateSceneProxy(struct FArkPpCreateProxyConfig &)
//   0x565b00  public: virtual class FArkPpNodeProxy * __thiscall UArkPpNodeCommonTarget::CreateSceneProxy(struct FArkPpCreateProxyConfig &)
//   0x565b90  public: virtual unsigned int __thiscall UArkPpNodeSwitch::IsValid(struct FArkPpIsValidData &)
