#pragma once
// DishonoredGame/inc/dishonoredgameaiclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (297):
//   0x63b940  public: void __thiscall UDisBehaviorEscapeExplosion::execRequestStateExitCallback_Flee(struct FFrame &, void * const)
//   0x63b9a0  public: void __thiscall UDisBehaviorEscapeExplosion::execThreatTerminatedCallback_Flee(struct FFrame &, void * const)
//   0x63ba00  public: void __thiscall UDisBehaviorGoHome::execOnEnterCallback_GenericAction(struct FFrame &, void * const)
//   0x63ba90  public: void __thiscall UDisBehaviorEscapePlague::execRefreshCallback_TakePosition(struct FFrame &, void * const)
//   0x63bb20  public: void __thiscall UDisBehaviorPanic::execOnEnterCallback_Flee(struct FFrame &, void * const)
//   0x63bbb0  public: void __thiscall UDisBehaviorCombatRatSwarm::execRefreshCallback_Stand(struct FFrame &, void * const)
//   0x63bc40  public: void __thiscall UDisBehaviorPanic::execRefreshCallback_Cower(struct FFrame &, void * const)
//   0x63bcd0  public: void __thiscall UDisBehaviorPatrol::execTickCallback_TakeActorPosition(struct FFrame &, void * const)
//   0x63bd60  public: void __thiscall UDisBehaviorNotice::execOnExitCallback_Init(struct FFrame &, void * const)
//   0x63bdf0  public: void __thiscall UDisBehaviorWeep::execOnEnterCallback_GenericAction(struct FFrame &, void * const)
//   0x63be80  public: void __thiscall UDisBehaviorWeep::execRequestStateExitCallback_GenericAction(struct FFrame &, void * const)
//   0x63bee0  public: void __thiscall UDisBehaviorWeep::execRequestStateExitCallback_DoWeaponManoeuver(struct FFrame &, void * const)
//   0x63bf40  public: void __thiscall UDisBehaviorFollow::execNoMoreTargetCallback_Follow(struct FFrame &, void * const)
//   0x63bfe0  public: void __thiscall UDisBehaviorEscapePlague::execOnResetCallback_TakePosition(struct FFrame &, void * const)
//   0x63c570  public: void __thiscall UDisBehaviorSearch::execRequestStateExitCallback_Stand(struct FFrame &, void * const)
//   0x63c630  public: void __thiscall UDisBehaviorGoHome::execRefreshCallback_Menace(struct FFrame &, void * const)
//   0x63c6c0  public: void __thiscall UDisBehaviorEnemyUnreachable::execRequestStateExitCallback_TakePosition(struct FFrame &, void * const)
//   0x63d180  public: void __thiscall UDisGFxMoviePlayerBase::execOnFocusLost(struct FFrame &, void * const)
//   0x63edd0  public: void __thiscall UDisBehaviorCombatMelee::execRefreshCallback_MeleeChase(struct FFrame &, void * const)
//   0x63f540  public: void __thiscall UDisBehaviorSearch::execOnEnterCallback_GenericAction(struct FFrame &, void * const)
//   0x63f660  public: void __thiscall UDisBehaviorSearch::execOnEnterCallback_Stand(struct FFrame &, void * const)
//   0x63f810  public: void __thiscall UDisBehaviorReact::execOnEnterCallback_GenericAction(struct FFrame &, void * const)
//   0x63f8a0  public: void __thiscall UDisBehaviorSearch::execOnExitCallback_Investigate(struct FFrame &, void * const)
//   0x63f930  public: void __thiscall UDisBehaviorTriggerAlarm::execRefreshCallback_TakePosition(struct FFrame &, void * const)
//   0x63f9c0  public: void __thiscall UDisBehaviorGoHome::execRequestStateExitCallback_GenericAction(struct FFrame &, void * const)
//   0x644860  public: virtual wchar_t const * __thiscall FAIRecord_RegisteredHideout::GetRecordClassName(void)const
//   0x64a240  public: virtual wchar_t const * __thiscall FAIKnowledgeRecord_WhaleOilDevice::GetRecordClassName(void)const
//   0x64c970  protected: virtual __thiscall UDisHideoutComponent::~UDisHideoutComponent(void)
//   0x64efc0  protected: virtual __thiscall UDisHideoutComponent_Usable::~UDisHideoutComponent_Usable(void)
//   0x64f050  protected: virtual __thiscall UDisHideoutComponent_Volume::~UDisHideoutComponent_Volume(void)
//   0x650b60  public: static void __cdecl UDisHideoutComponent::InternalConstructor(void *)
//   0x650b80  public: static void __cdecl UDisHideoutComponent_Usable::InternalConstructor(void *)
//   0x650ba0  public: static void __cdecl UDisHideoutComponent_Volume::InternalConstructor(void *)
//   0x715770  protected: virtual __thiscall UDishonoredSearchCrumbsComponent::~UDishonoredSearchCrumbsComponent(void)
//   0x717cd0  public: static void __cdecl UDishonoredSearchCrumbsComponent::InternalConstructor(void *)
//   0x72e200  public: virtual enum GASObjectInterface::ObjectType __thiscall GASRectangleObject::GetObjectType(void)const
//   0x72e210  public: virtual wchar_t const * __thiscall FAIKnowledgeRecord_LastCorpse::GetRecordClassName(void)const
//   0x732f80  protected: virtual __thiscall UDishonoredAIBehavior::~UDishonoredAIBehavior(void)
//   0x7330c0  protected: virtual __thiscall UDisAIBehaviorWithDesires::~UDisAIBehaviorWithDesires(void)
//   0x733270  protected: virtual __thiscall UDisBehaviorBattleVictory::~UDisBehaviorBattleVictory(void)
//   0x7333f0  protected: virtual __thiscall UDisBehaviorBlockingDialog::~UDisBehaviorBlockingDialog(void)
//   0x7334c0  protected: virtual __thiscall UDisBehaviorEscapeExplosion::~UDisBehaviorEscapeExplosion(void)
//   0x733630  protected: virtual __thiscall UDisBehaviorGoHome::~UDisBehaviorGoHome(void)
//   0x7337c0  protected: virtual __thiscall UDisBehaviorGuard::~UDisBehaviorGuard(void)
//   0x733930  protected: virtual __thiscall UDisBehaviorIdle::~UDisBehaviorIdle(void)
//   0x733aa0  protected: virtual __thiscall UDisBehaviorInteract::~UDisBehaviorInteract(void)
//   0x733b80  protected: virtual __thiscall UDisBehaviorMagicResponse::~UDisBehaviorMagicResponse(void)
//   0x733d00  protected: virtual __thiscall UDisBehaviorNotice::~UDisBehaviorNotice(void)
//   0x733eb0  protected: virtual __thiscall UDisBehaviorPanic::~UDisBehaviorPanic(void)
//   0x733f70  protected: virtual __thiscall UDisBehaviorPatrol::~UDisBehaviorPatrol(void)
//   0x734180  protected: virtual __thiscall UDisBehaviorRatStomp::~UDisBehaviorRatStomp(void)
//   0x7342f0  protected: virtual __thiscall UDisBehaviorReact::~UDisBehaviorReact(void)
//   0x7343c0  protected: virtual __thiscall UDisBehaviorReturnTravel::~UDisBehaviorReturnTravel(void)
//   0x734480  protected: virtual __thiscall UDisBehaviorSoiree::~UDisBehaviorSoiree(void)
//   0x734530  protected: virtual __thiscall UDisBehaviorEscapePlague::~UDisBehaviorEscapePlague(void)
//   0x7345e0  protected: virtual __thiscall UDisBehaviorFollow::~UDisBehaviorFollow(void)
//   0x735a60  public: static void __cdecl UDisAIBehaviorWithDesires::InternalConstructor(void *)
//   0x735aa0  public: static void __cdecl UDisBehaviorBattleVictory::InternalConstructor(void *)
//   0x735ac0  public: static void __cdecl UDisBehaviorBlockingDialog::InternalConstructor(void *)
//   0x735ae0  public: static void __cdecl UDisBehaviorEscapeExplosion::InternalConstructor(void *)
//   0x735b20  public: static void __cdecl UDisBehaviorGoHome::InternalConstructor(void *)
//   0x735b40  public: static void __cdecl UDisBehaviorGuard::InternalConstructor(void *)
//   0x735b60  public: static void __cdecl UDisBehaviorIdle::InternalConstructor(void *)
//   0x735b80  public: static void __cdecl UDisBehaviorInteract::InternalConstructor(void *)
//   0x735ba0  public: static void __cdecl UDisBehaviorMagicResponse::InternalConstructor(void *)
//   0x735be0  public: static void __cdecl UDisBehaviorNotice::InternalConstructor(void *)
//   0x735c00  public: static void __cdecl UDisBehaviorPanic::InternalConstructor(void *)
//   0x735c20  public: static void __cdecl UDisBehaviorPatrol::InternalConstructor(void *)
//   0x735c40  public: static void __cdecl UDisBehaviorRatStomp::InternalConstructor(void *)
//   0x735c60  public: static void __cdecl UDisBehaviorReact::InternalConstructor(void *)
//   0x735c80  public: static void __cdecl UDisBehaviorReturnTravel::InternalConstructor(void *)
//   0x735cc0  public: static void __cdecl UDisBehaviorSoiree::InternalConstructor(void *)
//   0x735d00  public: static void __cdecl UDisBehaviorEscapePlague::InternalConstructor(void *)
//   0x735d30  public: static void __cdecl UDisBehaviorFollow::InternalConstructor(void *)
//   0x7379e0  protected: virtual __thiscall UDisTweaks_AIBehavior::~UDisTweaks_AIBehavior(void)
//   0x737a90  protected: virtual __thiscall UDisTweaks_AIBehavior_EscapeExplosion::~UDisTweaks_AIBehavior_EscapeExplosion(void)
//   0x737b20  protected: virtual __thiscall UDisTweaks_AIBehavior_GoHome::~UDisTweaks_AIBehavior_GoHome(void)
//   0x737bb0  protected: virtual __thiscall UDisTweaks_AIBehavior_Notice::~UDisTweaks_AIBehavior_Notice(void)
//   0x737c40  protected: virtual __thiscall UDisTweaks_AIBehavior_Panic::~UDisTweaks_AIBehavior_Panic(void)
//   0x737ce0  protected: virtual __thiscall UDisTweaks_AIBehavior_PatrolSearch::~UDisTweaks_AIBehavior_PatrolSearch(void)
//   0x737d70  protected: virtual __thiscall UDisTweaks_AIBehavior_RatStomp::~UDisTweaks_AIBehavior_RatStomp(void)
//   0x737e00  protected: virtual __thiscall UDisTweaks_AIBehavior_MagicResponse::~UDisTweaks_AIBehavior_MagicResponse(void)
//   0x738dc0  public: static void __cdecl UDisTweaks_AIBehavior_EscapeExplosion::InternalConstructor(void *)
//   0x738de0  public: static void __cdecl UDisTweaks_AIBehavior_GoHome::InternalConstructor(void *)
//   0x738e00  public: static void __cdecl UDisTweaks_AIBehavior_Notice::InternalConstructor(void *)
//   0x738e20  public: static void __cdecl UDisTweaks_AIBehavior_Panic::InternalConstructor(void *)
//   0x738e40  public: static void __cdecl UDisTweaks_AIBehavior_PatrolSearch::InternalConstructor(void *)
//   0x738e60  public: static void __cdecl UDisTweaks_AIBehavior_RatStomp::InternalConstructor(void *)
//   0x738e80  public: static void __cdecl UDisTweaks_AIBehavior_MagicResponse::InternalConstructor(void *)
//   0x74d620  public: virtual enum EAIBlackboardRecordType __thiscall FAIKnowledgeRecord_Pawn::GetRecordType(void)const
//   0x74d630  public: virtual wchar_t const * __thiscall FAIKnowledgeRecord_Pawn::GetRecordClassName(void)const
//   0x754590  protected: virtual __thiscall UDisBehaviorGoTo_Base::~UDisBehaviorGoTo_Base(void)
//   0x754730  protected: virtual __thiscall UDisBehaviorGoTo::~UDisBehaviorGoTo(void)
//   0x7547f0  protected: virtual __thiscall UDisBehaviorWeep::~UDisBehaviorWeep(void)
//   0x7548a0  protected: virtual __thiscall UDisBehaviorStolen::~UDisBehaviorStolen(void)
//   0x7549f0  protected: virtual __thiscall UDishonoredAIBrain::~UDishonoredAIBrain(void)
//   0x756590  public: static void __cdecl UDishonoredAIBehavior::InternalConstructor(void *)
//   0x7565b0  public: static void __cdecl UDisBehaviorGoTo_Base::InternalConstructor(void *)
//   0x7565d0  public: static void __cdecl UDisBehaviorGoTo::InternalConstructor(void *)
//   0x756600  public: static void __cdecl UDisBehaviorWeep::InternalConstructor(void *)
//   0x756640  public: static void __cdecl UDisBehaviorStolen::InternalConstructor(void *)
//   0x756670  public: static void __cdecl UDishonoredAIBrain::InternalConstructor(void *)
//   0x759220  protected: virtual __thiscall UDisTweaks_AIBehavior_Guard::~UDisTweaks_AIBehavior_Guard(void)
//   0x7592b0  protected: virtual __thiscall UDisTweaks_AIBehavior_TriggerAlarm::~UDisTweaks_AIBehavior_TriggerAlarm(void)
//   0x759340  protected: virtual __thiscall UDisTweaks_AIBehavior_Weep::~UDisTweaks_AIBehavior_Weep(void)
//   0x75a700  public: static void __cdecl UDisTweaks_AIBehavior::InternalConstructor(void *)
//   0x75a720  public: static void __cdecl UDisTweaks_AIBehavior_Patrol::InternalConstructor(void *)
//   0x75a740  public: static void __cdecl UDisTweaks_AIBehavior_TriggerAlarm::InternalConstructor(void *)
//   0x75a760  public: static void __cdecl UDisTweaks_AIBehavior_Weep::InternalConstructor(void *)
//   0x766880  protected: virtual __thiscall UDisAISubProcess::~UDisAISubProcess(void)
//   0x766920  protected: virtual __thiscall UDisAISubProcessWithDesires::~UDisAISubProcessWithDesires(void)
//   0x766990  public: virtual class UObject * __thiscall UDisAISubProcessWithDesires::GetUObjectInterfaceDisDesiresInterface(void)
//   0x7669d0  protected: virtual __thiscall UDisFleeConstraint::~UDisFleeConstraint(void)
//   0x766a60  protected: virtual __thiscall UDisAISubState::~UDisAISubState(void)
//   0x766b00  protected: virtual __thiscall UDisAISubStateWithDesires::~UDisAISubStateWithDesires(void)
//   0x766b80  public: virtual class UObject * __thiscall UDisAISubStateWithDesires::GetUObjectInterfaceDisDesiresInterface(void)
//   0x766bc0  protected: virtual __thiscall UDisAISubStateTakePosition::~UDisAISubStateTakePosition(void)
//   0x766c90  protected: virtual __thiscall UDisNavConstraint_MinDistanceFromLocation::~UDisNavConstraint_MinDistanceFromLocation(void)
//   0x766d20  protected: virtual __thiscall UDisNavConstraint_ShootingPosition::~UDisNavConstraint_ShootingPosition(void)
//   0x766db0  protected: virtual __thiscall UDisStimManager::~UDisStimManager(void)
//   0x76e0a0  protected: virtual __thiscall UDisAISubProcessAmbientAnims::~UDisAISubProcessAmbientAnims(void)
//   0x76e140  protected: virtual __thiscall UDisAISubProcessAmbientBarks::~UDisAISubProcessAmbientBarks(void)
//   0x76e240  protected: virtual __thiscall UDisAISubProcessCombatBarks::~UDisAISubProcessCombatBarks(void)
//   0x76e2e0  protected: virtual __thiscall UDisAISubProcessGenericBark::~UDisAISubProcessGenericBark(void)
//   0x76e380  public: static void __cdecl UDisFleeConstraint::InternalConstructor(void *)
//   0x76e420  protected: virtual __thiscall UDisAISubStateGenericAction::~UDisAISubStateGenericAction(void)
//   0x76e4c0  protected: virtual __thiscall UDisAISubStateInit::~UDisAISubStateInit(void)
//   0x76e600  protected: virtual __thiscall UDisAISubStateCower::~UDisAISubStateCower(void)
//   0x76e760  protected: virtual __thiscall UDisAISubStateFollow::~UDisAISubStateFollow(void)
//   0x76e8d0  protected: virtual __thiscall UDisAISubStateMenace::~UDisAISubStateMenace(void)
//   0x76ea50  protected: virtual __thiscall UDisAISubStateStand::~UDisAISubStateStand(void)
//   0x76eb30  public: static void __cdecl UDisNavConstraint_MinDistanceFromLocation::InternalConstructor(void *)
//   0x76eb50  public: static void __cdecl UDisNavConstraint_ShootingPosition::InternalConstructor(void *)
//   0x76eb70  public: static void __cdecl UDisStimManager::InternalConstructor(void *)
//   0x771e70  public: static void __cdecl UDisAISubProcess::InternalConstructor(void *)
//   0x771e90  public: static void __cdecl UDisAISubProcessAmbientAnims::InternalConstructor(void *)
//   0x771ec0  public: static void __cdecl UDisAISubProcessAmbientBarks::InternalConstructor(void *)
//   0x771ef0  public: static void __cdecl UDisAISubProcessCombatBarks::InternalConstructor(void *)
//   0x771f10  public: static void __cdecl UDisAISubProcessGenericBark::InternalConstructor(void *)
//   0x771fc0  protected: virtual __thiscall UDisAISubProcessFleetingGaze::~UDisAISubProcessFleetingGaze(void)
//   0x772140  protected: virtual __thiscall UDisAISubProcessPersonalSpace::~UDisAISubProcessPersonalSpace(void)
//   0x772230  public: static void __cdecl UDisAISubState::InternalConstructor(void *)
//   0x772250  public: static void __cdecl UDisAISubStateGenericAction::InternalConstructor(void *)
//   0x772280  public: static void __cdecl UDisAISubStateInit::InternalConstructor(void *)
//   0x7722b0  public: static void __cdecl UDisAISubStateWithDesires::InternalConstructor(void *)
//   0x7722f0  public: static void __cdecl UDisAISubStateCower::InternalConstructor(void *)
//   0x7723c0  protected: virtual __thiscall UDisAISubStateFlee::~UDisAISubStateFlee(void)
//   0x772480  public: static void __cdecl UDisAISubStateFollow::InternalConstructor(void *)
//   0x772550  protected: virtual __thiscall UDisAISubStateMaintainDistance::~UDisAISubStateMaintainDistance(void)
//   0x772630  public: static void __cdecl UDisAISubStateMenace::InternalConstructor(void *)
//   0x772650  public: static void __cdecl UDisAISubStateStand::InternalConstructor(void *)
//   0x772720  protected: virtual __thiscall UDisAISubStateTakeActorPosition::~UDisAISubStateTakeActorPosition(void)
//   0x774c40  protected: virtual __thiscall UDisAISubProcessDistractions::~UDisAISubProcessDistractions(void)
//   0x774cf0  public: static void __cdecl UDisAISubProcessFleetingGaze::InternalConstructor(void *)
//   0x774d10  public: static void __cdecl UDisAISubProcessPersonalSpace::InternalConstructor(void *)
//   0x774d30  public: static void __cdecl UDisAISubStateFlee::InternalConstructor(void *)
//   0x774d50  public: static void __cdecl UDisAISubStateMaintainDistance::InternalConstructor(void *)
//   0x774d70  public: static void __cdecl UDisAISubStateTakePosition::InternalConstructor(void *)
//   0x774d90  public: static void __cdecl UDisAISubStateTakeActorPosition::InternalConstructor(void *)
//   0x776870  public: static void __cdecl UDisAISubProcessDistractions::InternalConstructor(void *)
//   0x781250  protected: virtual __thiscall UDisTweaks_AIBrain::~UDisTweaks_AIBrain(void)
//   0x781300  protected: virtual __thiscall UDisTweaks_AIBrain_Reaction::~UDisTweaks_AIBrain_Reaction(void)
//   0x781420  protected: virtual __thiscall UDisTweaks_AIBrain_Steering::~UDisTweaks_AIBrain_Steering(void)
//   0x781540  protected: virtual __thiscall UDisTweaks_AISubState_Cower::~UDisTweaks_AISubState_Cower(void)
//   0x7815d0  protected: virtual __thiscall UDisTweaks_AISubState_Flee::~UDisTweaks_AISubState_Flee(void)
//   0x781660  protected: virtual __thiscall UDisTweaks_AISubState_GenericAction::~UDisTweaks_AISubState_GenericAction(void)
//   0x781780  protected: virtual __thiscall UDisTweaks_AISubState_MeleeEngage::~UDisTweaks_AISubState_MeleeEngage(void)
//   0x781810  protected: virtual __thiscall UDisTweaks_AISubState_TakeActorPosition::~UDisTweaks_AISubState_TakeActorPosition(void)
//   0x782b10  public: static void __cdecl UDisTweaks_AIBrain::InternalConstructor(void *)
//   0x782b30  public: static void __cdecl UDisTweaks_AIBrain_Reaction::InternalConstructor(void *)
//   0x782b50  public: static void __cdecl UDisTweaks_AIBrain_Steering::InternalConstructor(void *)
//   0x782b90  public: static void __cdecl UDisTweaks_AISubState_Cower::InternalConstructor(void *)
//   0x782bb0  public: static void __cdecl UDisTweaks_AISubState_Flee::InternalConstructor(void *)
//   0x782bd0  public: static void __cdecl UDisTweaks_AISubState_Follow::InternalConstructor(void *)
//   0x782c10  public: static void __cdecl UDisTweaks_AISubState_MeleeEngage::InternalConstructor(void *)
//   0x782c30  public: static void __cdecl UDisTweaks_AISubState_TakeActorPosition::InternalConstructor(void *)
//   0x7852d0  protected: virtual __thiscall UDisAISubStateMachine::~UDisAISubStateMachine(void)
//   0x785d80  public: static void __cdecl UDisAISubStateMachine::InternalConstructor(void *)
//   0x78edf0  protected: virtual __thiscall UDisAIBrainProcess::~UDisAIBrainProcess(void)
//   0x78eea0  protected: virtual __thiscall UDisAISubProcessHeadTrackBase::~UDisAISubProcessHeadTrackBase(void)
//   0x792010  protected: virtual __thiscall UDisAIBrainProcessHideoutWatcher::~UDisAIBrainProcessHideoutWatcher(void)
//   0x7920b0  protected: virtual __thiscall UDisAIBrainProcessRatCrusher::~UDisAIBrainProcessRatCrusher(void)
//   0x792150  protected: virtual __thiscall UDisAIBrainProcessWolfhound::~UDisAIBrainProcessWolfhound(void)
//   0x792240  protected: virtual __thiscall UDisAISubProcessHeadTrackBark::~UDisAISubProcessHeadTrackBark(void)
//   0x792300  protected: virtual __thiscall UDisAISubProcessStandardBodyIntention::~UDisAISubProcessStandardBodyIntention(void)
//   0x7923c0  protected: virtual __thiscall UDisAISubProcessWolfHoundCount::~UDisAISubProcessWolfHoundCount(void)
//   0x796c80  public: static void __cdecl UDisAIBrainProcess::InternalConstructor(void *)
//   0x796cb0  public: static void __cdecl UDisAIBrainProcessHideoutWatcher::InternalConstructor(void *)
//   0x796ce0  public: static void __cdecl UDisAIBrainProcessRatCrusher::InternalConstructor(void *)
//   0x796d10  public: static void __cdecl UDisAIBrainProcessWolfhound::InternalConstructor(void *)
//   0x796d40  public: static void __cdecl UDisAISubProcessWithDesires::InternalConstructor(void *)
//   0x796d90  public: static void __cdecl UDisAISubProcessHeadTrackBase::InternalConstructor(void *)
//   0x796db0  public: static void __cdecl UDisAISubProcessHeadTrackBark::InternalConstructor(void *)
//   0x796e70  protected: virtual __thiscall UDisAISubProcessHeadTrackPause::~UDisAISubProcessHeadTrackPause(void)
//   0x796f30  public: static void __cdecl UDisAISubProcessStandardBodyIntention::InternalConstructor(void *)
//   0x796f80  public: static void __cdecl UDisAISubProcessWolfHoundCount::InternalConstructor(void *)
//   0x79a720  public: static void __cdecl UDisAISubProcessHeadTrackPause::InternalConstructor(void *)
//   0x79a7f0  protected: virtual __thiscall UDisAISubProcessWatchPoints::~UDisAISubProcessWatchPoints(void)
//   0x79ba70  protected: virtual __thiscall UDisAIBrainProcessPanic::~UDisAIBrainProcessPanic(void)
//   0x79bb10  public: static void __cdecl UDisAISubProcessWatchPoints::InternalConstructor(void *)
//   ... 97 more, see resources/docs/symbols/functions.csv
