/*===========================================================================
    DishonoredGameDLC07AIClasses.h - C++ class definitions of the retail (2013) DishonoredGame module.
    Generated by resources/tools/symbols/gen_classes_header.py --sdk from the CodeRed SDK dump
    (retail_sdk_layout.json: member offsets/types/flags, function parameter blocks), native_class_sizes.csv
    (retail sizeof, ClassFlags, Within, config), script_classes_2013.json (enum values, consts, property
    kinds, header groups) and the 2012 types.json (names of native-only members). DO NOT edit by hand:
    regenerate, or carry the change into the generator.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "DishonoredGameNames.h"

#ifndef NAMES_ONLY
#include "DishonoredGameEngineShims.h"
#include "DishonoredGameAttributesClasses.h"
#include "DishonoredGameGlobalStructsClasses.h"
#include "DishonoredGameClasses.h"
#endif

#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_DISHONOREDGAME_DLC07AI_ENUMS
#define INCLUDED_DISHONOREDGAME_DLC07AI_ENUMS 1


#endif // !INCLUDED_DISHONOREDGAME_DLC07AI_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_DISHONOREDGAME_DLC07AI_CLASSES
#define INCLUDED_DISHONOREDGAME_DLC07AI_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

// DishonoredGame.DisDLC07NavMeshGoal_CombatVsRiverKrustPosition.CombatVsRiverKrustPositionNavGoal: retail SDK size 20
struct FCombatVsRiverKrustPositionNavGoal
{
    FPointer m_pGoalPoly;
    FVector m_GoalLocation;
    FLOAT m_fSortValue;

    /** Constructors */
    FCombatVsRiverKrustPositionNavGoal() {}
    FCombatVsRiverKrustPositionNavGoal(EEventParm)
    {
        appMemzero(this, sizeof(FCombatVsRiverKrustPositionNavGoal));
    }
};

// DishonoredGame.DisDLC07AISubStateDoPullSpell: retail sizeof 320, reflected span 208..320 (new in 2013)
class UDisDLC07AISubStateDoPullSpell : public UDisAISubStateWithDesires
{
public:
    //## BEGIN PROPS DisDLC07AISubStateDoPullSpell
    class AActor* m_pTargetActor;
    BITFIELD m_bWasItemContextStarted:1;
    BITFIELD m_bShouldExitStateNextTick:1;
    FDisFaceToRequest m_FaceToRequest;
    FDisBodyIntentionRequest m_BodyIntentionRequest;
    //## END PROPS DisDLC07AISubStateDoPullSpell

    DECLARE_CLASS(UDisDLC07AISubStateDoPullSpell,UDisAISubStateWithDesires,0,DishonoredGame)
};

// DishonoredGame.DisDLC07AISubStateTentacleAttack: retail sizeof 260, reflected span 204..260 (new in 2013)
class UDisDLC07AISubStateTentacleAttack : public UDisAISubState, public IDisAttributesInterface
{
public:
    //## BEGIN PROPS DisDLC07AISubStateTentacleAttack
    BYTE m_TentacleAttackState;
    FLOAT m_fDespawnTimer;
    FLOAT m_fDespawnWaitTimer;
    FLOAT m_fAOEDamageTimer;
    class UDisParticleSystemComponent* m_pAOEParticleSystem;
    FLOAT m_fNoLOSStopAttractionTimer;
    FLOAT m_fAttractionCooldownTimer;
    class UDisParticleSystemComponent* m_pAttractionParticleSystem;
    class UDisParticleSystemComponent* m_pAttractionPlayerParticleSystem;
    FLOAT m_fAttractionPlayerFadeTimer;
    FLOAT m_fGrabWindupTimer;
    FLOAT m_fGrabWindupCooldownTimer;
    class UDisAttributes* m_pAttributes;
    //## END PROPS DisDLC07AISubStateTentacleAttack

    DECLARE_CLASS(UDisDLC07AISubStateTentacleAttack,UDisAISubState,0,DishonoredGame)
};

// DishonoredGame.DisDLC07AISubStateTentacleSpawn: retail sizeof 208, reflected span 204..208 (new in 2013)
class UDisDLC07AISubStateTentacleSpawn : public UDisAISubState
{
public:
    //## BEGIN PROPS DisDLC07AISubStateTentacleSpawn
    FLOAT m_fWaitBeforeAttackTimer;
    //## END PROPS DisDLC07AISubStateTentacleSpawn

    DECLARE_CLASS(UDisDLC07AISubStateTentacleSpawn,UDisAISubState,0,DishonoredGame)
};

// DishonoredGame.DisDLC07BehaviorAssassinVsRiverKrustCombat: retail sizeof 196, reflected span 160..196 (new in 2013)
class UDisDLC07BehaviorAssassinVsRiverKrustCombat : public UDisAIBehaviorWithDesires
{
public:
    //## BEGIN PROPS DisDLC07BehaviorAssassinVsRiverKrustCombat
    class ADisRiverKrust* m_pTargetRiverKrust;
    FLOAT m_fElapsedIdleTimeAtCurrentLocation;
    FDisBodyIntentionRequest m_BodyIntentionRequest;
    FPointer m_pPositionGoalEvaluator;
    BITFIELD m_bIsSettingUpCustomPathfinding:1;
    //## END PROPS DisDLC07BehaviorAssassinVsRiverKrustCombat

    DECLARE_FUNCTION(execRequestStateExitCallback_TakePosition);
    DECLARE_FUNCTION(execRefreshCallback_TakePosition);
    DECLARE_FUNCTION(execOnEnterCallback_TakePosition);
    DECLARE_FUNCTION(execRequestStateExitCallback_DoPullSpell);
    DECLARE_FUNCTION(execRefreshCallback_Stand);
    DECLARE_FUNCTION(execOnEnterCallback_Stand);
    DECLARE_CLASS(UDisDLC07BehaviorAssassinVsRiverKrustCombat,UDisAIBehaviorWithDesires,0,DishonoredGame)
};

// DishonoredGame.DisDLC07BehaviorTentacleIdle: retail sizeof 348, reflected span 160..348 (new in 2013)
class UDisDLC07BehaviorTentacleIdle : public UDisAIBehaviorWithDesires
{
public:
    //## BEGIN PROPS DisDLC07BehaviorTentacleIdle
    class ADishonoredPawn* m_pTentacleSummoner;
    class ADishonoredPawn* m_pTentacleTarget;
    FDisFaceToRequest m_FaceToRequest;
    FDisLocoRequest m_LocoRequest;
    //## END PROPS DisDLC07BehaviorTentacleIdle

    DECLARE_FUNCTION(execRequestStateExitCallback_TentacleAttack);
    DECLARE_FUNCTION(execRequestStateExitCallback_TentacleSpawn);
    DECLARE_CLASS(UDisDLC07BehaviorTentacleIdle,UDisAIBehaviorWithDesires,0,DishonoredGame)
};

// DishonoredGame.DisDLC07NavMeshGoal_CombatVsRiverKrustPosition: retail sizeof 2116, reflected span 76..2116 (new in 2013)
class UDisDLC07NavMeshGoal_CombatVsRiverKrustPosition : public UNavMeshPathGoalEvaluator
{
public:
    //## BEGIN PROPS DisDLC07NavMeshGoal_CombatVsRiverKrustPosition
    FLOAT m_fGoalPolyFloodFillStepX;
    FLOAT m_fGoalPolyFloodFillStepY;
    class UNavigationHandle* m_pNavHandle;
    FVector m_StartLocation;
    FVector m_KeyLocation;
    FVector m_KeyDirection;
    FLOAT m_fKeyFOVDegrees;
    FLOAT m_fDistanceMinSquared;
    FLOAT m_fDistanceMaxSquared;
    FLOAT m_fDistanceFromKeyMinSquared;
    FLOAT m_fDistanceFromKeyMaxSquared;
    FLOAT m_fMaxHeightDiffFromKey;
    FLOAT m_fTestCylinderRadius;
    FBox m_GoalSearchBounds;
    INT m_NumGoalsEvaluated;
    INT m_NumGoalsCollected;
    FCombatVsRiverKrustPositionNavGoal m_NavGoalList[96];
    INT m_NumPotentialGoals;
    INT m_NextPotentialGoal;
    //## END PROPS DisDLC07NavMeshGoal_CombatVsRiverKrustPosition

    DECLARE_CLASS(UDisDLC07NavMeshGoal_CombatVsRiverKrustPosition,UNavMeshPathGoalEvaluator,0,DishonoredGame)
};

// DishonoredGame.DisDLC07Tweaks_AIBehavior_AssassinVsRiverKrustCombat: retail sizeof 204, reflected span 168..204 (new in 2013)
class UDisDLC07Tweaks_AIBehavior_AssassinVsRiverKrustCombat : public UDisTweaks_AIBehavior
{
public:
    //## BEGIN PROPS DisDLC07Tweaks_AIBehavior_AssassinVsRiverKrustCombat
    FDisRangedFloat m_CombatRange;
    FLOAT m_fCombatHeightDiffMax;
    FLOAT m_fPredictedTargetFOVDegrees;
    FVector m_LineOfSightTraceExtents;
    FLOAT m_fMinRepositionDistance;
    FLOAT m_fMaxAllowedIdleTimeAtPosition;
    //## END PROPS DisDLC07Tweaks_AIBehavior_AssassinVsRiverKrustCombat

    DECLARE_CLASS(UDisDLC07Tweaks_AIBehavior_AssassinVsRiverKrustCombat,UDisTweaks_AIBehavior,0,DishonoredGame)
};

// DishonoredGame.DisDLC07Tweaks_AIBehavior_TentacleIdle: retail sizeof 168, reflected span 168..168 (new in 2013)
class UDisDLC07Tweaks_AIBehavior_TentacleIdle : public UDisTweaks_AIBehavior
{
public:
    //## BEGIN PROPS DisDLC07Tweaks_AIBehavior_TentacleIdle
    //## END PROPS DisDLC07Tweaks_AIBehavior_TentacleIdle

    DECLARE_CLASS(UDisDLC07Tweaks_AIBehavior_TentacleIdle,UDisTweaks_AIBehavior,0,DishonoredGame)
};

// DishonoredGame.DisDLC07Tweaks_AIBrain_Tentacle: retail sizeof 204, reflected span 204..204 (new in 2013)
class UDisDLC07Tweaks_AIBrain_Tentacle : public UDisTweaks_AIBrain
{
public:
    //## BEGIN PROPS DisDLC07Tweaks_AIBrain_Tentacle
    //## END PROPS DisDLC07Tweaks_AIBrain_Tentacle

    DECLARE_CLASS(UDisDLC07Tweaks_AIBrain_Tentacle,UDisTweaks_AIBrain,0,DishonoredGame)
};

// DishonoredGame.DisDLC07Tweaks_AISubState_DoPullSpell: retail sizeof 140, reflected span 140..140 (new in 2013)
class UDisDLC07Tweaks_AISubState_DoPullSpell : public UDisTweaks_AISubState
{
public:
    //## BEGIN PROPS DisDLC07Tweaks_AISubState_DoPullSpell
    //## END PROPS DisDLC07Tweaks_AISubState_DoPullSpell

    DECLARE_CLASS(UDisDLC07Tweaks_AISubState_DoPullSpell,UDisTweaks_AISubState,0,DishonoredGame)
    DECLARE_WITHIN(UDisTweaks_AIBehavior)
};

// DishonoredGame.DisDLC07Tweaks_AISubState_TentacleAttack: retail sizeof 444, reflected span 140..444 (new in 2013)
class UDisDLC07Tweaks_AISubState_TentacleAttack : public UDisTweaks_AISubState
{
public:
    //## BEGIN PROPS DisDLC07Tweaks_AISubState_TentacleAttack
    BITFIELD m_bRequireLOSForAttack:1;
    FVector2D m_AttackLOSExtents;
    FLOAT m_fDespawnTime;
    FLOAT m_fDespawnWait;
    FLOAT m_fAOEHalfHeight;
    FLOAT m_fAOERadius;
    FLOAT m_fAOEDamageInterval;
    FDisAttribute m_AOEDamage;
    class UClass* m_pAOEDamageType;
    class UParticleSystem* m_pAOEParticleEffect;
    class UClass* m_pAOECameraEffectClass;
    class UDisTweaks_EmitterCameraLensEffect* m_pAOECameraEffectTweaks;
    FLOAT m_fAttractionMinRange;
    FLOAT m_fAttractionHalfHeight;
    FLOAT m_fAttractionRadius;
    FLOAT m_fAttractionAllowedAngle;
    FLOAT m_fAttractionVelocity;
    FLOAT m_fNoLOSStopAttractionWait;
    FDisRangedFloat m_AttractionCooldown;
    class UParticleSystem* m_pAttractionParticleEffect;
    class UParticleSystem* m_pAttractionPlayerParticleEffect;
    FName m_AttractionEffectSourceSocket;
    FName m_AttractionPlayerFadeParameter;
    FLOAT m_fAttractionPlayerFadeInDuration;
    FLOAT m_fAttractionPlayerFadeOutDuration;
    FArkPpConfig m_AttractionPlayerPpSettings;
    FLOAT m_fAttractionPlayerPpBlendSpeed;
    FLOAT m_fPullMinDistance;
    FLOAT m_fPullSpeed;
    FLOAT m_fPullCutOffThreshold;
    FLOAT m_fGrabStartRange;
    FLOAT m_fGrabWindupTime;
    FDisRangedFloat m_GrabWindupCooldown;
    //## END PROPS DisDLC07Tweaks_AISubState_TentacleAttack

    DECLARE_CLASS(UDisDLC07Tweaks_AISubState_TentacleAttack,UDisTweaks_AISubState,0,DishonoredGame)
    DECLARE_WITHIN(UDisTweaks_AIBehavior)
};

// DishonoredGame.DisDLC07Tweaks_AISubState_TentacleSpawn: retail sizeof 144, reflected span 140..144 (new in 2013)
class UDisDLC07Tweaks_AISubState_TentacleSpawn : public UDisTweaks_AISubState
{
public:
    //## BEGIN PROPS DisDLC07Tweaks_AISubState_TentacleSpawn
    FLOAT m_fWaitBeforeAttack;
    //## END PROPS DisDLC07Tweaks_AISubState_TentacleSpawn

    DECLARE_CLASS(UDisDLC07Tweaks_AISubState_TentacleSpawn,UDisTweaks_AISubState,0,DishonoredGame)
    DECLARE_WITHIN(UDisTweaks_AIBehavior)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_DISHONOREDGAME_DLC07AI_CLASSES
#endif // !NAMES_ONLY

AUTOGENERATE_FUNCTION(UDisDLC07BehaviorAssassinVsRiverKrustCombat,-1,execRequestStateExitCallback_TakePosition);
AUTOGENERATE_FUNCTION(UDisDLC07BehaviorAssassinVsRiverKrustCombat,-1,execRefreshCallback_TakePosition);
AUTOGENERATE_FUNCTION(UDisDLC07BehaviorAssassinVsRiverKrustCombat,-1,execOnEnterCallback_TakePosition);
AUTOGENERATE_FUNCTION(UDisDLC07BehaviorAssassinVsRiverKrustCombat,-1,execRequestStateExitCallback_DoPullSpell);
AUTOGENERATE_FUNCTION(UDisDLC07BehaviorAssassinVsRiverKrustCombat,-1,execRefreshCallback_Stand);
AUTOGENERATE_FUNCTION(UDisDLC07BehaviorAssassinVsRiverKrustCombat,-1,execOnEnterCallback_Stand);
AUTOGENERATE_FUNCTION(UDisDLC07BehaviorTentacleIdle,-1,execRequestStateExitCallback_TentacleAttack);
AUTOGENERATE_FUNCTION(UDisDLC07BehaviorTentacleIdle,-1,execRequestStateExitCallback_TentacleSpawn);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DISHONOREDGAME_DLC07AI_NATIVE_DEFS
#define DISHONOREDGAME_DLC07AI_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_DISHONOREDGAME_DLC07AI \
	UDisDLC07AISubStateDoPullSpell::StaticClass(); \
	UDisDLC07AISubStateTentacleAttack::StaticClass(); \
	UDisDLC07AISubStateTentacleSpawn::StaticClass(); \
	UDisDLC07BehaviorAssassinVsRiverKrustCombat::StaticClass(); \
	GNativeLookupFuncs.Set(FName("DisDLC07BehaviorAssassinVsRiverKrustCombat"), GDishonoredGameUDisDLC07BehaviorAssassinVsRiverKrustCombatNatives); \
	UDisDLC07BehaviorTentacleIdle::StaticClass(); \
	GNativeLookupFuncs.Set(FName("DisDLC07BehaviorTentacleIdle"), GDishonoredGameUDisDLC07BehaviorTentacleIdleNatives); \
	UDisDLC07NavMeshGoal_CombatVsRiverKrustPosition::StaticClass(); \
	UDisDLC07Tweaks_AIBehavior_AssassinVsRiverKrustCombat::StaticClass(); \
	UDisDLC07Tweaks_AIBehavior_TentacleIdle::StaticClass(); \
	UDisDLC07Tweaks_AIBrain_Tentacle::StaticClass(); \
	UDisDLC07Tweaks_AISubState_DoPullSpell::StaticClass(); \
	UDisDLC07Tweaks_AISubState_TentacleAttack::StaticClass(); \
	UDisDLC07Tweaks_AISubState_TentacleSpawn::StaticClass(); \

#endif // DISHONOREDGAME_DLC07AI_NATIVE_DEFS

#ifdef NATIVES_ONLY
FNativeFunctionLookup GDishonoredGameUDisDLC07BehaviorAssassinVsRiverKrustCombatNatives[] = 
{ 
	MAP_NATIVE(UDisDLC07BehaviorAssassinVsRiverKrustCombat, execRequestStateExitCallback_TakePosition)
	MAP_NATIVE(UDisDLC07BehaviorAssassinVsRiverKrustCombat, execRefreshCallback_TakePosition)
	MAP_NATIVE(UDisDLC07BehaviorAssassinVsRiverKrustCombat, execOnEnterCallback_TakePosition)
	MAP_NATIVE(UDisDLC07BehaviorAssassinVsRiverKrustCombat, execRequestStateExitCallback_DoPullSpell)
	MAP_NATIVE(UDisDLC07BehaviorAssassinVsRiverKrustCombat, execRefreshCallback_Stand)
	MAP_NATIVE(UDisDLC07BehaviorAssassinVsRiverKrustCombat, execOnEnterCallback_Stand)
	{NULL, NULL}
};

FNativeFunctionLookup GDishonoredGameUDisDLC07BehaviorTentacleIdleNatives[] = 
{ 
	MAP_NATIVE(UDisDLC07BehaviorTentacleIdle, execRequestStateExitCallback_TentacleAttack)
	MAP_NATIVE(UDisDLC07BehaviorTentacleIdle, execRequestStateExitCallback_TentacleSpawn)
	{NULL, NULL}
};

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07AISubStateDoPullSpell,DisDLC07AISubStateDoPullSpell,m_pTargetActor)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07AISubStateDoPullSpell,DisDLC07AISubStateDoPullSpell,m_BodyIntentionRequest)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07AISubStateDoPullSpell)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07AISubStateTentacleAttack,DisDLC07AISubStateTentacleAttack,m_TentacleAttackState)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07AISubStateTentacleAttack,DisDLC07AISubStateTentacleAttack,m_pAttributes)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07AISubStateTentacleAttack)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07AISubStateTentacleSpawn,DisDLC07AISubStateTentacleSpawn,m_fWaitBeforeAttackTimer)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07AISubStateTentacleSpawn)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07BehaviorAssassinVsRiverKrustCombat,DisDLC07BehaviorAssassinVsRiverKrustCombat,m_pTargetRiverKrust)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07BehaviorAssassinVsRiverKrustCombat,DisDLC07BehaviorAssassinVsRiverKrustCombat,m_pPositionGoalEvaluator)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07BehaviorAssassinVsRiverKrustCombat)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07BehaviorTentacleIdle,DisDLC07BehaviorTentacleIdle,m_pTentacleSummoner)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07BehaviorTentacleIdle,DisDLC07BehaviorTentacleIdle,m_LocoRequest)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07BehaviorTentacleIdle)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07NavMeshGoal_CombatVsRiverKrustPosition,DisDLC07NavMeshGoal_CombatVsRiverKrustPosition,m_fGoalPolyFloodFillStepX)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07NavMeshGoal_CombatVsRiverKrustPosition,DisDLC07NavMeshGoal_CombatVsRiverKrustPosition,m_NextPotentialGoal)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07NavMeshGoal_CombatVsRiverKrustPosition)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07Tweaks_AIBehavior_AssassinVsRiverKrustCombat,DisDLC07Tweaks_AIBehavior_AssassinVsRiverKrustCombat,m_CombatRange)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07Tweaks_AIBehavior_AssassinVsRiverKrustCombat,DisDLC07Tweaks_AIBehavior_AssassinVsRiverKrustCombat,m_fMaxAllowedIdleTimeAtPosition)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07Tweaks_AIBehavior_AssassinVsRiverKrustCombat)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07Tweaks_AIBehavior_TentacleIdle)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07Tweaks_AIBrain_Tentacle)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07Tweaks_AISubState_DoPullSpell)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07Tweaks_AISubState_TentacleAttack,DisDLC07Tweaks_AISubState_TentacleAttack,m_AttackLOSExtents)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07Tweaks_AISubState_TentacleAttack,DisDLC07Tweaks_AISubState_TentacleAttack,m_GrabWindupCooldown)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07Tweaks_AISubState_TentacleAttack)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC07Tweaks_AISubState_TentacleSpawn,DisDLC07Tweaks_AISubState_TentacleSpawn,m_fWaitBeforeAttack)
VERIFY_CLASS_SIZE_NODIE(UDisDLC07Tweaks_AISubState_TentacleSpawn)
#endif // VERIFY_CLASS_SIZES

#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
