/*===========================================================================
    DishonoredGameDLC06ButcherClasses.h - C++ class definitions of the retail (2013) DishonoredGame module.
    Generated by resources/tools/symbols/gen_classes_header.py --sdk from the CodeRed SDK dump
    (retail_sdk_layout.json: member offsets/types/flags, function parameter blocks), native_class_sizes.csv
    (retail sizeof, ClassFlags, Within, config), script_classes_2013.json (enum values, consts, property
    kinds, header groups) and the 2012 types.json (names of native-only members). DO NOT edit by hand:
    regenerate, or carry the change into the generator.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "DishonoredGameNames.h"

#ifndef NAMES_ONLY
#include "DishonoredGameEngineShims.h"
#include "DishonoredGameAICombatClasses.h"
#include "DishonoredGameDLC06NPCClasses.h"
#endif

#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_DISHONOREDGAME_DLC06BUTCHER_ENUMS
#define INCLUDED_DISHONOREDGAME_DLC06BUTCHER_ENUMS 1


#endif // !INCLUDED_DISHONOREDGAME_DLC06BUTCHER_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_DISHONOREDGAME_DLC06BUTCHER_CLASSES
#define INCLUDED_DISHONOREDGAME_DLC06BUTCHER_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

// DishonoredGame.DisDLC06ButcherNPCPawn: retail sizeof 3584, reflected span 3572..3572 (new in 2013)
class ADisDLC06ButcherNPCPawn : public ADisDLC06NPCPawn
{
public:
    //## BEGIN PROPS DisDLC06ButcherNPCPawn
    //## END PROPS DisDLC06ButcherNPCPawn

    DECLARE_CLASS(ADisDLC06ButcherNPCPawn,ADisDLC06NPCPawn,0|CLASS_Config,DishonoredGame)
};

// DishonoredGame.DisDLC06BehaviorButcherCombat: retail sizeof 304, reflected span 304..304 (new in 2013)
class UDisDLC06BehaviorButcherCombat : public UDisBehaviorCombatMelee
{
public:
    //## BEGIN PROPS DisDLC06BehaviorButcherCombat
    //## END PROPS DisDLC06BehaviorButcherCombat

    DECLARE_CLASS(UDisDLC06BehaviorButcherCombat,UDisBehaviorCombatMelee,0,DishonoredGame)
};

// DishonoredGame.DisDLC06Tweaks_AIBehavior_ButcherCombat: retail sizeof 216, reflected span 208..216 (new in 2013)
class UDisDLC06Tweaks_AIBehavior_ButcherCombat : public UDisTweaks_AIBehavior_CombatMelee
{
public:
    //## BEGIN PROPS DisDLC06Tweaks_AIBehavior_ButcherCombat
    FLOAT m_fSawDangerCapsuleLength;
    FLOAT m_fSawDangerCapsuleRadius;
    //## END PROPS DisDLC06Tweaks_AIBehavior_ButcherCombat

    DECLARE_CLASS(UDisDLC06Tweaks_AIBehavior_ButcherCombat,UDisTweaks_AIBehavior_CombatMelee,0,DishonoredGame)
};

// DishonoredGame.DisDLC06Tweaks_ButcherNPCPawn: retail sizeof 940, reflected span 928..940 (new in 2013)
class UDisDLC06Tweaks_ButcherNPCPawn : public UDisDLC06Tweaks_NPCPawn
{
public:
    //## BEGIN PROPS DisDLC06Tweaks_ButcherNPCPawn
    TArrayNoInit<class UDisTweaksBase*> m_AttachmentTweaksToDestroyWhenSawIsDropped;
    //## END PROPS DisDLC06Tweaks_ButcherNPCPawn

    DECLARE_CLASS(UDisDLC06Tweaks_ButcherNPCPawn,UDisDLC06Tweaks_NPCPawn,0,DishonoredGame)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_DISHONOREDGAME_DLC06BUTCHER_CLASSES
#endif // !NAMES_ONLY


#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DISHONOREDGAME_DLC06BUTCHER_NATIVE_DEFS
#define DISHONOREDGAME_DLC06BUTCHER_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_DISHONOREDGAME_DLC06BUTCHER \
	ADisDLC06ButcherNPCPawn::StaticClass(); \
	UDisDLC06BehaviorButcherCombat::StaticClass(); \
	UDisDLC06Tweaks_AIBehavior_ButcherCombat::StaticClass(); \
	UDisDLC06Tweaks_ButcherNPCPawn::StaticClass(); \

#endif // DISHONOREDGAME_DLC06BUTCHER_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(ADisDLC06ButcherNPCPawn)
VERIFY_CLASS_SIZE_NODIE(UDisDLC06BehaviorButcherCombat)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC06Tweaks_AIBehavior_ButcherCombat,DisDLC06Tweaks_AIBehavior_ButcherCombat,m_fSawDangerCapsuleLength)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC06Tweaks_AIBehavior_ButcherCombat,DisDLC06Tweaks_AIBehavior_ButcherCombat,m_fSawDangerCapsuleRadius)
VERIFY_CLASS_SIZE_NODIE(UDisDLC06Tweaks_AIBehavior_ButcherCombat)
VERIFY_CLASS_OFFSET_NODIE(UDisDLC06Tweaks_ButcherNPCPawn,DisDLC06Tweaks_ButcherNPCPawn,m_AttachmentTweaksToDestroyWhenSawIsDropped)
VERIFY_CLASS_SIZE_NODIE(UDisDLC06Tweaks_ButcherNPCPawn)
#endif // VERIFY_CLASS_SIZES

#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
