#pragma once
// DishonoredGame/inc/dishonoredgamecontactsystemclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (35):
//   0x63cc40  public: static class UClass * __cdecl UDisContactType_Corpse::StaticClass(void)
//   0x63cc60  public: static class UClass * __cdecl UDisContactType_Environment::StaticClass(void)
//   0x63cc80  public: static class UClass * __cdecl UDisContactType_PistolBlast::StaticClass(void)
//   0x647a60  protected: virtual __thiscall UDisContactType::~UDisContactType(void)
//   0x825110  protected: virtual __thiscall UDisContactPhysicalMaterial::~UDisContactPhysicalMaterial(void)
//   0x828df0  public: static void __cdecl UDisContactPhysicalMaterial::InternalConstructor(void *)
//   0x82fc40  protected: virtual __thiscall UDisContactSubIntersection::~UDisContactSubIntersection(void)
//   0x82fce0  protected: virtual __thiscall UDisContactSub_SoundCue::~UDisContactSub_SoundCue(void)
//   0x82fd70  protected: virtual __thiscall UDisContactSub_AINoise::~UDisContactSub_AINoise(void)
//   0x82fe00  protected: virtual __thiscall UDisContactSub_CameraEffectEmitter::~UDisContactSub_CameraEffectEmitter(void)
//   0x82fe90  protected: virtual __thiscall UDisContactSub_CameraShake::~UDisContactSub_CameraShake(void)
//   0x82ff20  protected: virtual __thiscall UDisContactSub_Particle::~UDisContactSub_Particle(void)
//   0x82ffb0  protected: virtual __thiscall UDisContactSub_Rumble::~UDisContactSub_Rumble(void)
//   0x830040  protected: virtual __thiscall UDisContactType_Footfall_Sprint_Player::~UDisContactType_Footfall_Sprint_Player(void)
//   0x8300d0  protected: virtual __thiscall UDisContactType_SleepingBody::~UDisContactType_SleepingBody(void)
//   0x830160  protected: virtual __thiscall UDisContactType_Player::~UDisContactType_Player(void)
//   0x8301f0  protected: virtual __thiscall UDisContactType_SlideImpact::~UDisContactType_SlideImpact(void)
//   0x835ae0  public: static void __cdecl UDisContactSubIntersection::InternalConstructor(void *)
//   0x835b00  public: static void __cdecl UDisContactSub_SoundCue::InternalConstructor(void *)
//   0x835b20  public: static void __cdecl UDisContactSub_AINoise::InternalConstructor(void *)
//   0x835b40  public: static void __cdecl UDisContactSub_CameraEffectEmitter::InternalConstructor(void *)
//   0x835b60  public: static void __cdecl UDisContactSub_CameraShake::InternalConstructor(void *)
//   0x835b80  public: static void __cdecl UDisContactSub_Particle::InternalConstructor(void *)
//   0x835ba0  public: static void __cdecl UDisContactSub_Rumble::InternalConstructor(void *)
//   0x835bc0  public: static void __cdecl UDisContactType::InternalConstructor(void *)
//   0x835be0  public: static void __cdecl UDisContactType_Footfall_Sprint_Player::InternalConstructor(void *)
//   0x835c00  public: static void __cdecl UDisContactType_SleepingBody::InternalConstructor(void *)
//   0x835c20  public: static void __cdecl UDisContactType_Player::InternalConstructor(void *)
//   0x835c40  public: static void __cdecl UDisContactType_SlideImpact::InternalConstructor(void *)
//   0x83c9d0  protected: virtual __thiscall UDisContactSub_Decal::~UDisContactSub_Decal(void)
//   0x83ca70  protected: virtual __thiscall ADisDecalManager::~ADisDecalManager(void)
//   0x83e9b0  public: static void __cdecl UDisContactSub_Decal::InternalConstructor(void *)
//   0x83e9d0  public: static void __cdecl ADisDecalManager::InternalConstructor(void *)
//   0x841390  protected: virtual __thiscall UDishonoredContactSystem::~UDishonoredContactSystem(void)
//   0x841440  public: static void __cdecl UDishonoredContactSystem::InternalConstructor(void *)
