#pragma once
// DishonoredGame/inc/dishonoredgameobjectivesclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (45):
//   0x72f420  protected: virtual __thiscall UDishonoredObjective::~UDishonoredObjective(void)
//   0x72f4d0  protected: virtual __thiscall UDishonoredObjectivesComponent::~UDishonoredObjectivesComponent(void)
//   0x7311f0  public: static void __cdecl UDishonoredObjective::InternalConstructor(void *)
//   0x731210  public: static void __cdecl UDishonoredObjectivesComponent::InternalConstructor(void *)
//   0x734ce0  protected: virtual __thiscall UDishonoredTask_Base::~UDishonoredTask_Base(void)
//   0x735de0  protected: virtual __thiscall UDishonoredTask_Custom::~UDishonoredTask_Custom(void)
//   0x737fe0  public: static void __cdecl UDishonoredTask_Base::InternalConstructor(void *)
//   0x738000  public: static void __cdecl UDishonoredTask_Custom::InternalConstructor(void *)
//   0x7e4570  protected: virtual __thiscall UDisSeqAct_ObjectiveAction::~UDisSeqAct_ObjectiveAction(void)
//   0x7e4610  protected: virtual __thiscall UDisSeqAct_AddObjective::~UDisSeqAct_AddObjective(void)
//   0x7e46a0  protected: virtual __thiscall UDisSeqAct_CompleteObjective::~UDisSeqAct_CompleteObjective(void)
//   0x7e4730  protected: virtual __thiscall UDisSeqAct_FailObjective::~UDisSeqAct_FailObjective(void)
//   0x7e47c0  protected: virtual __thiscall UDisSeqAct_RemoveObjective::~UDisSeqAct_RemoveObjective(void)
//   0x7e4850  protected: virtual __thiscall UDisSeqAct_SetObjectiveHidden::~UDisSeqAct_SetObjectiveHidden(void)
//   0x7e48e0  protected: virtual __thiscall UDisSeqAct_TaskAction::~UDisSeqAct_TaskAction(void)
//   0x7e4970  protected: virtual __thiscall UDisSeqAct_SetTaskHidden::~UDisSeqAct_SetTaskHidden(void)
//   0x7e4a00  protected: virtual __thiscall UDisSeqAct_SetTaskState::~UDisSeqAct_SetTaskState(void)
//   0x7e4a90  protected: virtual __thiscall UDisSeqAct_UpdateCustomTask::~UDisSeqAct_UpdateCustomTask(void)
//   0x7e4b20  protected: virtual __thiscall UDisSeqAct_UpdateTaskTarget::~UDisSeqAct_UpdateTaskTarget(void)
//   0x7e4bc0  protected: virtual __thiscall UDisSeqCond_HasObjective::~UDisSeqCond_HasObjective(void)
//   0x7e4c50  protected: virtual __thiscall UDisSeqCond_IsObjectiveComplete::~UDisSeqCond_IsObjectiveComplete(void)
//   0x7e4ce0  protected: virtual __thiscall UDisSeqCond_TaskState::~UDisSeqCond_TaskState(void)
//   0x7e4d70  protected: virtual __thiscall UDisSeqEvent_ObjectiveCompleted::~UDisSeqEvent_ObjectiveCompleted(void)
//   0x7e4e00  protected: virtual __thiscall UDisSeqEvent_TaskEvent::~UDisSeqEvent_TaskEvent(void)
//   0x7e4e90  protected: virtual __thiscall UDisSeqEvent_TaskStateChanged::~UDisSeqEvent_TaskStateChanged(void)
//   0x7e6420  public: static void __cdecl UDisSeqAct_ObjectiveAction::InternalConstructor(void *)
//   0x7e6440  public: static void __cdecl UDisSeqAct_AddObjective::InternalConstructor(void *)
//   0x7e6460  public: static void __cdecl UDisSeqAct_CompleteObjective::InternalConstructor(void *)
//   0x7e6480  public: static void __cdecl UDisSeqAct_FailObjective::InternalConstructor(void *)
//   0x7e64a0  public: static void __cdecl UDisSeqAct_RemoveObjective::InternalConstructor(void *)
//   0x7e64c0  public: static void __cdecl UDisSeqAct_SetObjectiveHidden::InternalConstructor(void *)
//   0x7e64e0  public: static void __cdecl UDisSeqAct_TaskAction::InternalConstructor(void *)
//   0x7e6500  public: static void __cdecl UDisSeqAct_SetTaskHidden::InternalConstructor(void *)
//   0x7e6520  public: static void __cdecl UDisSeqAct_SetTaskState::InternalConstructor(void *)
//   0x7e6540  public: static void __cdecl UDisSeqAct_UpdateCustomTask::InternalConstructor(void *)
//   0x7e6560  public: static void __cdecl UDisSeqAct_UpdateTaskTarget::InternalConstructor(void *)
//   0x7e6580  public: static void __cdecl UDisSeqCond_HasObjective::InternalConstructor(void *)
//   0x7e65a0  public: static void __cdecl UDisSeqCond_IsObjectiveComplete::InternalConstructor(void *)
//   0x7e65c0  public: static void __cdecl UDisSeqCond_TaskState::InternalConstructor(void *)
//   0x7e65e0  public: static void __cdecl UDisSeqEvent_ObjectiveCompleted::InternalConstructor(void *)
//   0x7e6600  public: static void __cdecl UDisSeqEvent_TaskEvent::InternalConstructor(void *)
//   0x7e6620  public: static void __cdecl UDisSeqEvent_TaskStateChanged::InternalConstructor(void *)
//   0x811590  protected: virtual __thiscall UDisSeqVar_Task::~UDisSeqVar_Task(void)
//   0x814840  public: static void __cdecl UDisSeqVar_Task::InternalConstructor(void *)
//   0xba8d10  _dynamic_initializer_for__UDisSeqVar_TaskexecGetObjectValueTemp__
