#pragma once
// DishonoredGame/inc/dishonoredgamenpcclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (216):
//   0x63ab50  public: __thiscall FDisSeveredLimbRequest::FDisSeveredLimbRequest(class FName const &, unsigned int, unsigned int, unsigned int, unsigned int, enum eDisSeverLimbImpulse, float, class FVector const &, class ADisProjectile_Arrow *)
//   0x63abc0  public: void __thiscall ADishonoredNPCPawn::execNPCTouchedDeepWater(struct FFrame &, void * const)
//   0x63ac00  public: void __thiscall ADishonoredNPCPawn::execOnSeverLimb(struct FFrame &, void * const)
//   0x63ac60  public: void __thiscall ADishonoredNPCPawn::execOnNPCMarkForVanish(struct FFrame &, void * const)
//   0x63acc0  public: void __thiscall ADishonoredNPCPawn::execOnNPCDoTeleportSpell(struct FFrame &, void * const)
//   0x63ade0  public: static class UClass * __cdecl ADishonoredNPCPawn::StaticClass(void)
//   0x63ae00  public: static class UClass * __cdecl UStateNPCMasterBePossessed::StaticClass(void)
//   0x63ae20  public: static class UClass * __cdecl UStateNPCMasterFalling::StaticClass(void)
//   0x63ae40  public: static class UClass * __cdecl UStateNPCMasterStrongHitReact::StaticClass(void)
//   0x63ae60  public: static class UClass * __cdecl UStateNPCMasterStunned::StaticClass(void)
//   0x63ae80  public: static class UClass * __cdecl UStateNPCMasterThrown::StaticClass(void)
//   0x63aea0  public: static class UClass * __cdecl UStateNPCMasterActionMeleeSwarm::StaticClass(void)
//   0x63aec0  public: static class UClass * __cdecl UStateNPCMasterActionMeleeVersus::StaticClass(void)
//   0x63aee0  public: static class UClass * __cdecl UStateNPCMasterBeingAssassinated::StaticClass(void)
//   0x63af00  public: static class UClass * __cdecl UStateNPCMasterFallingUncontrolled::StaticClass(void)
//   0x63af20  public: void __thiscall ADishonoredNPCController::execGetMoveTargetLocation(struct FFrame &, void * const)
//   0x63af80  public: void __thiscall ADishonoredNPCController::execOnAIAmbush(struct FFrame &, void * const)
//   0x63afe0  public: void __thiscall ADishonoredNPCController::execOnAIDoSearch(struct FFrame &, void * const)
//   0x63b040  public: void __thiscall ADishonoredNPCController::execOnAIGoToActor(struct FFrame &, void * const)
//   0x63b0a0  public: void __thiscall ADishonoredNPCController::execOnAIGuard(struct FFrame &, void * const)
//   0x63b100  public: void __thiscall ADishonoredNPCController::execOnAIKismetDoBehavior(struct FFrame &, void * const)
//   0x63b160  public: void __thiscall ADishonoredNPCController::execOnAISetPatrol(struct FFrame &, void * const)
//   0x63b1c0  public: void __thiscall ADishonoredNPCController::execOnAISetSenses(struct FFrame &, void * const)
//   0x63b220  public: void __thiscall ADishonoredNPCController::execOnAIShoot(struct FFrame &, void * const)
//   0x63b280  public: void __thiscall ADishonoredNPCController::execOnAIProtectNeutralsOverride(struct FFrame &, void * const)
//   0x63b2e0  public: void __thiscall ADishonoredNPCController::execOnAISetSuspicionLevel(struct FFrame &, void * const)
//   0x63b340  public: void __thiscall ADishonoredNPCController::execOnAIClearAttention(struct FFrame &, void * const)
//   0x63b3a0  public: void __thiscall ADishonoredNPCController::execOnAIPsychicAttention(struct FFrame &, void * const)
//   0x63b400  public: void __thiscall ADishonoredNPCController::execOnAIGetBrainFlags(struct FFrame &, void * const)
//   0x63b460  public: void __thiscall ADishonoredNPCController::execOnAIRingAlarm(struct FFrame &, void * const)
//   0x63b4c0  public: void __thiscall ADishonoredNPCController::execDisplayDebug_Native(struct FFrame &, void * const)
//   0x63b5e0  public: void __thiscall ADishonoredNPCController::execIsDead(struct FFrame &, void * const)
//   0x63b620  public: static class UClass * __cdecl ADishonoredNPCController::StaticClass(void)
//   0x63b640  public: static class UClass * __cdecl ADisPossessionProxyPawn::StaticClass(void)
//   0x63b660  public: void __thiscall ADisRiverKrust::execOnAnimEnd(struct FFrame &, void * const)
//   0x63b720  public: void __thiscall ADisRiverKrust::execTakeDamage_Native(struct FFrame &, void * const)
//   0x63b920  public: static class UClass * __cdecl ADisRiverKrust::StaticClass(void)
//   0x693bf0  protected: virtual __thiscall IDisCorpseInterface::~IDisCorpseInterface(void)
//   0x6a27b0  protected: virtual __thiscall ADisGuardWatchPoint::~ADisGuardWatchPoint(void)
//   0x6a2890  protected: virtual __thiscall ADisRiverKrustBodyPart::~ADisRiverKrustBodyPart(void)
//   0x6a2950  protected: virtual __thiscall ADishonoredSpawner::~ADishonoredSpawner(void)
//   0x6a2cf0  protected: virtual __thiscall ADisTravelSpawner::~ADisTravelSpawner(void)
//   0x6a2dd0  protected: virtual __thiscall ADisNPCDistractor::~ADisNPCDistractor(void)
//   0x6a2e60  protected: virtual __thiscall UDisTravelSpawnerComponent::~UDisTravelSpawnerComponent(void)
//   0x6a4770  public: static void __cdecl ADisGuardWatchPoint::InternalConstructor(void *)
//   0x6a47b0  public: static void __cdecl ADisRiverKrustBodyPart::InternalConstructor(void *)
//   0x6a4800  public: static void __cdecl ADishonoredSpawner::InternalConstructor(void *)
//   0x6a4820  public: static void __cdecl ADisTravelSpawner::InternalConstructor(void *)
//   0x6a4840  public: static void __cdecl ADisNPCDistractor::InternalConstructor(void *)
//   0x6a4870  public: static void __cdecl UDisTravelSpawnerComponent::InternalConstructor(void *)
//   0x6a6b80  protected: virtual __thiscall UDisTweaks_RiverKrust::~UDisTweaks_RiverKrust(void)
//   0x6a7ee0  public: static void __cdecl UDisTweaks_RiverKrust::InternalConstructor(void *)
//   0x6a9c30  public: virtual class UObject * __thiscall ADishonoredKAsset::GetUObjectInterfaceDisHitReboundInterface(void)
//   0x6a9c40  public: virtual class UObject * __thiscall ADisRiverKrust::GetUObjectInterfaceDisSoulRenderInterface(void)
//   0x6a9c50  public: virtual class UObject * __thiscall ADisRiverKrust::GetUObjectInterfaceDisContactTypeInterface(void)
//   0x6a9c60  public: virtual class UObject * __thiscall ADisRiverKrust::GetUObjectInterfaceDisInteractableInterface(void)
//   0x6a9d20  protected: virtual __thiscall ADisRiverKrust::~ADisRiverKrust(void)
//   0x6ac6c0  public: static void __cdecl ADisRiverKrust::InternalConstructor(void *)
//   0x6b2650  protected: virtual __thiscall UStateNPCMasterWalk::~UStateNPCMasterWalk(void)
//   0x6b26e0  protected: virtual __thiscall UStateNPCMasterAction::~UStateNPCMasterAction(void)
//   0x6b2770  protected: virtual __thiscall UStateNPCActionParry::~UStateNPCActionParry(void)
//   0x6b2800  protected: virtual __thiscall UStateNPCInstigatedMasterAction::~UStateNPCInstigatedMasterAction(void)
//   0x6b2890  protected: virtual __thiscall UStateNPCMasterActionImmolate::~UStateNPCMasterActionImmolate(void)
//   0x6b2920  protected: virtual __thiscall UStateNPCMasterActionPostPossessed::~UStateNPCMasterActionPostPossessed(void)
//   0x6b29b0  protected: virtual __thiscall UStateNPCMasterBePossessed::~UStateNPCMasterBePossessed(void)
//   0x6b2a40  protected: virtual __thiscall UStateNPCMasterFalling::~UStateNPCMasterFalling(void)
//   0x6b2ad0  protected: virtual __thiscall UStateNPCMasterProjectileHitReact::~UStateNPCMasterProjectileHitReact(void)
//   0x6b2b60  protected: virtual __thiscall UStateNPCMasterStrongHitReact::~UStateNPCMasterStrongHitReact(void)
//   0x6b2bf0  protected: virtual __thiscall UStateNPCMasterStunned::~UStateNPCMasterStunned(void)
//   0x6b2c80  protected: virtual __thiscall UStateNPCMasterThrown::~UStateNPCMasterThrown(void)
//   0x6b2d10  protected: virtual __thiscall UStateNPCMasterActionMelee::~UStateNPCMasterActionMelee(void)
//   0x6b2da0  protected: virtual __thiscall UStateNPCMasterActionMeleeVersus::~UStateNPCMasterActionMeleeVersus(void)
//   0x6b2e30  protected: virtual __thiscall UStateNPCMasterAim::~UStateNPCMasterAim(void)
//   0x6b2ea0  public: virtual class UObject * __thiscall UStateNPCMasterAim::GetUObjectInterfaceDisFireProjectileInterface(void)
//   0x6b2ee0  protected: virtual __thiscall UStateNPCMasterBeingAssassinated::~UStateNPCMasterBeingAssassinated(void)
//   0x6b2f70  protected: virtual __thiscall UStateNPCMasterBeingChoked::~UStateNPCMasterBeingChoked(void)
//   0x6b3000  protected: virtual __thiscall UStateNPCMasterDistracted::~UStateNPCMasterDistracted(void)
//   0x6b3090  protected: virtual __thiscall UStateNPCMasterDodge::~UStateNPCMasterDodge(void)
//   0x6b3120  protected: virtual __thiscall UStateNPCMasterFallingUncontrolled::~UStateNPCMasterFallingUncontrolled(void)
//   0x6b31b0  protected: virtual __thiscall UStateNPCMasterGesture::~UStateNPCMasterGesture(void)
//   0x6b3240  protected: virtual __thiscall UStateNPCMasterLyingInWait::~UStateNPCMasterLyingInWait(void)
//   0x6b32d0  protected: virtual __thiscall UStateNPCMasterMinigame::~UStateNPCMasterMinigame(void)
//   0x6b3360  protected: virtual __thiscall UStateNPCMasterPlayAnim::~UStateNPCMasterPlayAnim(void)
//   0x6b33f0  protected: virtual __thiscall UStateNPCAttractSpell::~UStateNPCAttractSpell(void)
//   0x6b3480  protected: virtual __thiscall UStateNPCMasterDualPlayAnim::~UStateNPCMasterDualPlayAnim(void)
//   0x6b3510  protected: virtual __thiscall UStateNPCMasterRangedAttack::~UStateNPCMasterRangedAttack(void)
//   0x6b35a0  protected: virtual __thiscall UStateNPCMasterSurprised::~UStateNPCMasterSurprised(void)
//   0x6b3630  protected: virtual __thiscall UStateNPCUpperBodyAction::~UStateNPCUpperBodyAction(void)
//   0x6b36c0  protected: virtual __thiscall UStateNPCMasterEquip::~UStateNPCMasterEquip(void)
//   0x6b3750  protected: virtual __thiscall UStateNPCUpperPlayAnim::~UStateNPCUpperPlayAnim(void)
//   0x6b37e0  protected: virtual __thiscall UStateNPCMusicBox::~UStateNPCMusicBox(void)
//   0x6b66c0  public: static void __cdecl UStateNPCMasterWalk::InternalConstructor(void *)
//   0x6b66e0  public: static void __cdecl UStateNPCMasterAction::InternalConstructor(void *)
//   0x6b6700  public: static void __cdecl UStateNPCActionParry::InternalConstructor(void *)
//   0x6b6720  public: static void __cdecl UStateNPCInstigatedMasterAction::InternalConstructor(void *)
//   0x6b6740  public: static void __cdecl UStateNPCMasterActionImmolate::InternalConstructor(void *)
//   0x6b6760  public: static void __cdecl UStateNPCMasterActionPostPossessed::InternalConstructor(void *)
//   0x6b6780  public: static void __cdecl UStateNPCMasterBePossessed::InternalConstructor(void *)
//   0x6b67a0  public: static void __cdecl UStateNPCMasterFalling::InternalConstructor(void *)
//   0x6b67c0  public: static void __cdecl UStateNPCMasterProjectileHitReact::InternalConstructor(void *)
//   0x6b67e0  public: static void __cdecl UStateNPCMasterStrongHitReact::InternalConstructor(void *)
//   0x6b6800  public: static void __cdecl UStateNPCMasterStunned::InternalConstructor(void *)
//   0x6b6820  public: static void __cdecl UStateNPCMasterThrown::InternalConstructor(void *)
//   0x6b6840  public: static void __cdecl UStateNPCMasterActionMelee::InternalConstructor(void *)
//   0x6b6860  public: static void __cdecl UStateNPCMasterActionMeleeVersus::InternalConstructor(void *)
//   0x6b6880  protected: virtual __thiscall UStateNPCMasterAim_Grenade::~UStateNPCMasterAim_Grenade(void)
//   0x6b6990  protected: virtual __thiscall UStateNPCMasterTallboyAim::~UStateNPCMasterTallboyAim(void)
//   0x6b6a30  public: static void __cdecl UStateNPCMasterBeingAssassinated::InternalConstructor(void *)
//   0x6b6a50  public: static void __cdecl UStateNPCMasterBeingChoked::InternalConstructor(void *)
//   0x6b6a70  public: static void __cdecl UStateNPCMasterDistracted::InternalConstructor(void *)
//   0x6b6a90  public: static void __cdecl UStateNPCMasterDodge::InternalConstructor(void *)
//   0x6b6ab0  public: static void __cdecl UStateNPCMasterFallingUncontrolled::InternalConstructor(void *)
//   0x6b6ad0  public: static void __cdecl UStateNPCMasterGesture::InternalConstructor(void *)
//   0x6b6af0  public: static void __cdecl UStateNPCMasterLyingInWait::InternalConstructor(void *)
//   0x6b6b10  public: static void __cdecl UStateNPCMasterMinigame::InternalConstructor(void *)
//   0x6b6b30  public: static void __cdecl UStateNPCMasterPlayAnim::InternalConstructor(void *)
//   0x6b6b50  public: static void __cdecl UStateNPCAttractSpell::InternalConstructor(void *)
//   0x6b6b70  public: static void __cdecl UStateNPCMasterDualPlayAnim::InternalConstructor(void *)
//   0x6b6b90  public: static void __cdecl UStateNPCMasterRangedAttack::InternalConstructor(void *)
//   0x6b6bb0  public: static void __cdecl UStateNPCMasterSurprised::InternalConstructor(void *)
//   0x6b6bd0  public: static void __cdecl UStateNPCUpperBodyAction::InternalConstructor(void *)
//   0x6b6bf0  public: static void __cdecl UStateNPCMasterEquip::InternalConstructor(void *)
//   0x6b6c10  public: static void __cdecl UStateNPCUpperPlayAnim::InternalConstructor(void *)
//   0x6b6c30  public: static void __cdecl UStateNPCMusicBox::InternalConstructor(void *)
//   0x6be4d0  public: static void __cdecl UStateNPCMasterAim::InternalConstructor(void *)
//   0x6be500  public: static void __cdecl UStateNPCMasterAim_Grenade::InternalConstructor(void *)
//   0x6be530  public: static void __cdecl UStateNPCMasterTallboyAim::InternalConstructor(void *)
//   0x6c5ee0  protected: virtual __thiscall UStateNPCMasterActionMeleeSwarm::~UStateNPCMasterActionMeleeSwarm(void)
//   0x6c73d0  public: static void __cdecl UStateNPCMasterActionMeleeSwarm::InternalConstructor(void *)
//   0x725c40  protected: virtual __thiscall UStateNPCEscapeExplosion::~UStateNPCEscapeExplosion(void)
//   0x729600  public: static void __cdecl UStateNPCEscapeExplosion::InternalConstructor(void *)
//   0x7b6020  protected: virtual __thiscall UDisActorFactoryNPCPawn::~UDisActorFactoryNPCPawn(void)
//   0x7b9790  public: static void __cdecl UDisActorFactoryNPCPawn::InternalConstructor(void *)
//   0x7be530  protected: virtual __thiscall UDisDistractionGlobalManager::~UDisDistractionGlobalManager(void)
//   0x7be5e0  protected: virtual __thiscall ADishonoredNPCController::~ADishonoredNPCController(void)
//   0x7be7d0  public: static void __cdecl UDisDistractionGlobalManager::InternalConstructor(void *)
//   0x7be7f0  public: static void __cdecl ADishonoredNPCController::InternalConstructor(void *)
//   0x7c4db0  protected: virtual __thiscall ADisPossessablePawn::~ADisPossessablePawn(void)
//   0x7c5210  public: virtual class UObject * __thiscall ADishonoredNPCPawn::GetUObjectInterfaceDisInteractableInterface(void)
//   0x7c5220  public: virtual class UObject * __thiscall ADishonoredNPCPawn::GetUObjectInterfaceDisSoulRenderInterface(void)
//   0x7c5230  public: virtual class UObject * __thiscall ADishonoredNPCPawn::GetUObjectInterfaceDisCorpseInterface(void)
//   0x7c5240  public: virtual class UObject * __thiscall ADishonoredNPCPawn::GetUObjectInterfaceDisSpringRazorTargetInterface(void)
//   0x7c5250  public: virtual class UObject * __thiscall ADishonoredNPCPawn::GetUObjectInterfaceDisStealthVolumeUserInterface(void)
//   0x7c53b0  protected: virtual __thiscall ADishonoredNPCPawn::~ADishonoredNPCPawn(void)
//   0x7c7270  public: static void __cdecl ADisPossessablePawn::InternalConstructor(void *)
//   0x7c7290  public: static void __cdecl ADishonoredNPCPawn::InternalConstructor(void *)
//   0x7cbe50  protected: virtual __thiscall UDisTallboyLightComponent::~UDisTallboyLightComponent(void)
//   0x7ce480  public: static void __cdecl UDisTallboyLightComponent::InternalConstructor(void *)
//   0x7ddc70  public: virtual class UObject * __thiscall UDisNPCDistractionComponent::GetUObjectInterfaceDisLookAtInterface(void)
//   0x7ddca0  protected: virtual __thiscall UDisNPCDistractionComponent::~UDisNPCDistractionComponent(void)
//   0x7deff0  public: static void __cdecl UDisNPCDistractionComponent::InternalConstructor(void *)
//   0x7e07a0  protected: virtual __thiscall UDisTweaks_NPCPlotSettings::~UDisTweaks_NPCPlotSettings(void)
//   0x7e0840  protected: virtual __thiscall UDisTweaks_PlayerPawn_Animation::~UDisTweaks_PlayerPawn_Animation(void)
//   0x7e08d0  protected: virtual __thiscall UDisTweaks_NPCPawn_Combat::~UDisTweaks_NPCPawn_Combat(void)
//   0x7e0ad0  public: static void __cdecl UDisTweaks_NPCPlotSettings::InternalConstructor(void *)
//   0x7e0af0  public: static void __cdecl UDisTweaks_PlayerPawn_Animation::InternalConstructor(void *)
//   0x7e0b10  public: static void __cdecl UDisTweaks_NPCPawn_Combat::InternalConstructor(void *)
//   0x7e0f60  protected: virtual __thiscall UDisTweaks_NPCPawn_Body::~UDisTweaks_NPCPawn_Body(void)
//   0x7e5690  public: static void __cdecl UDisTweaks_NPCPawn_Body::InternalConstructor(void *)
//   0x7eec80  protected: virtual __thiscall ADisTallboyNPCPawn::~ADisTallboyNPCPawn(void)
//   0x7efc10  public: static void __cdecl ADisTallboyNPCPawn::InternalConstructor(void *)
//   0x7f08c0  protected: virtual __thiscall UDisTweaks_NPCPawn::~UDisTweaks_NPCPawn(void)
//   0x7f0a30  protected: virtual __thiscall UDisTweaks_TallboyNPCPawn::~UDisTweaks_TallboyNPCPawn(void)
//   0x7f0e10  public: static void __cdecl UDisTweaks_NPCPawn::InternalConstructor(void *)
//   0x7f0e30  public: static void __cdecl UDisTweaks_TallboyNPCPawn::InternalConstructor(void *)
//   0x85d060  protected: virtual __thiscall UDisSeveredLimbInfo::~UDisSeveredLimbInfo(void)
//   0x85d800  public: static void __cdecl UDisSeveredLimbInfo::InternalConstructor(void *)
//   0x85fa10  protected: virtual __thiscall ADisPossessionProxyPawn::~ADisPossessionProxyPawn(void)
//   0x8601d0  public: static void __cdecl ADisPossessionProxyPawn::InternalConstructor(void *)
//   0x89aa80  protected: virtual __thiscall UDisTweaks_Armor::~UDisTweaks_Armor(void)
//   0x89c640  public: static void __cdecl UDisTweaks_Armor::InternalConstructor(void *)
//   0x8b0f90  public: __thiscall FDisRagdollImpulseDeferred::FDisRagdollImpulseDeferred(class FVector const &, class FVector const &, class FName, unsigned int)
//   0xba77d0  _dynamic_initializer_for__ADishonoredNPCControllerexecIsDeadTemp__
//   0xba77f0  _dynamic_initializer_for__ADishonoredNPCControllerexecDisplayDebug_NativeTemp__
//   0xba7810  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIRingAlarmTemp__
//   0xba7830  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIStartDistractionTemp__
//   0xba7850  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIGetBrainFlagsTemp__
//   0xba7870  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAISetBrainFlagsTemp__
//   0xba7890  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIPsychicAttentionTemp__
//   0xba78b0  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIClearAttentionTemp__
//   0xba78d0  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAISetSuspicionLevelTemp__
//   0xba78f0  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIProtectNeutralsOverrideTemp__
//   0xba7910  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIShootTemp__
//   0xba7930  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAISetSensesTemp__
//   0xba7950  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAISetPatrolTemp__
//   0xba7970  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIKismetDoBehaviorTemp__
//   0xba7990  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIGuardTemp__
//   0xba79b0  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIGoToActorTemp__
//   0xba79d0  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIDoSearchTemp__
//   0xba79f0  _dynamic_initializer_for__ADishonoredNPCControllerexecOnAIAmbushTemp__
//   0xba7a10  _dynamic_initializer_for__ADishonoredNPCControllerexecGetMoveTargetLocationTemp__
//   0xba7a30  _dynamic_initializer_for__ADishonoredNPCPawnexecSetDesiredRotationTemp__
//   0xba7a50  _dynamic_initializer_for__ADishonoredNPCPawnexecSetPushesRigidBodiesTemp__
//   0xba7a70  _dynamic_initializer_for__ADishonoredNPCPawnexecOnNPCSetMaterialsTemp__
//   0xba7a90  _dynamic_initializer_for__ADishonoredNPCPawnexecOnSetIgnoreDeathTemp__
//   0xba7ab0  _dynamic_initializer_for__ADishonoredNPCPawnexecOnOverridePossessTemp__
//   0xba7ad0  _dynamic_initializer_for__ADishonoredNPCPawnexecOnPlayMusicBoxTemp__
//   0xba7af0  _dynamic_initializer_for__ADishonoredNPCPawnexecOnEquipItemTypeTemp__
//   0xba7b10  _dynamic_initializer_for__ADishonoredNPCPawnexecOnSpawnStealableTemp__
//   0xba7b30  _dynamic_initializer_for__ADishonoredNPCPawnexecOnNPCDoTeleportSpellTemp__
//   ... 16 more, see resources/docs/symbols/functions.csv
