/*===========================================================================
    DishonoredGameGlobalStructsClasses.h - C++ class definitions of the retail (2013) DishonoredGame module.
    Generated by resources/tools/symbols/gen_classes_header.py --sdk from the CodeRed SDK dump
    (retail_sdk_layout.json: member offsets/types/flags, function parameter blocks), native_class_sizes.csv
    (retail sizeof, ClassFlags, Within, config), script_classes_2013.json (enum values, consts, property
    kinds, header groups) and the 2012 types.json (names of native-only members). DO NOT edit by hand:
    regenerate, or carry the change into the generator.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "DishonoredGameNames.h"

#ifndef NAMES_ONLY
#include "DishonoredGameEngineShims.h"
#endif

#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_DISHONOREDGAME_GLOBALSTRUCTS_ENUMS
#define INCLUDED_DISHONOREDGAME_GLOBALSTRUCTS_ENUMS 1


#endif // !INCLUDED_DISHONOREDGAME_GLOBALSTRUCTS_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_DISHONOREDGAME_GLOBALSTRUCTS_CLASSES
#define INCLUDED_DISHONOREDGAME_GLOBALSTRUCTS_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

// DishonoredGame.DisGlobalStructs.DisMaterialReplacement: retail SDK size 8 (2012 PDB 8)
struct FDisMaterialReplacement
{
    class UMaterialInterface* m_pDefaultMaterial;
    class UMaterialInterface* m_pCustomMaterial;

    /** Constructors */
    FDisMaterialReplacement() {}
    FDisMaterialReplacement(EEventParm)
    {
        appMemzero(this, sizeof(FDisMaterialReplacement));
    }
};

// DishonoredGame.DisGlobalStructs.DisMaterialsOverride: retail SDK size 12 (2012 PDB 12)
struct FDisMaterialsOverride
{
    TArrayNoInit<FDisMaterialReplacement> m_MaterialReplacements;

    /** Constructors */
    FDisMaterialsOverride() {}
    FDisMaterialsOverride(EEventParm)
    {
        appMemzero(this, sizeof(FDisMaterialsOverride));
    }
};

// DishonoredGame.DisGlobalStructs.DisLocRot: retail SDK size 24 (2012 PDB 24)
struct FDisLocRot
{
    FVector m_Loc;
    FRotator m_Rot;

    /** Constructors */
    FDisLocRot() {}
    FDisLocRot(EEventParm)
    {
        appMemzero(this, sizeof(FDisLocRot));
    }
};

// DishonoredGame.DisGlobalStructs.DisSpotlightManager: retail SDK size 24 (2012 PDB 24)
struct FDisSpotlightManager
{
    class UMaterialInstanceConstant* m_pLight_MIC;
    FLOAT m_fCurrentLightIntensity;
    FLOAT m_fCurrentLightAngle;
    FLOAT m_fOriginalInnerToOuterRatio;
    FLOAT m_fOriginalLightBrightness;
    FLOAT m_fOriginalMaterialOpacity;

    /** Constructors */
    FDisSpotlightManager() {}
    FDisSpotlightManager(EEventParm)
    {
        appMemzero(this, sizeof(FDisSpotlightManager));
    }
};

// DishonoredGame.DisGlobalStructs.FollowParameters: retail SDK size 12 (2012 PDB 12)
struct FFollowParameters
{
    FLOAT m_fDistance;
    FLOAT m_fAngle;
    BYTE m_eDesiredSpeed;

    /** Constructors */
    FFollowParameters() {}
    FFollowParameters(EEventParm)
    {
        appMemzero(this, sizeof(FFollowParameters));
    }
};

// DishonoredGame.DisGlobalStructs.DisRangedFloat: retail SDK size 8 (2012 PDB 8)
struct FDisRangedFloat
{
    FLOAT m_fMinValue;
    FLOAT m_fMaxValue;

    /** Constructors */
    FDisRangedFloat() {}
    FDisRangedFloat(EEventParm)
    {
        appMemzero(this, sizeof(FDisRangedFloat));
    }
};

// DishonoredGame.DisGlobalStructs.DisDirectionConstraint: retail SDK size 12 (2012 PDB 12)
struct FDisDirectionConstraint
{
    BYTE m_Direction;
    FDisRangedFloat m_AngleRange;

    /** Constructors */
    FDisDirectionConstraint() {}
    FDisDirectionConstraint(EEventParm)
    {
        appMemzero(this, sizeof(FDisDirectionConstraint));
    }
};

// DishonoredGame.DisGlobalStructs.PawnAction: retail SDK size 44 (2012 PDB 44)
struct FPawnAction
{
    FName m_ActionName;
    TArrayNoInit<FName> m_AnimStates;
    BITFIELD m_bCanMove:1;
    BITFIELD m_bCanLook:1;
    BITFIELD m_bNoInterrupt:1;
    BITFIELD m_bAesthetic:1;
    BITFIELD m_bAllowSelfInterrupt:1;
    BITFIELD m_bAllowAttackToInterrupt:1;
    BITFIELD m_bAllowDodgeToInterrupt:1;
    BITFIELD m_bAllowParryToInterrupt:1;
    BITFIELD m_bAllowReloadToInterrupt:1;
    BITFIELD m_bInterruptsStun:1;
    BYTE m_DeathType;
    FName m_CustomDeathAnimState;
    FLOAT m_fPlayRateOverride;
    BITFIELD m_bActionUsesLeftHand:1;
    BITFIELD m_bAutomaticallyStopSneaking:1;
    BITFIELD m_bDisableFootPlacement:1;
    BITFIELD m_bForceVisionForward:1;
    BITFIELD m_bSpineBendTowardsTarget:1;

    /** Constructors */
    FPawnAction() {}
    FPawnAction(EEventParm)
    {
        appMemzero(this, sizeof(FPawnAction));
    }
};

// DishonoredGame.DisGlobalStructs.DisCameraRumbleAxis: retail SDK size 20 (2012 PDB 20)
struct FDisCameraRumbleAxis
{
    FLOAT m_fAmplitude;
    FLOAT m_fFrequency;
    FLOAT m_fDuration;
    FLOAT m_fEaseInSeconds;
    FLOAT m_fEaseOutSeconds;

    /** Constructors */
    FDisCameraRumbleAxis() {}
    FDisCameraRumbleAxis(EEventParm)
    {
        appMemzero(this, sizeof(FDisCameraRumbleAxis));
    }
};

// DishonoredGame.DisGlobalStructs.DisCameraSustainedRumble: retail SDK size 60 (2012 PDB 60)
struct FDisCameraSustainedRumble
{
    FDisCameraRumbleAxis m_Rumble_Pitch;
    FDisCameraRumbleAxis m_Rumble_Yaw;
    FDisCameraRumbleAxis m_Rumble_Roll;

    /** Constructors */
    FDisCameraSustainedRumble() {}
    FDisCameraSustainedRumble(EEventParm)
    {
        appMemzero(this, sizeof(FDisCameraSustainedRumble));
    }
};

// DishonoredGame.DisGlobalStructs.DisDispositionChange: retail SDK size 8 (2012 PDB 8)
struct FDisDispositionChange
{
    class UDisTweaks_Faction* m_pFaction;
    BYTE m_Relationship;

    /** Constructors */
    FDisDispositionChange() {}
    FDisDispositionChange(EEventParm)
    {
        appMemzero(this, sizeof(FDisDispositionChange));
    }
};

// DishonoredGame.DisGlobalStructs.DisLineProbeResult: retail SDK size 84 (2012 PDB 84)
struct FDisLineProbeResult
{
    FImpactInfo m_ImpactInfo;
    FLOAT m_fCheckResult_Time;

    /** Constructors */
    FDisLineProbeResult() {}
    FDisLineProbeResult(EEventParm)
    {
        appMemzero(this, sizeof(FDisLineProbeResult));
    }
};

// DishonoredGame.DisGlobalStructs.DisMaterialSetting: retail SDK size 8 (2012 PDB 8)
struct FDisMaterialSetting
{
    INT m_MaterialIndex;
    class UMaterialInterface* m_pMaterial;

    /** Constructors */
    FDisMaterialSetting() {}
    FDisMaterialSetting(EEventParm)
    {
        appMemzero(this, sizeof(FDisMaterialSetting));
    }
};

// DishonoredGame.DisGlobalStructs.DisRangedInt: retail SDK size 8 (2012 PDB 8)
struct FDisRangedInt
{
    INT m_MinValue;
    INT m_MaxValue;

    /** Constructors */
    FDisRangedInt() {}
    FDisRangedInt(EEventParm)
    {
        appMemzero(this, sizeof(FDisRangedInt));
    }
};

// DishonoredGame.DisGlobalStructs.ImmolationParams: retail SDK size 36 (2012 PDB 36)
struct FImmolationParams
{
    FLOAT m_fDamageRadius;
    FLOAT m_fDamagePeriod;
    FLOAT m_fDamage;
    class UClass* m_pDamageType;
    FLOAT m_fAvoidanceRadius;
    FLOAT m_fRatLightRadius;
    FLOAT m_fRatLightStrength;
    FLOAT m_fNoisePeriod;
    BYTE m_NoiseLoudness;
    BYTE m_NoiseContext;

    /** Constructors */
    FImmolationParams() {}
    FImmolationParams(EEventParm)
    {
        appMemzero(this, sizeof(FImmolationParams));
    }
};

// DishonoredGame.DisGlobalStructs: retail sizeof 56, reflected span 56..56 (2012 PDB sizeof 56)
class UDisGlobalStructs : public UObject
{
public:
    //## BEGIN PROPS DisGlobalStructs
    //## END PROPS DisGlobalStructs

    DECLARE_ABSTRACT_CLASS(UDisGlobalStructs,UObject,0,DishonoredGame)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_DISHONOREDGAME_GLOBALSTRUCTS_CLASSES
#endif // !NAMES_ONLY


#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DISHONOREDGAME_GLOBALSTRUCTS_NATIVE_DEFS
#define DISHONOREDGAME_GLOBALSTRUCTS_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_DISHONOREDGAME_GLOBALSTRUCTS \
	UDisGlobalStructs::StaticClass(); \

#endif // DISHONOREDGAME_GLOBALSTRUCTS_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UDisGlobalStructs)
#endif // VERIFY_CLASS_SIZES

#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
