/*===========================================================================
    DishonoredGameRiverKrustClasses.h - C++ class definitions of the retail (2013) DishonoredGame module.
    Generated by resources/tools/symbols/gen_classes_header.py --sdk from the CodeRed SDK dump
    (retail_sdk_layout.json: member offsets/types/flags, function parameter blocks), native_class_sizes.csv
    (retail sizeof, ClassFlags, Within, config), script_classes_2013.json (enum values, consts, property
    kinds, header groups) and the 2012 types.json (names of native-only members). DO NOT edit by hand:
    regenerate, or carry the change into the generator.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "DishonoredGameNames.h"

#ifndef NAMES_ONLY
#include "DishonoredGameEngineShims.h"
#include "DishonoredGameGlobalEnumsClasses.h"
#include "DishonoredGameClasses.h"
#include "DishonoredGameDLC07PullClasses.h"
#endif

#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_DISHONOREDGAME_RIVERKRUST_ENUMS
#define INCLUDED_DISHONOREDGAME_RIVERKRUST_ENUMS 1


#endif // !INCLUDED_DISHONOREDGAME_RIVERKRUST_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_DISHONOREDGAME_RIVERKRUST_CLASSES
#define INCLUDED_DISHONOREDGAME_RIVERKRUST_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

// DishonoredGame.DisRiverKrust.RiverKrustSeenActorInfo: retail SDK size 28 (2012 PDB 28)
struct FRiverKrustSeenActorInfo
{
    class AActor* m_pActor;
    FLOAT m_fStartedSeeingTime;
    FLOAT m_fStoppedSeeingTime;
    FVector m_LastSeenLocation;
    BYTE m_RelationshipToActor;

    /** Constructors */
    FRiverKrustSeenActorInfo() {}
    FRiverKrustSeenActorInfo(EEventParm)
    {
        appMemzero(this, sizeof(FRiverKrustSeenActorInfo));
    }
};

struct DisRiverKrust_eventTakeDamage_Parms
{
    INT Damage;
    class AController* InstigatedBy;
    FVector HitLocation;
    FVector Momentum;
    class UClass* DamageType;
    FTraceHitInfo HitInfo;
    class AActor* DamageCauser;
    DisRiverKrust_eventTakeDamage_Parms(EEventParm)
    : HitLocation(EC_EventParm)
    , Momentum(EC_EventParm)
    , HitInfo(EC_EventParm)
    {
    }
};
struct DisRiverKrust_eventOnAnimEnd_Parms
{
    class UAnimNodeSequence* _seqNode;
    FLOAT _playedTime;
    FLOAT _excessTime;
    DisRiverKrust_eventOnAnimEnd_Parms(EEventParm)
    {
    }
};
// DishonoredGame.DisRiverKrust: retail sizeof 1008, reflected span 584..1008 (2012 PDB sizeof 992)
class ADisRiverKrust : public AActor, public IArkHealthInterface, public IDisTweaksInterface, public IDisPossessableInterface, public IDisRelationshipInterface, public IDisFireProjectileInterface, public IDisHitReboundInterface, public IDisDrawVisionComponentOwnerInterface, public IDisSpringRazorTargetInterface, public IDisSoulRenderInterface, public IDisContactTypeInterface, public IDisInteractableInterface, public IDisDLC07PullTargetInterface
{
public:
    //## BEGIN PROPS DisRiverKrust
    BYTE m_eCurrentState;
    BYTE m_eCurrentAnimState;
    BYTE m_eStimulusReactionState;
    BYTE m_NextDemoStateIndex;
    BYTE m_eScriptedState;
    INT m_CurrentHealth;
    INT m_MaximumHealth;
    FVector m_VisionLocation;
    FRotator m_VisionRotation;
    FVector m_ProjectileLaunchLocation;
    FRotator m_ProjectileLaunchRotation;
    BITFIELD m_bHasStartedRagdoll:1;
    BITFIELD m_bHasThreatInsideDefensiveEnterRange:1;
    BITFIELD m_bIsScriptedVisionEnabled:1;
    BITFIELD m_bIsScriptedAttackingEnabled:1;
    BITFIELD m_bIsPrimaryThreatInsideFieldOfFire:1;
    BITFIELD m_bHasThreatInsideDefensiveExitRange:1;
    BITFIELD m_bHasThreatInsideAggressiveEnterRange:1;
    BITFIELD m_bHasThreatInsideAggressiveExitRange:1;
    BITFIELD m_bIsTimeToRespondToThreatInsideDefensiveEnterRange:1;
    BITFIELD m_bHadThreatInsideDefensiveExitRangeRecently:1;
    BITFIELD m_bHadThreatInsideAggressiveExitRangeRecently:1;
    BITFIELD m_bSpawnDead:1;
    BITFIELD m_bPullDisabled:1;
    INT m_NumVolleyShotsToFire;
    INT m_NumVolleyShotsFired;
    FLOAT m_fNextVolleyShotTimeSeconds;
    FVector m_MostRecentValidThreatLocation;
    FLOAT m_fStimulusReactionExpireTime;
    FLOAT m_fRecentThreatInsideDefensiveEnterRangeRespondTime;
    FLOAT m_fRecentThreatInsideDefensiveExitRangeExpireTime;
    FLOAT m_fRecentThreatInsideAggressiveExitRangeExpireTime;
    FLOAT m_fNextDemoStateChangeTimeSeconds;
    TArrayNoInit<FRiverKrustSeenActorInfo> m_SeenActors;
    FDisRelationshipOverrideInfo m_PersonalRelationships;
    class ADisPickup_Base* m_pLootPickup;
    class AActor* m_pScriptedTargetActor;
    class AActor* m_pMostRecentDamageInstigator;
    FVector m_MostRecentDamageMomentum;
    TArrayNoInit<class ADisRiverKrustBodyPart*> m_pBodyParts;
    FLOAT m_fPullTimeRemaining;
    class AActor* m_pPrimaryThreatActor;
    FVector m_PrimaryThreatLocation;
    FLOAT m_fDistanceToPrimaryThreat;
    class USkeletalMeshComponent* m_pSkeletalMeshCpnt;
    class UAnimNodeSlot* m_pFullBodyAnimNodeSlot;
    class UDisRiverKrustComponent* m_pRiverKrustCpnt;
    class UDisDrawVisionComponent* m_pDrawVisionCpnt;
    class UDisTweaks_RiverKrust* m_pRiverKrustTweaks;
    class UArkComponentContainer* m_ComponentContainer;
    BYTE m_PreviewMeshInfo[12];  // DISHONORED(layout): retail SDK gap @960: ArrayProperty m_PreviewMeshInfo (script_classes_2013) the dump did not type
    TArrayNoInit<class USkeletalMeshComponent*> m_PreviewSkeletalComponents;
    TArrayNoInit<class UStaticMeshComponent*> m_PreviewStaticComponents;
    FVector m_PullImpulseOnDeath;
    //## END PROPS DisRiverKrust

    void eventTakeDamage(INT Damage,class AController* InstigatedBy,FVector HitLocation,FVector Momentum,class UClass* DamageType,FTraceHitInfo HitInfo=FTraceHitInfo(EC_EventParm),class AActor* DamageCauser=NULL)
    {
        DisRiverKrust_eventTakeDamage_Parms Parms(EC_EventParm);
        Parms.Damage=Damage;
        Parms.InstigatedBy=InstigatedBy;
        Parms.HitLocation=HitLocation;
        Parms.Momentum=Momentum;
        Parms.DamageType=DamageType;
        Parms.HitInfo=HitInfo;
        Parms.DamageCauser=DamageCauser;
        ProcessEvent(FindFunctionChecked(DISHONOREDGAME_TakeDamage),&Parms);
    }
    void eventOnAnimEnd(class UAnimNodeSequence* _seqNode,FLOAT _playedTime,FLOAT _excessTime)
    {
        DisRiverKrust_eventOnAnimEnd_Parms Parms(EC_EventParm);
        Parms._seqNode=_seqNode;
        Parms._playedTime=_playedTime;
        Parms._excessTime=_excessTime;
        ProcessEvent(FindFunctionChecked(DISHONOREDGAME_OnAnimEnd),&Parms);
    }
    virtual UObject* GetUObjectInterfaceArkHealthInterface() { return this; }  // DISHONORED(port): IArkHealthInterface interface glue
    virtual INT ArkGetCurHealth() const { appErrorf(TEXT("DishonoredGame native not ported: %s"), TEXT("ADisRiverKrust::ArkGetCurHealth")); return {}; }  // DISHONORED(port): IArkHealthInterface pure virtual
    virtual UBOOL ArkIsIncapacitated() const { appErrorf(TEXT("DishonoredGame native not ported: %s"), TEXT("ADisRiverKrust::ArkIsIncapacitated")); return {}; }  // DISHONORED(port): IArkHealthInterface pure virtual
    virtual UBOOL ArkIsDeadOrDestroyed() const { appErrorf(TEXT("DishonoredGame native not ported: %s"), TEXT("ADisRiverKrust::ArkIsDeadOrDestroyed")); return {}; }  // DISHONORED(port): IArkHealthInterface pure virtual
    DECLARE_FUNCTION(execOnRiverKrustDisable);
    DECLARE_FUNCTION(execOnRiverKrustSpitAtTarget);
    DECLARE_FUNCTION(execTakeDamage);
    DECLARE_FUNCTION(execTakeDamage_Native);
    DECLARE_FUNCTION(execOnAnimEnd);
    DECLARE_CLASS(ADisRiverKrust,AActor,0,DishonoredGame)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_DISHONOREDGAME_RIVERKRUST_CLASSES
#endif // !NAMES_ONLY

AUTOGENERATE_FUNCTION(ADisRiverKrust,-1,execOnRiverKrustDisable);
AUTOGENERATE_FUNCTION(ADisRiverKrust,-1,execOnRiverKrustSpitAtTarget);
AUTOGENERATE_FUNCTION(ADisRiverKrust,-1,execTakeDamage);
AUTOGENERATE_FUNCTION(ADisRiverKrust,-1,execTakeDamage_Native);
AUTOGENERATE_FUNCTION(ADisRiverKrust,-1,execOnAnimEnd);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DISHONOREDGAME_RIVERKRUST_NATIVE_DEFS
#define DISHONOREDGAME_RIVERKRUST_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_DISHONOREDGAME_RIVERKRUST \
	ADisRiverKrust::StaticClass(); \
	GNativeLookupFuncs.Set(FName("DisRiverKrust"), GDishonoredGameADisRiverKrustNatives); \

#endif // DISHONOREDGAME_RIVERKRUST_NATIVE_DEFS

#ifdef NATIVES_ONLY
FNativeFunctionLookup GDishonoredGameADisRiverKrustNatives[] = 
{ 
	MAP_NATIVE(ADisRiverKrust, execOnRiverKrustDisable)
	MAP_NATIVE(ADisRiverKrust, execOnRiverKrustSpitAtTarget)
	MAP_NATIVE(ADisRiverKrust, execTakeDamage)
	MAP_NATIVE(ADisRiverKrust, execTakeDamage_Native)
	MAP_NATIVE(ADisRiverKrust, execOnAnimEnd)
	{NULL, NULL}
};

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(ADisRiverKrust,DisRiverKrust,m_eCurrentState)
VERIFY_CLASS_OFFSET_NODIE(ADisRiverKrust,DisRiverKrust,m_PullImpulseOnDeath)
VERIFY_CLASS_SIZE_NODIE(ADisRiverKrust)
#endif // VERIFY_CLASS_SIZES

#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
