#pragma once
// DishonoredGame/inc/dishonoredgameitemclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (100):
//   0x63c7a0  public: static class UClass * __cdecl UDishonoredItemEmpty::StaticClass(void)
//   0x63c7c0  public: static class UClass * __cdecl UDisItemPowers::StaticClass(void)
//   0x63c7e0  public: void __thiscall AController::execUnPossess(struct FFrame &, void * const)
//   0x63c820  public: static class UClass * __cdecl ADisWhaleOilBattery::StaticClass(void)
//   0x63c840  public: static class UClass * __cdecl ADisPickup_Base::StaticClass(void)
//   0x63f350  public: void __thiscall ADisPickup_Base::execBaseChange(struct FFrame &, void * const)
//   0x64f130  public: virtual class UObject * __thiscall ADisSkeletalBreakable::GetUObjectInterfaceDisEngineTweaksInterface(void)
//   0x64f160  protected: virtual __thiscall ADisDetectionEye::~ADisDetectionEye(void)
//   0x650bc0  public: static void __cdecl ADisDetectionEye::InternalConstructor(void *)
//   0x656d50  protected: virtual __thiscall ADishonoredBreakable::~ADishonoredBreakable(void)
//   0x656fa0  public: virtual class UObject * __thiscall ADishonoredMovable::GetUObjectInterfaceDisInteractableInterface(void)
//   0x657020  protected: virtual __thiscall ADishonoredBreakableNavBlock::~ADishonoredBreakableNavBlock(void)
//   0x658410  public: static void __cdecl ADishonoredBreakable::InternalConstructor(void *)
//   0x658430  public: static void __cdecl ADishonoredBreakableNavBlock::InternalConstructor(void *)
//   0x66ba90  protected: virtual __thiscall IDisMovableInterface::~IDisMovableInterface(void)
//   0x66f1c0  protected: virtual __thiscall UDisMovableComponent::~UDisMovableComponent(void)
//   0x672960  public: static void __cdecl UDisMovableComponent::InternalConstructor(void *)
//   0x6763b0  protected: virtual __thiscall ADisPickup_Base::~ADisPickup_Base(void)
//   0x676470  public: virtual class UObject * __thiscall ADishonoredBreakable::GetUObjectInterfaceArkHealthInterface(void)
//   0x676480  public: virtual class UObject * __thiscall ADisPickup_Base::GetUObjectInterfaceDisSoulRenderInterface(void)
//   0x6765c0  protected: virtual __thiscall ADisAbstractItemPickup::~ADisAbstractItemPickup(void)
//   0x676830  protected: virtual __thiscall ADisAbstractItemPickupNote::~ADisAbstractItemPickupNote(void)
//   0x6769d0  protected: virtual __thiscall ADisElixirHealth::~ADisElixirHealth(void)
//   0x676b70  protected: virtual __thiscall ADisElixirMana::~ADisElixirMana(void)
//   0x676d10  protected: virtual __thiscall ADisGenericPickup::~ADisGenericPickup(void)
//   0x676eb0  protected: virtual __thiscall ADisKey_Base::~ADisKey_Base(void)
//   0x677060  protected: virtual __thiscall ADisStatPickup::~ADisStatPickup(void)
//   0x677200  protected: virtual __thiscall ADisWhaleBoneCharm::~ADisWhaleBoneCharm(void)
//   0x677360  public: virtual class UObject * __thiscall ADisWallOfLight::GetUObjectInterfaceDisWhaleOilConsumerInterface(void)
//   0x677370  public: virtual class UObject * __thiscall ADisWallOfLight::GetUObjectInterfaceInterface_NavMeshPathObject(void)
//   0x677380  public: virtual class UObject * __thiscall ADisWallOfLight::GetUObjectInterfaceDisSoulRenderInterface(void)
//   0x6773d0  protected: virtual __thiscall ADisWallOfLight::~ADisWallOfLight(void)
//   0x677c30  public: static void __cdecl ADisPickup_Base::InternalConstructor(void *)
//   0x677c50  public: static void __cdecl ADisAbstractItemPickupNote::InternalConstructor(void *)
//   0x677c70  public: static void __cdecl ADisElixirHealth::InternalConstructor(void *)
//   0x677c90  public: static void __cdecl ADisElixirMana::InternalConstructor(void *)
//   0x677cb0  public: static void __cdecl ADisGenericPickup::InternalConstructor(void *)
//   0x677cd0  public: static void __cdecl ADisKey_Base::InternalConstructor(void *)
//   0x677cf0  public: static void __cdecl ADisStatPickup::InternalConstructor(void *)
//   0x677d10  public: static void __cdecl ADisWhaleBoneCharm::InternalConstructor(void *)
//   0x677d30  public: static void __cdecl ADisWallOfLight::InternalConstructor(void *)
//   0x67c2f0  protected: virtual __thiscall ADishonoredMovable::~ADishonoredMovable(void)
//   0x67d090  public: static void __cdecl ADishonoredMovable::InternalConstructor(void *)
//   0x69c0a0  protected: virtual __thiscall UDisAbstractItem::~UDisAbstractItem(void)
//   0x69c130  public: virtual class FString const __thiscall UDisAbstractItem::GetAbstractItemDesc(void)const
//   0x69c1b0  protected: virtual __thiscall UDisAbstractItemAudioLog::~UDisAbstractItemAudioLog(void)
//   0x69e720  public: static void __cdecl UDisAbstractItemAudioLog::InternalConstructor(void *)
//   0x6a2fd0  protected: virtual __thiscall ADisAbstractItemPickupAudioLog::~ADisAbstractItemPickupAudioLog(void)
//   0x6a4890  public: static void __cdecl ADisAbstractItemPickupAudioLog::InternalConstructor(void *)
//   0x6a8d30  protected: virtual __thiscall ADisSpeaker_PA::~ADisSpeaker_PA(void)
//   0x6a9ee0  public: static void __cdecl ADisSpeaker_PA::InternalConstructor(void *)
//   0x718d80  protected: virtual __thiscall UDisTweaks_PlayerLoadout::~UDisTweaks_PlayerLoadout(void)
//   0x7199d0  public: static void __cdecl UDisTweaks_PlayerLoadout::InternalConstructor(void *)
//   0x7e6340  protected: virtual __thiscall ADisTallboyAttachment::~ADisTallboyAttachment(void)
//   0x7ecd70  public: static void __cdecl ADisTallboyAttachment::InternalConstructor(void *)
//   0x84a470  protected: virtual __thiscall UDishonoredInventoryItemPostUpdateTickComponent::~UDishonoredInventoryItemPostUpdateTickComponent(void)
//   0x84ef20  public: static void __cdecl UDishonoredInventoryItemPostUpdateTickComponent::InternalConstructor(void *)
//   0x858dd0  protected: virtual __thiscall UDishonoredInventory::~UDishonoredInventory(void)
//   0x85a0f0  public: static void __cdecl UDishonoredInventory::InternalConstructor(void *)
//   0x861660  public: virtual class UObject * __thiscall UDishonoredInventoryItem::GetUObjectInterfaceDisEngineTweaksInterface(void)
//   0x8616a0  protected: virtual __thiscall UDishonoredInventoryItem::~UDishonoredInventoryItem(void)
//   0x861980  public: static void __cdecl UDishonoredInventoryItem::InternalConstructor(void *)
//   0x8629b0  protected: virtual __thiscall UDisItemContext::~UDisItemContext(void)
//   0x862a50  protected: virtual __thiscall UDisItemContext_AimAssistAttack::~UDisItemContext_AimAssistAttack(void)
//   0x862ac0  public: virtual class UObject * __thiscall UDisItemContext_AimAssistAttack::GetUObjectInterfaceArkSettingsListenerInterface(void)
//   0x864900  protected: virtual __thiscall UDisItemContext_Choke::~UDisItemContext_Choke(void)
//   0x86d040  public: static void __cdecl UDisItemContext::InternalConstructor(void *)
//   0x86d060  public: static void __cdecl UDisItemContext_AimAssistAttack::InternalConstructor(void *)
//   0x86d0a0  public: static void __cdecl UDisItemContext_Choke::InternalConstructor(void *)
//   0x87b160  protected: virtual __thiscall ADishonoredInventoryPickup::~ADishonoredInventoryPickup(void)
//   0x87d1a0  public: static void __cdecl ADishonoredInventoryPickup::InternalConstructor(void *)
//   0x87e7d0  protected: virtual __thiscall UDisTweaks_LODConfig::~UDisTweaks_LODConfig(void)
//   0x87e860  protected: virtual __thiscall UDisTweaks_Choke::~UDisTweaks_Choke(void)
//   0x8801b0  protected: virtual __thiscall UDishonoredItemSkeletalComponent::~UDishonoredItemSkeletalComponent(void)
//   0x880240  public: static void __cdecl UDisTweaks_LODConfig::InternalConstructor(void *)
//   0x880260  public: static void __cdecl UDisTweaks_Choke::InternalConstructor(void *)
//   0x882890  public: static void __cdecl UDishonoredItemSkeletalComponent::InternalConstructor(void *)
//   0x893990  public: static void __cdecl UDisAbstractItem::InternalConstructor(void *)
//   0x898cf0  public: static void __cdecl ADisAbstractItemPickup::InternalConstructor(void *)
//   0x89ab30  protected: virtual __thiscall UDisTweaks_ItemPowers::~UDisTweaks_ItemPowers(void)
//   0x89abd0  protected: virtual __thiscall UDisTweaks_NPCTune::~UDisTweaks_NPCTune(void)
//   0x89ac60  protected: virtual __thiscall UDisTweaks_NPCTune_Protection::~UDisTweaks_NPCTune_Protection(void)
//   0x89c660  public: static void __cdecl UDisTweaks_ItemPowers::InternalConstructor(void *)
//   0x89c680  public: static void __cdecl UDisTweaks_NPCTune::InternalConstructor(void *)
//   0x89c6a0  public: static void __cdecl UDisTweaks_NPCTune_Protection::InternalConstructor(void *)
//   0x8aae90  protected: virtual __thiscall UDishonoredItemEmpty::~UDishonoredItemEmpty(void)
//   0x8aaf60  protected: virtual __thiscall UDisItemPowers::~UDisItemPowers(void)
//   0x8ac4a0  public: static void __cdecl UDishonoredItemEmpty::InternalConstructor(void *)
//   0x8ac4f0  public: static void __cdecl UDisItemPowers::InternalConstructor(void *)
//   0x8e6770  protected: virtual __thiscall ADisWhaleOilReceptacle::~ADisWhaleOilReceptacle(void)
//   0x8e9000  public: static void __cdecl ADisWhaleOilReceptacle::InternalConstructor(void *)
//   0x8eff00  protected: virtual __thiscall ADisWhaleOilBattery::~ADisWhaleOilBattery(void)
//   0x8f0a50  public: static void __cdecl ADisWhaleOilBattery::InternalConstructor(void *)
//   0xba8ad0  _dynamic_initializer_for__ADishonoredMovableexecOnSleepRBPhysics_NativeTemp__
//   0xba8af0  _dynamic_initializer_for__ADisTallboyAttachmentexecTakeDamage_NativeTemp__
//   0xba8b10  _dynamic_initializer_for__ADisWhaleOilBatteryexecTakeDamage_NativeTemp__
//   0xba8b30  _dynamic_initializer_for__ADisPickup_BaseexecBaseChangeTemp__
//   0xba8b50  _dynamic_initializer_for__ADisWhaleBoneCharmexecOnSetBoneCharmEffectTemp__
//   0xba8b70  _dynamic_initializer_for__ADisWallOfLightexecTakeDamageTemp__
//   0xba8b90  _dynamic_initializer_for__ADisWallOfLightexecTakeDamage_NativeTemp__
