/*===========================================================================
    DishonoredGameMantleClasses.h - C++ class definitions of the retail (2013) DishonoredGame module.
    Generated by resources/tools/symbols/gen_classes_header.py --sdk from the CodeRed SDK dump
    (retail_sdk_layout.json: member offsets/types/flags, function parameter blocks), native_class_sizes.csv
    (retail sizeof, ClassFlags, Within, config), script_classes_2013.json (enum values, consts, property
    kinds, header groups) and the 2012 types.json (names of native-only members). DO NOT edit by hand:
    regenerate, or carry the change into the generator.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "DishonoredGameNames.h"

#ifndef NAMES_ONLY
#include "DishonoredGameEngineShims.h"
#include "DishonoredGameGlobalEnumsClasses.h"
#include "DishonoredGameClasses.h"
#endif

#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_DISHONOREDGAME_MANTLE_ENUMS
#define INCLUDED_DISHONOREDGAME_MANTLE_ENUMS 1


#endif // !INCLUDED_DISHONOREDGAME_MANTLE_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_DISHONOREDGAME_MANTLE_CLASSES
#define INCLUDED_DISHONOREDGAME_MANTLE_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

// DishonoredGame.DishonoredMantleEdgeFinderComponent.DisMantleSpot: retail SDK size 24 (2012 PDB 24)
struct FDisMantleSpot
{
    FVector m_StartLocation;
    INT m_StartYaw;
    FLOAT m_fEdgeHeight;
    BITFIELD m_bRequiresImpactAnim:1;
    BITFIELD m_bForcesCrouch:1;

    /** Constructors */
    FDisMantleSpot() {}
    FDisMantleSpot(EEventParm)
    {
        appMemzero(this, sizeof(FDisMantleSpot));
    }
};

// DishonoredGame.DishonoredMantleEdgeFinderComponent.MantleCollisionCheckDebugInfo: retail SDK size 48 (2012 PDB 48)
struct FMantleCollisionCheckDebugInfo
{
    FVector m_Start;
    FVector m_Stop;
    FVector m_Mid;
    FVector m_Extents;

    /** Constructors */
    FMantleCollisionCheckDebugInfo() {}
    FMantleCollisionCheckDebugInfo(EEventParm)
    {
        appMemzero(this, sizeof(FMantleCollisionCheckDebugInfo));
    }
};

// DishonoredGame.DisMantleFinderState_Base: retail sizeof 132, reflected span 64..132 (2012 PDB sizeof 132)
class UDisMantleFinderState_Base : public UDishonoredNativeState
{
public:
    //## BEGIN PROPS DisMantleFinderState_Base
    class UDishonoredMantleEdgeFinderComponent* m_pOwningDMEFC;
    FDisMantleFinderOwnerInfo m_OwnerInfo;
    //## END PROPS DisMantleFinderState_Base

    DECLARE_ABSTRACT_CLASS(UDisMantleFinderState_Base,UDishonoredNativeState,0,DishonoredGame)
};

// DishonoredGame.DisMantleFinderState_CheckCanStand: retail sizeof 164, reflected span 132..164 (2012 PDB sizeof 164)
class UDisMantleFinderState_CheckCanStand : public UDisMantleFinderState_Base
{
public:
    //## BEGIN PROPS DisMantleFinderState_CheckCanStand
    BITFIELD m_bImpactAnimRequired:1;
    FVector m_SearchStart;
    FVector m_ForwardTraceDelta;
    FLOAT m_fCurrentHeightOffset;
    //## END PROPS DisMantleFinderState_CheckCanStand

    DECLARE_CLASS(UDisMantleFinderState_CheckCanStand,UDisMantleFinderState_Base,0,DishonoredGame)
};

// DishonoredGame.DisMantleFinderState_CheckDestinationValid: retail sizeof 188, reflected span 132..188 (2012 PDB sizeof 188)
class UDisMantleFinderState_CheckDestinationValid : public UDisMantleFinderState_Base
{
public:
    //## BEGIN PROPS DisMantleFinderState_CheckDestinationValid
    FVector m_SearchStart;
    BITFIELD m_bImpactAnimRequired:1;
    FVector m_DestLocation;
    FVector m_SearchPos;
    FLOAT m_fCurrentHeightOffset;
    FVector m_ForwardTraceDelta;
    //## END PROPS DisMantleFinderState_CheckDestinationValid

    DECLARE_CLASS(UDisMantleFinderState_CheckDestinationValid,UDisMantleFinderState_Base,0,DishonoredGame)
};

// DishonoredGame.DisMantleFinderState_FindClearDistanceAboveOwner: retail sizeof 136, reflected span 132..136 (2012 PDB sizeof 136)
class UDisMantleFinderState_FindClearDistanceAboveOwner : public UDisMantleFinderState_Base
{
public:
    //## BEGIN PROPS DisMantleFinderState_FindClearDistanceAboveOwner
    FLOAT m_Debug_fSearchStepSize;
    //## END PROPS DisMantleFinderState_FindClearDistanceAboveOwner

    DECLARE_CLASS(UDisMantleFinderState_FindClearDistanceAboveOwner,UDisMantleFinderState_Base,0,DishonoredGame)
};

// DishonoredGame.DisMantleFinderState_ForwardSearches: retail sizeof 192, reflected span 132..192 (2012 PDB sizeof 192)
class UDisMantleFinderState_ForwardSearches : public UDisMantleFinderState_Base
{
public:
    //## BEGIN PROPS DisMantleFinderState_ForwardSearches
    BITFIELD m_bImpactAnimRequired:1;
    BITFIELD m_bFoundBlockerInFront:1;
    BITFIELD m_bFirstBlockerInFront:1;
    FVector m_OwnerCrouchPos;
    FLOAT m_fSearchEndHeight;
    FLOAT m_fSearchDistance;
    FLOAT m_fSearchStepSize;
    FVector m_SearchStart;
    FVector m_SearchDir;
    FLOAT m_fSearchDist;
    FLOAT m_fCurrentHeightOffset;
    //## END PROPS DisMantleFinderState_ForwardSearches

    DECLARE_CLASS(UDisMantleFinderState_ForwardSearches,UDisMantleFinderState_Base,0,DishonoredGame)
};

// DishonoredGame.DisTweaks_PlayerPawn_Mantle: retail sizeof 224, reflected span 140..224 (2012 PDB sizeof 224)
class UDisTweaks_PlayerPawn_Mantle : public UDisTweaksBase
{
public:
    //## BEGIN PROPS DisTweaks_PlayerPawn_Mantle
    FLOAT m_LineCheckStepSize;
    FLOAT m_MantleMinEdgeHeight;
    FLOAT m_MantleMaxEdgeHeight;
    FLOAT m_LowMantleMaxEdgeHeight;
    BITFIELD m_bLowMantleUseStepUp:1;
    BITFIELD m_bAutomaticallyMantleInWater:1;
    FLOAT m_fLowMantleStepUpBlendTime;
    FLOAT m_fLowMantleStepUpDisallowFallTime;
    FName m_LowMantleStepUpAnimNodeName;
    FLOAT m_MediumMantleMaxEdgeHeight;
    FLOAT m_MaxVerticalAngleForEdgeFace;
    FLOAT m_MaxHorizontalAngleForEdgeFace;
    FLOAT m_MaxSlopeAngleForEdgeTop;
    FLOAT m_MantleEdgeSearchDist;
    FLOAT m_fMantleForwardMoveAmount;
    FLOAT m_fFallSpeedForLedgeGrab;
    FLOAT m_fMaxFallSpeedForMantle;
    FLOAT m_fLedgeGrabMantleMinEdgeHeight;
    INT m_FinalVerifyLocationGridSize;
    FLOAT m_fMaxMantleCheckTimePerTick_ms;
    FLOAT m_fMaxMantleCheckTimePerTick_DEBUG_ms;
    //## END PROPS DisTweaks_PlayerPawn_Mantle

    DECLARE_CLASS(UDisTweaks_PlayerPawn_Mantle,UDisTweaksBase,0,DishonoredGame)
    DECLARE_WITHIN(UDisTweaks_PlayerPawn)
};

// DishonoredGame.DishonoredAnimNodeBlendByMantleCrouchRequired: retail sizeof 256, reflected span 256..256 (2012 PDB sizeof 256)
class UDishonoredAnimNodeBlendByMantleCrouchRequired : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS DishonoredAnimNodeBlendByMantleCrouchRequired
    //## END PROPS DishonoredAnimNodeBlendByMantleCrouchRequired

    DECLARE_CLASS(UDishonoredAnimNodeBlendByMantleCrouchRequired,UAnimNodeBlendList,0,DishonoredGame)
};

// DishonoredGame.DishonoredAnimNodeBlendByMantleType: retail sizeof 256, reflected span 256..256 (2012 PDB sizeof 256)
class UDishonoredAnimNodeBlendByMantleType : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS DishonoredAnimNodeBlendByMantleType
    //## END PROPS DishonoredAnimNodeBlendByMantleType

    DECLARE_CLASS(UDishonoredAnimNodeBlendByMantleType,UAnimNodeBlendList,0,DishonoredGame)
};

// DishonoredGame.DishonoredMantleEdgeFinderComponent: retail sizeof 272, reflected span 81..272 (2012 PDB sizeof 272)
class UDishonoredMantleEdgeFinderComponent : public UActorComponent, public IDisTweaksInterface
{
public:
    //## BEGIN PROPS DishonoredMantleEdgeFinderComponent
    class UDisTweaks_PlayerPawn_Mantle* m_pTweaks;
    class UDishonoredNativeStateMachine* m_pMantleFinderFSM;
    FDisMantleSpot m_CurrentMantleSpot;
    BITFIELD m_bHasValidMantleSpot:1;
    BITFIELD m_bMantleCheckSteppingStarted:1;
    BITFIELD m_bMantleCheckSteppingCompleted:1;
    BITFIELD m_bMantleCheckDisabled:1;
    BITFIELD m_bUseAlternateStartPos:1;
    BITFIELD m_Debug_bSingleStepMode:1;
    BITFIELD m_Debug_bSingleStepMode_DoStep:1;
    FVector m_AlternateStartPos_FootPos;
    FVector m_AlternateStartPos_Facing;
    DOUBLE m_Debug_dCheckStartTime;
    FDisRollingAverage m_Debug_AverageCheckWait;
    FDisRollingAverage m_Debug_AverageNumStepsPerTick;
    FLOAT m_Debug_fOverrideMantleCheckTime_ms;
    FLOAT m_Debug_fOverrideMantleStepSize;
    BYTE m_DebugRays[12];  // DISHONORED(layout): retail SDK gap @260: ArrayProperty m_DebugRays (script_classes_2013) the dump did not type
    //## END PROPS DishonoredMantleEdgeFinderComponent

    DECLARE_CLASS(UDishonoredMantleEdgeFinderComponent,UActorComponent,0,DishonoredGame)
};

// DishonoredGame.DishonoredNotify_CrouchMantleTransition: retail sizeof 60, reflected span 60..60 (2012 PDB sizeof 60)
class UDishonoredNotify_CrouchMantleTransition : public UAnimNotify
{
public:
    //## BEGIN PROPS DishonoredNotify_CrouchMantleTransition
    //## END PROPS DishonoredNotify_CrouchMantleTransition

    DECLARE_CLASS(UDishonoredNotify_CrouchMantleTransition,UAnimNotify,0,DishonoredGame)
};

// DishonoredGame.StatePlayerMasterMantle: retail sizeof 192, reflected span 116..192 (2012 PDB sizeof 192)
class UStatePlayerMasterMantle : public UStatePlayerMasterAction
{
public:
    //## BEGIN PROPS StatePlayerMasterMantle
    BITFIELD m_bSavedCollideWorld:1;
    BITFIELD m_bSavedNoEncroachCheck:1;
    BITFIELD m_bIsDoingIntroTransition:1;
    BITFIELD m_bImpactAnimRequired:1;
    BITFIELD m_bCrouchRequired:1;
    BITFIELD m_bSneakRequired:1;
    BITFIELD m_bAllowPlayerEnd:1;
    BITFIELD m_bCancelable:1;
    BITFIELD m_bAllowPlayerCancelActive:1;
    BITFIELD m_bPlayerCancelled:1;
    BITFIELD m_bFaceEdge:1;
    FLOAT m_fTimeoutTimer;
    FLOAT m_fCurrentMantleHeight;
    FLOAT m_fTransitionTime;
    FVector m_MantleIntroStartLocation;
    INT m_MantleIntroStartYaw;
    FVector m_MantleIntroTargetLocation;
    INT m_MantleIntroTargetYaw;
    FLOAT m_fIntroTransitionTime;
    class UAnimNodeBlendList* m_pImpactBlendNode;
    FName m_DebugCurrentAnimName;
    FName m_ImpactBlendNodeName;
    FLOAT m_fMaxTimeInMantleState;
    //## END PROPS StatePlayerMasterMantle

    DECLARE_CLASS(UStatePlayerMasterMantle,UStatePlayerMasterAction,0|CLASS_Config,DishonoredGame)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_DISHONOREDGAME_MANTLE_CLASSES
#endif // !NAMES_ONLY


#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DISHONOREDGAME_MANTLE_NATIVE_DEFS
#define DISHONOREDGAME_MANTLE_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_DISHONOREDGAME_MANTLE \
	UDisMantleFinderState_Base::StaticClass(); \
	UDisMantleFinderState_CheckCanStand::StaticClass(); \
	UDisMantleFinderState_CheckDestinationValid::StaticClass(); \
	UDisMantleFinderState_FindClearDistanceAboveOwner::StaticClass(); \
	UDisMantleFinderState_ForwardSearches::StaticClass(); \
	UDisTweaks_PlayerPawn_Mantle::StaticClass(); \
	UDishonoredAnimNodeBlendByMantleCrouchRequired::StaticClass(); \
	UDishonoredAnimNodeBlendByMantleType::StaticClass(); \
	UDishonoredMantleEdgeFinderComponent::StaticClass(); \
	UDishonoredNotify_CrouchMantleTransition::StaticClass(); \
	UStatePlayerMasterMantle::StaticClass(); \

#endif // DISHONOREDGAME_MANTLE_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(UDisMantleFinderState_Base,DisMantleFinderState_Base,m_pOwningDMEFC)
VERIFY_CLASS_OFFSET_NODIE(UDisMantleFinderState_Base,DisMantleFinderState_Base,m_OwnerInfo)
VERIFY_CLASS_SIZE_NODIE(UDisMantleFinderState_Base)
VERIFY_CLASS_OFFSET_NODIE(UDisMantleFinderState_CheckCanStand,DisMantleFinderState_CheckCanStand,m_SearchStart)
VERIFY_CLASS_OFFSET_NODIE(UDisMantleFinderState_CheckCanStand,DisMantleFinderState_CheckCanStand,m_fCurrentHeightOffset)
VERIFY_CLASS_SIZE_NODIE(UDisMantleFinderState_CheckCanStand)
VERIFY_CLASS_OFFSET_NODIE(UDisMantleFinderState_CheckDestinationValid,DisMantleFinderState_CheckDestinationValid,m_SearchStart)
VERIFY_CLASS_OFFSET_NODIE(UDisMantleFinderState_CheckDestinationValid,DisMantleFinderState_CheckDestinationValid,m_ForwardTraceDelta)
VERIFY_CLASS_SIZE_NODIE(UDisMantleFinderState_CheckDestinationValid)
VERIFY_CLASS_OFFSET_NODIE(UDisMantleFinderState_FindClearDistanceAboveOwner,DisMantleFinderState_FindClearDistanceAboveOwner,m_Debug_fSearchStepSize)
VERIFY_CLASS_SIZE_NODIE(UDisMantleFinderState_FindClearDistanceAboveOwner)
VERIFY_CLASS_OFFSET_NODIE(UDisMantleFinderState_ForwardSearches,DisMantleFinderState_ForwardSearches,m_OwnerCrouchPos)
VERIFY_CLASS_OFFSET_NODIE(UDisMantleFinderState_ForwardSearches,DisMantleFinderState_ForwardSearches,m_fCurrentHeightOffset)
VERIFY_CLASS_SIZE_NODIE(UDisMantleFinderState_ForwardSearches)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_PlayerPawn_Mantle,DisTweaks_PlayerPawn_Mantle,m_LineCheckStepSize)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_PlayerPawn_Mantle,DisTweaks_PlayerPawn_Mantle,m_fMaxMantleCheckTimePerTick_DEBUG_ms)
VERIFY_CLASS_SIZE_NODIE(UDisTweaks_PlayerPawn_Mantle)
VERIFY_CLASS_SIZE_NODIE(UDishonoredAnimNodeBlendByMantleCrouchRequired)
VERIFY_CLASS_SIZE_NODIE(UDishonoredAnimNodeBlendByMantleType)
VERIFY_CLASS_OFFSET_NODIE(UDishonoredMantleEdgeFinderComponent,DishonoredMantleEdgeFinderComponent,m_pTweaks)
VERIFY_CLASS_OFFSET_NODIE(UDishonoredMantleEdgeFinderComponent,DishonoredMantleEdgeFinderComponent,m_Debug_fOverrideMantleStepSize)
VERIFY_CLASS_SIZE_NODIE(UDishonoredMantleEdgeFinderComponent)
VERIFY_CLASS_SIZE_NODIE(UDishonoredNotify_CrouchMantleTransition)
VERIFY_CLASS_OFFSET_NODIE(UStatePlayerMasterMantle,StatePlayerMasterMantle,m_fTimeoutTimer)
VERIFY_CLASS_OFFSET_NODIE(UStatePlayerMasterMantle,StatePlayerMasterMantle,m_fMaxTimeInMantleState)
VERIFY_CLASS_SIZE_NODIE(UStatePlayerMasterMantle)
#endif // VERIFY_CLASS_SIZES

#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
