#pragma once
// DishonoredGame/inc/dishonoredgamecameraclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (46):
//   0x63aa40  public: static class UClass * __cdecl UDishonoredCamera_PlayerControl::StaticClass(void)
//   0x63aa60  public: void __thiscall ADishonoredPlayerCamera::execApplyDebugCam_Native(struct FFrame &, void * const)
//   0x6fcad0  protected: virtual __thiscall UDishonoredCameraInfluence::~UDishonoredCameraInfluence(void)
//   0x6fcb60  protected: virtual __thiscall UDisCamera_StepUpMantleOffset::~UDisCamera_StepUpMantleOffset(void)
//   0x6fcbf0  protected: virtual __thiscall UDishonoredCamera_CrouchMantleOffset::~UDishonoredCamera_CrouchMantleOffset(void)
//   0x6fcc80  protected: virtual __thiscall UDishonoredCamera_DisableArmFollow::~UDishonoredCamera_DisableArmFollow(void)
//   0x6fcd10  protected: virtual __thiscall UDisCamera_DisableArmFollow_Secondary::~UDisCamera_DisableArmFollow_Secondary(void)
//   0x6fcda0  protected: virtual __thiscall UDishonoredCamera_DisableArmOffset::~UDishonoredCamera_DisableArmOffset(void)
//   0x6fce30  protected: virtual __thiscall UDisCamera_DisableArmOffset_Secondary::~UDisCamera_DisableArmOffset_Secondary(void)
//   0x6fcec0  protected: virtual __thiscall UDishonoredCamera_Lean::~UDishonoredCamera_Lean(void)
//   0x701b60  public: static void __cdecl UDishonoredCameraInfluence::InternalConstructor(void *)
//   0x701b80  public: static void __cdecl UDisCamera_StepUpMantleOffset::InternalConstructor(void *)
//   0x701ba0  protected: virtual __thiscall UDishonoredCamera_BumpSmoother::~UDishonoredCamera_BumpSmoother(void)
//   0x701c30  public: static void __cdecl UDishonoredCamera_CrouchMantleOffset::InternalConstructor(void *)
//   0x701c50  public: static void __cdecl UDishonoredCamera_DisableArmFollow::InternalConstructor(void *)
//   0x701c70  public: static void __cdecl UDisCamera_DisableArmFollow_Secondary::InternalConstructor(void *)
//   0x701c90  public: static void __cdecl UDishonoredCamera_DisableArmOffset::InternalConstructor(void *)
//   0x701cb0  public: static void __cdecl UDisCamera_DisableArmOffset_Secondary::InternalConstructor(void *)
//   0x701cd0  public: static void __cdecl UDishonoredCamera_Lean::InternalConstructor(void *)
//   0x70ad70  public: static void __cdecl UDishonoredCamera_BumpSmoother::InternalConstructor(void *)
//   0x7155f0  protected: virtual __thiscall UDisCamera_Rumble::~UDisCamera_Rumble(void)
//   0x715690  public: virtual class UObject * __thiscall ADishonoredPlayerCamera::GetUObjectInterfaceArkSettingsListenerInterface(void)
//   0x7156a0  protected: virtual __thiscall ADishonoredPlayerCamera::~ADishonoredPlayerCamera(void)
//   0x717c70  public: static void __cdecl UDisCamera_Rumble::InternalConstructor(void *)
//   0x717c90  public: static void __cdecl ADishonoredPlayerCamera::InternalConstructor(void *)
//   0x725850  protected: virtual __thiscall UDisCamera_Aim::~UDisCamera_Aim(void)
//   0x7258e0  protected: virtual __thiscall UDisCamera_FollowProjectile::~UDisCamera_FollowProjectile(void)
//   0x725970  protected: virtual __thiscall UDisCamera_Look::~UDisCamera_Look(void)
//   0x725a00  protected: virtual __thiscall UDisCamera_UnpossessDeath::~UDisCamera_UnpossessDeath(void)
//   0x725a90  protected: virtual __thiscall UDishonoredCamera_AnimDriven::~UDishonoredCamera_AnimDriven(void)
//   0x725b20  protected: virtual __thiscall UDishonoredCamera_PhysicalReact::~UDishonoredCamera_PhysicalReact(void)
//   0x725bb0  protected: virtual __thiscall UDishonoredCamera_PlayerControl::~UDishonoredCamera_PlayerControl(void)
//   0x729420  public: static void __cdecl UDisCamera_Aim::InternalConstructor(void *)
//   0x729440  public: static void __cdecl UDisCamera_FollowProjectile::InternalConstructor(void *)
//   0x729460  public: static void __cdecl UDisCamera_Look::InternalConstructor(void *)
//   0x729480  protected: virtual __thiscall UDisCamera_Possess::~UDisCamera_Possess(void)
//   0x729510  public: static void __cdecl UDisCamera_UnpossessDeath::InternalConstructor(void *)
//   0x729530  public: static void __cdecl UDishonoredCamera_AnimDriven::InternalConstructor(void *)
//   0x729550  protected: virtual __thiscall UDishonoredCamera_HitReact::~UDishonoredCamera_HitReact(void)
//   0x7295e0  public: static void __cdecl UDishonoredCamera_PlayerControl::InternalConstructor(void *)
//   0x72c840  public: static void __cdecl UDisCamera_Possess::InternalConstructor(void *)
//   0x72c870  public: static void __cdecl UDishonoredCamera_PhysicalReact::InternalConstructor(void *)
//   0x72c890  public: static void __cdecl UDishonoredCamera_HitReact::InternalConstructor(void *)
//   0x7be4a0  protected: virtual __thiscall ADisDebugNPCCamera::~ADisDebugNPCCamera(void)
//   0x7be7a0  public: static void __cdecl ADisDebugNPCCamera::InternalConstructor(void *)
//   0xba4d50  _dynamic_initializer_for__ADishonoredPlayerCameraexecApplyDebugCam_NativeTemp__
