#pragma once
// DishonoredGame/inc/dishonoredgameclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (396):
//   0x6324c0  protected: virtual __thiscall IDisNoiseMakerInterface::~IDisNoiseMakerInterface(void)
//   0x632500  protected: virtual __thiscall IDisPossessableInterface::~IDisPossessableInterface(void)
//   0x632540  public: void __thiscall ADisFish::execTakeDamage_Native(struct FFrame &, void * const)
//   0x632750  public: static class ADisFish * & __cdecl ADisFish::GetNextFishPtr(class ADisFish * const)
//   0x632760  public: void __thiscall ADisSkeletalBreakable::execTakeDamage_Native(struct FFrame &, void * const)
//   0x632920  public: void __thiscall ACamera::execRemoveCameraLensEffect(struct FFrame &, void * const)
//   0x632980  public: static class UClass * __cdecl ADishonoredUsableObject::StaticClass(void)
//   0x6329a0  protected: virtual __thiscall UDishonoredDamageType::~UDishonoredDamageType(void)
//   0x632a30  public: static class UClass * __cdecl UDisDamageType_Impact::StaticClass(void)
//   0x632a50  protected: virtual __thiscall UDisDamageType_UnpossessSquash::~UDisDamageType_UnpossessSquash(void)
//   0x632ae0  protected: virtual __thiscall UDisDamageType_BlinkKnockdown::~UDisDamageType_BlinkKnockdown(void)
//   0x632b70  protected: virtual __thiscall UDishonoredDamageType_FastHit::~UDishonoredDamageType_FastHit(void)
//   0x632c00  protected: virtual __thiscall UDisDamageType_ImpactHit::~UDisDamageType_ImpactHit(void)
//   0x632c90  protected: virtual __thiscall UDisDamageType_ImpactHit_Adrenaline_Up::~UDisDamageType_ImpactHit_Adrenaline_Up(void)
//   0x632d20  protected: virtual __thiscall UDisDamageType_ImpactHit_Up_Left::~UDisDamageType_ImpactHit_Up_Left(void)
//   0x632db0  protected: virtual __thiscall UDishonoredDamageType_BulletMedium::~UDishonoredDamageType_BulletMedium(void)
//   0x632e40  public: void __thiscall ADishonoredPawn::execDisplayDebug_Native(struct FFrame &, void * const)
//   0x632f60  public: void __thiscall ADishonoredPawn::execTakeDamage_Native(struct FFrame &, void * const)
//   0x633170  public: void __thiscall ADishonoredPawn::execTakeFallingDamage_Native(struct FFrame &, void * const)
//   0x633220  public: void __thiscall ADishonoredPawn::execPlayDying_Native(struct FFrame &, void * const)
//   0x6332f0  public: void __thiscall ADishonoredPawn::execChooseAndTriggerDeathEvent_Native(struct FFrame &, void * const)
//   0x633360  public: void __thiscall ADishonoredPawn::execLanded_Native(struct FFrame &, void * const)
//   0x633400  public: void __thiscall ADishonoredPawn::execOnTeleport_Native(struct FFrame &, void * const)
//   0x633470  public: void __thiscall ADishonoredPawn::execOnSetDisposition(struct FFrame &, void * const)
//   0x6334d0  public: void __thiscall ADishonoredPawn::execOnAddInventoryItem(struct FFrame &, void * const)
//   0x633530  public: void __thiscall ADishonoredPawn::execOnEquipItemType(struct FFrame &, void * const)
//   0x633590  public: void __thiscall ADishonoredPawn::execOnModifyAmmo(struct FFrame &, void * const)
//   0x6335f0  public: void __thiscall ADishonoredPawn::execOnAddAbstractItem(struct FFrame &, void * const)
//   0x633650  public: void __thiscall ADishonoredPawn::execOnRemoveAbstractItem(struct FFrame &, void * const)
//   0x6336b0  public: void __thiscall ADishonoredPawn::execOnGetAbstractItemQuantity(struct FFrame &, void * const)
//   0x633710  public: void __thiscall ADishonoredPawn::execOnModifyElixirCount(struct FFrame &, void * const)
//   0x633770  public: void __thiscall ADishonoredPawn::execCrushedBy_Native(struct FFrame &, void * const)
//   0x6337d0  public: static class UClass * __cdecl ADishonoredPawn::StaticClass(void)
//   0x6337f0  public: void __thiscall UDisGFxMoviePlayerMenuBase::execOnKeyListening(struct FFrame &, void * const)
//   0x633850  public: void __thiscall UDishonoredEngine::execPushDisableSave(struct FFrame &, void * const)
//   0x6338b0  public: void __thiscall UDishonoredEngine::execPopDisableSave(struct FFrame &, void * const)
//   0x633940  public: void __thiscall UDishonoredEngine::execPushIgnoreAutosave(struct FFrame &, void * const)
//   0x6339a0  public: void __thiscall UDishonoredEngine::execPopIgnoreAutosave(struct FFrame &, void * const)
//   0x633a00  public: void __thiscall UDishonoredEngine::execPublishRichPresence(struct FFrame &, void * const)
//   0x633a40  public: void __thiscall ADishonoredGameInfo::execGameEnding(struct FFrame &, void * const)
//   0x633a80  public: void __thiscall ADishonoredGameInfo::execCanStartMatch(struct FFrame &, void * const)
//   0x633ac0  public: void __thiscall ADishonoredGameInfo::execSpawnPlayer(struct FFrame &, void * const)
//   0x633ba0  public: void __thiscall ADishonoredGameInfo::execPreventDeath_Native(struct FFrame &, void * const)
//   0x633c90  public: static class UClass * __cdecl ADishonoredKAsset::StaticClass(void)
//   0x633cb0  public: static class UClass * __cdecl ADisClimbable::StaticClass(void)
//   0x633cd0  public: void __thiscall ADishonoredNote::execNativeNotePostRender(struct FFrame &, void * const)
//   0x633de0  public: void __thiscall UDishonoredViewportClient::execPostRender_Native(struct FFrame &, void * const)
//   0x633e40  public: void __thiscall UDishonoredCheatManager::execLocoDontRotate(struct FFrame &, void * const)
//   0x633e80  public: void __thiscall ADisForbiddenZone::execOnForbiddenZoneOverride(struct FFrame &, void * const)
//   0x633ee0  public: static class UClass * __cdecl ADisTripwire::StaticClass(void)
//   0x633f00  public: void __thiscall ADisWatchTower::execTakeDamage_Native(struct FFrame &, void * const)
//   0x638b40  public: void __thiscall ADishonoredHUD::execDrawHUD_Native(struct FFrame &, void * const)
//   0x63ca20  public: void __thiscall ADisWallOfLight::execTakeDamage_Native(struct FFrame &, void * const)
//   0x63e050  public: void __thiscall UDishonoredEngine::execDis_Load(struct FFrame &, void * const)
//   0x63ef30  public: void __thiscall ADishonoredKActor::execTakeDamage_Native(struct FFrame &, void * const)
//   0x641a10  public: static void __cdecl UDishonoredDamageType::InternalConstructor(void *)
//   0x641a30  public: static void __cdecl UDisDamageType_UnpossessSquash::InternalConstructor(void *)
//   0x641a50  public: static void __cdecl UDisDamageType_BlinkKnockdown::InternalConstructor(void *)
//   0x641a70  public: static void __cdecl UDishonoredDamageType_FastHit::InternalConstructor(void *)
//   0x641a90  public: static void __cdecl UDisDamageType_ImpactHit_Left::InternalConstructor(void *)
//   0x641ab0  public: static void __cdecl UDisDamageType_ImpactHit_Adrenaline::InternalConstructor(void *)
//   0x641ad0  public: static void __cdecl UDisDamageType_ImpactHit_Up_Left::InternalConstructor(void *)
//   0x641af0  public: static void __cdecl UDishonoredDamageType_BulletBlast::InternalConstructor(void *)
//   0x641b10  public: void __thiscall UDishonoredEngine::execUpdateRichPresenceChapter(struct FFrame &, void * const)
//   0x641b80  public: void __thiscall UDishonoredEngine::execUpdateRichPresenceChaos(struct FFrame &, void * const)
//   0x6471e0  public: void __thiscall UDishonoredDebugMenu::execLoadMenu(struct FFrame &, void * const)
//   0x647290  public: void __thiscall UDownloadableContentEnumerator::execInstallDLC(struct FFrame &, void * const)
//   0x64b460  public: static class UClass * __cdecl UDishonoredDamageType::StaticClass(void)
//   0x64c890  public: static class UClass * __cdecl UDisDamageType_BlinkKnockdown::StaticClass(void)
//   0x64c8b0  public: static class UClass * __cdecl UDisDamageType_BlinkPush::StaticClass(void)
//   0x64c8d0  public: static class UClass * __cdecl UDisDamageType_CrushKnockdown::StaticClass(void)
//   0x64c8f0  public: static class UClass * __cdecl UDisDamageType_Sleep_Deferred::StaticClass(void)
//   0x64c910  public: static class UClass * __cdecl UDishonoredDamageType_Electricity::StaticClass(void)
//   0x64c930  public: static class UClass * __cdecl UDishonoredDamageType_Explosion::StaticClass(void)
//   0x64c950  public: static class UClass * __cdecl UDishonoredDamageType_FastHit::StaticClass(void)
//   0x64e010  protected: virtual __thiscall ADisCrusher::~ADisCrusher(void)
//   0x64e120  public: virtual class UObject * __thiscall ADisRiverKrust::GetUObjectInterfaceDisRelationshipInterface(void)
//   0x64e170  protected: virtual __thiscall ADisDefenceTower::~ADisDefenceTower(void)
//   0x64e260  protected: virtual __thiscall UDisDrawVisionComponent::~UDisDrawVisionComponent(void)
//   0x64e2f0  protected: virtual __thiscall UDishonoredWaterVolumeInfo::~UDishonoredWaterVolumeInfo(void)
//   0x64e3c0  protected: virtual __thiscall ADishonoredWaterVolume::~ADishonoredWaterVolume(void)
//   0x64e4e0  public: virtual class UObject * __thiscall ADisFish::GetUObjectInterfaceDisSoulRenderInterface(void)
//   0x64e530  protected: virtual __thiscall ADisExplosion::~ADisExplosion(void)
//   0x64e6a0  protected: virtual __thiscall ADisFish::~ADisFish(void)
//   0x64e780  public: static class UClass * __cdecl UDisDamageType_FishBite::StaticClass(void)
//   0x64e7a0  public: static class UClass * __cdecl UDisDamageType_FastHit_Right::StaticClass(void)
//   0x64e7c0  public: static class UClass * __cdecl UDisDamageType_FastHit_Up::StaticClass(void)
//   0x64e7e0  public: static class UClass * __cdecl UDisDamageType_ImpactHit::StaticClass(void)
//   0x64e800  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline::StaticClass(void)
//   0x64e820  protected: virtual __thiscall ADishonoredDecalActorBase::~ADishonoredDecalActorBase(void)
//   0x64e8b0  protected: virtual __thiscall UDishonoredDecalComponent::~UDishonoredDecalComponent(void)
//   0x64e950  protected: virtual __thiscall ADishonoredEmitterPool::~ADishonoredEmitterPool(void)
//   0x64e9e0  protected: virtual __thiscall ADishonoredKActor::~ADishonoredKActor(void)
//   0x64ea90  public: virtual class UObject * __thiscall ADishonoredKActor::GetUObjectInterfaceDisContactTypeInterface(void)
//   0x64eaa0  public: virtual class UObject * __thiscall ADishonoredKActor::GetUObjectInterfaceDisNoiseMakerInterface(void)
//   0x64eab0  public: virtual class UObject * __thiscall ADishonoredKActor::GetUObjectInterfaceDisHitReboundInterface(void)
//   0x64eac0  public: virtual class UObject * __thiscall ADishonoredKActor::GetUObjectInterfaceDisEngineTweaksInterface(void)
//   0x64ebc0  protected: virtual __thiscall UDishonoredMapInfo::~UDishonoredMapInfo(void)
//   0x64ec70  protected: virtual __thiscall ADishonoredRiver::~ADishonoredRiver(void)
//   0x64ed10  protected: virtual __thiscall UDishonoredCameraInfluenceGroup::~UDishonoredCameraInfluenceGroup(void)
//   0x64edc0  protected: virtual __thiscall ADisProtectionTuneSource::~ADisProtectionTuneSource(void)
//   0x64ee70  protected: virtual __thiscall ADisSoundSource::~ADisSoundSource(void)
//   0x64ef20  protected: virtual __thiscall ADisStaticCollisionActor::~ADisStaticCollisionActor(void)
//   0x650720  public: static void __cdecl ADisCrusher::InternalConstructor(void *)
//   0x650750  public: static void __cdecl ADisDefenceTower::InternalConstructor(void *)
//   0x650770  public: static void __cdecl UDisDrawVisionComponent::InternalConstructor(void *)
//   0x650790  public: static void __cdecl UDishonoredWaterVolumeInfo::InternalConstructor(void *)
//   0x6507b0  public: static void __cdecl ADishonoredWaterVolume::InternalConstructor(void *)
//   0x6507f0  public: static void __cdecl ADisExplosion::InternalConstructor(void *)
//   0x650810  public: static void __cdecl ADisFish::InternalConstructor(void *)
//   0x650830  public: static class UClass * __cdecl UDisDamageType_FastHit_Up_Left::StaticClass(void)
//   0x650850  public: static class UClass * __cdecl UDisDamageType_FastHit_Up_Right::StaticClass(void)
//   0x650870  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Right::StaticClass(void)
//   0x650890  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Up::StaticClass(void)
//   0x6508b0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Right::StaticClass(void)
//   0x6508d0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Up::StaticClass(void)
//   0x6508f0  public: static void __cdecl ADishonoredDecalActorBase::InternalConstructor(void *)
//   0x650920  protected: virtual __thiscall ADishonoredDecalActor::~ADishonoredDecalActor(void)
//   0x6509b0  public: static void __cdecl UDishonoredDecalComponent::InternalConstructor(void *)
//   0x6509d0  public: static void __cdecl ADishonoredEmitterPool::InternalConstructor(void *)
//   0x650a10  public: static void __cdecl UDishonoredMapInfo::InternalConstructor(void *)
//   0x650a30  public: static void __cdecl ADishonoredRiver::InternalConstructor(void *)
//   0x650a60  public: static void __cdecl UDishonoredCameraInfluenceGroup::InternalConstructor(void *)
//   0x650a80  public: static void __cdecl ADisProtectionTuneSource::InternalConstructor(void *)
//   0x650ac0  public: static void __cdecl ADisSoundSource::InternalConstructor(void *)
//   0x650b20  public: static void __cdecl ADisStaticCollisionActor::InternalConstructor(void *)
//   0x652af0  protected: virtual __thiscall UDisGameplayEventsWriter::~UDisGameplayEventsWriter(void)
//   0x652b80  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Up_Right::StaticClass(void)
//   0x652ba0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Up_Left::StaticClass(void)
//   0x652bc0  public: static class UClass * __cdecl UDisDamageType_ImpactHit_Adrenaline_Up_Right::StaticClass(void)
//   0x652be0  public: static class UClass * __cdecl UDishonoredDamageType_BulletBlast::StaticClass(void)
//   0x652c00  public: static void __cdecl ADishonoredDecalActor::InternalConstructor(void *)
//   0x652c30  protected: virtual __thiscall UDisTweaks_Explosion::~UDisTweaks_Explosion(void)
//   0x6542e0  public: static class UClass * __cdecl ADisDefenceTower::StaticClass(void)
//   0x654300  public: static class UClass * __cdecl ADisFish::StaticClass(void)
//   0x654320  public: static void __cdecl UDisGameplayEventsWriter::InternalConstructor(void *)
//   0x654340  protected: virtual __thiscall UDishonoredCallbackSkeletalComponent::~UDishonoredCallbackSkeletalComponent(void)
//   0x6543d0  public: static void __cdecl UDisTweaks_Explosion::InternalConstructor(void *)
//   0x655770  public: static void __cdecl UDishonoredCallbackSkeletalComponent::InternalConstructor(void *)
//   0x6557a0  protected: virtual __thiscall UDishonoredEngine::~UDishonoredEngine(void)
//   0x655890  protected: virtual __thiscall UDishonoredViewportClient::~UDishonoredViewportClient(void)
//   0x656ac0  protected: virtual __thiscall UDishonoredDebugMenu::~UDishonoredDebugMenu(void)
//   0x656b60  public: static void __cdecl UDishonoredEngine::InternalConstructor(void *)
//   0x656c90  public: virtual void __thiscall ADishonoredGameInfo::eventNotifyPathChanged(void)
//   0x656cd0  public: virtual class UObject * __thiscall ADishonoredGameInfo::GetUObjectInterfaceInterface_NavigationHandle(void)
//   0x656cf0  public: static void __cdecl UDishonoredViewportClient::InternalConstructor(void *)
//   0x658220  public: static void __cdecl UDishonoredDebugMenu::InternalConstructor(void *)
//   0x658240  protected: virtual __thiscall ADishonoredGameInfo::~ADishonoredGameInfo(void)
//   0x6583c0  public: static void __cdecl ADishonoredGameInfo::InternalConstructor(void *)
//   0x6631c0  protected: virtual __thiscall UDisParticleSystemComponent::~UDisParticleSystemComponent(void)
//   0x663250  public: static void __cdecl UDisParticleSystemComponent::InternalConstructor(void *)
//   0x66b950  protected: virtual __thiscall IDisConvSpeakerInterface::~IDisConvSpeakerInterface(void)
//   0x66b990  protected: virtual __thiscall IDisInteractableInterface::~IDisInteractableInterface(void)
//   0x66b9d0  protected: virtual __thiscall IDisNoiseListenerInterface::~IDisNoiseListenerInterface(void)
//   0x66ba10  protected: virtual __thiscall IDisRelationshipInterface::~IDisRelationshipInterface(void)
//   0x66ba50  protected: virtual __thiscall IDisSpawnRequesterInterface::~IDisSpawnRequesterInterface(void)
//   0x674de0  protected: virtual __thiscall UDisAlarmBellComponent::~UDisAlarmBellComponent(void)
//   0x674e70  protected: virtual __thiscall ADisSkeletalBreakable::~ADisSkeletalBreakable(void)
//   0x675010  protected: virtual __thiscall ADishonoredUsableObject::~ADishonoredUsableObject(void)
//   0x6752c0  protected: virtual __thiscall ADisDoor::~ADisDoor(void)
//   0x6753d0  protected: virtual __thiscall ADishonoredKAsset::~ADishonoredKAsset(void)
//   0x675480  public: virtual class UObject * __thiscall ADisWatchTower::GetUObjectInterfaceDisBlinderInterface(void)
//   0x675490  public: virtual class UObject * __thiscall ADishonoredKAsset::GetUObjectInterfaceDisEngineTweaksInterface(void)
//   0x675600  public: virtual class UObject * __thiscall ADisGrenade::GetUObjectInterfaceDisInteractableInterface(void)
//   0x675670  protected: virtual __thiscall ADisClimbable::~ADisClimbable(void)
//   0x6757c0  public: virtual class UObject * __thiscall ADisAlarmBell::GetUObjectInterfaceDisSpawnRequesterInterface(void)
//   0x675840  protected: virtual __thiscall ADisAudioLogPlayer::~ADisAudioLogPlayer(void)
//   0x6759d0  protected: virtual __thiscall ADishonoredDynamicUsableObject::~ADishonoredDynamicUsableObject(void)
//   0x675b50  protected: virtual __thiscall ADisWaterSource::~ADisWaterSource(void)
//   0x675c90  public: virtual class UObject * __thiscall ADishonoredUsableObject::GetUObjectInterfaceDisInteractableInterface(void)
//   0x675ca0  public: virtual class UObject * __thiscall ADishonoredUsableObject::GetUObjectInterfaceDisSoulRenderInterface(void)
//   0x675d10  protected: virtual __thiscall ADisProjectileLauncher::~ADisProjectileLauncher(void)
//   0x675df0  protected: virtual __thiscall ADisTrigger::~ADisTrigger(void)
//   0x675e80  public: virtual class UObject * __thiscall ADisRiverKrust::GetUObjectInterfaceDisFireProjectileInterface(void)
//   0x675fa0  protected: virtual __thiscall ADisTriggerAbstractItem::~ADisTriggerAbstractItem(void)
//   0x6760d0  protected: virtual __thiscall ADisTripwire::~ADisTripwire(void)
//   0x676230  protected: virtual __thiscall ADisUpgrade::~ADisUpgrade(void)
//   0x676310  protected: virtual __thiscall ADisWatchTowerPlatform::~ADisWatchTowerPlatform(void)
//   0x677350  public: virtual class UObject * __thiscall ADisWallOfLight::GetUObjectInterfaceDisEngineTweaksInterface(void)
//   0x677a10  public: static void __cdecl UDisAlarmBellComponent::InternalConstructor(void *)
//   0x677a30  public: static void __cdecl ADisSkeletalBreakable::InternalConstructor(void *)
//   0x677a50  public: static void __cdecl ADishonoredUsableObject::InternalConstructor(void *)
//   0x677a70  public: static void __cdecl ADisDoor::InternalConstructor(void *)
//   0x677a90  public: static void __cdecl ADishonoredKActor::InternalConstructor(void *)
//   0x677ab0  public: static void __cdecl ADishonoredKAsset::InternalConstructor(void *)
//   0x677ad0  public: static void __cdecl ADisClimbable::InternalConstructor(void *)
//   0x677af0  public: static void __cdecl ADisAudioLogPlayer::InternalConstructor(void *)
//   0x677b10  public: static void __cdecl ADishonoredDynamicUsableObject::InternalConstructor(void *)
//   0x677b30  public: static void __cdecl ADisWaterSource::InternalConstructor(void *)
//   0x677b50  public: static void __cdecl ADisProjectileLauncher::InternalConstructor(void *)
//   0x677b70  public: static void __cdecl ADisTrigger::InternalConstructor(void *)
//   0x677b90  public: static void __cdecl ADisTriggerAbstractItem::InternalConstructor(void *)
//   0x677bb0  public: static void __cdecl ADisTripwire::InternalConstructor(void *)
//   0x677bd0  public: static void __cdecl ADisUpgrade::InternalConstructor(void *)
//   0x677bf0  public: static void __cdecl ADisWatchTowerPlatform::InternalConstructor(void *)
//   0x679fb0  protected: virtual __thiscall UDisSkeletalBreakStepsInterface::~UDisSkeletalBreakStepsInterface(void)
//   0x67a060  protected: virtual __thiscall UDisTweaks_Trigger::~UDisTweaks_Trigger(void)
//   0x67a6d0  public: static void __cdecl UDisSkeletalBreakStepsInterface::InternalConstructor(void *)
//   0x67a6f0  public: virtual struct FDisSkelBreakStep const * __thiscall UDisUsableObjectBreakSteps::GetStep(int)const
//   0x67a740  protected: virtual __thiscall UDisUsableObjectBreakSteps::~UDisUsableObjectBreakSteps(void)
//   ... 196 more, see resources/docs/symbols/functions.csv
