/*===========================================================================
    DishonoredGameSearchClasses.h - C++ class definitions of the retail (2013) DishonoredGame module.
    Generated by resources/tools/symbols/gen_classes_header.py --sdk from the CodeRed SDK dump
    (retail_sdk_layout.json: member offsets/types/flags, function parameter blocks), native_class_sizes.csv
    (retail sizeof, ClassFlags, Within, config), script_classes_2013.json (enum values, consts, property
    kinds, header groups) and the 2012 types.json (names of native-only members). DO NOT edit by hand:
    regenerate, or carry the change into the generator.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "DishonoredGameNames.h"

#ifndef NAMES_ONLY
#include "DishonoredGameEngineShims.h"
#include "DishonoredGameGlobalStructsClasses.h"
#include "DishonoredGameClasses.h"
#endif

#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_DISHONOREDGAME_SEARCH_ENUMS
#define INCLUDED_DISHONOREDGAME_SEARCH_ENUMS 1


#endif // !INCLUDED_DISHONOREDGAME_SEARCH_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_DISHONOREDGAME_SEARCH_CLASSES
#define INCLUDED_DISHONOREDGAME_SEARCH_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

// DishonoredGame.DisTweaks_AIBehavior_Search.DisSearchFromReasonTweaks: retail SDK size 4 (2012 PDB 4)
struct FDisSearchFromReasonTweaks
{
    BITFIELD m_bShouldRun:1;

    /** Constructors */
    FDisSearchFromReasonTweaks() {}
    FDisSearchFromReasonTweaks(EEventParm)
    {
        appMemzero(this, sizeof(FDisSearchFromReasonTweaks));
    }
};

// DishonoredGame.DisAISubStateInvestigate: retail sizeof 556, reflected span 208..556 (2012 PDB sizeof 556)
class UDisAISubStateInvestigate : public UDisAISubStateWithDesires
{
public:
    //## BEGIN PROPS DisAISubStateInvestigate
    FDisAttentionProxy m_InvestigateTargetProxy;
    FDisAttentionChangeReason m_InvestigateStartReason;
    FVector m_CachedProxyLoc;
    FVector m_InvestigateMoveDest;
    BITFIELD m_bRespondingToAlarm:1;
    BITFIELD m_bRunningInvestigate:1;
    BITFIELD m_bInvestigationFinished:1;
    BITFIELD m_bReachedProxy:1;
    BITFIELD m_bFacingProxy:1;
    BITFIELD m_bWantsStareAtUnreachable:1;
    BYTE m_SearchTransitSpeed;
    BYTE m_InvestigateHookOutput;
    FLOAT m_fReactionDelayTimer;
    FLOAT m_fMaxFunnelRadiusMultiplier;
    FLOAT m_fFocusTimer;
    INT m_PathingFailCount;
    FDisFaceToRequest m_FaceToRequest;
    FDisLocoRequest m_LocoRequest;
    FDisLookAtRequest m_LookAtRequest;
    //## END PROPS DisAISubStateInvestigate

    DECLARE_CLASS(UDisAISubStateInvestigate,UDisAISubStateWithDesires,0,DishonoredGame)
#include "CppText/UDisAISubStateInvestigate.h"
};

// DishonoredGame.DisAISubStateStareAtUnreachable: retail sizeof 396, reflected span 208..396 (2012 PDB sizeof 396)
class UDisAISubStateStareAtUnreachable : public UDisAISubStateWithDesires
{
public:
    //## BEGIN PROPS DisAISubStateStareAtUnreachable
    FDisAttentionProxy m_UnreachableProxy;
    FDisFaceToRequest m_FaceToRequest;
    FDisLookAtRequest m_LookAtRequest;
    //## END PROPS DisAISubStateStareAtUnreachable

    DECLARE_CLASS(UDisAISubStateStareAtUnreachable,UDisAISubStateWithDesires,0,DishonoredGame)
#include "CppText/UDisAISubStateStareAtUnreachable.h"
};

// DishonoredGame.DisAISubStateTrackTarget: retail sizeof 428, reflected span 208..428 (2012 PDB sizeof 428)
class UDisAISubStateTrackTarget : public UDisAISubStateWithDesires
{
public:
    //## BEGIN PROPS DisAISubStateTrackTarget
    FDisAttentionProxy m_TrackTargetProxy;
    FLOAT m_fMaxFunnelRadiusMultiplier;
    FVector m_CurrentSearchDest;
    BITFIELD m_bPostCombat:1;
    BITFIELD m_bCloseEnough:1;
    BITFIELD m_bDebug_PathFailWandering:1;
    FDisLocoRequest m_LocoRequest;
    FDisLookAtRequest m_LookAtRequest;
    //## END PROPS DisAISubStateTrackTarget

    DECLARE_CLASS(UDisAISubStateTrackTarget,UDisAISubStateWithDesires,0,DishonoredGame)
#include "CppText/UDisAISubStateTrackTarget.h"
};

// DishonoredGame.DisBehaviorPatrolSearch: retail sizeof 304, reflected span 284..304 (2012 PDB sizeof 304)
class UDisBehaviorPatrolSearch : public UDisBehaviorPatrol
{
public:
    //## BEGIN PROPS DisBehaviorPatrolSearch
    FDisBodyIntentionRequest m_BodyIntentionRequest;
    //## END PROPS DisBehaviorPatrolSearch

    DECLARE_FUNCTION(execOnEnterCallback_Stand);
    DECLARE_CLASS(UDisBehaviorPatrolSearch,UDisBehaviorPatrol,0,DishonoredGame)
#include "CppText/UDisBehaviorPatrolSearch.h"
};

// DishonoredGame.DisBehaviorSearch: retail sizeof 492, reflected span 176..492 (2012 PDB sizeof 492)
class UDisBehaviorSearch : public UDisBehaviorAttentionBase
{
public:
    //## BEGIN PROPS DisBehaviorSearch
    BITFIELD m_bSearchEnded:1;
    BITFIELD m_bPostCombat:1;
    BITFIELD m_bPostAlarm:1;
    BITFIELD m_bPostTrackTarget:1;
    BITFIELD m_bUseCombatStance:1;
    BITFIELD m_bTargetIsUnreachable:1;
    FName m_NameOfFirstCorpseFound;
    FLOAT m_fSearchAnimCooldownTimer;
    FLOAT m_fCancelInvestigateTimer;
    BYTE m_CurrentInvestigateReason;
    FLOAT m_fStareAtUnreachableTimer;
    FDisLocoRequest m_LocoRequest;
    FDisFaceToRequest m_FaceToRequest;
    FDisLookAtRequest m_LookAtRequest;
    FDisBodyIntentionRequest m_BodyIntentionRequest;
    //## END PROPS DisBehaviorSearch

    DECLARE_FUNCTION(execTickCallback_StareAtUnreachable);
    DECLARE_FUNCTION(execOnEnterCallback_StareAtUnreachable);
    DECLARE_FUNCTION(execOnExitCallback_Stand);
    DECLARE_FUNCTION(execRequestStateExitCallback_Stand);
    DECLARE_FUNCTION(execTickCallback_Stand);
    DECLARE_FUNCTION(execOnEnterCallback_Stand);
    DECLARE_FUNCTION(execOnExitCallback_GenericAction);
    DECLARE_FUNCTION(execRequestStateExitCallback_GenericAction);
    DECLARE_FUNCTION(execOnEnterCallback_GenericAction);
    DECLARE_FUNCTION(execOnExitCallback_TrackTarget);
    DECLARE_FUNCTION(execOnEnterCallback_TrackTarget);
    DECLARE_FUNCTION(execOnExitCallback_Investigate);
    DECLARE_FUNCTION(execRequestStateExitCallback_Investigate);
    DECLARE_FUNCTION(execOnEnterCallback_Investigate);
    DECLARE_CLASS(UDisBehaviorSearch,UDisBehaviorAttentionBase,0,DishonoredGame)
#include "CppText/UDisBehaviorSearch.h"
};

// DishonoredGame.DisBehaviorStationarySearch: retail sizeof 380, reflected span 176..380 (2012 PDB sizeof 380)
class UDisBehaviorStationarySearch : public UDisBehaviorAttentionBase
{
public:
    //## BEGIN PROPS DisBehaviorStationarySearch
    BITFIELD m_bSearchEnded:1;
    BITFIELD m_bPostCorpse:1;
    BITFIELD m_bPostAlarm:1;
    BYTE m_PendingReactionHook;
    FLOAT m_fProxyAttnTimer;
    FDisFaceToRequest m_FaceToRequest;
    FDisLookAtRequest m_LookAtRequest;
    FDisBodyIntentionRequest m_BodyIntentionRequest;
    //## END PROPS DisBehaviorStationarySearch

    DECLARE_CLASS(UDisBehaviorStationarySearch,UDisBehaviorAttentionBase,0,DishonoredGame)
};

// DishonoredGame.DisSeqAct_AIDoSearch: retail sizeof 256, reflected span 248..256 (2012 PDB sizeof 256)
class UDisSeqAct_AIDoSearch : public USequenceAction
{
public:
    //## BEGIN PROPS DisSeqAct_AIDoSearch
    BITFIELD m_bAbortRequested:1;
    class AActor* m_pSearchStart;
    //## END PROPS DisSeqAct_AIDoSearch

    DECLARE_CLASS(UDisSeqAct_AIDoSearch,USequenceAction,0,DishonoredGame)
};

// DishonoredGame.DisTweaks_AIBehavior_Search: retail sizeof 356, reflected span 168..356 (2012 PDB sizeof 356)
class UDisTweaks_AIBehavior_Search : public UDisTweaks_AIBehavior
{
public:
    //## BEGIN PROPS DisTweaks_AIBehavior_Search
    BITFIELD m_bAlwaysSearchWithSwordOut:1;
    FDisSearchFromReasonTweaks m_SearchFromReasonTweaks[21];
    FDisSearchFromReasonTweaks m_SearchFromNoiseTweaks[15];
    FDisRangedFloat m_SearchReactionDelay;
    FLOAT m_fSearchAnimCooldown;
    FLOAT m_fMaxFunnelRadiusMultiplier;
    FLOAT m_fSearchReachedProxyBroadcastRange;
    FLOAT m_fSearchReachedProxyLocEqualsRange;
    FLOAT m_fCancelInvestigateWaitTimeMin;
    FLOAT m_fCancelInvestigateWaitTimeMax;
    FLOAT m_fInvestigateStareAtUnreachableRadius;
    FLOAT m_fInvestigateStareAtUnreachableMaxTime_s;
    //## END PROPS DisTweaks_AIBehavior_Search

    DECLARE_CLASS(UDisTweaks_AIBehavior_Search,UDisTweaks_AIBehavior,0,DishonoredGame)
};

// DishonoredGame.DisTweaks_AIBehavior_StationarySearch: retail sizeof 176, reflected span 168..176 (2012 PDB sizeof 176)
class UDisTweaks_AIBehavior_StationarySearch : public UDisTweaks_AIBehavior
{
public:
    //## BEGIN PROPS DisTweaks_AIBehavior_StationarySearch
    FDisRangedFloat m_ProxyAttnSpan;
    //## END PROPS DisTweaks_AIBehavior_StationarySearch

    DECLARE_CLASS(UDisTweaks_AIBehavior_StationarySearch,UDisTweaks_AIBehavior,0,DishonoredGame)
};

// DishonoredGame.DisTweaks_AISubState_Investigate: retail sizeof 252, reflected span 140..252 (2012 PDB sizeof 232)
class UDisTweaks_AISubState_Investigate : public UDisTweaks_AISubState
{
public:
    //## BEGIN PROPS DisTweaks_AISubState_Investigate
    FLOAT m_fProximityThresholds[21];
    FLOAT m_fFocusAngle;
    FLOAT m_fFocusTimer;
    INT m_PathingFailRetryCount;
    FLOAT m_fPathingFailDistanceScale;
    FLOAT m_fPathingFailPointerSearchRange_Horiz;
    FLOAT m_fPathingFailPointerSearchRange_Up;
    FLOAT m_fPathingFailPointerSearchRange_Down;
    //## END PROPS DisTweaks_AISubState_Investigate

    DECLARE_CLASS(UDisTweaks_AISubState_Investigate,UDisTweaks_AISubState,0,DishonoredGame)
    DECLARE_WITHIN(UDisTweaks_AIBehavior)
};

// DishonoredGame.DisTweaks_AISubState_TrackTarget: retail sizeof 148, reflected span 140..148 (2012 PDB sizeof 148)
class UDisTweaks_AISubState_TrackTarget : public UDisTweaks_AISubState
{
public:
    //## BEGIN PROPS DisTweaks_AISubState_TrackTarget
    FLOAT m_fProximityThreshold;
    FLOAT m_fPathFailWanderRange;
    //## END PROPS DisTweaks_AISubState_TrackTarget

    DECLARE_CLASS(UDisTweaks_AISubState_TrackTarget,UDisTweaks_AISubState,0,DishonoredGame)
    DECLARE_WITHIN(UDisTweaks_AIBehavior)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_DISHONOREDGAME_SEARCH_CLASSES
#endif // !NAMES_ONLY

AUTOGENERATE_FUNCTION(UDisBehaviorPatrolSearch,-1,execOnEnterCallback_Stand);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execTickCallback_StareAtUnreachable);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execOnEnterCallback_StareAtUnreachable);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execOnExitCallback_Stand);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execRequestStateExitCallback_Stand);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execTickCallback_Stand);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execOnEnterCallback_Stand);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execOnExitCallback_GenericAction);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execRequestStateExitCallback_GenericAction);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execOnEnterCallback_GenericAction);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execOnExitCallback_TrackTarget);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execOnEnterCallback_TrackTarget);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execOnExitCallback_Investigate);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execRequestStateExitCallback_Investigate);
AUTOGENERATE_FUNCTION(UDisBehaviorSearch,-1,execOnEnterCallback_Investigate);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DISHONOREDGAME_SEARCH_NATIVE_DEFS
#define DISHONOREDGAME_SEARCH_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_DISHONOREDGAME_SEARCH \
	UDisAISubStateInvestigate::StaticClass(); \
	UDisAISubStateStareAtUnreachable::StaticClass(); \
	UDisAISubStateTrackTarget::StaticClass(); \
	UDisBehaviorPatrolSearch::StaticClass(); \
	GNativeLookupFuncs.Set(FName("DisBehaviorPatrolSearch"), GDishonoredGameUDisBehaviorPatrolSearchNatives); \
	UDisBehaviorSearch::StaticClass(); \
	GNativeLookupFuncs.Set(FName("DisBehaviorSearch"), GDishonoredGameUDisBehaviorSearchNatives); \
	UDisBehaviorStationarySearch::StaticClass(); \
	UDisSeqAct_AIDoSearch::StaticClass(); \
	UDisTweaks_AIBehavior_Search::StaticClass(); \
	UDisTweaks_AIBehavior_StationarySearch::StaticClass(); \
	UDisTweaks_AISubState_Investigate::StaticClass(); \
	UDisTweaks_AISubState_TrackTarget::StaticClass(); \

#endif // DISHONOREDGAME_SEARCH_NATIVE_DEFS

#ifdef NATIVES_ONLY
FNativeFunctionLookup GDishonoredGameUDisBehaviorPatrolSearchNatives[] = 
{ 
	MAP_NATIVE(UDisBehaviorPatrolSearch, execOnEnterCallback_Stand)
	{NULL, NULL}
};

FNativeFunctionLookup GDishonoredGameUDisBehaviorSearchNatives[] = 
{ 
	MAP_NATIVE(UDisBehaviorSearch, execTickCallback_StareAtUnreachable)
	MAP_NATIVE(UDisBehaviorSearch, execOnEnterCallback_StareAtUnreachable)
	MAP_NATIVE(UDisBehaviorSearch, execOnExitCallback_Stand)
	MAP_NATIVE(UDisBehaviorSearch, execRequestStateExitCallback_Stand)
	MAP_NATIVE(UDisBehaviorSearch, execTickCallback_Stand)
	MAP_NATIVE(UDisBehaviorSearch, execOnEnterCallback_Stand)
	MAP_NATIVE(UDisBehaviorSearch, execOnExitCallback_GenericAction)
	MAP_NATIVE(UDisBehaviorSearch, execRequestStateExitCallback_GenericAction)
	MAP_NATIVE(UDisBehaviorSearch, execOnEnterCallback_GenericAction)
	MAP_NATIVE(UDisBehaviorSearch, execOnExitCallback_TrackTarget)
	MAP_NATIVE(UDisBehaviorSearch, execOnEnterCallback_TrackTarget)
	MAP_NATIVE(UDisBehaviorSearch, execOnExitCallback_Investigate)
	MAP_NATIVE(UDisBehaviorSearch, execRequestStateExitCallback_Investigate)
	MAP_NATIVE(UDisBehaviorSearch, execOnEnterCallback_Investigate)
	{NULL, NULL}
};

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(UDisAISubStateInvestigate,DisAISubStateInvestigate,m_InvestigateTargetProxy)
VERIFY_CLASS_OFFSET_NODIE(UDisAISubStateInvestigate,DisAISubStateInvestigate,m_LookAtRequest)
VERIFY_CLASS_SIZE_NODIE(UDisAISubStateInvestigate)
VERIFY_CLASS_OFFSET_NODIE(UDisAISubStateStareAtUnreachable,DisAISubStateStareAtUnreachable,m_UnreachableProxy)
VERIFY_CLASS_OFFSET_NODIE(UDisAISubStateStareAtUnreachable,DisAISubStateStareAtUnreachable,m_LookAtRequest)
VERIFY_CLASS_SIZE_NODIE(UDisAISubStateStareAtUnreachable)
VERIFY_CLASS_OFFSET_NODIE(UDisAISubStateTrackTarget,DisAISubStateTrackTarget,m_TrackTargetProxy)
VERIFY_CLASS_OFFSET_NODIE(UDisAISubStateTrackTarget,DisAISubStateTrackTarget,m_LookAtRequest)
VERIFY_CLASS_SIZE_NODIE(UDisAISubStateTrackTarget)
VERIFY_CLASS_OFFSET_NODIE(UDisBehaviorPatrolSearch,DisBehaviorPatrolSearch,m_BodyIntentionRequest)
VERIFY_CLASS_SIZE_NODIE(UDisBehaviorPatrolSearch)
VERIFY_CLASS_OFFSET_NODIE(UDisBehaviorSearch,DisBehaviorSearch,m_NameOfFirstCorpseFound)
VERIFY_CLASS_OFFSET_NODIE(UDisBehaviorSearch,DisBehaviorSearch,m_BodyIntentionRequest)
VERIFY_CLASS_SIZE_NODIE(UDisBehaviorSearch)
VERIFY_CLASS_OFFSET_NODIE(UDisBehaviorStationarySearch,DisBehaviorStationarySearch,m_PendingReactionHook)
VERIFY_CLASS_OFFSET_NODIE(UDisBehaviorStationarySearch,DisBehaviorStationarySearch,m_BodyIntentionRequest)
VERIFY_CLASS_SIZE_NODIE(UDisBehaviorStationarySearch)
VERIFY_CLASS_OFFSET_NODIE(UDisSeqAct_AIDoSearch,DisSeqAct_AIDoSearch,m_pSearchStart)
VERIFY_CLASS_SIZE_NODIE(UDisSeqAct_AIDoSearch)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_AIBehavior_Search,DisTweaks_AIBehavior_Search,m_SearchFromReasonTweaks)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_AIBehavior_Search,DisTweaks_AIBehavior_Search,m_fInvestigateStareAtUnreachableMaxTime_s)
VERIFY_CLASS_SIZE_NODIE(UDisTweaks_AIBehavior_Search)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_AIBehavior_StationarySearch,DisTweaks_AIBehavior_StationarySearch,m_ProxyAttnSpan)
VERIFY_CLASS_SIZE_NODIE(UDisTweaks_AIBehavior_StationarySearch)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_AISubState_Investigate,DisTweaks_AISubState_Investigate,m_fProximityThresholds)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_AISubState_Investigate,DisTweaks_AISubState_Investigate,m_fPathingFailPointerSearchRange_Down)
VERIFY_CLASS_SIZE_NODIE(UDisTweaks_AISubState_Investigate)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_AISubState_TrackTarget,DisTweaks_AISubState_TrackTarget,m_fProximityThreshold)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_AISubState_TrackTarget,DisTweaks_AISubState_TrackTarget,m_fPathFailWanderRange)
VERIFY_CLASS_SIZE_NODIE(UDisTweaks_AISubState_TrackTarget)
#endif // VERIFY_CLASS_SIZES

#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
