#pragma once
// DishonoredGame/inc/dishonoredgameconversationclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (177):
//   0x6a30a0  protected: virtual __thiscall ADisDialogInanimateDummy::~ADisDialogInanimateDummy(void)
//   0x6a3240  protected: virtual __thiscall ADisSpeakerGroup_PA::~ADisSpeakerGroup_PA(void)
//   0x6a3300  protected: virtual __thiscall ADisDialogOneShot::~ADisDialogOneShot(void)
//   0x6a33a0  protected: virtual __thiscall ADisDialogOneShot_HeartGadget::~ADisDialogOneShot_HeartGadget(void)
//   0x6a3430  protected: virtual __thiscall UDisDialogOneShotRenderingComponent::~UDisDialogOneShotRenderingComponent(void)
//   0x6a34c0  protected: virtual __thiscall UDisSpeakerGroup_PA_RenderingComponent::~UDisSpeakerGroup_PA_RenderingComponent(void)
//   0x6a48b0  public: static void __cdecl ADisDialogInanimateDummy::InternalConstructor(void *)
//   0x6a48d0  public: static void __cdecl ADisSpeakerGroup_PA::InternalConstructor(void *)
//   0x6a4910  public: static void __cdecl ADisDialogOneShot::InternalConstructor(void *)
//   0x6a4940  public: static void __cdecl ADisDialogOneShot_HeartGadget::InternalConstructor(void *)
//   0x6a4970  public: static void __cdecl UDisDialogOneShotRenderingComponent::InternalConstructor(void *)
//   0x6a4990  public: static void __cdecl UDisSpeakerGroup_PA_RenderingComponent::InternalConstructor(void *)
//   0x6b3870  protected: virtual __thiscall UStatePlayerMasterInDialog::~UStatePlayerMasterInDialog(void)
//   0x6b6c50  public: static void __cdecl UStatePlayerMasterInDialog::InternalConstructor(void *)
//   0x8d9b40  protected: virtual __thiscall UDisConv_Node_InGameData::~UDisConv_Node_InGameData(void)
//   0x8db080  public: static void __cdecl UDisConv_Node_InGameData::InternalConstructor(void *)
//   0x8e6890  protected: virtual __thiscall UDisConv_Blurb_InGameData::~UDisConv_Blurb_InGameData(void)
//   0x8e69a0  protected: virtual __thiscall UDisConversation_InGameData_Base::~UDisConversation_InGameData_Base(void)
//   0x8e6a40  protected: virtual __thiscall UDisConversation_InGameData::~UDisConversation_InGameData(void)
//   0x8e9060  public: static void __cdecl UDisConv_Blurb_InGameData::InternalConstructor(void *)
//   0x8e9080  public: __thiscall FDisQueuedFireDialogHookGroup_Outer::FDisQueuedFireDialogHookGroup_Outer(void)
//   0x8e90a0  public: static void __cdecl UDisConversation_InGameData_Base::InternalConstructor(void *)
//   0x8e90c0  public: static void __cdecl UDisConversation_InGameData::InternalConstructor(void *)
//   0x8eb4a0  protected: virtual __thiscall UDisConv_Node::~UDisConv_Node(void)
//   0x8eb550  protected: virtual __thiscall UDisConv_Blurb::~UDisConv_Blurb(void)
//   0x8eb630  protected: virtual __thiscall UDisConv_NonWord::~UDisConv_NonWord(void)
//   0x8eb6c0  protected: virtual __thiscall UDisConv_Branch::~UDisConv_Branch(void)
//   0x8eb750  protected: virtual __thiscall UDisConv_SpeakerSupportsDialogTree::~UDisConv_SpeakerSupportsDialogTree(void)
//   0x8eb7f0  protected: virtual __thiscall UDisConv_Comment::~UDisConv_Comment(void)
//   0x8eb8a0  protected: virtual __thiscall UDisConv_Condition::~UDisConv_Condition(void)
//   0x8eb940  protected: virtual __thiscall UDisConv_TimeLimit::~UDisConv_TimeLimit(void)
//   0x8eb9d0  protected: virtual __thiscall UDisConv_ConversationRef::~UDisConv_ConversationRef(void)
//   0x8eba60  protected: virtual __thiscall UDisConversation::~UDisConversation(void)
//   0x8ebb30  protected: virtual __thiscall UDisTweaks_ConvSettings::~UDisTweaks_ConvSettings(void)
//   0x8ed970  public: static void __cdecl UDisConv_Node::InternalConstructor(void *)
//   0x8ed990  public: static void __cdecl UDisConv_Blurb::InternalConstructor(void *)
//   0x8ed9b0  public: static void __cdecl UDisConv_NonWord::InternalConstructor(void *)
//   0x8ed9d0  public: static void __cdecl UDisConv_Branch::InternalConstructor(void *)
//   0x8ed9f0  public: static void __cdecl UDisConv_SpeakerSupportsDialogTree::InternalConstructor(void *)
//   0x8eda10  public: static void __cdecl UDisConv_Comment::InternalConstructor(void *)
//   0x8eda30  public: static void __cdecl UDisConv_TimeLimit::InternalConstructor(void *)
//   0x8eda50  public: static void __cdecl UDisConv_ConversationRef::InternalConstructor(void *)
//   0x8eda70  public: static void __cdecl UDisConversation::InternalConstructor(void *)
//   0x8edaa0  public: static void __cdecl UDisTweaks_ConvSettings::InternalConstructor(void *)
//   0x8f0a90  public: __thiscall TMultiMap<class USkeletalMesh *, class USkeletalMeshComponent *, class FDefaultSetAllocator>::TMultiMap<class USkeletalMesh *, class USkeletalMeshComponent *, class FDefaultSetAllocator>(void)
//   0x8f1f50  protected: virtual __thiscall UDisConv_PlayerChoice::~UDisConv_PlayerChoice(void)
//   0x8f3d10  public: static void __cdecl UDisConv_PlayerChoice::InternalConstructor(void *)
//   0x8f5900  protected: virtual __thiscall UDisConversationComponent::~UDisConversationComponent(void)
//   0x8f6870  public: static void __cdecl UDisConversationComponent::InternalConstructor(void *)
//   0x8f75c0  protected: virtual __thiscall UDisConvGlobalMan::~UDisConvGlobalMan(void)
//   0x8f8000  public: static void __cdecl UDisConvGlobalMan::InternalConstructor(void *)
//   0x8f9160  protected: virtual __thiscall UDisConv_Hook_Distance_InGameData::~UDisConv_Hook_Distance_InGameData(void)
//   0x8f91f0  protected: virtual __thiscall UDisConv_Hook_PlayerLookAt_InGameData::~UDisConv_Hook_PlayerLookAt_InGameData(void)
//   0x8f9280  protected: virtual __thiscall UDisConv_TimeLimit_InGameData::~UDisConv_TimeLimit_InGameData(void)
//   0x8f9310  protected: virtual __thiscall UDisConv_Soiree_InGameData::~UDisConv_Soiree_InGameData(void)
//   0x8fa980  public: static void __cdecl UDisConv_Hook_PlayerLoiter_InGameData::InternalConstructor(void *)
//   0x8fa9a0  public: static void __cdecl UDisConv_Hook_PlayerLookAt_InGameData::InternalConstructor(void *)
//   0x8fa9c0  public: static void __cdecl UDisConv_TimeLimit_InGameData::InternalConstructor(void *)
//   0x8fa9e0  public: static void __cdecl UDisConv_Soiree_InGameData::InternalConstructor(void *)
//   0x8ffdd0  public: static void __cdecl UDisConv_Hook_Distance_InGameData::InternalConstructor(void *)
//   0x905d60  protected: virtual __thiscall UDisConv_RandomSequentialBranch_InGameData::~UDisConv_RandomSequentialBranch_InGameData(void)
//   0x908170  protected: virtual __thiscall UDisConv_Action::~UDisConv_Action(void)
//   0x908200  protected: virtual __thiscall UDisConv_KismetActivateRemoteEvent::~UDisConv_KismetActivateRemoteEvent(void)
//   0x908290  protected: virtual __thiscall UDisConv_PlayerLookAtSpeaker::~UDisConv_PlayerLookAtSpeaker(void)
//   0x908320  protected: virtual __thiscall UDisConv_PlayerLookAtActor::~UDisConv_PlayerLookAtActor(void)
//   0x9083b0  protected: virtual __thiscall UDisConv_PlayerStopLookAt::~UDisConv_PlayerStopLookAt(void)
//   0x908440  protected: virtual __thiscall UDisConv_SetStoryFlag::~UDisConv_SetStoryFlag(void)
//   0x9084d0  protected: virtual __thiscall UDisConv_TryFallbackTree::~UDisConv_TryFallbackTree(void)
//   0x908560  protected: virtual __thiscall UDisConv_FactionBranch::~UDisConv_FactionBranch(void)
//   0x908600  protected: virtual __thiscall UDisConv_RandomBranch::~UDisConv_RandomBranch(void)
//   0x9086a0  protected: virtual __thiscall UDisConv_SequentialBranch::~UDisConv_SequentialBranch(void)
//   0x908750  protected: virtual __thiscall UDisConv_RandomSequentialBranch::~UDisConv_RandomSequentialBranch(void)
//   0x9087e0  protected: virtual __thiscall UDisConv_SpawnerBranch::~UDisConv_SpawnerBranch(void)
//   0x908880  protected: virtual __thiscall UDisConv_SpeakerHasTweaks::~UDisConv_SpeakerHasTweaks(void)
//   0x908920  protected: virtual __thiscall UDisConv_SpeakerInStoryGroup::~UDisConv_SpeakerInStoryGroup(void)
//   0x9089c0  protected: virtual __thiscall UDisConv_CheckSpeakerRelationship::~UDisConv_CheckSpeakerRelationship(void)
//   0x908a50  protected: virtual __thiscall UDisConv_CheckSpeakerSuspicionLevel::~UDisConv_CheckSpeakerSuspicionLevel(void)
//   0x908ae0  protected: virtual __thiscall UDisConv_CheckStoryFlag::~UDisConv_CheckStoryFlag(void)
//   0x908b70  protected: virtual __thiscall UDisConv_CheckTaskState::~UDisConv_CheckTaskState(void)
//   0x908c00  protected: virtual __thiscall UDisConv_Comparison::~UDisConv_Comparison(void)
//   0x908c90  protected: virtual __thiscall UDisConv_CompareDarknessLevel::~UDisConv_CompareDarknessLevel(void)
//   0x908d20  protected: virtual __thiscall UDisConv_ConversationFired::~UDisConv_ConversationFired(void)
//   0x908db0  protected: virtual __thiscall UDisConv_HadConversation::~UDisConv_HadConversation(void)
//   0x908e40  protected: virtual __thiscall UDisConv_HasAbstractItem::~UDisConv_HasAbstractItem(void)
//   0x908ed0  protected: virtual __thiscall UDisConv_HasInventoryItem::~UDisConv_HasInventoryItem(void)
//   0x908f60  protected: virtual __thiscall UDisConv_HasInventoryItemEquipped::~UDisConv_HasInventoryItemEquipped(void)
//   0x908ff0  protected: virtual __thiscall UDisConv_HasObjective::~UDisConv_HasObjective(void)
//   0x909080  protected: virtual __thiscall UDisConv_IsObjectiveComplete::~UDisConv_IsObjectiveComplete(void)
//   0x909110  protected: virtual __thiscall UDisConv_IsPossessed::~UDisConv_IsPossessed(void)
//   0x9091a0  protected: virtual __thiscall UDisConv_IsSpeakerAvailable::~UDisConv_IsSpeakerAvailable(void)
//   0x909230  protected: virtual __thiscall UDisConv_SeenDialogLabel::~UDisConv_SeenDialogLabel(void)
//   0x9092c0  protected: virtual __thiscall UDisConv_SpeakerCombatStatus::~UDisConv_SpeakerCombatStatus(void)
//   0x909350  protected: virtual __thiscall UDisConv_DialogHook::~UDisConv_DialogHook(void)
//   0x9093f0  protected: virtual __thiscall UDisConv_Hook_Distance::~UDisConv_Hook_Distance(void)
//   0x909480  protected: virtual __thiscall UDisConv_Hook_Distraction::~UDisConv_Hook_Distraction(void)
//   0x909520  protected: virtual __thiscall UDisConv_Hook_Investigate::~UDisConv_Hook_Investigate(void)
//   0x9095b0  protected: virtual __thiscall UDisConv_Hook_KismetActivated::~UDisConv_Hook_KismetActivated(void)
//   0x909670  protected: virtual __thiscall UDisConv_Hook_Notice::~UDisConv_Hook_Notice(void)
//   0x909700  protected: virtual __thiscall UDisConv_Hook_PlayAudioLog::~UDisConv_Hook_PlayAudioLog(void)
//   0x9097c0  protected: virtual __thiscall UDisConv_Hook_PlayerLoiter::~UDisConv_Hook_PlayerLoiter(void)
//   0x909850  protected: virtual __thiscall UDisConv_Hook_PlayerLookAt::~UDisConv_Hook_PlayerLookAt(void)
//   0x9098f0  protected: virtual __thiscall UDisConv_Hook_SplitByTypeAndActor::~UDisConv_Hook_SplitByTypeAndActor(void)
//   0x9099a0  protected: virtual __thiscall UDisConv_Hook_HeartTargeted::~UDisConv_Hook_HeartTargeted(void)
//   0x909a30  protected: virtual __thiscall UDisConv_Hook_NoticeBroken::~UDisConv_Hook_NoticeBroken(void)
//   0x909ac0  protected: virtual __thiscall UDisConv_Hook_WitnessedInteraction::~UDisConv_Hook_WitnessedInteraction(void)
//   0x909b50  protected: virtual __thiscall UDisConv_Hook_SuspicionLevel::~UDisConv_Hook_SuspicionLevel(void)
//   0x909be0  protected: virtual __thiscall UDisConv_Hook_SuspicionDist::~UDisConv_Hook_SuspicionDist(void)
//   0x909c70  protected: virtual __thiscall UDisConv_Hook_WitnessedMagic::~UDisConv_Hook_WitnessedMagic(void)
//   0x909d10  protected: virtual __thiscall UDisConv_Speaker::~UDisConv_Speaker(void)
//   0x909db0  protected: virtual __thiscall UDisConv_InitiatorSpeaker::~UDisConv_InitiatorSpeaker(void)
//   0x909e40  protected: virtual __thiscall UDisConv_MeSpeaker::~UDisConv_MeSpeaker(void)
//   0x909ed0  protected: virtual __thiscall UDisConv_OneShotSpeaker::~UDisConv_OneShotSpeaker(void)
//   0x909f60  public: static void __cdecl UDisConv_RandomSequentialBranch_InGameData::InternalConstructor(void *)
//   0x90a860  protected: virtual __thiscall UDisConv_Soiree::~UDisConv_Soiree(void)
//   0x90a980  public: static void __cdecl UDisConv_Action::InternalConstructor(void *)
//   0x90a9a0  public: static void __cdecl UDisConv_KismetActivateRemoteEvent::InternalConstructor(void *)
//   0x90a9c0  public: static void __cdecl UDisConv_PlayerLookAtSpeaker::InternalConstructor(void *)
//   0x90a9e0  public: static void __cdecl UDisConv_PlayerLookAtActor::InternalConstructor(void *)
//   0x90aa00  public: static void __cdecl UDisConv_PlayerStopLookAt::InternalConstructor(void *)
//   0x90aa20  public: static void __cdecl UDisConv_SetStoryFlag::InternalConstructor(void *)
//   0x90aa40  public: static void __cdecl UDisConv_Soiree::InternalConstructor(void *)
//   0x90aa60  public: static void __cdecl UDisConv_TryFallbackTree::InternalConstructor(void *)
//   0x90aa80  public: static void __cdecl UDisConv_FactionBranch::InternalConstructor(void *)
//   0x90aaa0  public: static void __cdecl UDisConv_RandomBranch::InternalConstructor(void *)
//   0x90aac0  public: static void __cdecl UDisConv_SequentialBranch::InternalConstructor(void *)
//   0x90aae0  public: static void __cdecl UDisConv_RandomSequentialBranch::InternalConstructor(void *)
//   0x90ab00  public: static void __cdecl UDisConv_SpawnerBranch::InternalConstructor(void *)
//   0x90ab20  public: static void __cdecl UDisConv_SpeakerHasTweaks::InternalConstructor(void *)
//   0x90ab40  public: static void __cdecl UDisConv_SpeakerInStoryGroup::InternalConstructor(void *)
//   0x90ab60  public: static void __cdecl UDisConv_Condition::InternalConstructor(void *)
//   0x90ab80  public: static void __cdecl UDisConv_CheckSpeakerRelationship::InternalConstructor(void *)
//   0x90aba0  public: static void __cdecl UDisConv_CheckSpeakerSuspicionLevel::InternalConstructor(void *)
//   0x90abc0  public: static void __cdecl UDisConv_CheckStoryFlag::InternalConstructor(void *)
//   0x90abe0  public: static void __cdecl UDisConv_CheckTaskState::InternalConstructor(void *)
//   0x90ac00  public: static void __cdecl UDisConv_Comparison::InternalConstructor(void *)
//   0x90ac20  public: static void __cdecl UDisConv_CompareDarknessLevel::InternalConstructor(void *)
//   0x90ac40  public: static void __cdecl UDisConv_ConversationFired::InternalConstructor(void *)
//   0x90ac60  public: static void __cdecl UDisConv_HadConversation::InternalConstructor(void *)
//   0x90ac80  public: static void __cdecl UDisConv_HasAbstractItem::InternalConstructor(void *)
//   0x90aca0  public: static void __cdecl UDisConv_HasInventoryItem::InternalConstructor(void *)
//   0x90acc0  public: static void __cdecl UDisConv_HasInventoryItemEquipped::InternalConstructor(void *)
//   0x90ace0  public: static void __cdecl UDisConv_HasObjective::InternalConstructor(void *)
//   0x90ad00  public: static void __cdecl UDisConv_IsObjectiveComplete::InternalConstructor(void *)
//   0x90ad20  public: static void __cdecl UDisConv_IsPossessed::InternalConstructor(void *)
//   0x90ad40  public: static void __cdecl UDisConv_IsSpeakerAvailable::InternalConstructor(void *)
//   0x90ad60  public: static void __cdecl UDisConv_SeenDialogLabel::InternalConstructor(void *)
//   0x90ad80  public: static void __cdecl UDisConv_SpeakerCombatStatus::InternalConstructor(void *)
//   0x90ada0  public: static void __cdecl UDisConv_DialogHook::InternalConstructor(void *)
//   0x90adc0  public: static void __cdecl UDisConv_Hook_Distance::InternalConstructor(void *)
//   0x90ade0  public: static void __cdecl UDisConv_Hook_Distraction::InternalConstructor(void *)
//   0x90ae00  public: static void __cdecl UDisConv_Hook_Investigate::InternalConstructor(void *)
//   0x90ae20  public: static void __cdecl UDisConv_Hook_KismetActivated::InternalConstructor(void *)
//   0x90ae40  public: static void __cdecl UDisConv_Hook_Notice::InternalConstructor(void *)
//   0x90ae60  public: static void __cdecl UDisConv_Hook_PlayAudioLog::InternalConstructor(void *)
//   0x90ae80  public: static void __cdecl UDisConv_Hook_PlayerLoiter::InternalConstructor(void *)
//   0x90aea0  public: static void __cdecl UDisConv_Hook_PlayerLookAt::InternalConstructor(void *)
//   0x90aec0  public: static void __cdecl UDisConv_Hook_SplitByTypeAndActor::InternalConstructor(void *)
//   0x90aee0  public: static void __cdecl UDisConv_Hook_HeartTargeted::InternalConstructor(void *)
//   0x90af00  public: static void __cdecl UDisConv_Hook_NoticeBroken::InternalConstructor(void *)
//   0x90af20  public: static void __cdecl UDisConv_Hook_WitnessedInteraction::InternalConstructor(void *)
//   0x90af40  public: static void __cdecl UDisConv_Hook_SuspicionLevel::InternalConstructor(void *)
//   0x90af60  public: static void __cdecl UDisConv_Hook_SuspicionDist::InternalConstructor(void *)
//   0x90af80  public: static void __cdecl UDisConv_Hook_WitnessedMagic::InternalConstructor(void *)
//   0x90afa0  public: static void __cdecl UDisConv_Speaker::InternalConstructor(void *)
//   0x90afc0  public: static void __cdecl UDisConv_InitiatorSpeaker::InternalConstructor(void *)
//   0x90afe0  public: static void __cdecl UDisConv_MeSpeaker::InternalConstructor(void *)
//   0x90b000  public: static void __cdecl UDisConv_OneShotSpeaker::InternalConstructor(void *)
//   0x90eb00  protected: virtual __thiscall UDisDialogTree::~UDisDialogTree(void)
//   0x90ec80  protected: virtual __thiscall UDisDialogTree_OneShot::~UDisDialogTree_OneShot(void)
//   0x90eda0  protected: virtual __thiscall UDisDialogTree_InGameBind::~UDisDialogTree_InGameBind(void)
//   0x90f040  public: static void __cdecl UDisDialogTree::InternalConstructor(void *)
//   0x90f060  public: static void __cdecl UDisDialogTree_OneShot::InternalConstructor(void *)
//   0x90f080  public: static void __cdecl UDisDialogTree_InGameBind::InternalConstructor(void *)
//   0x914ce0  protected: virtual __thiscall UDisDialogVoiceData::~UDisDialogVoiceData(void)
//   0x914d90  protected: virtual __thiscall UDisDialogVoiceData_OneShot::~UDisDialogVoiceData_OneShot(void)
//   0x914e20  public: static void __cdecl UDisDialogVoiceData::InternalConstructor(void *)
//   0x914e40  public: static void __cdecl UDisDialogVoiceData_OneShot::InternalConstructor(void *)
