/*===========================================================================
    DishonoredGameAlarmClasses.h - C++ class definitions of the retail (2013) DishonoredGame module.
    Generated by resources/tools/symbols/gen_classes_header.py --sdk from the CodeRed SDK dump
    (retail_sdk_layout.json: member offsets/types/flags, function parameter blocks), native_class_sizes.csv
    (retail sizeof, ClassFlags, Within, config), script_classes_2013.json (enum values, consts, property
    kinds, header groups) and the 2012 types.json (names of native-only members). DO NOT edit by hand:
    regenerate, or carry the change into the generator.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "DishonoredGameNames.h"

#ifndef NAMES_ONLY
#include "DishonoredGameEngineShims.h"
#include "DishonoredGameClasses.h"
#endif

#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_DISHONOREDGAME_ALARM_ENUMS
#define INCLUDED_DISHONOREDGAME_ALARM_ENUMS 1


#endif // !INCLUDED_DISHONOREDGAME_ALARM_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_DISHONOREDGAME_ALARM_CLASSES
#define INCLUDED_DISHONOREDGAME_ALARM_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

// DishonoredGame.DisAlarmBell: retail sizeof 928, reflected span 772..920 (2012 PDB sizeof 912)
class ADisAlarmBell : public ADishonoredUsableObject, public IDisSpawnRequesterInterface
{
public:
    //## BEGIN PROPS DisAlarmBell
    class UDisTweaks_AlarmBell* m_pAlarmBellTweaks;
    TArrayNoInit<class ADishonoredSpawner*> m_TriggeredSpawners;
    TArrayNoInit<FName> m_ListenerVolumeTags;
    BITFIELD m_bOverrideMaxSpawnedPawnsPerRing:1;
    BITFIELD m_bAlarmIsRinging:1;
    BITFIELD m_bAlarmIsReady:1;
    BITFIELD m_bUseListenerVolumes:1;
    INT m_MaxSpawnedPawnsPerRingOverride;
    class ADisAlarmBell* m_pNextAlarmBell;
    class UDisBehaviorTriggerAlarm* m_pBestPendingRinger;
    FLOAT m_fBestPendingRingerDistToBellSq;
    FLOAT m_fBestPendingRingerDistToEnemySq;
    class UDisBehaviorTriggerAlarm* m_pPreviousBestPendingRinger;
    FLOAT m_fPreviousBestPendingRingerDistToEnemySq;
    FVector m_PreviousNearestValidNPCPosition;
    FLOAT m_fCooldownTimer;
    FLOAT m_fDelayBeforeAINoise;
    class ADishonoredNPCPawn* m_pNPCOnHisWayToRing;
    INT m_RingerAttentionTag;
    TScriptInterface<class IDisAttentionTargetInterface> m_pRingerEnemyAttentionTarget;
    class UDisAlarmBellComponent* m_pAlarmBellComponent;
    class UParticleSystemComponent* m_pRingingEffect;
    class UMaterialInstance* m_pSignalMaterial;
    INT m_AllowedSpawnsThisRing;
    FDisAudioCellCache m_AudioCellCache;
    TArrayNoInit<class ADishonoredAudioVolume*> m_ListenerVolumes;
    //## END PROPS DisAlarmBell

    DECLARE_CLASS(ADisAlarmBell,ADishonoredUsableObject,0,DishonoredGame)
};

// DishonoredGame.DisBehaviorTriggerAlarm: retail sizeof 312, reflected span 160..312 (2012 PDB sizeof 312)
class UDisBehaviorTriggerAlarm : public UDisAIBehaviorWithDesires
{
public:
    //## BEGIN PROPS DisBehaviorTriggerAlarm
    FLOAT m_fDecisionTimer;
    class ADisAlarmBell* m_pBellToHeadToward;
    BITFIELD m_bHasAcquiredBell:1;
    BITFIELD m_bRingAnimFinished:1;
    BITFIELD m_bForcedRing:1;
    FVector m_Destination;
    BYTE m_RingAlarmStage;
    FDisAttentionProxy m_EnemyProxyInstigator;
    FDisLookAtRequest m_LookAtRequest;
    FDisBodyIntentionRequest m_BodyIntentionRequest;
    //## END PROPS DisBehaviorTriggerAlarm

    DECLARE_FUNCTION(execOnExitCallback_GenericAction);
    DECLARE_FUNCTION(execRequestStateExitCallback_GenericAction);
    DECLARE_FUNCTION(execOnEnterCallback_GenericAction);
    DECLARE_FUNCTION(execOnExitCallback_TakePosition);
    DECLARE_FUNCTION(execRequestStateExitCallback_TakePosition);
    DECLARE_FUNCTION(execRefreshCallback_TakePosition);
    DECLARE_FUNCTION(execOnEnterCallback_TakePosition);
    DECLARE_FUNCTION(execOnExitCallback_Stand);
    DECLARE_FUNCTION(execTickCallback_Stand);
    DECLARE_FUNCTION(execOnEnterCallback_Stand);
    DECLARE_CLASS(UDisBehaviorTriggerAlarm,UDisAIBehaviorWithDesires,0,DishonoredGame)
#include "CppText/UDisBehaviorTriggerAlarm.h"
};

// DishonoredGame.DisNotify_ActivateAlarm: retail sizeof 60, reflected span 60..60 (2012 PDB sizeof 60)
class UDisNotify_ActivateAlarm : public UAnimNotify
{
public:
    //## BEGIN PROPS DisNotify_ActivateAlarm
    //## END PROPS DisNotify_ActivateAlarm

    DECLARE_CLASS(UDisNotify_ActivateAlarm,UAnimNotify,0,DishonoredGame)
};

// DishonoredGame.DisSeqAct_AIRingAlarm: retail sizeof 256, reflected span 248..256 (2012 PDB sizeof 256)
class UDisSeqAct_AIRingAlarm : public USequenceAction
{
public:
    //## BEGIN PROPS DisSeqAct_AIRingAlarm
    class ADishonoredPawn* m_pEnemy;
    class AActor* m_pEnemyLocOverride;
    //## END PROPS DisSeqAct_AIRingAlarm

    DECLARE_CLASS(UDisSeqAct_AIRingAlarm,USequenceAction,0,DishonoredGame)
};

// DishonoredGame.DisSeqAct_AlarmBell: retail sizeof 248, reflected span 248..248 (2012 PDB sizeof 248)
class UDisSeqAct_AlarmBell : public USequenceAction
{
public:
    //## BEGIN PROPS DisSeqAct_AlarmBell
    //## END PROPS DisSeqAct_AlarmBell

    DECLARE_CLASS(UDisSeqAct_AlarmBell,USequenceAction,0,DishonoredGame)
};

// DishonoredGame.DisSeqEvent_AlarmEnded: retail sizeof 272, reflected span 272..272 (2012 PDB sizeof 272)
class UDisSeqEvent_AlarmEnded : public USequenceEvent
{
public:
    //## BEGIN PROPS DisSeqEvent_AlarmEnded
    //## END PROPS DisSeqEvent_AlarmEnded

    DECLARE_CLASS(UDisSeqEvent_AlarmEnded,USequenceEvent,0,DishonoredGame)
};

// DishonoredGame.DisTweaks_AlarmBell: retail sizeof 476, reflected span 400..476 (2012 PDB sizeof 472)
class UDisTweaks_AlarmBell : public UDisTweaks_UsableObject
{
public:
    //## BEGIN PROPS DisTweaks_AlarmBell
    BYTE m_AlarmLoudness;
    FLOAT m_fNPCGoToAlarmCloseness;
    FLOAT m_fNPCUseCloseness;
    FLOAT m_fTimeInBetweenUses;
    FLOAT m_fExtraNPCPositionDist;
    FLOAT m_fSpawnerMinDistFromPlayer;
    INT m_MaxSpawnedPawnsPerRing;
    FLOAT m_fAlarmRingDelayBeforeAINoise;
    class UParticleSystem* m_pRingingEffect;
    FName m_SignalMaterialParamName;
    FColor m_SignalColor_On;
    FColor m_SignalColor_Off;
    FColor m_SignalColor_Ready;
    class UAkEvent* m_pAlarmRingBeginEvent;
    class UAkEvent* m_pAlarmRingEndEvent;
    class UAkEvent* m_pAlarmAllClearEvent;
    class UAkEvent* m_pAlarmReadyBeginEvent;
    class UAkEvent* m_pAlarmReadyEndEvent;
    //## END PROPS DisTweaks_AlarmBell

    DECLARE_CLASS(UDisTweaks_AlarmBell,UDisTweaks_UsableObject,0,DishonoredGame)
};

// DishonoredGame.DisTweaks_Interactable_AlarmBell: retail sizeof 236, reflected span 224..236 (2012 PDB sizeof 236)
class UDisTweaks_Interactable_AlarmBell : public UDisTweaks_InteractableInterface
{
public:
    //## BEGIN PROPS DisTweaks_Interactable_AlarmBell
    FStringNoInit m_UnringAlarmText;
    //## END PROPS DisTweaks_Interactable_AlarmBell

    DECLARE_CLASS(UDisTweaks_Interactable_AlarmBell,UDisTweaks_InteractableInterface,0,DishonoredGame)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_DISHONOREDGAME_ALARM_CLASSES
#endif // !NAMES_ONLY

AUTOGENERATE_FUNCTION(UDisBehaviorTriggerAlarm,-1,execOnExitCallback_GenericAction);
AUTOGENERATE_FUNCTION(UDisBehaviorTriggerAlarm,-1,execRequestStateExitCallback_GenericAction);
AUTOGENERATE_FUNCTION(UDisBehaviorTriggerAlarm,-1,execOnEnterCallback_GenericAction);
AUTOGENERATE_FUNCTION(UDisBehaviorTriggerAlarm,-1,execOnExitCallback_TakePosition);
AUTOGENERATE_FUNCTION(UDisBehaviorTriggerAlarm,-1,execRequestStateExitCallback_TakePosition);
AUTOGENERATE_FUNCTION(UDisBehaviorTriggerAlarm,-1,execRefreshCallback_TakePosition);
AUTOGENERATE_FUNCTION(UDisBehaviorTriggerAlarm,-1,execOnEnterCallback_TakePosition);
AUTOGENERATE_FUNCTION(UDisBehaviorTriggerAlarm,-1,execOnExitCallback_Stand);
AUTOGENERATE_FUNCTION(UDisBehaviorTriggerAlarm,-1,execTickCallback_Stand);
AUTOGENERATE_FUNCTION(UDisBehaviorTriggerAlarm,-1,execOnEnterCallback_Stand);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DISHONOREDGAME_ALARM_NATIVE_DEFS
#define DISHONOREDGAME_ALARM_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_DISHONOREDGAME_ALARM \
	ADisAlarmBell::StaticClass(); \
	UDisBehaviorTriggerAlarm::StaticClass(); \
	GNativeLookupFuncs.Set(FName("DisBehaviorTriggerAlarm"), GDishonoredGameUDisBehaviorTriggerAlarmNatives); \
	UDisNotify_ActivateAlarm::StaticClass(); \
	UDisSeqAct_AIRingAlarm::StaticClass(); \
	UDisSeqAct_AlarmBell::StaticClass(); \
	UDisSeqEvent_AlarmEnded::StaticClass(); \
	UDisTweaks_AlarmBell::StaticClass(); \
	UDisTweaks_Interactable_AlarmBell::StaticClass(); \

#endif // DISHONOREDGAME_ALARM_NATIVE_DEFS

#ifdef NATIVES_ONLY
FNativeFunctionLookup GDishonoredGameUDisBehaviorTriggerAlarmNatives[] = 
{ 
	MAP_NATIVE(UDisBehaviorTriggerAlarm, execOnExitCallback_GenericAction)
	MAP_NATIVE(UDisBehaviorTriggerAlarm, execRequestStateExitCallback_GenericAction)
	MAP_NATIVE(UDisBehaviorTriggerAlarm, execOnEnterCallback_GenericAction)
	MAP_NATIVE(UDisBehaviorTriggerAlarm, execOnExitCallback_TakePosition)
	MAP_NATIVE(UDisBehaviorTriggerAlarm, execRequestStateExitCallback_TakePosition)
	MAP_NATIVE(UDisBehaviorTriggerAlarm, execRefreshCallback_TakePosition)
	MAP_NATIVE(UDisBehaviorTriggerAlarm, execOnEnterCallback_TakePosition)
	MAP_NATIVE(UDisBehaviorTriggerAlarm, execOnExitCallback_Stand)
	MAP_NATIVE(UDisBehaviorTriggerAlarm, execTickCallback_Stand)
	MAP_NATIVE(UDisBehaviorTriggerAlarm, execOnEnterCallback_Stand)
	{NULL, NULL}
};

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(ADisAlarmBell,DisAlarmBell,m_pAlarmBellTweaks)
VERIFY_CLASS_OFFSET_NODIE(ADisAlarmBell,DisAlarmBell,m_ListenerVolumes)
VERIFY_CLASS_SIZE_NODIE(ADisAlarmBell)
VERIFY_CLASS_OFFSET_NODIE(UDisBehaviorTriggerAlarm,DisBehaviorTriggerAlarm,m_fDecisionTimer)
VERIFY_CLASS_OFFSET_NODIE(UDisBehaviorTriggerAlarm,DisBehaviorTriggerAlarm,m_BodyIntentionRequest)
VERIFY_CLASS_SIZE_NODIE(UDisBehaviorTriggerAlarm)
VERIFY_CLASS_SIZE_NODIE(UDisNotify_ActivateAlarm)
VERIFY_CLASS_OFFSET_NODIE(UDisSeqAct_AIRingAlarm,DisSeqAct_AIRingAlarm,m_pEnemy)
VERIFY_CLASS_OFFSET_NODIE(UDisSeqAct_AIRingAlarm,DisSeqAct_AIRingAlarm,m_pEnemyLocOverride)
VERIFY_CLASS_SIZE_NODIE(UDisSeqAct_AIRingAlarm)
VERIFY_CLASS_SIZE_NODIE(UDisSeqAct_AlarmBell)
VERIFY_CLASS_SIZE_NODIE(UDisSeqEvent_AlarmEnded)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_AlarmBell,DisTweaks_AlarmBell,m_AlarmLoudness)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_AlarmBell,DisTweaks_AlarmBell,m_pAlarmReadyEndEvent)
VERIFY_CLASS_SIZE_NODIE(UDisTweaks_AlarmBell)
VERIFY_CLASS_OFFSET_NODIE(UDisTweaks_Interactable_AlarmBell,DisTweaks_Interactable_AlarmBell,m_UnringAlarmText)
VERIFY_CLASS_SIZE_NODIE(UDisTweaks_Interactable_AlarmBell)
#endif // VERIFY_CLASS_SIZES

#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
