#pragma once
// DishonoredGame/inc/dishonoredgameweaponclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (136):
//   0x63c860  public: static class UClass * __cdecl UDishonoredWeapon::StaticClass(void)
//   0x63c880  public: static class UClass * __cdecl UDishonoredWepSword::StaticClass(void)
//   0x63c8a0  public: static class UClass * __cdecl UDisWepMusicBox::StaticClass(void)
//   0x63c8c0  public: static class UClass * __cdecl UDisWepThrowingHand::StaticClass(void)
//   0x63c8e0  public: static class UClass * __cdecl UDisItemContext_NPCAttractSpellCoupDeGrace::StaticClass(void)
//   0x63c900  public: static class UClass * __cdecl UDisItemContext_NPCPush::StaticClass(void)
//   0x63c920  public: static class UClass * __cdecl UDisItemContext_NPCAttractSpell::StaticClass(void)
//   0x63c940  public: static class UClass * __cdecl UDisItemContext_NPCSideStep::StaticClass(void)
//   0x862b00  protected: virtual __thiscall UDisItemContext_MeleeBlock::~UDisItemContext_MeleeBlock(void)
//   0x8649a0  protected: virtual __thiscall UDisItemContext_DropAssassinate::~UDisItemContext_DropAssassinate(void)
//   0x864a40  protected: virtual __thiscall UDisItemContext_MeleeBlockPlayer::~UDisItemContext_MeleeBlockPlayer(void)
//   0x864ae0  protected: virtual __thiscall UDisItemContext_NPCAttractSpell::~UDisItemContext_NPCAttractSpell(void)
//   0x864b80  protected: virtual __thiscall UDisItemContext_NPCWhiskeyFire::~UDisItemContext_NPCWhiskeyFire(void)
//   0x86d0d0  public: static void __cdecl UDisItemContext_DropAssassinate::InternalConstructor(void *)
//   0x86d100  public: static void __cdecl UDisItemContext_MeleeBlock::InternalConstructor(void *)
//   0x86d130  public: static void __cdecl UDisItemContext_MeleeBlockPlayer::InternalConstructor(void *)
//   0x86d160  public: static void __cdecl UDisItemContext_NPCAttractSpell::InternalConstructor(void *)
//   0x86d190  public: static void __cdecl UDisItemContext_NPCWhiskeyFire::InternalConstructor(void *)
//   0x87b230  protected: virtual __thiscall UDisItemContext_MeleeAttack::~UDisItemContext_MeleeAttack(void)
//   0x87b2a0  public: static void __cdecl UDisItemContext_MeleeAttack::InternalConstructor(void *)
//   0x87b300  protected: virtual __thiscall UDisItemContext_MeleeAttackNPCBase::~UDisItemContext_MeleeAttackNPCBase(void)
//   0x87b3b0  protected: virtual __thiscall UDisItemContext_AttackNPCTallboyMelee::~UDisItemContext_AttackNPCTallboyMelee(void)
//   0x87b450  protected: virtual __thiscall UDisItemContext_Minigame::~UDisItemContext_Minigame(void)
//   0x87b4f0  protected: virtual __thiscall UDisItemContext_NPCAttackLeft180::~UDisItemContext_NPCAttackLeft180(void)
//   0x87b590  protected: virtual __thiscall UDisItemContext_NPCAttackRight180::~UDisItemContext_NPCAttackRight180(void)
//   0x87b630  protected: virtual __thiscall UDisItemContext_NPCFatality::~UDisItemContext_NPCFatality(void)
//   0x87b6d0  protected: virtual __thiscall UDisItemContext_NPCAttackRight90::~UDisItemContext_NPCAttackRight90(void)
//   0x87b770  protected: virtual __thiscall UDisItemContext_NPCPush::~UDisItemContext_NPCPush(void)
//   0x87b810  protected: virtual __thiscall UDisItemContext_NPCRatCrushAttempt::~UDisItemContext_NPCRatCrushAttempt(void)
//   0x87b8b0  protected: virtual __thiscall UDisItemContext_NPCRiposte::~UDisItemContext_NPCRiposte(void)
//   0x87b950  protected: virtual __thiscall UDisItemContext_NPCStomp::~UDisItemContext_NPCStomp(void)
//   0x87b9f0  protected: virtual __thiscall UDisItemContext_ParryNPC::~UDisItemContext_ParryNPC(void)
//   0x87ba80  protected: virtual __thiscall UDisItemContext_MeleeAttackPlayer::~UDisItemContext_MeleeAttackPlayer(void)
//   0x87bb20  protected: virtual __thiscall UDisItemContext_Finisher::~UDisItemContext_Finisher(void)
//   0x87bbd0  protected: virtual __thiscall UDisItemContext_Assassinate::~UDisItemContext_Assassinate(void)
//   0x87be10  protected: virtual __thiscall UDisItemContext_Fatality::~UDisItemContext_Fatality(void)
//   0x87beb0  protected: virtual __thiscall UDisItemContext_MultiFatality::~UDisItemContext_MultiFatality(void)
//   0x87d1c0  public: static void __cdecl UDisItemContext_MeleeAttackNPCBase::InternalConstructor(void *)
//   0x87d1f0  public: static void __cdecl UDisItemContext_AttackNPCTallboyMelee::InternalConstructor(void *)
//   0x87d220  public: static void __cdecl UDisItemContext_Minigame::InternalConstructor(void *)
//   0x87d250  public: static void __cdecl UDisItemContext_NPCAttackLeft180::InternalConstructor(void *)
//   0x87d280  public: static void __cdecl UDisItemContext_NPCAttackRight180::InternalConstructor(void *)
//   0x87d2b0  public: static void __cdecl UDisItemContext_NPCFatality::InternalConstructor(void *)
//   0x87d2e0  public: static void __cdecl UDisItemContext_NPCAttackLeft90::InternalConstructor(void *)
//   0x87d310  public: static void __cdecl UDisItemContext_NPCPush::InternalConstructor(void *)
//   0x87d340  public: static void __cdecl UDisItemContext_NPCRatCrushAttempt::InternalConstructor(void *)
//   0x87d370  public: static void __cdecl UDisItemContext_NPCRiposte::InternalConstructor(void *)
//   0x87d3a0  public: static void __cdecl UDisItemContext_NPCStomp::InternalConstructor(void *)
//   0x87d3d0  public: static void __cdecl UDisItemContext_ParryNPC::InternalConstructor(void *)
//   0x87d400  public: static void __cdecl UDisItemContext_MeleeAttackPlayer::InternalConstructor(void *)
//   0x87d430  public: static void __cdecl UDisItemContext_Finisher::InternalConstructor(void *)
//   0x87d460  public: static void __cdecl UDisItemContext_Assassinate::InternalConstructor(void *)
//   0x87d490  public: static void __cdecl UDisItemContext_Fatality::InternalConstructor(void *)
//   0x87d4c0  public: static void __cdecl UDisItemContext_MultiFatality::InternalConstructor(void *)
//   0x87e8f0  protected: virtual __thiscall UDisTweaks_MeleeAttack::~UDisTweaks_MeleeAttack(void)
//   0x87e990  protected: virtual __thiscall UDisTweaks_MeleeAttackPlayer::~UDisTweaks_MeleeAttackPlayer(void)
//   0x87eaa0  protected: virtual __thiscall UDisTweaks_Finisher::~UDisTweaks_Finisher(void)
//   0x87eba0  protected: virtual __thiscall UDisTweaks_Fatality::~UDisTweaks_Fatality(void)
//   0x87ecc0  protected: virtual __thiscall UDisTweaks_Assassinate::~UDisTweaks_Assassinate(void)
//   0x87ede0  protected: virtual __thiscall UDisTweaks_DropAssassinate::~UDisTweaks_DropAssassinate(void)
//   0x87ee90  protected: virtual __thiscall UDisTweaks_MeleeAttackNPCBase::~UDisTweaks_MeleeAttackNPCBase(void)
//   0x87ef50  protected: virtual __thiscall UDisTweaks_Minigame::~UDisTweaks_Minigame(void)
//   0x87efe0  protected: virtual __thiscall UDisTweaks_NPCAttackRight90::~UDisTweaks_NPCAttackRight90(void)
//   0x87f070  protected: virtual __thiscall UDisTweaks_NPCRatCrushAttempt::~UDisTweaks_NPCRatCrushAttempt(void)
//   0x87f100  protected: virtual __thiscall UDisTweaks_NPCRiposte::~UDisTweaks_NPCRiposte(void)
//   0x87f1c0  protected: virtual __thiscall UDisTweaks_ParryNPC::~UDisTweaks_ParryNPC(void)
//   0x87f250  protected: virtual __thiscall UDisTweaks_MultiFatality::~UDisTweaks_MultiFatality(void)
//   0x87f2f0  protected: virtual __thiscall UDisTweaks_MeleeBlockPlayer::~UDisTweaks_MeleeBlockPlayer(void)
//   0x87f3a0  protected: virtual __thiscall UDisTweaks_NPCAttractSpell::~UDisTweaks_NPCAttractSpell(void)
//   0x87f430  protected: virtual __thiscall UDisTweaks_NPCWhiskeyFire::~UDisTweaks_NPCWhiskeyFire(void)
//   0x87f4c0  protected: virtual __thiscall UDisTweaks_UseSpringRazor::~UDisTweaks_UseSpringRazor(void)
//   0x880280  public: static void __cdecl UDisTweaks_MeleeAttack::InternalConstructor(void *)
//   0x8802a0  public: static void __cdecl UDisTweaks_MeleeAttackPlayer::InternalConstructor(void *)
//   0x8802c0  public: static void __cdecl UDisTweaks_Finisher::InternalConstructor(void *)
//   0x8802e0  public: static void __cdecl UDisTweaks_Fatality::InternalConstructor(void *)
//   0x880300  public: static void __cdecl UDisTweaks_Assassinate::InternalConstructor(void *)
//   0x880320  public: static void __cdecl UDisTweaks_DropAssassinate::InternalConstructor(void *)
//   0x880340  public: static void __cdecl UDisTweaks_MeleeAttackNPCBase::InternalConstructor(void *)
//   0x880360  public: static void __cdecl UDisTweaks_Minigame::InternalConstructor(void *)
//   0x880380  public: static void __cdecl UDisTweaks_NPCAttractSpellCoupDeGrace::InternalConstructor(void *)
//   0x8803a0  public: static void __cdecl UDisTweaks_NPCRatCrushAttempt::InternalConstructor(void *)
//   0x8803c0  public: static void __cdecl UDisTweaks_NPCRiposte::InternalConstructor(void *)
//   0x8803e0  public: static void __cdecl UDisTweaks_ParryNPC::InternalConstructor(void *)
//   0x880400  public: static void __cdecl UDisTweaks_MultiFatality::InternalConstructor(void *)
//   0x880420  public: static void __cdecl UDisTweaks_MeleeBlockPlayer::InternalConstructor(void *)
//   0x880440  public: static void __cdecl UDisTweaks_NPCAttractSpell::InternalConstructor(void *)
//   0x880460  public: static void __cdecl UDisTweaks_NPCWhiskeyFire::InternalConstructor(void *)
//   0x880480  public: static void __cdecl UDisTweaks_UseSpringRazor::InternalConstructor(void *)
//   0x888790  protected: virtual __thiscall UDisItemContext_NPCBackStep::~UDisItemContext_NPCBackStep(void)
//   0x888820  protected: virtual __thiscall UDisItemContext_NPCSideStep::~UDisItemContext_NPCSideStep(void)
//   0x8888b0  protected: virtual __thiscall UDisItemContext_NPCTaunt::~UDisItemContext_NPCTaunt(void)
//   0x888940  protected: virtual __thiscall UDisItemContext_NPCTune::~UDisItemContext_NPCTune(void)
//   0x888a30  protected: virtual __thiscall UDisItemContext_NPCTune_Combat::~UDisItemContext_NPCTune_Combat(void)
//   0x888ac0  protected: virtual __thiscall UDisItemContext_NPCTune_Protection::~UDisItemContext_NPCTune_Protection(void)
//   0x88bb90  public: static void __cdecl UDisItemContext_NPCBackStep::InternalConstructor(void *)
//   0x88bbc0  public: static void __cdecl UDisItemContext_NPCSideStep::InternalConstructor(void *)
//   0x88bbf0  public: static void __cdecl UDisItemContext_NPCTaunt::InternalConstructor(void *)
//   0x88bc20  public: static void __cdecl UDisItemContext_NPCTune::InternalConstructor(void *)
//   0x88bc50  public: static void __cdecl UDisItemContext_NPCTune_Combat::InternalConstructor(void *)
//   0x88bc70  public: static void __cdecl UDisItemContext_NPCTune_Protection::InternalConstructor(void *)
//   0x894c90  protected: virtual __thiscall UDisItemContext_NPCTeleportSpell::~UDisItemContext_NPCTeleportSpell(void)
//   0x896ea0  protected: virtual __thiscall UDisItemContext_WeeperGrab::~UDisItemContext_WeeperGrab(void)
//   0x896f40  protected: virtual __thiscall UDisItemContext_NPCAttackUnder::~UDisItemContext_NPCAttackUnder(void)
//   0x896fe0  protected: virtual __thiscall UDisItemContext_NPCAttractSpellCoupDeGrace::~UDisItemContext_NPCAttractSpellCoupDeGrace(void)
//   0x897070  public: static void __cdecl UDisItemContext_NPCTeleportSpell::InternalConstructor(void *)
//   0x898d10  public: static void __cdecl UDisItemContext_WeeperGrab::InternalConstructor(void *)
//   0x898d40  public: static void __cdecl UDisItemContext_NPCAttackUnder::InternalConstructor(void *)
//   0x898d70  public: static void __cdecl UDisItemContext_NPCAttractSpellCoupDeGrace::InternalConstructor(void *)
//   0x89acf0  protected: virtual __thiscall UDisTweaks_WepSwordOfAssassin::~UDisTweaks_WepSwordOfAssassin(void)
//   0x89ad80  protected: virtual __thiscall UDisTweaks_WeeperGrab::~UDisTweaks_WeeperGrab(void)
//   0x89ae10  protected: virtual __thiscall UDisTweaks_NPCBackStep::~UDisTweaks_NPCBackStep(void)
//   0x89aea0  protected: virtual __thiscall UDisTweaks_NPCTaunt::~UDisTweaks_NPCTaunt(void)
//   0x89af30  protected: virtual __thiscall UDisTweaks_NPCTeleportSpell::~UDisTweaks_NPCTeleportSpell(void)
//   0x89afe0  protected: virtual __thiscall UDisTweaks_NPCTune_Combat::~UDisTweaks_NPCTune_Combat(void)
//   0x89bf20  protected: virtual __thiscall UDisTweaks_WepMusicBox::~UDisTweaks_WepMusicBox(void)
//   0x89c6c0  public: static void __cdecl UDisTweaks_WepSwordOfAssassin::InternalConstructor(void *)
//   0x89c6e0  public: static void __cdecl UDisTweaks_WeeperGrab::InternalConstructor(void *)
//   0x89c700  public: static void __cdecl UDisTweaks_NPCBackStep::InternalConstructor(void *)
//   0x89c720  public: static void __cdecl UDisTweaks_NPCTaunt::InternalConstructor(void *)
//   0x89c740  public: static void __cdecl UDisTweaks_NPCTeleportSpell::InternalConstructor(void *)
//   0x89c760  public: static void __cdecl UDisTweaks_NPCTune_Combat::InternalConstructor(void *)
//   0x89d120  public: static void __cdecl UDisTweaks_WepThrowingHand::InternalConstructor(void *)
//   0x8ab000  protected: virtual __thiscall UDishonoredWeapon::~UDishonoredWeapon(void)
//   0x8ab0d0  protected: virtual __thiscall UDisWepMelee::~UDisWepMelee(void)
//   0x8ab1d0  protected: virtual __thiscall UDishonoredWepSword::~UDishonoredWepSword(void)
//   0x8ab2a0  protected: virtual __thiscall UDisWepMusicAmp::~UDisWepMusicAmp(void)
//   0x8ab380  protected: virtual __thiscall UDisWepMusicBox::~UDisWepMusicBox(void)
//   0x8ab450  protected: virtual __thiscall UDisWepThrowingHand::~UDisWepThrowingHand(void)
//   0x8ab520  protected: virtual __thiscall UDisWepWhiskeyBottle::~UDisWepWhiskeyBottle(void)
//   0x8ac540  public: static void __cdecl UDishonoredWeapon::InternalConstructor(void *)
//   0x8ac590  public: static void __cdecl UDisWepMelee::InternalConstructor(void *)
//   0x8ac5e0  public: static void __cdecl UDishonoredWepSword::InternalConstructor(void *)
//   0x8ac630  public: static void __cdecl UDisWepMusicAmp::InternalConstructor(void *)
//   0x8ac680  public: static void __cdecl UDisWepMusicBox::InternalConstructor(void *)
//   0x8ac6d0  public: static void __cdecl UDisWepThrowingHand::InternalConstructor(void *)
//   0x8ac720  public: static void __cdecl UDisWepWhiskeyBottle::InternalConstructor(void *)
