#pragma once
// DishonoredGame/inc/dishonoredgamenpcdeathclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (34):
//   0x6aa060  public: virtual class UObject * __thiscall ADisMovableLimb::GetUObjectInterfaceDisAttentionTargetInterface(void)
//   0x6aa070  public: virtual class UObject * __thiscall ADisMovableLimb::GetUObjectInterfaceDisCorpseInterface(void)
//   0x6aa080  public: virtual class UObject * __thiscall ADisMovableLimb::GetUObjectInterfaceDisRelationshipInterface(void)
//   0x6aa090  public: virtual class UObject * __thiscall ADisMovableLimb::GetUObjectInterfaceDisSoulRenderInterface(void)
//   0x6aa0a0  public: virtual class UObject * __thiscall ADisMovableLimb::GetUObjectInterfaceDisStealthVolumeUserInterface(void)
//   0x6aa0b0  public: virtual class UObject * __thiscall ADisMovableLimb::GetUObjectInterfaceDisVisSettingsUserInterface(void)
//   0x6aa190  protected: virtual __thiscall ADisMovableLimb::~ADisMovableLimb(void)
//   0x6ac6e0  public: static void __cdecl ADisMovableLimb::InternalConstructor(void *)
//   0x6b48b0  protected: virtual __thiscall UStateNPCMasterDead::~UStateNPCMasterDead(void)
//   0x6b4940  protected: virtual __thiscall UStateNPCMasterDead_Limp::~UStateNPCMasterDead_Limp(void)
//   0x6b4a00  protected: virtual __thiscall UStateNPCMasterDead_Electrocuted::~UStateNPCMasterDead_Electrocuted(void)
//   0x6b93f0  public: virtual class UObject * __thiscall UStateSharedActionBase_PlayerOnly::GetUObjectInterfaceDisAnimStateFiringInterface(void)
//   0x6b9420  protected: virtual __thiscall UStatePlayerCarryCorpseIdle::~UStatePlayerCarryCorpseIdle(void)
//   0x6b94c0  public: static void __cdecl UStateNPCMasterDead::InternalConstructor(void *)
//   0x6b94e0  public: static void __cdecl UStateNPCMasterDead_Limp::InternalConstructor(void *)
//   0x6b9510  public: static void __cdecl UStateNPCMasterDead_Electrocuted::InternalConstructor(void *)
//   0x6bf100  public: static void __cdecl UStatePlayerCarryCorpseIdle::InternalConstructor(void *)
//   0x6c2290  protected: virtual __thiscall UStateNPCMasterDead_BeingCarried::~UStateNPCMasterDead_BeingCarried(void)
//   0x6c44d0  public: static void __cdecl UStateNPCMasterDead_BeingCarried::InternalConstructor(void *)
//   0x6c9570  protected: virtual __thiscall UDisTweaks_StateNPCMasterDead_BeingCarried::~UDisTweaks_StateNPCMasterDead_BeingCarried(void)
//   0x6c9600  protected: virtual __thiscall UDisTweaks_StatePlayerCarryCorpseIdle::~UDisTweaks_StatePlayerCarryCorpseIdle(void)
//   0x6ca6b0  public: static void __cdecl UDisTweaks_StateNPCMasterDead_BeingCarried::InternalConstructor(void *)
//   0x6ca6d0  public: static void __cdecl UDisTweaks_StatePlayerCarryCorpseIdle::InternalConstructor(void *)
//   0x6d47e0  protected: virtual __thiscall UDisNotify_AcquireCorpse::~UDisNotify_AcquireCorpse(void)
//   0x6d4870  protected: virtual __thiscall UDisNotify_EndLiftCorpse::~UDisNotify_EndLiftCorpse(void)
//   0x6d8e60  public: static void __cdecl UDisNotify_AcquireCorpse::InternalConstructor(void *)
//   0x6d8e80  public: static void __cdecl UDisNotify_EndLiftCorpse::InternalConstructor(void *)
//   0x7e4fe0  protected: virtual __thiscall UDisSeqAct_SetIgnoreDeath::~UDisSeqAct_SetIgnoreDeath(void)
//   0x7e5080  public: virtual void __thiscall UDisSeqEvent_Assassinated::UpdateObject(void)
//   0x7e51d0  protected: virtual __thiscall UDisSeqEvent_Assassinated::~UDisSeqEvent_Assassinated(void)
//   0x7e66f0  public: static void __cdecl UDisSeqAct_SetIgnoreDeath::InternalConstructor(void *)
//   0x7e6710  public: static void __cdecl UDisSeqEvent_Assassinated::InternalConstructor(void *)
//   0x909f80  protected: virtual __thiscall UDisConv_Hook_DeathMode::~UDisConv_Hook_DeathMode(void)
//   0x90b020  public: static void __cdecl UDisConv_Hook_DeathMode::InternalConstructor(void *)
