/*===========================================================================
    DishonoredGameDLC07ItemClasses.h - C++ class definitions of the retail (2013) DishonoredGame module.
    Generated by resources/tools/symbols/gen_classes_header.py --sdk from the CodeRed SDK dump
    (retail_sdk_layout.json: member offsets/types/flags, function parameter blocks), native_class_sizes.csv
    (retail sizeof, ClassFlags, Within, config), script_classes_2013.json (enum values, consts, property
    kinds, header groups) and the 2012 types.json (names of native-only members). DO NOT edit by hand:
    regenerate, or carry the change into the generator.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "DishonoredGameNames.h"

#ifndef NAMES_ONLY
#include "DishonoredGameEngineShims.h"
#include "DishonoredGameItemClasses.h"
#endif

#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_DISHONOREDGAME_DLC07ITEM_ENUMS
#define INCLUDED_DISHONOREDGAME_DLC07ITEM_ENUMS 1


#endif // !INCLUDED_DISHONOREDGAME_DLC07ITEM_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_DISHONOREDGAME_DLC07ITEM_CLASSES
#define INCLUDED_DISHONOREDGAME_DLC07ITEM_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

// DishonoredGame.DisDLC07WhaleBoneCharmCracked: retail sizeof 976, reflected span 952..964 (new in 2013)
class ADisDLC07WhaleBoneCharmCracked : public ADisPickup_Base
{
public:
    //## BEGIN PROPS DisDLC07WhaleBoneCharmCracked
    class UDisDLC07Tweaks_WhaleBoneCharmCracked* m_pTweaks;
    FPointer m_pActivatedWhaleBoneCharmCrackedLevel;
    INT m_Effect;
    //## END PROPS DisDLC07WhaleBoneCharmCracked

    DECLARE_FUNCTION(execOnSetBoneCharmCrackedEffect);
    DECLARE_CLASS(ADisDLC07WhaleBoneCharmCracked,ADisPickup_Base,0,DishonoredGame)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_DISHONOREDGAME_DLC07ITEM_CLASSES
#endif // !NAMES_ONLY

AUTOGENERATE_FUNCTION(ADisDLC07WhaleBoneCharmCracked,-1,execOnSetBoneCharmCrackedEffect);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DISHONOREDGAME_DLC07ITEM_NATIVE_DEFS
#define DISHONOREDGAME_DLC07ITEM_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_DISHONOREDGAME_DLC07ITEM \
	ADisDLC07WhaleBoneCharmCracked::StaticClass(); \
	GNativeLookupFuncs.Set(FName("DisDLC07WhaleBoneCharmCracked"), GDishonoredGameADisDLC07WhaleBoneCharmCrackedNatives); \

#endif // DISHONOREDGAME_DLC07ITEM_NATIVE_DEFS

#ifdef NATIVES_ONLY
FNativeFunctionLookup GDishonoredGameADisDLC07WhaleBoneCharmCrackedNatives[] = 
{ 
	MAP_NATIVE(ADisDLC07WhaleBoneCharmCracked, execOnSetBoneCharmCrackedEffect)
	{NULL, NULL}
};

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(ADisDLC07WhaleBoneCharmCracked,DisDLC07WhaleBoneCharmCracked,m_pTweaks)
VERIFY_CLASS_OFFSET_NODIE(ADisDLC07WhaleBoneCharmCracked,DisDLC07WhaleBoneCharmCracked,m_Effect)
VERIFY_CLASS_SIZE_NODIE(ADisDLC07WhaleBoneCharmCracked)
#endif // VERIFY_CLASS_SIZES

#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
