/*===========================================================================
    DishonoredGameDLC07SkeletalMovableClasses.h - C++ class definitions of the retail (2013) DishonoredGame module.
    Generated by resources/tools/symbols/gen_classes_header.py --sdk from the CodeRed SDK dump
    (retail_sdk_layout.json: member offsets/types/flags, function parameter blocks), native_class_sizes.csv
    (retail sizeof, ClassFlags, Within, config), script_classes_2013.json (enum values, consts, property
    kinds, header groups) and the 2012 types.json (names of native-only members). DO NOT edit by hand:
    regenerate, or carry the change into the generator.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "DishonoredGameNames.h"

#ifndef NAMES_ONLY
#include "DishonoredGameEngineShims.h"
#include "DishonoredGameClasses.h"
#include "DishonoredGameDLC07PullClasses.h"
#include "DishonoredGameItemClasses.h"
#endif

#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_DISHONOREDGAME_DLC07SKELETALMOVABLE_ENUMS
#define INCLUDED_DISHONOREDGAME_DLC07SKELETALMOVABLE_ENUMS 1


#endif // !INCLUDED_DISHONOREDGAME_DLC07SKELETALMOVABLE_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_DISHONOREDGAME_DLC07SKELETALMOVABLE_CLASSES
#define INCLUDED_DISHONOREDGAME_DLC07SKELETALMOVABLE_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

// DishonoredGame.DisDLC07SkeletalMovable: retail sizeof 720, reflected span 672..708 (new in 2013)
class ADisDLC07SkeletalMovable : public ADishonoredKAsset, public IDisInteractableInterface, public IDisMovableInterface, public IDisDLC07PullTargetInterface, public IDisSoulRenderInterface
{
public:
    //## BEGIN PROPS DisDLC07SkeletalMovable
    BITFIELD m_bPullDisabled:1;
    class UDisMovableComponent* m_pMovableComponent;
    FVector m_MovableOffset;
    //## END PROPS DisDLC07SkeletalMovable

    DECLARE_CLASS(ADisDLC07SkeletalMovable,ADishonoredKAsset,0,DishonoredGame)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_DISHONOREDGAME_DLC07SKELETALMOVABLE_CLASSES
#endif // !NAMES_ONLY


#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DISHONOREDGAME_DLC07SKELETALMOVABLE_NATIVE_DEFS
#define DISHONOREDGAME_DLC07SKELETALMOVABLE_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_DISHONOREDGAME_DLC07SKELETALMOVABLE \
	ADisDLC07SkeletalMovable::StaticClass(); \

#endif // DISHONOREDGAME_DLC07SKELETALMOVABLE_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(ADisDLC07SkeletalMovable,DisDLC07SkeletalMovable,m_pMovableComponent)
VERIFY_CLASS_OFFSET_NODIE(ADisDLC07SkeletalMovable,DisDLC07SkeletalMovable,m_MovableOffset)
VERIFY_CLASS_SIZE_NODIE(ADisDLC07SkeletalMovable)
#endif // VERIFY_CLASS_SIZES

#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
