#pragma once
// DishonoredGame/inc/dishonoredgametweaksclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (201):
//   0x632420  public: static class UClass * __cdecl UDisTweaksBase::StaticClass(void)
//   0x632440  public: void __thiscall UDisTweaks_Faction::execOnSetDisposition(struct FFrame &, void * const)
//   0x6324a0  protected: virtual __thiscall IDisTweaksInterface::~IDisTweaksInterface(void)
//   0x641600  public: class UDisTweaks_PlayerPawn const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_PlayerPawn>(void)const
//   0x641710  public: class UDisTweaks_ActivePowerBase const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_ActivePowerBase>(void)const
//   0x641740  public: class UDisTweaksBase const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaksBase>(void)const
//   0x641810  public: class UDisTweaks_NPCPawn const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_NPCPawn>(void)const
//   0x641930  public: class UDisTweaks_AIBrain const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_AIBrain>(void)const
//   0x6419b0  public: unsigned int __thiscall IDisTweaksInterface::IsTweaksValid(void)const
//   0x6526a0  protected: virtual __thiscall UDisTweaksBase::~UDisTweaksBase(void)
//   0x652760  protected: virtual __thiscall UDisTweaks_DefenceTower::~UDisTweaks_DefenceTower(void)
//   0x652800  protected: virtual __thiscall UDisTweaks_DetectionEye::~UDisTweaks_DetectionEye(void)
//   0x6528a0  protected: virtual __thiscall UDisTweaks_Fish::~UDisTweaks_Fish(void)
//   0x652940  protected: virtual __thiscall UDisTweaks_PlayerPawn_Visibility::~UDisTweaks_PlayerPawn_Visibility(void)
//   0x6529d0  protected: virtual __thiscall UDisTweaks_SoundSource::~UDisTweaks_SoundSource(void)
//   0x652a60  protected: virtual __thiscall UDisTweaks_TuneSource_Protection::~UDisTweaks_TuneSource_Protection(void)
//   0x654230  public: static void __cdecl UDisTweaks_DefenceTower::InternalConstructor(void *)
//   0x654250  public: static void __cdecl UDisTweaks_DetectionEye::InternalConstructor(void *)
//   0x654270  public: static void __cdecl UDisTweaks_Fish::InternalConstructor(void *)
//   0x6542a0  public: static void __cdecl UDisTweaks_SoundSource::InternalConstructor(void *)
//   0x6542c0  public: static void __cdecl UDisTweaks_TuneSource_Protection::InternalConstructor(void *)
//   0x655690  protected: virtual __thiscall UDisTweaks_StaticBreakable::~UDisTweaks_StaticBreakable(void)
//   0x656aa0  public: static void __cdecl UDisTweaks_StaticBreakable::InternalConstructor(void *)
//   0x6581f0  public: class UDisTweaks_DefenceTower const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_DefenceTower>(void)const
//   0x66f080  public: class UDisTweaks_GFxMoviePlayerHUD const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_GFxMoviePlayerHUD>(void)const
//   0x679280  protected: virtual __thiscall UDisTweaks_InteractableInterface::~UDisTweaks_InteractableInterface(void)
//   0x679370  protected: virtual __thiscall UDisTweaks_Interactable_PickupBase::~UDisTweaks_Interactable_PickupBase(void)
//   0x679410  protected: virtual __thiscall UDisTweaks_PickupBase::~UDisTweaks_PickupBase(void)
//   0x6794b0  protected: virtual __thiscall UDisTweaks_AbstractItemPickup::~UDisTweaks_AbstractItemPickup(void)
//   0x679550  protected: virtual __thiscall UDisTweaks_AbstractItemPickupNote::~UDisTweaks_AbstractItemPickupNote(void)
//   0x679600  protected: virtual __thiscall UDisTweaks_WhaleBoneCharm::~UDisTweaks_WhaleBoneCharm(void)
//   0x679690  protected: virtual __thiscall UDisTweaks_Key::~UDisTweaks_Key(void)
//   0x679740  protected: virtual __thiscall UDisTweaks_StatPickup::~UDisTweaks_StatPickup(void)
//   0x6797f0  protected: virtual __thiscall UDisTweaks_Climbable::~UDisTweaks_Climbable(void)
//   0x679890  protected: virtual __thiscall UDisTweaks_SkeletalBreakable::~UDisTweaks_SkeletalBreakable(void)
//   0x679940  protected: virtual __thiscall UDisTweaks_ProjectileLauncher::~UDisTweaks_ProjectileLauncher(void)
//   0x6799d0  protected: virtual __thiscall UDisTweaks_UsableObject::~UDisTweaks_UsableObject(void)
//   0x679ac0  private: int __thiscall UDisAISubStateMachine::GetPendingSubStateIndex(void)const
//   0x679ad0  public: virtual struct FUsableObjectStage const & __thiscall UDisTweaks_UsableObject::GetUsableStage(int)const
//   0x679b60  protected: virtual __thiscall UDisTweaks_AudioLogPlayer::~UDisTweaks_AudioLogPlayer(void)
//   0x679bf0  protected: virtual __thiscall UDisTweaks_Door::~UDisTweaks_Door(void)
//   0x679ce0  protected: virtual __thiscall UDisTweaks_Tripwire::~UDisTweaks_Tripwire(void)
//   0x679d70  protected: virtual __thiscall UDisTweaks_Upgrade::~UDisTweaks_Upgrade(void)
//   0x679e50  protected: virtual __thiscall UDisTweaks_WallOfLight::~UDisTweaks_WallOfLight(void)
//   0x679ef0  protected: virtual __thiscall UDisTweaks_WatchTower::~UDisTweaks_WatchTower(void)
//   0x67a4b0  public: static void __cdecl UDisTweaks_InteractableInterface::InternalConstructor(void *)
//   0x67a4d0  public: static void __cdecl UDisTweaks_Interactable_PickupBase::InternalConstructor(void *)
//   0x67a4f0  public: static void __cdecl UDisTweaks_PickupBase::InternalConstructor(void *)
//   0x67a510  public: static void __cdecl UDisTweaks_AbstractItemPickupNote::InternalConstructor(void *)
//   0x67a530  public: static void __cdecl UDisTweaks_WhaleBoneCharm::InternalConstructor(void *)
//   0x67a550  public: static void __cdecl UDisTweaks_Key::InternalConstructor(void *)
//   0x67a570  public: static void __cdecl UDisTweaks_StatPickup::InternalConstructor(void *)
//   0x67a590  public: static void __cdecl UDisTweaks_Climbable::InternalConstructor(void *)
//   0x67a5b0  public: static void __cdecl UDisTweaks_SkeletalBreakable::InternalConstructor(void *)
//   0x67a5d0  public: static void __cdecl UDisTweaks_ProjectileLauncher::InternalConstructor(void *)
//   0x67a5f0  public: static void __cdecl UDisTweaks_UsableObject::InternalConstructor(void *)
//   0x67a610  public: static void __cdecl UDisTweaks_AudioLogPlayer::InternalConstructor(void *)
//   0x67a630  public: static void __cdecl UDisTweaks_Door::InternalConstructor(void *)
//   0x67a650  public: static void __cdecl UDisTweaks_Tripwire::InternalConstructor(void *)
//   0x67a670  public: static void __cdecl UDisTweaks_Upgrade::InternalConstructor(void *)
//   0x67a690  public: static void __cdecl UDisTweaks_WallOfLight::InternalConstructor(void *)
//   0x67a6b0  public: static void __cdecl UDisTweaks_WatchTower::InternalConstructor(void *)
//   0x67b830  protected: virtual __thiscall UDisTweaks_Movable::~UDisTweaks_Movable(void)
//   0x67c0f0  public: static void __cdecl UDisTweaks_Movable::InternalConstructor(void *)
//   0x67cbe0  public: class UDisTweaks_WallOfLight const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_WallOfLight>(void)const
//   0x67cc10  public: class UDisTweaks_PickupBase const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_PickupBase>(void)const
//   0x67cc40  protected: virtual __thiscall UDisTweaks_WhaleBoneCharmList::~UDisTweaks_WhaleBoneCharmList(void)
//   0x681640  public: static void __cdecl UDisTweaks_WhaleBoneCharmList::InternalConstructor(void *)
//   0x689a80  public: class UDisTweaks_Door const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_Door>(void)const
//   0x696ae0  public: class UDisTweaks_PlayerInput const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_PlayerInput>(void)const
//   0x696c50  public: class UDisTweaks_WeaponRanged const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_WeaponRanged>(void)const
//   0x6a68e0  protected: virtual __thiscall UDisTweaks_AbstractItemPickupAudioLog::~UDisTweaks_AbstractItemPickupAudioLog(void)
//   0x6a6970  protected: virtual __thiscall UDisTweaks_MovableLimb::~UDisTweaks_MovableLimb(void)
//   0x6a7e30  public: static void __cdecl UDisTweaks_AbstractItemPickupAudioLog::InternalConstructor(void *)
//   0x6a7e50  public: static void __cdecl UDisTweaks_MovableLimb::InternalConstructor(void *)
//   0x6b1fe0  public: void __thiscall IDisTweaksInterface::SetTweaks(class UDisTweaksBase *)
//   0x6b5e80  public: class UDisTweaks_Pawn const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_Pawn>(void)const
//   0x6b5fa0  public: class UDisTweaks_InventoryItem const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_InventoryItem>(void)const
//   0x6d7ba0  public: class UDisTweaks_Possess const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_Possess>(void)const
//   0x701360  public: class UDisTweaks_DarkVision const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_DarkVision>(void)const
//   0x737000  protected: virtual __thiscall UDisTweaks_Attributes::~UDisTweaks_Attributes(void)
//   0x737090  protected: virtual __thiscall UDisTweaks_Pawn_Attributes::~UDisTweaks_Pawn_Attributes(void)
//   0x737120  protected: virtual __thiscall UDisTweaks_PlayerPawn_Attributes::~UDisTweaks_PlayerPawn_Attributes(void)
//   0x7371b0  protected: virtual __thiscall UDisTweaks_PlayerVisRegion::~UDisTweaks_PlayerVisRegion(void)
//   0x738cc0  public: static void __cdecl UDisTweaks_PlayerPawn_Attributes::InternalConstructor(void *)
//   0x738ce0  public: static void __cdecl UDisTweaks_PlayerVisRegion::InternalConstructor(void *)
//   0x73b190  protected: virtual __thiscall UDisTweaks_PlayerStats::~UDisTweaks_PlayerStats(void)
//   0x73bc90  public: class UDisTweaks_AIBehavior_RatStomp const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_AIBehavior_RatStomp>(void)const
//   0x73bde0  public: static void __cdecl UDisTweaks_PlayerStats::InternalConstructor(void *)
//   0x761e70  public: class UDisTweaks_AIBehavior_OverseerCombat const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_AIBehavior_OverseerCombat>(void)const
//   0x780dc0  protected: virtual __thiscall UDisTweaks_AISubProcess_AmbientAnims::~UDisTweaks_AISubProcess_AmbientAnims(void)
//   0x780e50  protected: virtual __thiscall UDisTweaks_AISubProcess_AmbientBarks::~UDisTweaks_AISubProcess_AmbientBarks(void)
//   0x780ee0  protected: virtual __thiscall UDisTweaks_AISubState_TakePosition::~UDisTweaks_AISubState_TakePosition(void)
//   0x780f70  protected: virtual __thiscall UDisTweaks_AISubProcess_PersonalSpace::~UDisTweaks_AISubProcess_PersonalSpace(void)
//   0x7814b0  protected: virtual __thiscall UDisTweaks_StoryGroup::~UDisTweaks_StoryGroup(void)
//   0x7816f0  protected: virtual __thiscall UDisTweaks_AISubState_MaintainDistance::~UDisTweaks_AISubState_MaintainDistance(void)
//   0x782a50  public: static void __cdecl UDisTweaks_AISubProcess_AmbientAnims::InternalConstructor(void *)
//   0x782a70  public: static void __cdecl UDisTweaks_AISubProcess_AmbientBarks::InternalConstructor(void *)
//   0x782a90  public: static void __cdecl UDisTweaks_AISubState_TakePosition::InternalConstructor(void *)
//   0x782ab0  public: static void __cdecl UDisTweaks_AISubProcess_PersonalSpace::InternalConstructor(void *)
//   0x782b70  public: static void __cdecl UDisTweaks_StoryGroup::InternalConstructor(void *)
//   0x782bf0  public: static void __cdecl UDisTweaks_AISubState_WH_CombatLongDistance::InternalConstructor(void *)
//   0x785d20  public: class UDisTweaks_AISubState_LieInWait const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_AISubState_LieInWait>(void)const
//   0x785d50  public: class UDisTweaks_AISubProcess_FleetingGaze const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_AISubProcess_FleetingGaze>(void)const
//   0x7af540  public: class UDisTweaks_WindBlast const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_WindBlast>(void)const
//   0x7bea50  protected: virtual __thiscall UDisTweaks_ComponentMeshOffset::~UDisTweaks_ComponentMeshOffset(void)
//   0x7bed80  public: static void __cdecl UDisTweaks_Pawn_Attributes::InternalConstructor(void *)
//   0x7beda0  public: static void __cdecl UDisTweaks_ComponentMeshOffset::InternalConstructor(void *)
//   0x7e0650  protected: virtual __thiscall UDisTweaks_NPCPawn_Attributes::~UDisTweaks_NPCPawn_Attributes(void)
//   0x7e06e0  protected: virtual __thiscall UDisTweaks_GFxMoviePlayerBase::~UDisTweaks_GFxMoviePlayerBase(void)
//   0x7e0ab0  public: static void __cdecl UDisTweaks_NPCPawn_Attributes::InternalConstructor(void *)
//   0x7e0e30  protected: virtual __thiscall UDisTweaks_TallboyAttachment::~UDisTweaks_TallboyAttachment(void)
//   0x7e5650  public: static void __cdecl UDisTweaks_TallboyAttachment::InternalConstructor(void *)
//   0x816020  protected: __thiscall UDisTweaks_GFxMoviePlayerJournal::UDisTweaks_GFxMoviePlayerJournal(void)
//   0x8160b0  protected: virtual __thiscall UDisTweaks_GFxMoviePlayerJournal::~UDisTweaks_GFxMoviePlayerJournal(void)
//   0x816170  protected: virtual __thiscall UDisTweaks_GFxMoviePlayerMainMenu::~UDisTweaks_GFxMoviePlayerMainMenu(void)
//   0x816280  protected: virtual __thiscall UDisTweaks_GFxMoviePlayerMissionStats::~UDisTweaks_GFxMoviePlayerMissionStats(void)
//   0x816360  protected: __thiscall UDisTweaks_GFxMoviePlayerMenuBase::UDisTweaks_GFxMoviePlayerMenuBase(void)
//   0x816430  protected: virtual __thiscall UDisTweaks_GFxMoviePlayerMenuBase::~UDisTweaks_GFxMoviePlayerMenuBase(void)
//   0x8177a0  public: static void __cdecl UDisTweaks_GFxMoviePlayerBase::InternalConstructor(void *)
//   0x8177c0  public: static void __cdecl UDisTweaks_GFxMoviePlayerJournal::InternalConstructor(void *)
//   0x8177e0  public: static void __cdecl UDisTweaks_GFxMoviePlayerMainMenu::InternalConstructor(void *)
//   0x817800  public: static void __cdecl UDisTweaks_GFxMoviePlayerMissionStats::InternalConstructor(void *)
//   0x817820  public: static void __cdecl UDisTweaks_GFxMoviePlayerMenuBase::InternalConstructor(void *)
//   0x83f4a0  protected: virtual __thiscall UDisTweaks_ActivePowerBase::~UDisTweaks_ActivePowerBase(void)
//   0x83f540  protected: virtual __thiscall UDisTweaks_BendTime::~UDisTweaks_BendTime(void)
//   0x83f5d0  protected: virtual __thiscall UDisTweaks_Blink::~UDisTweaks_Blink(void)
//   0x83f660  protected: __thiscall UDisTweaks_GFxMoviePlayerNote::UDisTweaks_GFxMoviePlayerNote(void)
//   0x83f6d0  protected: virtual __thiscall UDisTweaks_GFxMoviePlayerNote::~UDisTweaks_GFxMoviePlayerNote(void)
//   0x83f780  protected: virtual __thiscall UDisTweaks_GFxMoviePlayerPauseMenu::~UDisTweaks_GFxMoviePlayerPauseMenu(void)
//   0x8400e0  public: static void __cdecl UDisTweaks_ActivePowerBase::InternalConstructor(void *)
//   0x840100  public: static void __cdecl UDisTweaks_BendTime::InternalConstructor(void *)
//   0x840120  public: static void __cdecl UDisTweaks_Blink::InternalConstructor(void *)
//   0x840140  public: static void __cdecl UDisTweaks_GFxMoviePlayerNote::InternalConstructor(void *)
//   0x840160  public: static void __cdecl UDisTweaks_GFxMoviePlayerPauseMenu::InternalConstructor(void *)
//   0x8441e0  public: class UDisTweaks_Blink const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_Blink>(void)const
//   0x84edd0  public: class UDisTweaks_InventoryPickup const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_InventoryPickup>(void)const
//   0x85afe0  protected: virtual __thiscall UDisTweaks_DevouringSwarm::~UDisTweaks_DevouringSwarm(void)
//   0x85b080  protected: virtual __thiscall UDisTweaks_Possess::~UDisTweaks_Possess(void)
//   0x85b130  protected: virtual __thiscall UDisTweaks_WindBlast::~UDisTweaks_WindBlast(void)
//   0x85b1c0  protected: virtual __thiscall UDisTweaks_Possessable::~UDisTweaks_Possessable(void)
//   0x85b260  protected: virtual __thiscall UDisTweaks_PostProcess::~UDisTweaks_PostProcess(void)
//   0x85c240  public: static void __cdecl UDisTweaks_DevouringSwarm::InternalConstructor(void *)
//   0x85c260  public: static void __cdecl UDisTweaks_Possess::InternalConstructor(void *)
//   0x85c280  public: static void __cdecl UDisTweaks_WindBlast::InternalConstructor(void *)
//   0x85c2a0  public: static void __cdecl UDisTweaks_Possessable::InternalConstructor(void *)
//   0x85c2c0  public: static void __cdecl UDisTweaks_PostProcess::InternalConstructor(void *)
//   0x87e600  protected: virtual __thiscall UDisTweaks_InventoryItem_Attributes::~UDisTweaks_InventoryItem_Attributes(void)
//   0x87e690  protected: virtual __thiscall UDisTweaks_InventoryItem::~UDisTweaks_InventoryItem(void)
//   0x87e740  protected: virtual __thiscall UDisTweaks_InventoryPickup::~UDisTweaks_InventoryPickup(void)
//   0x880140  public: static void __cdecl UDisTweaks_InventoryItem_Attributes::InternalConstructor(void *)
//   0x880160  public: static void __cdecl UDisTweaks_InventoryItem::InternalConstructor(void *)
//   0x880190  public: static void __cdecl UDisTweaks_InventoryPickup::InternalConstructor(void *)
//   0x8826a0  protected: virtual __thiscall UDisTweaks_InventoryItem_PawnSpecific::~UDisTweaks_InventoryItem_PawnSpecific(void)
//   0x8827b0  protected: virtual __thiscall UDisTweaks_InventoryItem_PlayerSpecific::~UDisTweaks_InventoryItem_PlayerSpecific(void)
//   0x882eb0  public: static void __cdecl UDisTweaks_InventoryItem_PawnSpecific::InternalConstructor(void *)
//   0x882ed0  public: static void __cdecl UDisTweaks_InventoryItem_PlayerSpecific::InternalConstructor(void *)
//   0x89a660  protected: virtual __thiscall UDisTweaks_WeaponRanged_Attributes::~UDisTweaks_WeaponRanged_Attributes(void)
//   0x89a6f0  protected: virtual __thiscall UDisTweaks_Heart::~UDisTweaks_Heart(void)
//   0x89a7a0  protected: virtual __thiscall UDisTweaks_ItemEmpty::~UDisTweaks_ItemEmpty(void)
//   0x89a830  protected: virtual __thiscall UDisTweaks_WeaponRanged::~UDisTweaks_WeaponRanged(void)
//   0x89a8d0  protected: virtual __thiscall UDisTweaks_SpringRazorPlaced::~UDisTweaks_SpringRazorPlaced(void)
//   0x89a960  protected: virtual __thiscall UDisTweaks_RatSpawner::~UDisTweaks_RatSpawner(void)
//   0x89a9f0  protected: virtual __thiscall UDisTweaks_Tune_Protection::~UDisTweaks_Tune_Protection(void)
//   0x89bfb0  protected: virtual __thiscall UDisTweaks_SpringRazor::~UDisTweaks_SpringRazor(void)
//   0x89c540  public: static void __cdecl UDisTweaks_WeaponRanged_Attributes::InternalConstructor(void *)
//   0x89c560  public: static void __cdecl UDisTweaks_Heart::InternalConstructor(void *)
//   0x89c580  public: static void __cdecl UDisTweaks_ItemEmpty::InternalConstructor(void *)
//   0x89c5a0  public: static void __cdecl UDisTweaks_WeaponRanged::InternalConstructor(void *)
//   0x89c5c0  public: static void __cdecl UDisTweaks_AbstractItemPickup::InternalConstructor(void *)
//   0x89c5e0  public: static void __cdecl UDisTweaks_SpringRazorPlaced::InternalConstructor(void *)
//   0x89c600  public: static void __cdecl UDisTweaks_RatSpawner::InternalConstructor(void *)
//   0x89c620  public: static void __cdecl UDisTweaks_Tune_Protection::InternalConstructor(void *)
//   0x89d140  public: static void __cdecl UDisTweaks_SpringRazor::InternalConstructor(void *)
//   0x89ef40  protected: virtual __thiscall UDisTweaks_ItemEmpty_PlayerSpecific::~UDisTweaks_ItemEmpty_PlayerSpecific(void)
//   0x8a0030  public: static void __cdecl UDisTweaks_ItemEmpty_PlayerSpecific::InternalConstructor(void *)
//   0x8a08d0  public: class UDisTweaks_WepWhiskeyBottle const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_WepWhiskeyBottle>(void)const
//   0x8a53b0  public: class UDisTweaks_WepGrenade const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_WepGrenade>(void)const
//   0x8cacd0  protected: virtual __thiscall UDisTweaks_ComponentHitReactionThrow::~UDisTweaks_ComponentHitReactionThrow(void)
//   0x8cad60  protected: virtual __thiscall UDisTweaks_Faction::~UDisTweaks_Faction(void)
//   0x8cae10  protected: virtual __thiscall UDisTweaks_LODProfile::~UDisTweaks_LODProfile(void)
//   0x8caea0  protected: virtual __thiscall UDisTweaks_Vision::~UDisTweaks_Vision(void)
//   0x8cc7c0  public: static void __cdecl UDisTweaks_ComponentHitReactionThrow::InternalConstructor(void *)
//   0x8cc7e0  public: static void __cdecl UDisTweaks_Faction::InternalConstructor(void *)
//   0x8cc800  public: static void __cdecl UDisTweaks_LODProfile::InternalConstructor(void *)
//   0x8cc820  public: static void __cdecl UDisTweaks_Vision::InternalConstructor(void *)
//   0x8d1790  public: class UDisTweaks_GameCrowdAgentSkeletalRat const * __thiscall IDisTweaksInterface::GetTweaks<class UDisTweaks_GameCrowdAgentSkeletalRat>(void)const
//   0x8eb100  protected: virtual __thiscall UDisTweaks_ChapterInfoList::~UDisTweaks_ChapterInfoList(void)
//   0x8eb1a0  protected: virtual __thiscall UDisTweaks_RatSwarmGlobalManager::~UDisTweaks_RatSwarmGlobalManager(void)
//   0x8eb230  protected: virtual __thiscall UDisTweaks_Vulnerability::~UDisTweaks_Vulnerability(void)
//   0x8eb2d0  protected: virtual __thiscall UDisTweaks_WhaleOilReceptacle::~UDisTweaks_WhaleOilReceptacle(void)
//   0x8ed850  public: static void __cdecl UDisTweaksBase::InternalConstructor(void *)
//   0x8ed870  public: static void __cdecl UDisTweaks_ChapterInfoList::InternalConstructor(void *)
//   0x8ed890  public: static void __cdecl UDisTweaks_Attributes::InternalConstructor(void *)
//   0x8ed8b0  public: static void __cdecl UDisTweaks_KAsset::InternalConstructor(void *)
//   0x8ed8d0  public: static void __cdecl UDisTweaks_RatSwarmGlobalManager::InternalConstructor(void *)
//   0x8ed8f0  public: static void __cdecl UDisTweaks_Vulnerability::InternalConstructor(void *)
//   0x8ed910  public: static void __cdecl UDisTweaks_WhaleOilReceptacle::InternalConstructor(void *)
//   0x8eede0  protected: virtual __thiscall UDisTweaks_WhaleOilBattery::~UDisTweaks_WhaleOilBattery(void)
//   0x8efdb0  public: static void __cdecl UDisTweaks_WhaleOilBattery::InternalConstructor(void *)
//   ... 1 more, see resources/docs/symbols/functions.csv
