#pragma once
// DishonoredGame/inc/dishonoredgameweaponrangedclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (162):
//   0x63c960  public: static class UClass * __cdecl UDishonoredWeapon_Ranged::StaticClass(void)
//   0x63c980  public: static class UClass * __cdecl UDisWepGrenade::StaticClass(void)
//   0x63ca00  public: static class UClass * __cdecl UDisItemContext_NPC_OverseerJumpAway::StaticClass(void)
//   0x63cbe0  public: static class UClass * __cdecl ADisProjectile::StaticClass(void)
//   0x862b90  public: void __thiscall FDisCachedAimAssistPosResult::SetCache(int, class FVector const &, class FVector const &, struct FVector2D const &, unsigned int)
//   0x862bf0  protected: virtual __thiscall UDisItemContext_ProjectileAttack::~UDisItemContext_ProjectileAttack(void)
//   0x862c70  public: virtual class UObject * __thiscall UDisItemContext_ProjectileAttack::GetUObjectInterfaceDisFireProjectileInterface(void)
//   0x862cb0  protected: virtual __thiscall UDisItemContext_NPCThrow::~UDisItemContext_NPCThrow(void)
//   0x862d60  protected: virtual __thiscall UDisItemContext_NPCThrowGrenade::~UDisItemContext_NPCThrowGrenade(void)
//   0x862e10  protected: virtual __thiscall UDisItemContext_NPCThrowGrenade_Aimed::~UDisItemContext_NPCThrowGrenade_Aimed(void)
//   0x864c20  protected: virtual __thiscall UDisItemContext_FireCrossbow::~UDisItemContext_FireCrossbow(void)
//   0x864cf0  protected: virtual __thiscall UDisItemContext_FirePistol::~UDisItemContext_FirePistol(void)
//   0x864dc0  protected: virtual __thiscall UDisItemContext_NPCFireBow::~UDisItemContext_NPCFireBow(void)
//   0x864fc0  protected: virtual __thiscall UDisItemContext_NPCFireGun::~UDisItemContext_NPCFireGun(void)
//   0x865050  public: virtual class UObject * __thiscall UDisItemContext_NPCFireGun::GetUObjectInterfaceDisNoiseMakerInterface(void)
//   0x865150  protected: virtual __thiscall UDisItemContext_NPC_OverseerJumpAway::~UDisItemContext_NPC_OverseerJumpAway(void)
//   0x865220  protected: virtual __thiscall UDisItemContext_NPCLobGrenadeAtUnreachable::~UDisItemContext_NPCLobGrenadeAtUnreachable(void)
//   0x8652f0  protected: virtual __thiscall UDisItemContext_NPCThrowObject::~UDisItemContext_NPCThrowObject(void)
//   0x8653c0  protected: virtual __thiscall UDisItemContext_NPCThrowWhiskey::~UDisItemContext_NPCThrowWhiskey(void)
//   0x865490  protected: virtual __thiscall UDisItemContext_ThrowGrenade::~UDisItemContext_ThrowGrenade(void)
//   0x865560  protected: virtual __thiscall UDisItemContext_NPCReloadGun::~UDisItemContext_NPCReloadGun(void)
//   0x865600  protected: virtual __thiscall UDisItemContext_ReloadGunPlayer::~UDisItemContext_ReloadGunPlayer(void)
//   0x86d1c0  public: static void __cdecl UDisItemContext_ProjectileAttack::InternalConstructor(void *)
//   0x86d210  public: static void __cdecl UDisItemContext_FireCrossbow::InternalConstructor(void *)
//   0x86d260  public: static void __cdecl UDisItemContext_FirePistol::InternalConstructor(void *)
//   0x86d2b0  public: static void __cdecl UDisItemContext_NPCFireBow::InternalConstructor(void *)
//   0x86d300  public: static void __cdecl UDisItemContext_NPCFireGun::InternalConstructor(void *)
//   0x86d320  public: static void __cdecl UDisItemContext_NPCThrow::InternalConstructor(void *)
//   0x86d340  public: static void __cdecl UDisItemContext_NPCThrowGrenade::InternalConstructor(void *)
//   0x86d380  public: static void __cdecl UDisItemContext_NPC_OverseerJumpAway::InternalConstructor(void *)
//   0x86d3c0  public: static void __cdecl UDisItemContext_NPCThrowGrenade_Aimed::InternalConstructor(void *)
//   0x86d400  public: static void __cdecl UDisItemContext_NPCLobGrenadeAtUnreachable::InternalConstructor(void *)
//   0x86d440  public: static void __cdecl UDisItemContext_NPCThrowObject::InternalConstructor(void *)
//   0x86d480  public: static void __cdecl UDisItemContext_NPCThrowWhiskey::InternalConstructor(void *)
//   0x86d4c0  public: static void __cdecl UDisItemContext_ThrowGrenade::InternalConstructor(void *)
//   0x86d510  public: static void __cdecl UDisItemContext_NPCReloadGun::InternalConstructor(void *)
//   0x86d540  public: static void __cdecl UDisItemContext_ReloadGunPlayer::InternalConstructor(void *)
//   0x87f560  protected: virtual __thiscall UDisTweaks_NPCReloadGun::~UDisTweaks_NPCReloadGun(void)
//   0x87f5f0  protected: virtual __thiscall UDisTweaks_ProjectileAttack::~UDisTweaks_ProjectileAttack(void)
//   0x87f6b0  protected: virtual __thiscall UDisTweaks_FireCrossbow::~UDisTweaks_FireCrossbow(void)
//   0x87f7a0  protected: virtual __thiscall UDisTweaks_FirePistol::~UDisTweaks_FirePistol(void)
//   0x87f8a0  protected: virtual __thiscall UDisTweaks_NPCFireGun::~UDisTweaks_NPCFireGun(void)
//   0x87f930  protected: virtual __thiscall UDisTweaks_NPCThrow::~UDisTweaks_NPCThrow(void)
//   0x87f9c0  protected: virtual __thiscall UDisTweaks_NPCThrowGrenade::~UDisTweaks_NPCThrowGrenade(void)
//   0x87fa50  protected: virtual __thiscall UDisTweaks_NPCLobGrenadeAtUnreachable::~UDisTweaks_NPCLobGrenadeAtUnreachable(void)
//   0x87fae0  protected: virtual __thiscall UDisTweaks_NPCThrowWhiskey::~UDisTweaks_NPCThrowWhiskey(void)
//   0x87fb70  protected: virtual __thiscall UDisTweaks_ThrowGrenade::~UDisTweaks_ThrowGrenade(void)
//   0x87fc10  protected: virtual __thiscall UDisTweaks_ReloadGunPlayer::~UDisTweaks_ReloadGunPlayer(void)
//   0x8804a0  public: static void __cdecl UDisTweaks_NPCReloadGun::InternalConstructor(void *)
//   0x8804c0  public: static void __cdecl UDisTweaks_ProjectileAttack::InternalConstructor(void *)
//   0x8804e0  public: static void __cdecl UDisTweaks_FireCrossbow::InternalConstructor(void *)
//   0x880500  public: static void __cdecl UDisTweaks_FirePistol::InternalConstructor(void *)
//   0x880520  public: static void __cdecl UDisTweaks_NPCFireGun::InternalConstructor(void *)
//   0x880540  public: static void __cdecl UDisTweaks_NPCThrow::InternalConstructor(void *)
//   0x880560  public: static void __cdecl UDisTweaks_NPCThrowGrenade::InternalConstructor(void *)
//   0x880580  public: static void __cdecl UDisTweaks_NPCLobGrenadeAtUnreachable::InternalConstructor(void *)
//   0x8805a0  public: static void __cdecl UDisTweaks_NPCThrowWhiskey::InternalConstructor(void *)
//   0x8805c0  public: static void __cdecl UDisTweaks_ThrowGrenade::InternalConstructor(void *)
//   0x8805e0  public: static void __cdecl UDisTweaks_ReloadGunPlayer::InternalConstructor(void *)
//   0x888b50  protected: virtual __thiscall UDisItemContext_UsePower::~UDisItemContext_UsePower(void)
//   0x88bca0  protected: virtual __thiscall UDisGrenadeComponent::~UDisGrenadeComponent(void)
//   0x88bd50  protected: virtual __thiscall UDisItemContext_NPCAttackUnder_Gun::~UDisItemContext_NPCAttackUnder_Gun(void)
//   0x88be30  protected: virtual __thiscall UDisItemContext_NPCAttackUnder_Grenade::~UDisItemContext_NPCAttackUnder_Grenade(void)
//   0x88bf00  public: static void __cdecl UDisItemContext_UsePower::InternalConstructor(void *)
//   0x8916e0  public: static void __cdecl UDisGrenadeComponent::InternalConstructor(void *)
//   0x891710  public: static void __cdecl UDisItemContext_NPCAttackUnder_Gun::InternalConstructor(void *)
//   0x891750  public: static void __cdecl UDisItemContext_NPCAttackUnder_Grenade::InternalConstructor(void *)
//   0x897190  protected: virtual __thiscall ADisGrenade::~ADisGrenade(void)
//   0x897360  protected: virtual __thiscall ADisWhiskeyBottle::~ADisWhiskeyBottle(void)
//   0x897440  protected: virtual __thiscall ADisProjectile::~ADisProjectile(void)
//   0x8975e0  protected: virtual __thiscall ADisBullet::~ADisBullet(void)
//   0x897720  protected: virtual __thiscall ADisBullet_Explosive::~ADisBullet_Explosive(void)
//   0x8977e0  protected: virtual __thiscall ADisProjectile_Arrow::~ADisProjectile_Arrow(void)
//   0x897880  public: virtual class UObject * __thiscall ADisProjectile_GrenadeBase::GetUObjectInterfaceDisSoulRenderInterface(void)
//   0x897a00  protected: virtual __thiscall ADisProjectile_Arrow_Explosive::~ADisProjectile_Arrow_Explosive(void)
//   0x897b60  protected: virtual __thiscall ADisProjectile_Arrow_Flare::~ADisProjectile_Arrow_Flare(void)
//   0x897c20  protected: virtual __thiscall ADisProjectile_GrenadeBase::~ADisProjectile_GrenadeBase(void)
//   0x897e30  protected: virtual __thiscall ADisProjectile_Grenade::~ADisProjectile_Grenade(void)
//   0x897f90  protected: virtual __thiscall ADisProjectile_StickyGrenade::~ADisProjectile_StickyGrenade(void)
//   0x898090  protected: virtual __thiscall ADisProjectile_ThrownObject::~ADisProjectile_ThrownObject(void)
//   0x898190  protected: virtual __thiscall ADisProjectile_Whiskey::~ADisProjectile_Whiskey(void)
//   0x898da0  public: static void __cdecl ADisGrenade::InternalConstructor(void *)
//   0x898dc0  public: static void __cdecl ADisWhiskeyBottle::InternalConstructor(void *)
//   0x898de0  public: static void __cdecl ADisProjectile::InternalConstructor(void *)
//   0x898e00  public: static void __cdecl ADisBullet::InternalConstructor(void *)
//   0x898e50  public: static void __cdecl ADisBullet_Explosive::InternalConstructor(void *)
//   0x898ea0  public: static void __cdecl ADisProjectile_Arrow::InternalConstructor(void *)
//   0x898ec0  public: static void __cdecl ADisProjectile_Arrow_Explosive::InternalConstructor(void *)
//   0x898ee0  public: static void __cdecl ADisProjectile_Arrow_Flare::InternalConstructor(void *)
//   0x898f00  public: static void __cdecl ADisProjectile_GrenadeBase::InternalConstructor(void *)
//   0x898f20  public: static void __cdecl ADisProjectile_Grenade::InternalConstructor(void *)
//   0x898f40  public: static void __cdecl ADisProjectile_StickyGrenade::InternalConstructor(void *)
//   0x898f60  public: static void __cdecl ADisProjectile_ThrownObject::InternalConstructor(void *)
//   0x898fb0  public: static void __cdecl ADisProjectile_Whiskey::InternalConstructor(void *)
//   0x89b070  protected: virtual __thiscall UDisTweaks_GrenadeComponent::~UDisTweaks_GrenadeComponent(void)
//   0x89b100  protected: virtual __thiscall UDisTweaks_NPCAssassinHand::~UDisTweaks_NPCAssassinHand(void)
//   0x89b190  protected: virtual __thiscall UDisTweaks_WepBow::~UDisTweaks_WepBow(void)
//   0x89b220  protected: virtual __thiscall UDisTweaks_WepTallboyBow::~UDisTweaks_WepTallboyBow(void)
//   0x89b2b0  protected: virtual __thiscall UDisTweaks_WepCrossbow::~UDisTweaks_WepCrossbow(void)
//   0x89b340  protected: virtual __thiscall UDisTweaks_WepPistol::~UDisTweaks_WepPistol(void)
//   0x89b3e0  protected: virtual __thiscall UDisTweaks_WepMusicAmp::~UDisTweaks_WepMusicAmp(void)
//   0x89b470  protected: virtual __thiscall UDisTweaks_WepWhiskeyBottle::~UDisTweaks_WepWhiskeyBottle(void)
//   0x89b500  protected: virtual __thiscall UDisTweaks_Projectile::~UDisTweaks_Projectile(void)
//   0x89b590  protected: virtual __thiscall UDisTweaks_NPCAttackUnder_Gun::~UDisTweaks_NPCAttackUnder_Gun(void)
//   0x89b620  protected: virtual __thiscall UDisTweaks_NPCAttackUnder_Grenade::~UDisTweaks_NPCAttackUnder_Grenade(void)
//   0x89b6b0  protected: virtual __thiscall UDisTweaks_UsePower::~UDisTweaks_UsePower(void)
//   0x89b770  protected: virtual __thiscall UDisTweaks_Grenade::~UDisTweaks_Grenade(void)
//   0x89b800  protected: virtual __thiscall UDisTweaks_Arrow::~UDisTweaks_Arrow(void)
//   0x89b890  protected: virtual __thiscall UDisTweaks_Arrow_Explosive::~UDisTweaks_Arrow_Explosive(void)
//   0x89b920  protected: virtual __thiscall UDisTweaks_Arrow_Flare::~UDisTweaks_Arrow_Flare(void)
//   0x89b9b0  protected: virtual __thiscall UDisTweaks_Bullet::~UDisTweaks_Bullet(void)
//   0x89ba40  protected: virtual __thiscall UDisTweaks_Bullet_Explosive::~UDisTweaks_Bullet_Explosive(void)
//   0x89bad0  protected: virtual __thiscall UDisTweaks_Projectile_GrenadeBase::~UDisTweaks_Projectile_GrenadeBase(void)
//   0x89bb60  protected: virtual __thiscall UDisTweaks_Projectile_Grenade::~UDisTweaks_Projectile_Grenade(void)
//   0x89bbf0  protected: virtual __thiscall UDisTweaks_Projectile_StickyGrenade::~UDisTweaks_Projectile_StickyGrenade(void)
//   0x89bc80  protected: virtual __thiscall UDisTweaks_Projectile_ThrownObject::~UDisTweaks_Projectile_ThrownObject(void)
//   0x89bd10  protected: virtual __thiscall UDisTweaks_Projectile_Whiskey::~UDisTweaks_Projectile_Whiskey(void)
//   0x89bda0  protected: virtual __thiscall UDisTweaks_WhiskeyBottle::~UDisTweaks_WhiskeyBottle(void)
//   0x89c780  public: static void __cdecl UDisTweaks_GrenadeComponent::InternalConstructor(void *)
//   0x89c7a0  public: static void __cdecl UDisTweaks_NPCAssassinHand::InternalConstructor(void *)
//   0x89c7c0  public: static void __cdecl UDisTweaks_WepBow::InternalConstructor(void *)
//   0x89c7e0  public: static void __cdecl UDisTweaks_WepTallboyBow::InternalConstructor(void *)
//   0x89c800  public: static void __cdecl UDisTweaks_WepCrossbow::InternalConstructor(void *)
//   0x89c820  public: static void __cdecl UDisTweaks_WepPistol::InternalConstructor(void *)
//   0x89c840  public: static void __cdecl UDisTweaks_WepMusicAmp::InternalConstructor(void *)
//   0x89c860  public: static void __cdecl UDisTweaks_WepWhiskeyBottle::InternalConstructor(void *)
//   0x89c880  public: static void __cdecl UDisTweaks_Projectile::InternalConstructor(void *)
//   0x89c8a0  public: static void __cdecl UDisTweaks_NPCAttackUnder_Gun::InternalConstructor(void *)
//   0x89c8c0  public: static void __cdecl UDisTweaks_NPCAttackUnder_Grenade::InternalConstructor(void *)
//   0x89c8e0  public: static void __cdecl UDisTweaks_UsePower::InternalConstructor(void *)
//   0x89c900  public: static void __cdecl UDisTweaks_Grenade::InternalConstructor(void *)
//   0x89c920  public: static void __cdecl UDisTweaks_Arrow::InternalConstructor(void *)
//   0x89c940  public: static void __cdecl UDisTweaks_Arrow_Explosive::InternalConstructor(void *)
//   0x89c960  public: static void __cdecl UDisTweaks_Arrow_Flare::InternalConstructor(void *)
//   0x89c980  public: static void __cdecl UDisTweaks_Bullet::InternalConstructor(void *)
//   0x89c9a0  public: static void __cdecl UDisTweaks_Bullet_Explosive::InternalConstructor(void *)
//   0x89c9c0  public: static void __cdecl UDisTweaks_Projectile_GrenadeBase::InternalConstructor(void *)
//   0x89c9e0  public: static void __cdecl UDisTweaks_Projectile_Grenade::InternalConstructor(void *)
//   0x89ca00  public: static void __cdecl UDisTweaks_Projectile_StickyGrenade::InternalConstructor(void *)
//   0x89ca20  public: static void __cdecl UDisTweaks_Projectile_ThrownObject::InternalConstructor(void *)
//   0x89ca40  public: static void __cdecl UDisTweaks_Projectile_Whiskey::InternalConstructor(void *)
//   0x89ca60  public: static void __cdecl UDisTweaks_WhiskeyBottle::InternalConstructor(void *)
//   0x8ab5c0  protected: virtual __thiscall UDishonoredWeapon_Ranged::~UDishonoredWeapon_Ranged(void)
//   0x8ab6c0  protected: virtual __thiscall UDishonoredWepPistol::~UDishonoredWepPistol(void)
//   0x8ab790  protected: virtual __thiscall UDisWepBow::~UDisWepBow(void)
//   0x8ab860  protected: virtual __thiscall UDisWepCrossbow::~UDisWepCrossbow(void)
//   0x8ab930  protected: virtual __thiscall UDisWepGrenade::~UDisWepGrenade(void)
//   0x8aba00  protected: virtual __thiscall UDisWepNPCAssassinHand::~UDisWepNPCAssassinHand(void)
//   0x8ac770  public: static void __cdecl UDishonoredWeapon_Ranged::InternalConstructor(void *)
//   0x8ac7c0  public: static void __cdecl UDishonoredWepPistol::InternalConstructor(void *)
//   0x8ac810  public: static void __cdecl UDisWepBow::InternalConstructor(void *)
//   0x8ac860  public: static void __cdecl UDisWepCrossbow::InternalConstructor(void *)
//   0x8ac8b0  public: static void __cdecl UDisWepGrenade::InternalConstructor(void *)
//   0x8ac900  public: static void __cdecl UDisWepNPCAssassinHand::InternalConstructor(void *)
//   0xba8bb0  _dynamic_initializer_for__ADisGrenadeexecTakeDamage_NativeTemp__
//   0xba8bd0  _dynamic_initializer_for__ADisWhiskeyBottleexecTakeDamage_NativeTemp__
//   0xba8bf0  _dynamic_initializer_for__ADisProjectileexecTakeDamage_NativeTemp__
//   0xba8c10  _dynamic_initializer_for__ADisProjectileexecTakeDamageTemp__
//   0xba8c30  _dynamic_initializer_for__ADisProjectile_ArrowexecBaseChangeTemp__
//   0xba8c50  _dynamic_initializer_for__ADisProjectile_GrenadeBaseexecTakeDamage_NativeTemp__
//   0xba8c70  _dynamic_initializer_for__ADisProjectile_StickyGrenadeexecBaseChangeTemp__
//   0xba8c90  _dynamic_initializer_for__ADisProjectile_WhiskeyexecTakeDamage_NativeTemp__
