#pragma once
// DishonoredGame/inc/dishonoredgamekismetclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (242):
//   0x63c720  public: static class UClass * __cdecl UDisSeqEvent_RatPossess::StaticClass(void)
//   0x63c740  public: void __thiscall AGameCrowdDestination::execIncrementCustomerCount(struct FFrame &, void * const)
//   0x63eef0  public: void __thiscall UDisSeqVar_PlayerCamera::execGetObjectValue(struct FFrame &, void * const)
//   0x67ba10  protected: virtual __thiscall UDisSeqAct_WallofLightControl::~UDisSeqAct_WallofLightControl(void)
//   0x67c1a0  public: static void __cdecl UDisSeqAct_WallofLightControl::InternalConstructor(void *)
//   0x71a480  protected: virtual __thiscall UDisSeqAct_IncrementPlayerStat::~UDisSeqAct_IncrementPlayerStat(void)
//   0x71a510  protected: virtual __thiscall UDisSeqAct_PlayerAction::~UDisSeqAct_PlayerAction(void)
//   0x71a5a0  protected: virtual __thiscall UDisSeqAct_EvalAchievement::~UDisSeqAct_EvalAchievement(void)
//   0x71a630  protected: virtual __thiscall UDisSeqAct_GetPlayerStat::~UDisSeqAct_GetPlayerStat(void)
//   0x71c020  public: static void __cdecl UDisSeqAct_IncrementPlayerStat::InternalConstructor(void *)
//   0x71c040  public: static void __cdecl UDisSeqAct_EvalAchievement::InternalConstructor(void *)
//   0x71c060  public: static void __cdecl UDisSeqAct_GetPlayerStat::InternalConstructor(void *)
//   0x7bf400  protected: virtual __thiscall UDisSeqAct_SpawnStealable::~UDisSeqAct_SpawnStealable(void)
//   0x7c1b50  public: static void __cdecl UDisSeqAct_SpawnStealable::InternalConstructor(void *)
//   0x7dddd0  public: virtual class FString __thiscall UDisSeqVar_PlayerCamera::GetValueStr(void)
//   0x7dde00  protected: virtual __thiscall UDisSeqVar_PlayerCamera::~UDisSeqVar_PlayerCamera(void)
//   0x7df050  public: static void __cdecl UDisSeqVar_PlayerCamera::InternalConstructor(void *)
//   0x7e1010  protected: virtual __thiscall UDisSeqAct_ActivateProjectileLauncher::~UDisSeqAct_ActivateProjectileLauncher(void)
//   0x7e10a0  protected: virtual __thiscall UDisSeqAct_ActivateUsable::~UDisSeqAct_ActivateUsable(void)
//   0x7e1130  protected: virtual __thiscall UDisSeqAct_AddAttributeModifier::~UDisSeqAct_AddAttributeModifier(void)
//   0x7e11c0  protected: virtual __thiscall UDisSeqAct_AddDarkness::~UDisSeqAct_AddDarkness(void)
//   0x7e1260  protected: virtual __thiscall UDisSeqAct_AIClearAttention::~UDisSeqAct_AIClearAttention(void)
//   0x7e1300  protected: virtual __thiscall UDisSeqAct_AIDoBehavior_Base::~UDisSeqAct_AIDoBehavior_Base(void)
//   0x7e1370  public: virtual class FString __thiscall UDisSeqAct_AIDoBehavior_Base::GetHelpText(void)const
//   0x7e13d0  public: virtual class UClass * __thiscall UDisSeqAct_AIDoFollow::GetCurrentBehaviorClass(void)const
//   0x7e13f0  public: virtual class FString __thiscall UDisSeqAct_AIDoFollow::GetHelpText(void)const
//   0x7e1420  protected: virtual __thiscall UDisSeqAct_AIDoFollow::~UDisSeqAct_AIDoFollow(void)
//   0x7e14b0  protected: virtual __thiscall UDisSeqAct_AIDoSimpleBehaviors::~UDisSeqAct_AIDoSimpleBehaviors(void)
//   0x7e1540  protected: virtual __thiscall UDisSeqAct_AIGetBrainFlagValue::~UDisSeqAct_AIGetBrainFlagValue(void)
//   0x7e15d0  protected: virtual __thiscall UDisSeqAct_RemoveAbstractItem::~UDisSeqAct_RemoveAbstractItem(void)
//   0x7e1660  public: virtual class UObject * __thiscall UDisSeqAct_AINoise::GetUObjectInterfaceDisNoiseMakerInterface(void)
//   0x7e1680  protected: virtual __thiscall UDisSeqAct_AINoise::~UDisSeqAct_AINoise(void)
//   0x7e1720  protected: virtual __thiscall UDisSeqAct_AISetBrainFlags::~UDisSeqAct_AISetBrainFlags(void)
//   0x7e17c0  protected: virtual __thiscall UDisSeqAct_AttachAnimSet::~UDisSeqAct_AttachAnimSet(void)
//   0x7e1850  protected: virtual __thiscall UDisSeqAct_AttachPickup::~UDisSeqAct_AttachPickup(void)
//   0x7e18e0  protected: virtual __thiscall UDisSeqAct_BackupAndClearInventory::~UDisSeqAct_BackupAndClearInventory(void)
//   0x7e19b0  protected: virtual __thiscall UDisSeqAct_BendTime::~UDisSeqAct_BendTime(void)
//   0x7e1a40  protected: virtual __thiscall UDisSeqAct_BodyShadowKill::~UDisSeqAct_BodyShadowKill(void)
//   0x7e1ad0  protected: virtual __thiscall UDisSeqAct_CleanupBodies::~UDisSeqAct_CleanupBodies(void)
//   0x7e1b60  protected: virtual __thiscall UDisSeqAct_ClearPlayerVisSettings::~UDisSeqAct_ClearPlayerVisSettings(void)
//   0x7e1bf0  protected: virtual __thiscall UDisSeqAct_DialogInputs::~UDisSeqAct_DialogInputs(void)
//   0x7e1c80  protected: virtual __thiscall UDisSeqAct_DialogScriptedChoice::~UDisSeqAct_DialogScriptedChoice(void)
//   0x7e1d30  protected: virtual __thiscall UDisSeqAct_DiscardAllLevelStates::~UDisSeqAct_DiscardAllLevelStates(void)
//   0x7e1dc0  protected: virtual __thiscall UDisSeqAct_DiscardLevelState::~UDisSeqAct_DiscardLevelState(void)
//   0x7e1e50  protected: virtual __thiscall UDisSeqAct_EquipItemType::~UDisSeqAct_EquipItemType(void)
//   0x7e1ee0  protected: virtual __thiscall UDisSeqAct_PlayMusicBox::~UDisSeqAct_PlayMusicBox(void)
//   0x7e1f70  protected: virtual __thiscall UDisSeqAct_FireProjectile::~UDisSeqAct_FireProjectile(void)
//   0x7e2000  protected: virtual __thiscall UDisSeqAct_ForbiddenZoneOverride::~UDisSeqAct_ForbiddenZoneOverride(void)
//   0x7e20b0  protected: virtual __thiscall UDisSeqAct_GotoPlayerTravelDestination::~UDisSeqAct_GotoPlayerTravelDestination(void)
//   0x7e2140  protected: virtual __thiscall UDisSeqAct_Highlight::~UDisSeqAct_Highlight(void)
//   0x7e21d0  protected: virtual __thiscall UDisSeqAct_Latent::~UDisSeqAct_Latent(void)
//   0x7e2260  protected: virtual __thiscall UDisSeqAct_AIGoToActor::~UDisSeqAct_AIGoToActor(void)
//   0x7e22f0  protected: virtual __thiscall UDisSeqAct_AIShoot::~UDisSeqAct_AIShoot(void)
//   0x7e2380  protected: virtual __thiscall UDisSeqAct_AutoSave::~UDisSeqAct_AutoSave(void)
//   0x7e2410  protected: virtual __thiscall UDisSeqAct_NPCDoTeleportSpell::~UDisSeqAct_NPCDoTeleportSpell(void)
//   0x7e24a0  protected: virtual __thiscall UDisSeqAct_SpawnCameraLensEffect::~UDisSeqAct_SpawnCameraLensEffect(void)
//   0x7e2530  public: virtual class UObject * __thiscall UDisSeqAct_StartSpawn::GetUObjectInterfaceDisSpawnRequesterInterface(void)
//   0x7e2550  protected: virtual __thiscall UDisSeqAct_StartSpawn::~UDisSeqAct_StartSpawn(void)
//   0x7e25f0  protected: virtual __thiscall UDisSeqAct_LimitPawnMinHealth::~UDisSeqAct_LimitPawnMinHealth(void)
//   0x7e2680  protected: virtual __thiscall UDisSeqAct_Lock::~UDisSeqAct_Lock(void)
//   0x7e2710  protected: virtual __thiscall UDisSeqAct_ModifyAmmo::~UDisSeqAct_ModifyAmmo(void)
//   0x7e27b0  protected: virtual __thiscall UDisSeqAct_NotifyMissionEnd::~UDisSeqAct_NotifyMissionEnd(void)
//   0x7e2840  protected: virtual __thiscall UDisSeqAct_NPCDisableTeleportOnNavmesh::~UDisSeqAct_NPCDisableTeleportOnNavmesh(void)
//   0x7e28d0  protected: virtual __thiscall UDisSeqAct_NPCIgnoreRBDamages::~UDisSeqAct_NPCIgnoreRBDamages(void)
//   0x7e2960  protected: virtual __thiscall UDisSeqAct_NPCMarkForVanish::~UDisSeqAct_NPCMarkForVanish(void)
//   0x7e29f0  protected: virtual __thiscall UDisSeqAct_NPCSetMaterials::~UDisSeqAct_NPCSetMaterials(void)
//   0x7e2aa0  protected: virtual __thiscall UDisSeqAct_NPCTrackTarget::~UDisSeqAct_NPCTrackTarget(void)
//   0x7e2b30  protected: virtual __thiscall UDisSeqAct_OutsiderConfig::~UDisSeqAct_OutsiderConfig(void)
//   0x7e2bc0  protected: virtual __thiscall UDisSeqAct_OverrideDisableHitReactSoiree::~UDisSeqAct_OverrideDisableHitReactSoiree(void)
//   0x7e2c50  protected: virtual __thiscall UDisSeqAct_AddKey::~UDisSeqAct_AddKey(void)
//   0x7e2cf0  protected: virtual __thiscall UDisSeqAct_GiveUpgrade::~UDisSeqAct_GiveUpgrade(void)
//   0x7e2d80  protected: virtual __thiscall UDEPRECATED_DisSeqAct_AddHeartTarget::~UDEPRECATED_DisSeqAct_AddHeartTarget(void)
//   0x7e2e10  protected: virtual __thiscall UDisSeqAct_RemovePower::~UDisSeqAct_RemovePower(void)
//   0x7e2eb0  protected: virtual __thiscall UDisSeqAct_PlayerTrackTarget::~UDisSeqAct_PlayerTrackTarget(void)
//   0x7e2f40  protected: virtual __thiscall UDisSeqAct_PostProcess::~UDisSeqAct_PostProcess(void)
//   0x7e2fd0  protected: virtual __thiscall UDisSeqAct_RBConstraint::~UDisSeqAct_RBConstraint(void)
//   0x7e3060  protected: virtual __thiscall UDisSeqAct_RemoveInventoryItem::~UDisSeqAct_RemoveInventoryItem(void)
//   0x7e30f0  protected: virtual __thiscall UDisSeqAct_RestoreInventoryFromBackup::~UDisSeqAct_RestoreInventoryFromBackup(void)
//   0x7e3190  protected: virtual __thiscall UDisSeqAct_SaveLevelState::~UDisSeqAct_SaveLevelState(void)
//   0x7e3220  protected: virtual __thiscall UDisSeqAct_SetActiveSoundCaptureBox::~UDisSeqAct_SetActiveSoundCaptureBox(void)
//   0x7e32b0  protected: virtual __thiscall UDisSeqAct_SetAudioOcclusion::~UDisSeqAct_SetAudioOcclusion(void)
//   0x7e3340  protected: virtual __thiscall UDisSeqAct_SetDisposition::~UDisSeqAct_SetDisposition(void)
//   0x7e33e0  protected: virtual __thiscall UDisSeqAct_SetPlayerTravelDestination::~UDisSeqAct_SetPlayerTravelDestination(void)
//   0x7e3470  protected: virtual __thiscall UDisSeqAct_SetPlayerVisSettings::~UDisSeqAct_SetPlayerVisSettings(void)
//   0x7e3500  protected: virtual __thiscall UDisSeqAct_SetRainEmitter::~UDisSeqAct_SetRainEmitter(void)
//   0x7e3590  protected: virtual __thiscall UDisSeqAct_SetStoryFlag::~UDisSeqAct_SetStoryFlag(void)
//   0x7e3620  protected: virtual __thiscall USeqAct_Teleport::~USeqAct_Teleport(void)
//   0x7e36b0  protected: virtual __thiscall UDisSeqAct_TriggerExplosion::~UDisSeqAct_TriggerExplosion(void)
//   0x7e3740  protected: virtual __thiscall UDisSeqAct_UberPostProcess::~UDisSeqAct_UberPostProcess(void)
//   0x7e37d0  protected: virtual __thiscall UDisSeqAct_WatchTowerShootAtTarget::~UDisSeqAct_WatchTowerShootAtTarget(void)
//   0x7e3860  protected: virtual __thiscall UDisSeqCond_CheckStoryFlag::~UDisSeqCond_CheckStoryFlag(void)
//   0x7e38f0  protected: virtual __thiscall UDisSeqCond_CompareBoolExtended::~UDisSeqCond_CompareBoolExtended(void)
//   0x7e3980  protected: virtual __thiscall UDisSeqCond_CompareTweaks::~UDisSeqCond_CompareTweaks(void)
//   0x7e3a10  protected: virtual __thiscall UDisSeqCond_InStoryGroup::~UDisSeqCond_InStoryGroup(void)
//   0x7e3ac0  protected: virtual __thiscall UDisSeqCond_IsDLCUnlocked::~UDisSeqCond_IsDLCUnlocked(void)
//   0x7e3b50  protected: virtual __thiscall UDisSeqCond_IsDoorOpen::~UDisSeqCond_IsDoorOpen(void)
//   0x7e3be0  protected: virtual __thiscall UDisSeqCond_IsSentinel::~UDisSeqCond_IsSentinel(void)
//   0x7e3c70  protected: virtual __thiscall UDisSeqCond_PawnIsPossessed::~UDisSeqCond_PawnIsPossessed(void)
//   0x7e3d00  protected: virtual __thiscall UDisSeqEvent_Attention::~UDisSeqEvent_Attention(void)
//   0x7e3d90  protected: virtual __thiscall UDisSeqEvent_AttentionDecreasedTo::~UDisSeqEvent_AttentionDecreasedTo(void)
//   0x7e3e20  protected: virtual __thiscall UDisSeqEvent_BehaviorStarted::~UDisSeqEvent_BehaviorStarted(void)
//   0x7e3eb0  protected: virtual __thiscall UDisSeqEvent_BreakableBroken::~UDisSeqEvent_BreakableBroken(void)
//   0x7e3f40  protected: virtual __thiscall UDisSeqEvent_Windblasted::~UDisSeqEvent_Windblasted(void)
//   0x7e3fd0  protected: virtual __thiscall UDisSeqEvent_DialogOutputs::~UDisSeqEvent_DialogOutputs(void)
//   0x7e4060  protected: virtual __thiscall UDisSeqEvent_Interact::~UDisSeqEvent_Interact(void)
//   0x7e40f0  protected: virtual __thiscall UDisSeqEvent_PickupPickedUp::~UDisSeqEvent_PickupPickedUp(void)
//   0x7e4180  protected: virtual __thiscall UDisSeqEvent_PlayerEvent::~UDisSeqEvent_PlayerEvent(void)
//   0x7e4210  protected: virtual __thiscall UDisSeqEvent_PlayerManaThreshold::~UDisSeqEvent_PlayerManaThreshold(void)
//   0x7e42a0  protected: virtual __thiscall UDisSeqEvent_PowerUsed::~UDisSeqEvent_PowerUsed(void)
//   0x7e4330  protected: virtual __thiscall UDisSeqEvent_PowerEquipped::~UDisSeqEvent_PowerEquipped(void)
//   0x7e43c0  protected: virtual __thiscall UDisSeqEvent_PlayerHolsterWeapon::~UDisSeqEvent_PlayerHolsterWeapon(void)
//   0x7e4450  protected: virtual __thiscall UDisSeqEvent_Used::~UDisSeqEvent_Used(void)
//   0x7e44e0  protected: virtual __thiscall UDisSeqEvent_WitnessedInteraction::~UDisSeqEvent_WitnessedInteraction(void)
//   0x7e56b0  public: static void __cdecl UDisSeqAct_ActivateProjectileLauncher::InternalConstructor(void *)
//   0x7e56d0  public: static void __cdecl UDisSeqAct_ActivateUsable::InternalConstructor(void *)
//   0x7e56f0  public: static void __cdecl UDisSeqAct_AddAttributeModifier::InternalConstructor(void *)
//   0x7e5710  public: static void __cdecl UDisSeqAct_AddDarkness::InternalConstructor(void *)
//   0x7e5730  public: static void __cdecl UDisSeqAct_AIClearAttention::InternalConstructor(void *)
//   0x7e5750  public: static void __cdecl UDisSeqAct_AIDoBehavior_Base::InternalConstructor(void *)
//   0x7e5770  public: static void __cdecl UDisSeqAct_AIDoFollow::InternalConstructor(void *)
//   0x7e5790  public: static void __cdecl UDisSeqAct_AIDoSimpleBehaviors::InternalConstructor(void *)
//   0x7e57b0  public: static void __cdecl UDisSeqAct_AIGetBrainFlagValue::InternalConstructor(void *)
//   0x7e57d0  public: static void __cdecl UDisSeqAct_RemoveAbstractItem::InternalConstructor(void *)
//   0x7e57f0  public: static void __cdecl UDisSeqAct_AINoise::InternalConstructor(void *)
//   0x7e5820  public: static void __cdecl UDisSeqAct_AISetBrainFlags::InternalConstructor(void *)
//   0x7e5840  public: static void __cdecl UDisSeqAct_AttachAnimSet::InternalConstructor(void *)
//   0x7e5860  public: static void __cdecl UDisSeqAct_AttachPickup::InternalConstructor(void *)
//   0x7e5880  public: static void __cdecl UDisSeqAct_BackupAndClearInventory::InternalConstructor(void *)
//   0x7e58a0  public: static void __cdecl UDisSeqAct_BendTime::InternalConstructor(void *)
//   0x7e58c0  public: static void __cdecl UDisSeqAct_BodyShadowKill::InternalConstructor(void *)
//   0x7e58e0  public: static void __cdecl UDisSeqAct_CleanupBodies::InternalConstructor(void *)
//   0x7e5900  public: static void __cdecl UDisSeqAct_ClearPlayerVisSettings::InternalConstructor(void *)
//   0x7e5920  public: static void __cdecl UDisSeqAct_DialogInputs::InternalConstructor(void *)
//   0x7e5940  public: static void __cdecl UDisSeqAct_DialogScriptedChoice::InternalConstructor(void *)
//   0x7e5960  public: static void __cdecl UDisSeqAct_DiscardAllLevelStates::InternalConstructor(void *)
//   0x7e5980  public: static void __cdecl UDisSeqAct_DiscardLevelState::InternalConstructor(void *)
//   0x7e59a0  public: static void __cdecl UDisSeqAct_EquipItemType::InternalConstructor(void *)
//   0x7e59c0  public: static void __cdecl UDisSeqAct_PlayMusicBox::InternalConstructor(void *)
//   0x7e59e0  public: static void __cdecl UDisSeqAct_FireProjectile::InternalConstructor(void *)
//   0x7e5a00  public: static void __cdecl UDisSeqAct_ForbiddenZoneOverride::InternalConstructor(void *)
//   0x7e5a20  public: static void __cdecl UDisSeqAct_GotoPlayerTravelDestination::InternalConstructor(void *)
//   0x7e5a40  public: static void __cdecl UDisSeqAct_Highlight::InternalConstructor(void *)
//   0x7e5a60  public: static void __cdecl UDisSeqAct_Latent::InternalConstructor(void *)
//   0x7e5a80  public: static void __cdecl UDisSeqAct_AIGoToActor::InternalConstructor(void *)
//   0x7e5aa0  public: static void __cdecl UDisSeqAct_AIShoot::InternalConstructor(void *)
//   0x7e5ac0  public: static void __cdecl UDisSeqAct_AutoSave::InternalConstructor(void *)
//   0x7e5ae0  public: static void __cdecl UDisSeqAct_NPCDoTeleportSpell::InternalConstructor(void *)
//   0x7e5b00  public: static void __cdecl UDisSeqAct_SpawnCameraLensEffect::InternalConstructor(void *)
//   0x7e5b20  public: static void __cdecl UDisSeqAct_StartSpawn::InternalConstructor(void *)
//   0x7e5b50  public: static void __cdecl UDisSeqAct_LimitPawnMinHealth::InternalConstructor(void *)
//   0x7e5b70  public: static void __cdecl UDisSeqAct_Lock::InternalConstructor(void *)
//   0x7e5b90  public: static void __cdecl UDisSeqAct_ModifyAmmo::InternalConstructor(void *)
//   0x7e5bb0  public: static void __cdecl UDisSeqAct_NotifyMissionEnd::InternalConstructor(void *)
//   0x7e5bd0  public: static void __cdecl UDisSeqAct_NPCDisableTeleportOnNavmesh::InternalConstructor(void *)
//   0x7e5bf0  public: static void __cdecl UDisSeqAct_NPCIgnoreRBDamages::InternalConstructor(void *)
//   0x7e5c10  public: static void __cdecl UDisSeqAct_NPCMarkForVanish::InternalConstructor(void *)
//   0x7e5c30  public: static void __cdecl UDisSeqAct_NPCSetMaterials::InternalConstructor(void *)
//   0x7e5c50  public: static void __cdecl UDisSeqAct_NPCTrackTarget::InternalConstructor(void *)
//   0x7e5c70  public: static void __cdecl UDisSeqAct_OutsiderConfig::InternalConstructor(void *)
//   0x7e5c90  public: static void __cdecl UDisSeqAct_OverrideDisableHitReactSoiree::InternalConstructor(void *)
//   0x7e5cb0  public: static void __cdecl UDisSeqAct_PlayerAction::InternalConstructor(void *)
//   0x7e5cd0  public: static void __cdecl UDisSeqAct_AddKey::InternalConstructor(void *)
//   0x7e5cf0  public: static void __cdecl UDisSeqAct_GiveUpgrade::InternalConstructor(void *)
//   0x7e5d10  public: static void __cdecl UDEPRECATED_DisSeqAct_AddHeartTarget::InternalConstructor(void *)
//   0x7e5d30  public: static void __cdecl UDisSeqAct_RemovePower::InternalConstructor(void *)
//   0x7e5d50  public: static void __cdecl UDisSeqAct_PlayerTrackTarget::InternalConstructor(void *)
//   0x7e5d70  public: static void __cdecl UDisSeqAct_PostProcess::InternalConstructor(void *)
//   0x7e5d90  public: static void __cdecl UDisSeqAct_RBConstraint::InternalConstructor(void *)
//   0x7e5db0  public: static void __cdecl UDisSeqAct_RemoveInventoryItem::InternalConstructor(void *)
//   0x7e5dd0  public: static void __cdecl UDisSeqAct_RestoreInventoryFromBackup::InternalConstructor(void *)
//   0x7e5df0  public: static void __cdecl UDisSeqAct_SaveLevelState::InternalConstructor(void *)
//   0x7e5e10  public: static void __cdecl UDisSeqAct_SetActiveSoundCaptureBox::InternalConstructor(void *)
//   0x7e5e30  public: static void __cdecl UDisSeqAct_SetAudioOcclusion::InternalConstructor(void *)
//   0x7e5e50  public: static void __cdecl UDisSeqAct_SetDisposition::InternalConstructor(void *)
//   0x7e5e70  public: static void __cdecl UDisSeqAct_SetPlayerTravelDestination::InternalConstructor(void *)
//   0x7e5e90  public: static void __cdecl UDisSeqAct_SetPlayerVisSettings::InternalConstructor(void *)
//   0x7e5eb0  public: static void __cdecl UDisSeqAct_SetRainEmitter::InternalConstructor(void *)
//   0x7e5ed0  public: static void __cdecl UDisSeqAct_SetStoryFlag::InternalConstructor(void *)
//   0x7e5ef0  public: static void __cdecl USeqAct_Teleport::InternalConstructor(void *)
//   0x7e5f10  public: static void __cdecl UDisSeqAct_TriggerExplosion::InternalConstructor(void *)
//   0x7e5f30  public: static void __cdecl UDisSeqAct_UberPostProcess::InternalConstructor(void *)
//   0x7e5f50  public: static void __cdecl UDisSeqAct_WatchTowerShootAtTarget::InternalConstructor(void *)
//   0x7e5f70  public: static void __cdecl UDisSeqCond_CheckStoryFlag::InternalConstructor(void *)
//   0x7e5f90  public: static void __cdecl UDisSeqCond_CompareBoolExtended::InternalConstructor(void *)
//   0x7e5fb0  public: static void __cdecl UDisSeqCond_CompareTweaks::InternalConstructor(void *)
//   0x7e5fd0  public: static void __cdecl UDisSeqCond_InStoryGroup::InternalConstructor(void *)
//   0x7e5ff0  public: static void __cdecl UDisSeqCond_IsDLCUnlocked::InternalConstructor(void *)
//   0x7e6010  public: static void __cdecl UDisSeqCond_IsDoorOpen::InternalConstructor(void *)
//   0x7e6030  public: static void __cdecl UDisSeqCond_IsSentinel::InternalConstructor(void *)
//   0x7e6050  public: static void __cdecl UDisSeqCond_PawnIsPossessed::InternalConstructor(void *)
//   0x7e6070  public: static void __cdecl UDisSeqEvent_Attention::InternalConstructor(void *)
//   0x7e6090  public: static void __cdecl UDisSeqEvent_AttentionDecreasedTo::InternalConstructor(void *)
//   0x7e60b0  public: static void __cdecl UDisSeqEvent_BehaviorStarted::InternalConstructor(void *)
//   0x7e60d0  public: static void __cdecl UDisSeqEvent_BreakableBroken::InternalConstructor(void *)
//   0x7e60f0  public: static void __cdecl UDisSeqEvent_NPCIncapacitated::InternalConstructor(void *)
//   0x7e6110  public: static void __cdecl UDisSeqEvent_DialogOutputs::InternalConstructor(void *)
//   0x7e6130  public: static void __cdecl UDisSeqEvent_Interact::InternalConstructor(void *)
//   0x7e6150  public: static void __cdecl UDisSeqEvent_PickupPickedUp::InternalConstructor(void *)
//   0x7e6170  public: static void __cdecl UDisSeqEvent_PlayerEvent::InternalConstructor(void *)
//   0x7e6190  public: static void __cdecl UDisSeqEvent_PlayerManaThreshold::InternalConstructor(void *)
//   ... 42 more, see resources/docs/symbols/functions.csv
