"""P2.2 / P2.9: import a module from the reference engine tree, or create skeleton files for a
module the reference does not have.

Usage:
  python resources/tools/import_reference.py Core [Engine ...]         copy Inc/ Src/ Classes/ from ../UnrealEngine3
  python resources/tools/import_reference.py --skeleton DishonoredGame AkAudio DisJobs
  python resources/tools/import_reference.py --diff Core               diff our copy against the reference

Records every import in resources/docs/reference_import.md, creates stub files for PDB source
files the reference lacks, and writes <Module>/Sources.cmake with the reference-only compile
units that the Shipping PDB shows Dishonored did not build (excluded, not deleted).
"""
import argparse
import collections
import csv
import re
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "source" / "Development" / "Src"
DOCS = REPO / "resources" / "docs"
SYMBOLS = DOCS / "symbols"
REFERENCE = REPO.parent / "UnrealEngine3" / "Development" / "Src"
COPY_DIRS = ("Inc", "Src", "Classes", "Resources")
SRC_EXT = {".cpp", ".h", ".inl", ".uc", ".uci", ".upkg"}
EXCLUDE_RE = re.compile(r"(UnitTest|UnMathTest|UHelpCommandlet|Test\.cpp$)", re.I)


def pdb_files_by_module() -> dict[str, set[str]]:
    key = "development\\src\\"
    out: dict[str, set[str]] = collections.defaultdict(set)
    for line in (SYMBOLS / "sourcefiles.txt").read_text(encoding="utf-8").splitlines():
        if key in line:
            rel = line.strip().split(key, 1)[1]
            module, _, rest = rel.partition("\\")
            out[module].add(rest.replace("\\", "/"))
    return out


def functions_by_file() -> dict[str, list[tuple[str, str]]]:
    key = "development\\src\\"
    out: dict[str, list[tuple[str, str]]] = collections.defaultdict(list)
    with (SYMBOLS / "functions.csv").open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if key in row["file"]:
                rel = row["file"].split(key, 1)[1].replace("\\", "/")
                out[rel].append((row["rva"], row["demangled"]))
    return out


def reference_commit() -> str:
    try:
        return subprocess.check_output(["git", "-C", str(REPO.parent / "UnrealEngine3"), "rev-parse", "--short", "HEAD"], text=True).strip()
    except Exception:
        return "unknown"


def stub_text(rel: str, funcs: list[tuple[str, str]]) -> str:
    lines = [f"// {rel}", "// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's", "// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3)."]
    if funcs:
        lines.append(f"// PDB functions attributed to this file ({len(funcs)}):")
        lines += [f"//   {rva}  {name}" for rva, name in sorted(funcs)[:200]]
        if len(funcs) > 200:
            lines.append(f"//   ... {len(funcs) - 200} more, see resources/docs/symbols/functions.csv")
    if rel.lower().endswith((".h", ".inl")):
        lines.insert(0, "#pragma once")
    return "\n".join(lines) + "\n"


def import_module(module: str, pdb: dict[str, set[str]], funcs: dict[str, list]) -> list[str]:
    src = REFERENCE / module
    dst = SOURCE / module
    if not src.exists():
        raise SystemExit(f"reference has no module {module}")
    copied = []
    for d in COPY_DIRS:
        if (src / d).exists():
            shutil.copytree(src / d, dst / d, dirs_exist_ok=True)
            copied += [p.relative_to(dst).as_posix() for p in (dst / d).rglob("*") if p.is_file()]
    pdb_set = pdb.get(module.lower(), set())
    have = {c.lower() for c in copied}
    stubs = []
    for rel in sorted(pdb_set):
        if rel.lower() not in have and Path(rel).suffix.lower() in SRC_EXT:
            path = dst / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists():
                path.write_text(stub_text(f"{module}/{rel}", funcs.get(f"{module.lower()}/{rel.lower()}", [])), encoding="utf-8")
            stubs.append(rel)
    pdb_cpp = {p.lower() for p in pdb_set if p.lower().endswith(".cpp")}
    # The PDB file list only knows files that own functions with line records, so a compile unit
    # missing from it may still be built (data-only units such as UnObjVer.cpp, or units whose
    # functions were all inlined). Only self-evident test/tool units are excluded; the rest is
    # listed for review and compiled.
    not_in_pdb = sorted(c for c in copied if c.lower().endswith(".cpp") and c.lower() not in pdb_cpp)
    excluded = [c for c in not_in_pdb if EXCLUDE_RE.search(c)]
    (dst / "Sources.cmake").write_text(
        "# Generated by resources/tools/import_reference.py.\n"
        f"# {module}_EXCLUDE: reference compile units left out of the module target (tests, tools).\n"
        f"# {module}_NOT_IN_PDB: compiled, but the Shipping PDB attributes no function to them; verify in P2.7.\n"
        f"set({module}_EXCLUDE\n" + "".join(f"  {e}\n" for e in excluded) + ")\n"
        f"set({module}_NOT_IN_PDB\n" + "".join(f"  {e}\n" for e in not_in_pdb if e not in excluded) + ")\n", encoding="utf-8")

    section = [f"## {module} — {date.today().isoformat()} (reference commit `{reference_commit()}`)", "",
               f"Copied {len(copied)} files from `../UnrealEngine3/Development/Src/{module}` ({', '.join(d for d in COPY_DIRS if (src / d).exists())}).", "",
               f"PDB lists {len(pdb_set)} source files for this module; {len(stubs)} are not in the reference and were created as stubs:", ""]
    section += [f"- `{s}`" for s in stubs] or ["- none"]
    section += ["", f"Reference compile units excluded from the target ({len(excluded)}):", ""]
    section += [f"- `{e}`" for e in excluded] or ["- none"]
    section += ["", f"Reference compile units with no PDB function attribution, compiled anyway ({len(not_in_pdb) - len(excluded)}):", ""]
    section += [f"- `{e}`" for e in not_in_pdb if e not in excluded] or ["- none"]
    write_log_section(module, "\n".join(section) + "\n")
    print(f"{module}: copied={len(copied)} stubs={len(stubs)} excluded={len(excluded)} not_in_pdb={len(not_in_pdb)}")
    return copied


def write_log_section(module: str, body: str) -> None:
    """Replace (or append) the section for one module in reference_import.md."""
    log = DOCS / "reference_import.md"
    text = log.read_text(encoding="utf-8") if log.exists() else "# Reference imports\n\nOne section per module, rewritten on every `import_reference.py` run.\n"
    marker = f"## {module} "
    parts = re.split(r"(?m)^(?=## )", text)
    parts = [p for p in parts if not p.startswith(marker) and not p.startswith(f"## {module}\n")]
    text = "".join(parts).rstrip() + "\n\n" + body
    log.write_text(text, encoding="utf-8")


def skeleton_module(module: str, pdb: dict[str, set[str]], funcs: dict[str, list]) -> None:
    dst = SOURCE / module
    files = sorted(pdb.get(module.lower(), set()))
    created = 0
    for rel in files:
        if Path(rel).suffix.lower() not in SRC_EXT:
            continue
        path = dst / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(stub_text(f"{module}/{rel}", funcs.get(f"{module.lower()}/{rel.lower()}", [])), encoding="utf-8")
            created += 1
    write_log_section(module, f"## {module} — {date.today().isoformat()} (skeleton)\n\nNot in the reference tree. {created} stub files created from the PDB file list ({len(files)} entries).\n")
    print(f"{module}: skeleton files={created} of {len(files)}")


def diff_module(module: str) -> None:
    src = REFERENCE / module
    dst = SOURCE / module
    subprocess.call(["git", "diff", "--no-index", "--stat", str(src), str(dst)])


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("modules", nargs="+")
    ap.add_argument("--skeleton", action="store_true")
    ap.add_argument("--diff", action="store_true")
    args = ap.parse_args(argv[1:])
    if args.diff:
        for m in args.modules:
            diff_module(m)
        return 0
    pdb = pdb_files_by_module()
    funcs = functions_by_file()
    for m in args.modules:
        if args.skeleton:
            skeleton_module(m, pdb, funcs)
        else:
            import_module(m, pdb, funcs)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
