"""P2.5: compiled layout probe. Generates a console program that prints sizeof/offsetof for every
PDB type a module declares, then compares its output with the PDB layout.

Members are looked up with SFINAE so a PDB member the ported header lacks prints MISSING instead of
failing the build. Types the module's main header does not declare are collected from a build log
into resources/docs/types/probe_skip_<Module>.txt and left out on the next generate.

Usage:
  python resources/tools/symbols/gen_layout_probe.py generate Core [Engine ...]
      -> source/Tests/LayoutProbe/probe_<Module>.cpp (+ probe_main.cpp, CMakeLists.txt)
  python resources/tools/symbols/gen_layout_probe.py skip-from-log Core <build.log>
      -> appends undeclared types to probe_skip_Core.txt
  python resources/tools/symbols/gen_layout_probe.py compare build/x86-debug/layout_probe.txt
      -> resources/docs/types/reference_layout_delta.md
"""
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
TYPES = REPO / "resources" / "docs" / "types"
SOURCE = REPO / "source" / "Development" / "Src"
TESTS = REPO / "source" / "Tests" / "LayoutProbe"
TYPE_NAME_RE = re.compile(r"^[UAF][A-Z]\w*$")
IDENT_RE = re.compile(r"^[A-Za-z_]\w*$")
CONTRACT = ["FName", "FNameEntry", "FString", "FArchive", "UObject", "UField", "UStruct", "UState", "UClass", "UFunction",
            "UProperty", "UByteProperty", "UIntProperty", "UBoolProperty", "UFloatProperty", "UObjectProperty", "UClassProperty",
            "UNameProperty", "UStrProperty", "UArrayProperty", "UMapProperty", "UStructProperty", "UDelegateProperty",
            "UInterfaceProperty", "UComponentProperty", "UEnum", "UScriptStruct", "UConst", "FPackageFileSummary", "FObjectExport",
            "FObjectImport", "FGenerationInfo", "FCompressedChunk", "ULinkerLoad", "ULinker", "FFrame", "FStateFrame", "UPackage"]
UNDECLARED_RE = re.compile(r"probe_(\w+)\.cpp\(\d+\): error C(?:2065|2061|2027|3861): (?:'([A-Za-z_]\w*)': undeclared identifier|syntax error: identifier '([A-Za-z_]\w*)'|use of undefined type '(?:class|struct) ([A-Za-z_]\w*)')")


def declared_types(module_dir: Path) -> set[str]:
    found = set()
    for p in list((module_dir / "Inc").rglob("*.h")) + list((module_dir / "Src").rglob("*.h")):
        text = p.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r"\b(?:class|struct)\s+(?:[A-Z_]+\s+)?([UAF][A-Z]\w*)\s*(?::[^{;]*)?\{", text):
            found.add(m.group(1))
    return found


def load_types() -> dict:
    with (TYPES / "types.json").open(encoding="utf-8") as f:
        return {t["name"]: t for t in json.load(f)["types"]}


def skip_file(module: str) -> Path:
    return TYPES / f"probe_skip_{module}.txt"


def load_skips(module: str) -> set[str]:
    p = skip_file(module)
    return {l.strip() for l in p.read_text(encoding="utf-8").splitlines() if l.strip() and not l.startswith("#")} if p.exists() else set()


def probe_members(t: dict) -> list[dict]:
    out = []
    for m in t["members"]:
        if m["is_base"] or m["is_vftable"] or m.get("bits") is not None or not IDENT_RE.match(m["name"] or ""):
            continue
        if "&" in m["type"] or m["name"] in ("__vftable", "__vecDelDtor"):
            continue
        out.append(m)
    return out


def generate(modules: list[str]) -> None:
    types = load_types()
    TESTS.mkdir(parents=True, exist_ok=True)
    all_names = []
    for module in modules:
        skips = load_skips(module)
        names = sorted(n for n in declared_types(SOURCE / module) if n in types and TYPE_NAME_RE.match(n) and n not in skips)
        all_names.append((module, names))
        lines = [f"// Generated by resources/tools/symbols/gen_layout_probe.py for module {module}",
                 "#define _ALLOW_KEYWORD_MACROS 1  // MSVC STL xkeycheck: allow macroizing private/protected in this probe only",
                 "#define private public", "#define protected public",
                 f"#include \"{module}.h\"", "#undef private", "#undef protected",
                 "#include <cstdio>", "#include <cstddef>", "#include <type_traits>",
                 "#define OFF(T, m) (reinterpret_cast<size_t>(&reinterpret_cast<T*>(0x10000)->m) - 0x10000)",
                 "namespace {"]
        detectors = []
        body = []
        for n in names:
            body.append(f"    std::printf(\"{n},%zu\\n\", sizeof({n}));")
            for m in probe_members(types[n]):
                tag = f"{n}_{m['name']}"
                detectors.append(f"template<class U, class = void> struct Has_{tag} : std::false_type {{}};")
                detectors.append(f"template<class U> struct Has_{tag}<U, std::void_t<decltype(&U::{m['name']})>> : std::true_type {{}};")
                body.append(f"    if constexpr (Has_{tag}<{n}>::value) std::printf(\"{n}.{m['name']},%zu\\n\", OFF({n}, {m['name']})); else std::printf(\"{n}.{m['name']},MISSING\\n\");")
        lines += detectors + ["}", "", f"void probe_{module}()", "{"] + body + ["}", ""]
        (TESTS / f"probe_{module}.cpp").write_text("\n".join(lines), encoding="utf-8")
        print(f"{module}: {len(names)} types ({len(skips)} skipped) -> {TESTS / f'probe_{module}.cpp'}")
    main_lines = ["// Generated by resources/tools/symbols/gen_layout_probe.py", "#include <cstdio>"]
    main_lines += [f"void probe_{m}();" for m, _ in all_names]
    main_lines += ["int main()", "{"] + [f"    probe_{m}();" for m, _ in all_names] + ["    return 0;", "}", ""]
    (TESTS / "probe_main.cpp").write_text("\n".join(main_lines), encoding="utf-8")
    cmake = ["# Generated by resources/tools/symbols/gen_layout_probe.py",
             "add_executable(LayoutProbe probe_main.cpp " + " ".join(f"probe_{m}.cpp" for m, _ in all_names) + ")",
             "target_link_libraries(LayoutProbe PRIVATE " + " ".join(m for m, _ in all_names) + ")",
             "dishonored_apply_defines(LayoutProbe)",
             "target_compile_options(LayoutProbe PRIVATE ${DISHONORED_MSVC_WARNINGS} /wd4589 /bigobj)",
             "set_target_properties(LayoutProbe PROPERTIES FOLDER \"Tests\")",
             "add_custom_command(TARGET LayoutProbe POST_BUILD COMMAND LayoutProbe > \"${CMAKE_BINARY_DIR}/layout_probe.txt\" COMMENT \"layout probe -> layout_probe.txt\")", ""]
    (TESTS / "CMakeLists.txt").write_text("\n".join(cmake), encoding="utf-8")


def skip_from_log(module: str, log: Path) -> None:
    text = log.read_text(encoding="utf-8", errors="replace")
    found = set()
    for m in UNDECLARED_RE.finditer(text):
        if m.group(1) == module:
            found.add(m.group(2) or m.group(3) or m.group(4))
    skips = load_skips(module)
    new = sorted(n for n in found if TYPE_NAME_RE.match(n) and n not in skips)
    p = skip_file(module)
    with p.open("a", encoding="utf-8") as f:
        if not skips:
            f.write(f"# Types the {module} module's main header does not declare (collected from probe build logs)\n")
        f.write("".join(n + "\n" for n in new))
    print(f"{module}: {len(new)} new skips (total {len(skips) + len(new)}) -> {p.relative_to(REPO)}")


def compare(probe_output: Path) -> int:
    types = load_types()
    sizes = {}
    offsets = {}
    missing_members = set()
    for line in probe_output.read_text(encoding="utf-8", errors="replace").splitlines():
        if "," not in line:
            continue
        key, val = line.rsplit(",", 1)
        if "." in key:
            t, m = key.split(".", 1)
            if val.strip() == "MISSING":
                missing_members.add((t, m))
            else:
                offsets[(t, m)] = int(val)
        else:
            sizes[key] = int(val)
    rows = []
    for name in sorted(sizes):
        pdb = types[name]
        bad = []
        missing = []
        for m in probe_members(pdb):
            got = offsets.get((name, m["name"]))
            if got is None:
                missing.append(m["name"])
            elif got != m["offset"]:
                bad.append((m["name"], m["offset"], got))
        rows.append((name, pdb["size"], sizes[name], pdb["size"] == sizes[name], bad, missing))
    contract = [r for r in rows if r[0] in CONTRACT]
    contract_bad = [r for r in contract if not r[3] or r[4] or r[5]]
    exact = sum(1 for r in rows if r[3] and not r[4] and not r[5])
    out = TYPES / "reference_layout_delta.md"
    with out.open("w", encoding="utf-8") as f:
        f.write("# Compiled layout delta: ported headers vs 2012 Shipping PDB\n\n")
        f.write(f"Generated by `gen_layout_probe.py compare` from `{probe_output.name}`. {len(rows)} types probed; {exact} match exactly (size and every member offset).\n\n")
        f.write(f"## Contract types ({len(contract)} probed, {len(contract_bad)} mismatching)\n\n| Type | PDB size | Ours | Size ok | Offset mismatches (member: pdb→ours) | Missing members (Arkane additions) |\n|---|---:|---:|---|---|---|\n")
        for name, ps, os_, ok, bad, missing in contract:
            f.write(f"| {name} | {ps} | {os_} | {'yes' if ok else '**no**'} | {', '.join(f'{m}: {p}→{g}' for m, p, g in bad[:8])} | {', '.join(missing[:8])} |\n")
        f.write("\n## All other probed types with differences\n\n| Type | PDB size | Ours | First offset mismatch | Missing members |\n|---|---:|---:|---|---|\n")
        for name, ps, os_, ok, bad, missing in rows:
            if name in CONTRACT or (ok and not bad and not missing):
                continue
            first = f"{bad[0][0]}: {bad[0][1]}→{bad[0][2]}" if bad else ""
            f.write(f"| {name} | {ps} | {os_} | {first} | {', '.join(missing[:4])} |\n")
    print(f"probed={len(rows)} exact={exact} contract_mismatches={len(contract_bad)} -> {out}")
    return 1 if contract_bad else 0


def main(argv: list[str]) -> int:
    if len(argv) < 2 or argv[1] not in ("generate", "compare", "skip-from-log"):
        print(__doc__)
        return 2
    if argv[1] == "generate":
        generate(argv[2:] or ["Core"])
        return 0
    if argv[1] == "skip-from-log":
        skip_from_log(argv[2], Path(argv[3]))
        return 0
    return compare(Path(argv[2]))


if __name__ == "__main__":
    sys.exit(main(sys.argv))
