"""P2.5: generate static_assert size checks from the PDB type sizes for classes a module declares.

For every non-template U*/A*/F* type in resources/docs/types/sizes.csv that is declared in the
module's headers, emit `static_assert(sizeof(T) == N, ...)`. The header is included at the end of
the module's main header behind DISHONORED_LAYOUT_CHECKS.

Usage: python resources/tools/symbols/gen_layout_asserts.py Core [Engine ...]
Writes source/Development/Src/<Module>/Inc/DishonoredLayouts.h
"""
import csv
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SIZES = REPO / "resources" / "docs" / "types" / "sizes.csv"
SOURCE = REPO / "source" / "Development" / "Src"
TYPE_NAME_RE = re.compile(r"^[UAF][A-Z]\w*$")
# types whose PDB size is an artifact of the build (empty, or whose layout we deliberately change)
SKIP = {"FScopedLock", "FRandomStream"}


def declared_types(module_dir: Path) -> set[str]:
    found = set()
    for p in list((module_dir / "Inc").rglob("*.h")) + list((module_dir / "Src").rglob("*.h")):
        text = p.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r"\b(?:class|struct)\s+(?:[A-Z_]+\s+)?([UAF][A-Z]\w*)\s*(?::[^{;]*)?\{", text):
            found.add(m.group(1))
    return found


def main(argv: list[str]) -> int:
    modules = argv[1:] or ["Core"]
    with SIZES.open(newline="", encoding="utf-8") as f:
        sizes = {r["name"]: int(r["size"]) for r in csv.DictReader(f) if TYPE_NAME_RE.match(r["name"]) and int(r["size"]) > 1}
    for module in modules:
        module_dir = SOURCE / module
        declared = declared_types(module_dir)
        names = sorted(n for n in declared if n in sizes and n not in SKIP)
        out = module_dir / "Inc" / "DishonoredLayouts.h"
        lines = ["// Generated by resources/tools/symbols/gen_layout_asserts.py from the 2012 Shipping PDB",
                 "// (resources/docs/types/sizes.csv). A failing assert means the ported header's layout differs",
                 "// from Dishonored's; fix the header and cite the PDB member in a // DISHONORED(layout) comment.",
                 "#pragma once", "#if DISHONORED_LAYOUT_CHECKS", ""]
        lines += [f"static_assert(sizeof({n}) == {sizes[n]}, \"{n}: Dishonored PDB size is {sizes[n]}\");" for n in names]
        lines += ["", "#endif // DISHONORED_LAYOUT_CHECKS", ""]
        out.write_text("\n".join(lines), encoding="utf-8")
        print(f"{module}: {len(names)} size checks -> {out.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
