"""P2.5: compiled layout probe. Generates a console program that prints sizeof/offsetof for every
PDB type a module declares, then compares its output with the PDB layout.

Usage:
  python resources/tools/symbols/gen_layout_probe.py generate Core [Engine ...]
      -> source/Tests/LayoutProbe/probe_<Module>.cpp (+ probe_main.cpp)
  python resources/tools/symbols/gen_layout_probe.py compare build/x86-debug/layout_probe.txt
      -> resources/docs/types/reference_layout_delta.md
"""
import csv
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
TYPES = REPO / "resources" / "docs" / "types"
SOURCE = REPO / "source" / "Development" / "Src"
TESTS = REPO / "source" / "Tests" / "LayoutProbe"
TYPE_NAME_RE = re.compile(r"^[UAF][A-Z]\w*$")
IDENT_RE = re.compile(r"^[A-Za-z_]\w*$")
CONTRACT = ["FName", "FNameEntry", "FString", "FArchive", "UObject", "UField", "UStruct", "UState", "UClass", "UFunction",
            "UProperty", "UByteProperty", "UIntProperty", "UBoolProperty", "UFloatProperty", "UObjectProperty", "UClassProperty",
            "UNameProperty", "UStrProperty", "UArrayProperty", "UMapProperty", "UStructProperty", "UDelegateProperty",
            "UInterfaceProperty", "UComponentProperty", "UEnum", "UScriptStruct", "UConst", "FPackageFileSummary", "FObjectExport",
            "FObjectImport", "FGenerationInfo", "FCompressedChunk", "ULinkerLoad", "ULinker", "FFrame", "FStateFrame", "UPackage"]


def declared_types(module_dir: Path) -> set[str]:
    found = set()
    for p in list((module_dir / "Inc").rglob("*.h")) + list((module_dir / "Src").rglob("*.h")):
        text = p.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r"\b(?:class|struct)\s+(?:[A-Z_]+\s+)?([UAF][A-Z]\w*)\s*(?::[^{;]*)?\{", text):
            found.add(m.group(1))
    return found


def load_types() -> dict:
    with (TYPES / "types.json").open(encoding="utf-8") as f:
        return {t["name"]: t for t in json.load(f)["types"]}


def generate(modules: list[str]) -> None:
    types = load_types()
    TESTS.mkdir(parents=True, exist_ok=True)
    all_names = []
    for module in modules:
        names = sorted(n for n in declared_types(SOURCE / module) if n in types and TYPE_NAME_RE.match(n))
        all_names.append((module, names))
        lines = [f"// Generated by resources/tools/symbols/gen_layout_probe.py for module {module}",
                 "#define private public", "#define protected public",
                 f"#include \"{module}.h\"", "#undef private", "#undef protected",
                 "#include <cstdio>", "#include <cstddef>",
                 "#define OFF(T, m) (reinterpret_cast<size_t>(&reinterpret_cast<T*>(0x10000)->m) - 0x10000)",
                 f"void probe_{module}()", "{"]
        for n in names:
            lines.append(f"    std::printf(\"{n},%zu\\n\", sizeof({n}));")
            for m in types[n]["members"]:
                if m["is_base"] or m["is_vftable"] or m.get("bits") is not None or not IDENT_RE.match(m["name"] or ""):
                    continue
                if "&" in m["type"] or m["name"] in ("__vftable", "__vecDelDtor"):
                    continue
                lines.append(f"    std::printf(\"{n}.{m['name']},%zu\\n\", OFF({n}, {m['name']}));")
        lines += ["}", ""]
        (TESTS / f"probe_{module}.cpp").write_text("\n".join(lines), encoding="utf-8")
        print(f"{module}: {len(names)} types -> {TESTS / f'probe_{module}.cpp'}")
    main_lines = ["// Generated by resources/tools/symbols/gen_layout_probe.py", "#include <cstdio>"]
    main_lines += [f"void probe_{m}();" for m, _ in all_names]
    main_lines += ["int main()", "{"] + [f"    probe_{m}();" for m, _ in all_names] + ["    return 0;", "}", ""]
    (TESTS / "probe_main.cpp").write_text("\n".join(main_lines), encoding="utf-8")
    cmake = ["# Generated by resources/tools/symbols/gen_layout_probe.py",
             "add_executable(LayoutProbe probe_main.cpp " + " ".join(f"probe_{m}.cpp" for m, _ in all_names) + ")",
             "target_link_libraries(LayoutProbe PRIVATE " + " ".join(m for m, _ in all_names) + ")",
             "dishonored_apply_defines(LayoutProbe)",
             "target_compile_options(LayoutProbe PRIVATE ${DISHONORED_MSVC_WARNINGS} /wd4589)",
             "set_target_properties(LayoutProbe PROPERTIES FOLDER \"Tests\")",
             "add_custom_command(TARGET LayoutProbe POST_BUILD COMMAND LayoutProbe > \"${CMAKE_BINARY_DIR}/layout_probe.txt\" COMMENT \"layout probe -> layout_probe.txt\")", ""]
    (TESTS / "CMakeLists.txt").write_text("\n".join(cmake), encoding="utf-8")


def compare(probe_output: Path) -> int:
    types = load_types()
    sizes = {}
    offsets = {}
    for line in probe_output.read_text(encoding="utf-8", errors="replace").splitlines():
        if "," not in line:
            continue
        key, val = line.rsplit(",", 1)
        if "." in key:
            t, m = key.split(".", 1)
            offsets[(t, m)] = int(val)
        else:
            sizes[key] = int(val)
    rows = []
    for name in sorted(sizes):
        pdb = types[name]
        size_ok = pdb["size"] == sizes[name]
        bad = []
        missing = []
        for m in pdb["members"]:
            if m["is_base"] or m["is_vftable"] or m.get("bits") is not None or not IDENT_RE.match(m["name"] or ""):
                continue
            got = offsets.get((name, m["name"]))
            if got is None:
                missing.append(m["name"])
            elif got != m["offset"]:
                bad.append((m["name"], m["offset"], got))
        rows.append((name, pdb["size"], sizes[name], size_ok, bad, missing))
    contract = [r for r in rows if r[0] in CONTRACT]
    contract_bad = [r for r in contract if not r[3] or r[4] or r[5]]
    out = TYPES / "reference_layout_delta.md"
    with out.open("w", encoding="utf-8") as f:
        f.write("# Compiled layout delta: ported headers vs 2012 Shipping PDB\n\n")
        f.write(f"Generated by `gen_layout_probe.py compare` from `{probe_output.name}`. {len(rows)} types probed; ")
        f.write(f"{sum(1 for r in rows if r[3] and not r[4] and not r[5])} match exactly.\n\n")
        f.write(f"## Contract types ({len(contract)} probed, {len(contract_bad)} mismatching)\n\n| Type | PDB size | Ours | Size ok | Offset mismatches (member: pdb→ours) | Missing members |\n|---|---:|---:|---|---|---|\n")
        for name, ps, os_, ok, bad, missing in contract:
            f.write(f"| {name} | {ps} | {os_} | {'yes' if ok else '**no**'} | {', '.join(f'{m}: {p}→{g}' for m, p, g in bad[:6])} | {', '.join(missing[:6])} |\n")
        f.write("\n## All other probed types with differences\n\n| Type | PDB size | Ours | First offset mismatch | Missing members |\n|---|---:|---:|---|---|\n")
        for name, ps, os_, ok, bad, missing in rows:
            if name in CONTRACT or (ok and not bad and not missing):
                continue
            first = f"{bad[0][0]}: {bad[0][1]}→{bad[0][2]}" if bad else ""
            f.write(f"| {name} | {ps} | {os_} | {first} | {', '.join(missing[:4])} |\n")
    print(f"probed={len(rows)} contract_mismatches={len(contract_bad)} -> {out}")
    return 1 if contract_bad else 0


def main(argv: list[str]) -> int:
    if len(argv) < 2 or argv[1] not in ("generate", "compare"):
        print(__doc__)
        return 2
    if argv[1] == "generate":
        generate(argv[2:] or ["Core"])
        return 0
    return compare(Path(argv[2]))


if __name__ == "__main__":
    sys.exit(main(sys.argv))
