"""P2.5: generate static_assert size checks from the PDB type sizes for classes a module declares.

For every non-template U*/A*/F* type in resources/docs/types/sizes.csv that is declared in the
module's headers, emit `static_assert(sizeof(T) == N, ...)`. The header is included at the end of
the module's main header behind DISHONORED_LAYOUT_CHECKS.

The contract types of gen_layout_probe.py are always asserted. Other types are asserted only when
the latest probe output (build/<dir>/layout_probe.txt, passed with --probe) shows their size already
matches; the rest are listed as `// pending:` lines so Core keeps compiling while they converge.

Dishonored was built with /Zp4 (UE3 VCToolChain.cs); the generated header first checks that packing
and reports it as one clear error instead of hundreds of size mismatches.

Usage: python resources/tools/symbols/gen_layout_asserts.py [--probe build/agentA/layout_probe.txt] [--dry-run] Core [Engine ...]
Writes source/Development/Src/<Module>/Inc/DishonoredLayouts.h
"""
import csv
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_layout_probe import CONTRACT, load_skips, retail_sizes  # noqa: E402

REPO = Path(__file__).resolve().parents[3]
SIZES = REPO / "resources" / "docs" / "types" / "sizes.csv"
SOURCE = REPO / "source" / "Development" / "Src"
TYPE_NAME_RE = re.compile(r"^[UAF][A-Z]\w*$")
# types whose PDB size is an artifact of the build (empty, or whose layout we deliberately change)
SKIP = {"FScopedLock", "FRandomStream"}


def declared_types(module_dir: Path) -> set[str]:
    found = set()
    for p in list((module_dir / "Inc").rglob("*.h")) + list((module_dir / "Src").rglob("*.h")):
        # preprocessor lines are dropped so `class UObject #if ... : public UObjectBase #endif {` still matches
        text = "\n".join(l for l in p.read_text(encoding="utf-8", errors="replace").splitlines() if not l.lstrip().startswith("#"))
        for m in re.finditer(r"\b(?:class|struct)\s+(?:[A-Z_]+\s+)?([UAF][A-Z]\w*)\s*(?::[^{;]*)?\{", text):
            found.add(m.group(1))
    return found


INCLUDE_RE = re.compile(r'^\s*#\s*include\s+"([^"]+)"', re.M)


def reachable_headers(module_dir: Path) -> set[Path]:
    """Headers included, transitively, by <Module>.h (quoted includes resolved inside the module's Inc/Src);
    the layout header is included at the end of <Module>.h, so only types declared there are complete."""
    roots = [module_dir / "Inc", module_dir / "Src"] + [d for d in (module_dir / "Inc").iterdir() if d.is_dir()]
    seen = set()
    todo = [module_dir / "Inc" / f"{module_dir.name}.h"]
    while todo:
        p = todo.pop()
        if p in seen or not p.exists():
            continue
        seen.add(p)
        for inc in INCLUDE_RE.findall(p.read_text(encoding="utf-8", errors="replace")):
            for r in roots:
                q = r / Path(inc).name
                if q.exists():
                    todo.append(q)
                    break
    return seen


def probed_sizes(probe: Path | None) -> dict[str, int]:
    if probe is None or not probe.exists():
        return {}
    out = {}
    for line in probe.read_text(encoding="utf-8", errors="replace").splitlines():
        if "," in line and "." not in line.split(",", 1)[0]:
            name, val = line.rsplit(",", 1)
            out[name] = int(val)
    return out


def main(argv: list[str]) -> int:
    probe = None
    args = argv[1:]
    if args and args[0] == "--probe":
        probe = REPO / args[1]
        args = args[2:]
    dry_run = False
    if args and args[0] == "--dry-run":
        dry_run = True
        args = args[1:]
    modules = args or ["Core"]
    with SIZES.open(newline="", encoding="utf-8") as f:
        sizes = {r["name"]: int(r["size"]) for r in csv.DictReader(f) if TYPE_NAME_RE.match(r["name"]) and int(r["size"]) > 1}
    ours = probed_sizes(probe)
    retail = retail_sizes()
    for module in modules:
        module_dir = SOURCE / module
        # probe_skip_<Module>.txt lists declared types the module's main header does not reach
        skips = SKIP | load_skips(module)
        reachable = reachable_headers(module_dir)
        declared = set()
        for p in reachable:
            text = "\n".join(l for l in p.read_text(encoding="utf-8", errors="replace").splitlines() if not l.lstrip().startswith("#"))
            declared |= {m.group(1) for m in re.finditer(r"\b(?:class|struct)\s+(?:[A-Z_]+\s+)?([UAF][A-Z]\w*)\s*(?::[^{;]*)?\{", text)}
        # types the probe never saw (guarded out, template-only) would be incomplete here as well
        names = sorted(n for n in declared if n in sizes and n not in skips and (not ours or n in ours))
        unreachable = sorted(n for n in declared_types(module_dir) if n in sizes and n not in skips and n not in declared)
        out = module_dir / "Inc" / "DishonoredLayouts.h"
        lines = ["// Generated by resources/tools/symbols/gen_layout_asserts.py. Sizes are the retail 2013 sizeof",
                 "// (resources/docs/types/native_class_sizes.csv) where the class exists in the retail exe, else the",
                 "// 2012 Shipping PDB size (resources/docs/types/sizes.csv). A failing assert means the ported header's",
                 "// layout differs from Dishonored's; fix the header and cite the evidence in a // DISHONORED(layout) comment.",
                 "// `pending` types are declared but not yet converged (see types/reference_layout_delta.md).",
                 "#pragma once", "#if DISHONORED_LAYOUT_CHECKS", "",
                 f"struct FDishonoredPackingProbe{module} {{ BYTE A; QWORD B; }};",
                 f"static_assert(sizeof(FDishonoredPackingProbe{module}) == 12, \"Dishonored is built with 4-byte struct packing (/Zp4, UE3 VCToolChain.cs); add /Zp4 to the compile options\");",
                 ""]
        asserted = pending = 0
        for n in names:
            target = retail.get(n, sizes[n])
            why = f"retail 2013 size is {target}" + (f" (2012 PDB: {sizes[n]})" if target != sizes[n] else "") if n in retail else f"Dishonored PDB size is {target}"
            if n in CONTRACT or ours.get(n) == target:
                lines.append(f"static_assert(sizeof({n}) == {target}, \"{n}: {why}\");")
                asserted += 1
            else:
                lines.append(f"// pending: sizeof({n}) == {target}" + (f" (ours {ours[n]})" if n in ours else ""))
                pending += 1
        if unreachable:
            lines += ["", f"// not reachable from {module}.h (declared in headers the module's .cpp files include on their own), not asserted:",
                      "// " + ", ".join(unreachable)]
        lines += ["", "#endif // DISHONORED_LAYOUT_CHECKS", ""]
        if dry_run:
            print(f"{module}: dry run: {asserted} size checks, {pending} pending, {len(unreachable)} unreachable")
            continue
        out.write_text("\n".join(lines), encoding="utf-8")
        print(f"{module}: {asserted} size checks, {pending} pending, {len(unreachable)} unreachable -> {out.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
