"""P2.6: regenerate Core/Inc/UnNames.h from the hardcoded FName table recovered from the 2012 exe.

The exact index of every hardcoded name is kept (resources/docs/symbols/hardcoded_names.csv).
Names that the reference sources still use as NAME_<X> but Dishonored never hardcoded are appended
from index 1301 upward, marked reference-only, so the ported code keeps compiling. Those extra
names never appear in cooked data (package name tables are per-package), so the indices are free.

Usage: python resources/tools/symbols/gen_unnames.py [--check]
"""
import argparse
import csv
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
CSV = REPO / "resources" / "docs" / "symbols" / "hardcoded_names.csv"
SOURCE = REPO / "source" / "Development" / "Src"
TARGET = SOURCE / "Core" / "Inc" / "UnNames.h"
REFERENCE = REPO.parent / "UnrealEngine3" / "Development" / "Src" / "Core" / "Inc" / "UnNames.h"
REGISTER_RE = re.compile(r"^\s*REGISTER_NAME\(\s*(\d+)\s*,\s*(\w+)\s*\)", re.M)
NAME_USE_RE = re.compile(r"\bNAME_([A-Za-z_]\w*)\b")
NOT_NAMES = {"None_", "MAX", "Nonexistent", "Undefined", "Index", "Unique", "Hash", "No_Number", "NO_NUMBER"}
EXTRA_START = 1301


def load_csv() -> dict[int, str]:
    with CSV.open(newline="", encoding="utf-8") as f:
        return {int(r["index"]): r["name"] for r in csv.DictReader(f)}


def names_used_in_sources() -> set[str]:
    used = set()
    for p in SOURCE.rglob("*"):
        if p.suffix.lower() in (".cpp", ".h", ".inl") and p.name != "UnNames.h":
            used.update(NAME_USE_RE.findall(p.read_text(encoding="utf-8", errors="replace")))
    return used


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify the generated header matches the CSV; exit 1 otherwise")
    args = ap.parse_args(argv[1:])
    table = load_csv()

    if args.check:
        text = TARGET.read_text(encoding="utf-8")
        got = {int(i): n for i, n in REGISTER_RE.findall(text) if int(i) < EXTRA_START}
        bad = [(i, table.get(i), got.get(i)) for i in sorted(set(table) | set(got)) if table.get(i) != got.get(i)]
        for i, want, have in bad[:20]:
            print(f"index {i}: csv={want!r} header={have!r}")
        print(f"{len(got)} hardcoded names in header, {len(table)} in csv, {len(bad)} mismatches")
        return 1 if bad else 0

    ref = REFERENCE.read_text(encoding="utf-8", errors="replace")
    matches = list(REGISTER_RE.finditer(ref))
    preamble = ref[: matches[0].start()]
    trailer = ref[matches[-1].end():]
    trailer = trailer[trailer.find("\n") + 1:] if "\n" in trailer else trailer
    reference_names = {n for _, n in REGISTER_RE.findall(ref)}

    invalid = [n for n in table.values() if not re.match(r"^[A-Za-z_]\w*$", n)]
    if invalid:
        print(f"warning: {len(invalid)} hardcoded names are not identifiers and were skipped: {invalid[:10]}", file=sys.stderr)
    # Only names the reference's own table registers are real FNames; scanning the sources for
    # NAME_<X> tokens would also pick up macros and typedefs (NAME_INDEX, NAME_PROBEMIN, ...).
    have = set(table.values())
    extras = sorted(n for n in reference_names if n not in have and n not in NOT_NAMES and re.match(r"^[A-Za-z_]\w*$", n))
    unused_extras = sorted(n for n in extras if n not in names_used_in_sources())
    print(f"{len(unused_extras)} of the reference-only names are not referenced by the imported sources", file=sys.stderr)
    probe_defines = [l for l in ref.splitlines() if l.startswith("#define NAME_PROBE")]

    lines = [preamble.rstrip("\n"), "",
             "// DISHONORED: table regenerated by resources/tools/symbols/gen_unnames.py from the 2012 exe",
             "// (FName::StaticInit). Indices must stay exactly as listed; do not renumber.",
             ""]
    width = max(len(n) for n in table.values()) + 1
    for index in sorted(table):
        name = table[index]
        if re.match(r"^[A-Za-z_]\w*$", name):
            lines.append(f"REGISTER_NAME({index:4d}, {name.ljust(width)})")
    lines += ["", "// DISHONORED: names below are not hardcoded in Dishonored but are referenced as NAME_<X> by the",
              "// reference engine sources. They only exist so that code compiles; indices from 1301 are free.",
              "#ifndef DISHONORED_NO_REFERENCE_NAMES"]
    for i, name in enumerate(extras):
        lines.append(f"REGISTER_NAME({EXTRA_START + i:4d}, {name.ljust(width)}) // reference-only")
    lines += ["#endif", ""]
    lines += ["// Special engine-generated probe messages (kept from the reference header)"] + probe_defines + [""]
    lines += [trailer.lstrip("\n")]
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(table)} hardcoded names + {len(extras)} reference-only names -> {TARGET.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
