"""P1.10: per-module size map from the joined functions.csv.

Writes docs/module_map.md and seeds docs/progress.md.
Usage: python resources/tools/symbols/module_map.py [suffix]
"""
import collections
import csv
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SYMBOLS = REPO / "resources" / "docs" / "symbols"
PHASE3_ORDER = [
    "core", "engine", "gameframework", "ipdrv", "onlinesubsystemsteamworks",
    "windrv", "d3d9drv", "akaudio", "gfxui", "dishonoredgame", "disjobs", "launch",
]
EDITOR_MODULES = {"unrealed", "unrealedclr", "dishonorededitor", "gfxuieditor", "unrealswarm", "edgetool"}


def main(argv: list[str]) -> int:
    suffix = argv[1] if len(argv) > 1 else ""
    funcs = collections.Counter()
    size = collections.Counter()
    files = collections.defaultdict(set)
    origin_of = {}
    total_bytes = 0
    with (SYMBOLS / f"functions{suffix}.csv").open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            key = row["module"] or f"<{row['origin']}>"
            origin_of[key] = row["origin"]
            n = int(row["size"])
            funcs[key] += 1
            size[key] += n
            total_bytes += n
            if row["file"]:
                files[key].add(row["file"])

    nofile_buckets = []
    summary = SYMBOLS / f"functions_nofile_summary{suffix}.md"
    if summary.exists():
        for line in summary.read_text(encoding="utf-8").splitlines():
            if line.startswith("| `"):
                nofile_buckets.append(line)

    out = REPO / "resources" / "docs" / f"module_map{suffix}.md"
    with out.open("w", encoding="utf-8") as f:
        f.write("# Module map (2012 Shipping)\n\n")
        f.write(f"Generated by `tools/symbols/module_map.py` from `docs/symbols/functions{suffix}.csv`. ")
        f.write(f"Total: {sum(funcs.values()):,} functions, {total_bytes:,} bytes of code.\n\n")

        f.write("## Game modules (`Development\\Src\\<Module>`)\n\n| Module | Source files | Functions | Code bytes | % of code | Scope |\n|---|---:|---:|---:|---:|---|\n")
        game = [(k, v) for k, v in size.most_common() if origin_of[k] == "game"]
        for k, b in game:
            scope = "editor (out of scope)" if k in EDITOR_MODULES else "runtime"
            f.write(f"| {k} | {len(files[k])} | {funcs[k]:,} | {b:,} | {100.0 * b / total_bytes:.1f} | {scope} |\n")

        f.write("\n## External libraries\n\nRows with source files come from `Development\\External\\<Lib>` line records; rows without come from the static library the linker pulled the code from (section contributions).\n\n| Library | Source files | Functions | Code bytes | % of code |\n|---|---:|---:|---:|---:|\n")
        for k, b in size.most_common():
            if origin_of[k].startswith(("external:", "lib:")):
                f.write(f"| {k} | {len(files[k])} | {funcs[k]:,} | {b:,} | {100.0 * b / total_bytes:.1f} |\n")

        f.write("\n## Other\n\n| Origin | Functions | Code bytes | % of code |\n|---|---:|---:|---:|\n")
        for k, b in size.most_common():
            if origin_of[k] in ("crt", "unknown"):
                f.write(f"| {k} | {funcs[k]:,} | {b:,} | {100.0 * b / total_bytes:.1f} |\n")

        if nofile_buckets:
            f.write("\n## Functions without line info, by namespace / prefix\n\nStatic libraries shipped without source line records (Scaleform, FaceFX, PathEngine, PhysX inline code, ...). See `docs/symbols/functions_nofile_summary.md`.\n\n| Bucket | Functions | Bytes |\n|---|---:|---:|\n")
            f.write("\n".join(nofile_buckets) + "\n")

        f.write("\n## Phase 3 order (runtime modules, dependency order)\n\n| # | Module | Functions | Code bytes |\n|---:|---|---:|---:|\n")
        for i, k in enumerate(PHASE3_ORDER, 1):
            f.write(f"| {i} | {k} | {funcs.get(k, 0):,} | {size.get(k, 0):,} |\n")

    progress = REPO / "resources" / "docs" / "progress.md"
    if not progress.exists():
        with progress.open("w", encoding="utf-8") as f:
            f.write("# Phase 3 progress\n\nOne row per runtime module. `rewritten` = hand-written and compiling; `stubbed` = present but empty/placeholder; `verified` = behavior checked against the reference build.\n\n")
            f.write("| Module | Functions | Rewritten | Stubbed | Verified | % rewritten |\n|---|---:|---:|---:|---:|---:|\n")
            for k in PHASE3_ORDER:
                f.write(f"| {k} | {funcs.get(k, 0):,} | 0 | 0 | 0 | 0.0 |\n")
    print(f"wrote {out}; total functions={sum(funcs.values())} bytes={total_bytes}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
