// Engine/debugger/undebuggercore.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (76):
//   0x5676b0  public: virtual void __thiscall UDebuggerCore::NotifyBeginTick(void)
//   0x5676c0  public: class UClass * __thiscall UDebuggerCore::GetStackOwnerClass(struct FFrame const *)const
//   0x5676e0  ParseNextName
//   0x567760  public: virtual unsigned int __thiscall FDebuggerWatch::GetWatchValue(class UProperty const * &, unsigned char const * &, int &)
//   0x5677a0  public: virtual unsigned int __thiscall FDebuggerDataWatch::Modified(void)const
//   0x5677c0  protected: virtual void __thiscall FDebuggerWatchNode::ResetBase(class UClass const *, class UObject const *, class UFunction const *, unsigned char const *, struct FFrame const *)
//   0x567830  public: virtual int __thiscall FDebuggerWatchNode::GetArrayIndex(void)const
//   0x567860  public: virtual __thiscall DSBreakOnChange::~DSBreakOnChange(void)
//   0x5678d0  protected: virtual void __thiscall DSBreakOnChange::SetCurrentNode(class FStackNode const *)
//   0x5678f0  protected: virtual class FDebuggerState * __thiscall DSBreakOnChange::GetCurrent(void)
//   0x567910  public: virtual class FStackNode const * __thiscall DSBreakOnChange::GetCurrentNode(void)const
//   0x567930  public: virtual unsigned int __thiscall DSBreakOnChange::InterceptNewState(class FDebuggerState *)
//   0x567980  public: virtual unsigned int __thiscall DSBreakOnChange::InterceptOldState(class FDebuggerState *)
//   0x5679d0  public: void __thiscall UDebuggerCore::ProcessPendingState(void)
//   0x5683a0  IsValidObject
//   0x5683d0  public: virtual void __thiscall FDebuggerWatch::Refresh(class UObject const *, struct FFrame const *)
//   0x568460  public: virtual void __thiscall DSBreakOnChange::HandleInput(enum EUserAction)
//   0x5684b0  protected: virtual void __thiscall DSWaitForInput::PumpMessages(void)
//   0x568a80  public: void __thiscall UDebuggerCore::AttachScriptDebugger(unsigned int)
//   0x568b00  public: void __thiscall UDebuggerCore::StackChanged(class FStackNode const *)
//   0x568b90  public: void __thiscall FStackNode::Update(int, int, unsigned char, int)
//   0x568be0  public: virtual void __thiscall FDebuggerArrayNode::ResetBase(class UClass const *, class UObject const *, class UFunction const *, unsigned char const *, struct FFrame const *)
//   0x568c80  public: unsigned int __thiscall FBreakpointManager::QueryBreakpoint(wchar_t const *, int)
//   0x568d40  public: __thiscall FDebuggerState::FDebuggerState(class UDebuggerCore * const)
//   0x568db0  public: void __thiscall FDebuggerState::UpdateStackInfo(class FStackNode const *)
//   0x568e00  public: __thiscall DSIdleState::DSIdleState(class UDebuggerCore * const)
//   0x568e30  public: __thiscall DSStepOut::DSStepOut(class UDebuggerCore * const)
//   0x568e90  public: __thiscall DSStepInto::DSStepInto(class UDebuggerCore * const)
//   0x568ec0  public: __thiscall DSStepOverStack::DSStepOverStack(class UObject const *, class UDebuggerCore * const)
//   0x568ef0  protected: virtual unsigned int __thiscall DSStepInto::EvaluateCondition(unsigned int)
//   0x568f30  public: void __thiscall UDebuggerCore::DumpStack(void)
//   0x569e50  public: void __thiscall UDebuggerCore::RemoveWatch(wchar_t const *)
//   0x569f10  public: virtual void __thiscall FDebuggerLog::Serialize(wchar_t const *, enum EName)
//   0x569ff0  public: __thiscall FStackNode::FStackNode(class UObject const *, struct FFrame const *, class UClass *, int, int, int, unsigned char)
//   0x56a0b0  public: virtual __thiscall FDebuggerWatch::~FDebuggerWatch(void)
//   0x56a120  public: virtual __thiscall FDebuggerWatchNode::~FDebuggerWatchNode(void)
//   0x56a1b0  protected: virtual unsigned int __thiscall FDebuggerWatchNode::Refresh(class UStruct const *, class UObject const *, unsigned char const *)
//   0x56a4e0  public: virtual unsigned int __thiscall FDebuggerWatchNode::GetWatchValue(class UProperty const * &, unsigned char const * &, int &)const
//   0x56ab00  public: virtual int __thiscall FDebuggerArrayNode::GetArrayIndex(void)const
//   0x56ac10  public: void __thiscall FBreakpointManager::SetBreakpoint(wchar_t const *, int)
//   0x56ad70  protected: virtual unsigned int __thiscall FDebuggerState::EvaluateCondition(unsigned int)
//   0x56ae80  protected: virtual unsigned int __thiscall DSStepOut::EvaluateCondition(unsigned int)
//   0x56aec0  protected: virtual unsigned int __thiscall DSStepOverStack::EvaluateCondition(unsigned int)
//   0x56af30  protected: virtual unsigned int __thiscall DSBreakOnChange::EvaluateCondition(unsigned int)
//   0x56af80  public: void __thiscall UDebuggerCore::ChangeState(class FDebuggerState *, unsigned int)
//   0x56b060  public: void __thiscall UDebuggerCore::Break(void)
//   0x56b7a0  public: virtual unsigned int __thiscall UDebuggerCore::NotifyAssertionFailed(int)
//   0x56b7f0  public: virtual unsigned int __thiscall UDebuggerCore::NotifyInfiniteLoop(void)
//   0x56b870  protected: virtual void __thiscall FDebuggerWatchNode::AddArrayNode(wchar_t const *)
//   0x56b920  public: virtual void __thiscall DSWaitForInput::HandleInput(enum EUserAction)
//   0x56baa0  public: virtual void __thiscall FDebuggerState::Process(unsigned int)
//   0x56bae0  public: virtual void __thiscall DSWaitForCondition::Process(unsigned int)
//   0x56bb60  public: virtual void __thiscall DSBreakOnChange::Process(unsigned int)
//   0x56c9a0  protected: virtual unsigned int __thiscall FDebuggerWatchNode::GetArrayDelimiter(class FString &, class FString &)const
//   0x56ebd0  public: void __thiscall FCallStack::Empty(void)
//   0x56ec10  public: __thiscall FDebuggerWatchNode::FDebuggerWatchNode(class FStringOutputDevice &, wchar_t const *)
//   0x56edc0  public: void __thiscall FBreakpointManager::RemoveBreakpoint(wchar_t const *, int)
//   0x56eec0  private: void __thiscall FCallStack::StackCorruptionDetected(void)
//   0x56f500  public: virtual void __thiscall UDebuggerCore::Close(unsigned int)
//   0x56f600  public: __thiscall FCallStack::~FCallStack(void)
//   0x56f6a0  public: __thiscall FDebuggerWatch::FDebuggerWatch(class FStringOutputDevice &, wchar_t const *)
//   0x56f760  public: __thiscall DSBreakOnChange::DSBreakOnChange(class UDebuggerCore * const, wchar_t const *, class FDebuggerState *)
//   0x56f830  public: unsigned int __thiscall FCallStack::UpdateStack(class UObject const *, struct FFrame const *, int, int, unsigned char)
//   0x5703d0  public: void __thiscall UDebuggerCore::SetDataBreakpoint(wchar_t const *)
//   0x570460  public: virtual void __thiscall UDebuggerCore::DebugInfo(class UObject const *, struct FFrame const *, unsigned char, int, int)
//   0x5706d0  public: virtual __thiscall UDebuggerCore::~UDebuggerCore(void)
//   0x570ca0  private: void __thiscall UDebuggerCore::BuildParentChain(int, class TMap<class UClass *, int, class FDefaultSetAllocator> &, class UClass *, int)
//   0x571900  private: void __thiscall UDebuggerCore::PropertyToWatch(class UProperty *, unsigned char *, int, int, int, wchar_t const *)
//   0x5723d0  private: void __thiscall UDebuggerCore::RefreshUserWatches(void)
//   0x572860  public: void __thiscall UDebuggerCore::AddWatch(wchar_t const *)
//   0x572a10  public: __thiscall UDebuggerCore::UDebuggerCore(void)
//   0x573000  private: void __thiscall UDebuggerCore::PropertyToWatch(class UProperty *, unsigned char *, unsigned int, int, wchar_t const *)
//   0x573110  private: void __thiscall UDebuggerCore::RefreshWatch(class FStackNode const *)
//   0x573340  public: void __thiscall UDebuggerCore::ChangeStack(int)
//   0x573510  public: void __thiscall UDebuggerCore::UpdateInterface(void)
//   0x5736c0  public: virtual void __thiscall DSWaitForInput::Process(unsigned int)
