// OnlineSubsystemSteamworksLayouts.h - compile-time layout checks of the retail (2013) OnlineSubsystemSteamworks classes and script structs:
// sizeof = retail descriptor (native_class_sizes.csv) / retail struct size, member offsets = the offsets the retail
// UStruct::Link computed (CodeRed SDK dump). Generated by resources/tools/symbols/gen_classes_header.py --sdk.
// `pending` lines are known mismatches listed in <Module>Layouts.pending.txt (base classes not converged yet, ...).
// DISHONORED_SDK_LAYOUT_CHECKS (root CMakeLists.txt, per module target) turns them on independently of the Core/Engine PDB asserts.
#pragma once
#if DISHONORED_LAYOUT_CHECKS || DISHONORED_SDK_LAYOUT_CHECKS
#include <cstddef>

static_assert(sizeof(FAchievementMappingInfo) == 28, "FAchievementMappingInfo: retail sizeof 28");
static_assert(offsetof(FAchievementMappingInfo, AchievementId) == 0, "FAchievementMappingInfo::AchievementId: retail offset 0");
static_assert(offsetof(FAchievementMappingInfo, AchievementName) == 4, "FAchievementMappingInfo::AchievementName: retail offset 4");
static_assert(offsetof(FAchievementMappingInfo, ViewId) == 12, "FAchievementMappingInfo::ViewId: retail offset 12");
static_assert(offsetof(FAchievementMappingInfo, ProgressCount) == 16, "FAchievementMappingInfo::ProgressCount: retail offset 16");
static_assert(offsetof(FAchievementMappingInfo, MaxProgress) == 20, "FAchievementMappingInfo::MaxProgress: retail offset 20");
static_assert(sizeof(FAchievementProgressStat) == 16, "FAchievementProgressStat: retail sizeof 16");
static_assert(offsetof(FAchievementProgressStat, AchievementId) == 0, "FAchievementProgressStat::AchievementId: retail offset 0");
static_assert(offsetof(FAchievementProgressStat, Progress) == 4, "FAchievementProgressStat::Progress: retail offset 4");
static_assert(offsetof(FAchievementProgressStat, MaxProgress) == 8, "FAchievementProgressStat::MaxProgress: retail offset 8");
static_assert(sizeof(FControllerConnectionState) == 8, "FControllerConnectionState: retail sizeof 8");
static_assert(offsetof(FControllerConnectionState, bIsControllerConnected) == 0, "FControllerConnectionState::bIsControllerConnected: retail offset 0");
static_assert(offsetof(FControllerConnectionState, bLastIsControllerConnected) == 4, "FControllerConnectionState::bLastIsControllerConnected: retail offset 4");
static_assert(sizeof(FDeviceIdCache) == 28, "FDeviceIdCache: retail sizeof 28");
static_assert(offsetof(FDeviceIdCache, DeviceID) == 0, "FDeviceIdCache::DeviceID: retail offset 0");
static_assert(offsetof(FDeviceIdCache, DeviceSelectionMulticast) == 4, "FDeviceIdCache::DeviceSelectionMulticast: retail offset 4");
static_assert(offsetof(FDeviceIdCache, DeviceSelectionDelegates) == 16, "FDeviceIdCache::DeviceSelectionDelegates: retail offset 16");
static_assert(sizeof(FLocalTalkerSteam) == 8, "FLocalTalkerSteam: retail sizeof 8");
static_assert(offsetof(FLocalTalkerSteam, MuteType) == 4, "FLocalTalkerSteam::MuteType: retail offset 4");
static_assert(sizeof(FOnlineStatusMapping) == 16, "FOnlineStatusMapping: retail sizeof 16");
static_assert(offsetof(FOnlineStatusMapping, StatusId) == 0, "FOnlineStatusMapping::StatusId: retail offset 0");
static_assert(offsetof(FOnlineStatusMapping, StatusString) == 4, "FOnlineStatusMapping::StatusString: retail offset 4");
static_assert(sizeof(FPlayerStat) == 20, "FPlayerStat: retail sizeof 20");
static_assert(offsetof(FPlayerStat, ViewId) == 0, "FPlayerStat::ViewId: retail offset 0");
static_assert(offsetof(FPlayerStat, ColumnId) == 4, "FPlayerStat::ColumnId: retail offset 4");
static_assert(offsetof(FPlayerStat, Data) == 8, "FPlayerStat::Data: retail offset 8");
static_assert(sizeof(FPendingPlayerStats) == 84, "FPendingPlayerStats: retail sizeof 84");
static_assert(offsetof(FPendingPlayerStats, Player) == 0, "FPendingPlayerStats::Player: retail offset 0");
static_assert(offsetof(FPendingPlayerStats, playerName) == 8, "FPendingPlayerStats::playerName: retail offset 8");
static_assert(offsetof(FPendingPlayerStats, StatGuid) == 20, "FPendingPlayerStats::StatGuid: retail offset 20");
static_assert(offsetof(FPendingPlayerStats, Stats) == 32, "FPendingPlayerStats::Stats: retail offset 32");
static_assert(offsetof(FPendingPlayerStats, Score) == 44, "FPendingPlayerStats::Score: retail offset 44");
static_assert(offsetof(FPendingPlayerStats, Place) == 72, "FPendingPlayerStats::Place: retail offset 72");
static_assert(sizeof(FProfileSettingsCache) == 40, "FProfileSettingsCache: retail sizeof 40");
static_assert(offsetof(FProfileSettingsCache, Profile) == 0, "FProfileSettingsCache::Profile: retail offset 0");
static_assert(offsetof(FProfileSettingsCache, ReadDelegates) == 4, "FProfileSettingsCache::ReadDelegates: retail offset 4");
static_assert(offsetof(FProfileSettingsCache, WriteDelegates) == 16, "FProfileSettingsCache::WriteDelegates: retail offset 16");
static_assert(offsetof(FProfileSettingsCache, ProfileDataChangedDelegates) == 28, "FProfileSettingsCache::ProfileDataChangedDelegates: retail offset 28");
static_assert(sizeof(FQueuedAvatarRequest) == 32, "FQueuedAvatarRequest: retail sizeof 32");
static_assert(offsetof(FQueuedAvatarRequest, CheckTime) == 0, "FQueuedAvatarRequest::CheckTime: retail offset 0");
static_assert(offsetof(FQueuedAvatarRequest, NumberOfAttempts) == 4, "FQueuedAvatarRequest::NumberOfAttempts: retail offset 4");
static_assert(offsetof(FQueuedAvatarRequest, PlayerNetId) == 8, "FQueuedAvatarRequest::PlayerNetId: retail offset 8");
static_assert(offsetof(FQueuedAvatarRequest, Size) == 16, "FQueuedAvatarRequest::Size: retail offset 16");
static_assert(offsetof(FQueuedAvatarRequest, ReadOnlineAvatarCompleteDelegate) == 20, "FQueuedAvatarRequest::ReadOnlineAvatarCompleteDelegate: retail offset 20");
static_assert(sizeof(FSteamPlayerClanData) == 24, "FSteamPlayerClanData: retail sizeof 24");
static_assert(offsetof(FSteamPlayerClanData, ClanName) == 0, "FSteamPlayerClanData::ClanName: retail offset 0");
static_assert(offsetof(FSteamPlayerClanData, ClanTag) == 12, "FSteamPlayerClanData::ClanTag: retail offset 12");
static_assert(sizeof(UOnlineLobbyInterfaceSteamworks) == 56, "UOnlineLobbyInterfaceSteamworks: retail sizeof 56");
// pending: sizeof(UOnlineSubsystemSteamworks) == 1132 (every reflected member is shifted by +4 in our tree: base UOnlineSubsystemCommonImpl is not converged yet (probe))
// pending: offsetof(UOnlineSubsystemSteamworks, CallbackBridge) == 200
// pending: offsetof(UOnlineSubsystemSteamworks, TotalGSStatsStoresPending) == 208
// pending: offsetof(UOnlineSubsystemSteamworks, UserStatsReceivedState) == 212
// pending: offsetof(UOnlineSubsystemSteamworks, LoggedInStatus) == 213
// pending: offsetof(UOnlineSubsystemSteamworks, bWasKeyboardInputCanceled) == 214
// pending: offsetof(UOnlineSubsystemSteamworks, CurrentNotificationPosition) == 215
// pending: offsetof(UOnlineSubsystemSteamworks, LocalProfileName) == 216
// pending: offsetof(UOnlineSubsystemSteamworks, LoggedInPlayerName) == 228
// pending: offsetof(UOnlineSubsystemSteamworks, LoggedInPlayerId) == 240
// pending: offsetof(UOnlineSubsystemSteamworks, LoggedInPlayerNum) == 248
// pending: offsetof(UOnlineSubsystemSteamworks, ProfileDataDirectory) == 252
// pending: offsetof(UOnlineSubsystemSteamworks, ProfileDataExtension) == 264
// pending: offsetof(UOnlineSubsystemSteamworks, WriteProfileSettingsDelegates) == 276
// pending: offsetof(UOnlineSubsystemSteamworks, CachedProfile) == 288
// pending: offsetof(UOnlineSubsystemSteamworks, LocalPlayerStorageReadDelegates) == 292
// pending: offsetof(UOnlineSubsystemSteamworks, LocalPlayerStorageWriteDelegates) == 304
// pending: offsetof(UOnlineSubsystemSteamworks, RemotePlayerStorageReadDelegates) == 316
// pending: offsetof(UOnlineSubsystemSteamworks, ReadFriendsDelegates) == 328
// pending: offsetof(UOnlineSubsystemSteamworks, FriendsChangeDelegates) == 340
// pending: offsetof(UOnlineSubsystemSteamworks, MutingChangeDelegates) == 352
// pending: offsetof(UOnlineSubsystemSteamworks, LoginChangeDelegates) == 364
// pending: offsetof(UOnlineSubsystemSteamworks, LoginFailedDelegates) == 376
// pending: offsetof(UOnlineSubsystemSteamworks, LogoutCompletedDelegates) == 388
// pending: offsetof(UOnlineSubsystemSteamworks, AccountCreateDelegates) == 400
// pending: offsetof(UOnlineSubsystemSteamworks, ConnectionStatusChangeDelegates) == 412
// pending: offsetof(UOnlineSubsystemSteamworks, ControllerChangeDelegates) == 424
// pending: offsetof(UOnlineSubsystemSteamworks, LinkStatusDelegates) == 436
// pending: offsetof(UOnlineSubsystemSteamworks, ReadTitleFileCompleteDelegates) == 448
// pending: offsetof(UOnlineSubsystemSteamworks, AchievementDelegates) == 460
// pending: offsetof(UOnlineSubsystemSteamworks, AchievementReadDelegates) == 472
// pending: offsetof(UOnlineSubsystemSteamworks, CurrentLocalTalker) == 484
// pending: offsetof(UOnlineSubsystemSteamworks, RemoteTalkers) == 492
// pending: offsetof(UOnlineSubsystemSteamworks, GameID) == 504
// pending: offsetof(UOnlineSubsystemSteamworks, CurrentStatsRead) == 508
// pending: offsetof(UOnlineSubsystemSteamworks, PendingStats) == 512
// pending: offsetof(UOnlineSubsystemSteamworks, KeyboardResultsString) == 524
// pending: offsetof(UOnlineSubsystemSteamworks, KeyboardInputDelegates) == 536
// pending: offsetof(UOnlineSubsystemSteamworks, ProfileCache) == 548
// pending: offsetof(UOnlineSubsystemSteamworks, PlayerStorageCache) == 588
// pending: offsetof(UOnlineSubsystemSteamworks, CachedFriendMessage) == 592
// pending: offsetof(UOnlineSubsystemSteamworks, DeviceCache) == 604
// pending: offsetof(UOnlineSubsystemSteamworks, LocationUrlsForInvites) == 632
// pending: offsetof(UOnlineSubsystemSteamworks, LocationUrl) == 644
// pending: offsetof(UOnlineSubsystemSteamworks, CachedFriendMessages) == 656
// pending: offsetof(UOnlineSubsystemSteamworks, StatusMappings) == 668
// pending: offsetof(UOnlineSubsystemSteamworks, DefaultStatus) == 680
// pending: offsetof(UOnlineSubsystemSteamworks, GameInviteMessage) == 692
// pending: offsetof(UOnlineSubsystemSteamworks, ControllerStates) == 704
// pending: offsetof(UOnlineSubsystemSteamworks, ConnectionPresenceTimeInterval) == 736
// pending: offsetof(UOnlineSubsystemSteamworks, ConnectionPresenceElapsedTime) == 740
// pending: offsetof(UOnlineSubsystemSteamworks, EncryptedProductKey) == 744
// pending: offsetof(UOnlineSubsystemSteamworks, MuteList) == 756
// pending: offsetof(UOnlineSubsystemSteamworks, QueuedAvatarRequests) == 768
// pending: offsetof(UOnlineSubsystemSteamworks, AchievementMappings) == 780
// pending: offsetof(UOnlineSubsystemSteamworks, PendingAchievementProgress) == 792
// pending: offsetof(UOnlineSubsystemSteamworks, m_paEnumeratedDLCs) == 804
// pending: offsetof(UOnlineSubsystemSteamworks, __OnLoginChange__Delegate) == 808
// pending: offsetof(UOnlineSubsystemSteamworks, __OnLoginCancelled__Delegate) == 820
// pending: offsetof(UOnlineSubsystemSteamworks, __OnMutingChange__Delegate) == 832
// pending: offsetof(UOnlineSubsystemSteamworks, __OnFriendsChange__Delegate) == 844
// pending: offsetof(UOnlineSubsystemSteamworks, __OnLoginFailed__Delegate) == 856
// pending: offsetof(UOnlineSubsystemSteamworks, __OnLogoutCompleted__Delegate) == 868
// pending: offsetof(UOnlineSubsystemSteamworks, __OnLoginStatusChange__Delegate) == 880
// pending: offsetof(UOnlineSubsystemSteamworks, __OnReadProfileSettingsComplete__Delegate) == 892
// pending: offsetof(UOnlineSubsystemSteamworks, __OnWriteProfileSettingsComplete__Delegate) == 904
// pending: offsetof(UOnlineSubsystemSteamworks, __OnReadPlayerStorageComplete__Delegate) == 916
// pending: offsetof(UOnlineSubsystemSteamworks, __OnReadPlayerStorageForNetIdComplete__Delegate) == 928
// pending: offsetof(UOnlineSubsystemSteamworks, __OnWritePlayerStorageComplete__Delegate) == 940
// pending: offsetof(UOnlineSubsystemSteamworks, __OnReadFriendsComplete__Delegate) == 952
// pending: offsetof(UOnlineSubsystemSteamworks, __OnLinkStatusChange__Delegate) == 964
// pending: offsetof(UOnlineSubsystemSteamworks, __OnExternalUIChange__Delegate) == 976
// pending: offsetof(UOnlineSubsystemSteamworks, __OnControllerChange__Delegate) == 988
// pending: offsetof(UOnlineSubsystemSteamworks, __OnConnectionStatusChange__Delegate) == 1000
// pending: offsetof(UOnlineSubsystemSteamworks, __OnStorageDeviceChange__Delegate) == 1012
// pending: offsetof(UOnlineSubsystemSteamworks, __OnReadTitleFileComplete__Delegate) == 1024
// pending: offsetof(UOnlineSubsystemSteamworks, __OnCreateOnlineAccountCompleted__Delegate) == 1036
// pending: offsetof(UOnlineSubsystemSteamworks, __OnKeyboardInputComplete__Delegate) == 1048
// pending: offsetof(UOnlineSubsystemSteamworks, __OnDeviceSelectionComplete__Delegate) == 1060
// pending: offsetof(UOnlineSubsystemSteamworks, __OnUnlockAchievementComplete__Delegate) == 1072
// pending: offsetof(UOnlineSubsystemSteamworks, __OnProfileDataChanged__Delegate) == 1084
// pending: offsetof(UOnlineSubsystemSteamworks, __OnReadAchievementsComplete__Delegate) == 1096
// pending: offsetof(UOnlineSubsystemSteamworks, __OnReadOnlineAvatarComplete__Delegate) == 1108
// pending: offsetof(UOnlineSubsystemSteamworks, __OnReadCrossTitleProfileSettingsComplete__Delegate) == 1120
#endif // DISHONORED_LAYOUT_CHECKS || DISHONORED_SDK_LAYOUT_CHECKS
