/*===========================================================================
    OnlineSubsystemSteamworksClasses.h - C++ class definitions of the retail (2013) OnlineSubsystemSteamworks module.
    Generated by resources/tools/symbols/gen_classes_header.py --sdk from the CodeRed SDK dump
    (retail_sdk_layout.json: member offsets/types/flags, function parameter blocks), native_class_sizes.csv
    (retail sizeof, ClassFlags, Within, config), script_classes_2013.json (enum values, consts, property
    kinds, header groups) and the 2012 types.json (names of native-only members). DO NOT edit by hand:
    regenerate, or carry the change into the generator.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "OnlineSubsystemSteamworksNames.h"

#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_ONLINESUBSYSTEMSTEAMWORKS_ENUMS
#define INCLUDED_ONLINESUBSYSTEMSTEAMWORKS_ENUMS 1

enum EMuteType
{
    MUTE_None               =0,
    MUTE_AllButFriends      =1,
    MUTE_All                =2,
    MUTE_MAX                =3,
};
#define FOREACH_ENUM_EMUTETYPE(op) \
    op(MUTE_None) \
    op(MUTE_AllButFriends) \
    op(MUTE_All) 

#endif // !INCLUDED_ONLINESUBSYSTEMSTEAMWORKS_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_ONLINESUBSYSTEMSTEAMWORKS_CLASSES
#define INCLUDED_ONLINESUBSYSTEMSTEAMWORKS_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO


// forward declarations: every class of the module, plus classes referenced by pointer that no included header declares
class UOnlineLobbyInterfaceSteamworks;
class UOnlineSubsystemSteamworks;

// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.AchievementMappingInfo: retail SDK size 28 (2012 PDB 28)
struct FAchievementMappingInfo
{
    INT AchievementId;
    FName AchievementName;
    INT ViewId;
    INT ProgressCount;
    INT MaxProgress;
    BITFIELD bAutoUnlock:1;

    /** Constructors */
    FAchievementMappingInfo() {}
    FAchievementMappingInfo(EEventParm)
    {
        appMemzero(this, sizeof(FAchievementMappingInfo));
    }
};

// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.AchievementProgressStat: retail SDK size 16 (2012 PDB 16)
struct FAchievementProgressStat
{
    INT AchievementId;
    INT Progress;
    INT MaxProgress;
    BITFIELD bUnlock:1;

    /** Constructors */
    FAchievementProgressStat() {}
    FAchievementProgressStat(EEventParm)
    {
        appMemzero(this, sizeof(FAchievementProgressStat));
    }
};

// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.ControllerConnectionState: retail SDK size 8 (2012 PDB 8)
struct FControllerConnectionState
{
    INT bIsControllerConnected;
    INT bLastIsControllerConnected;

    /** Constructors */
    FControllerConnectionState() {}
    FControllerConnectionState(EEventParm)
    {
        appMemzero(this, sizeof(FControllerConnectionState));
    }
};

// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.DeviceIdCache: retail SDK size 28 (2012 PDB 28)
struct FDeviceIdCache
{
    INT DeviceID;
    FScriptDelegate DeviceSelectionMulticast;
    TArrayNoInit<FScriptDelegate> DeviceSelectionDelegates;

    /** Constructors */
    FDeviceIdCache() {}
    FDeviceIdCache(EEventParm)
    {
        appMemzero(this, sizeof(FDeviceIdCache));
    }
};

// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.LocalTalkerSteam: retail SDK size 8 (2012 PDB 8)
struct FLocalTalkerSteam : public FLocalTalker
{
    BYTE MuteType;

    /** Constructors */
    FLocalTalkerSteam() {}
    FLocalTalkerSteam(EEventParm)
    {
        appMemzero(this, sizeof(FLocalTalkerSteam));
    }
};

// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.OnlineStatusMapping: retail SDK size 16 (2012 PDB 16)
struct FOnlineStatusMapping
{
    INT StatusId;
    FStringNoInit StatusString;

    /** Constructors */
    FOnlineStatusMapping() {}
    FOnlineStatusMapping(EEventParm)
    {
        appMemzero(this, sizeof(FOnlineStatusMapping));
    }
};

// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.PlayerStat: retail SDK size 20 (2012 PDB 20)
struct FPlayerStat
{
    INT ViewId;
    INT ColumnId;
    FSettingsData Data;

    /** Constructors */
    FPlayerStat() {}
    FPlayerStat(EEventParm)
    {
        appMemzero(this, sizeof(FPlayerStat));
    }
};

// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.PendingPlayerStats: retail SDK size 84 (2012 PDB 72)
struct FPendingPlayerStats
{
    FUniqueNetId Player;
    FStringNoInit playerName;
    FStringNoInit StatGuid;
    TArrayNoInit<FPlayerStat> Stats;
    FOnlinePlayerScore Score;
    FStringNoInit Place;

    /** Constructors */
    FPendingPlayerStats() {}
    FPendingPlayerStats(EEventParm)
    {
        appMemzero(this, sizeof(FPendingPlayerStats));
    }
};

// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.ProfileSettingsCache: retail SDK size 40 (2012 PDB 40)
struct FProfileSettingsCache
{
    class UOnlineProfileSettings* Profile;
    TArrayNoInit<FScriptDelegate> ReadDelegates;
    TArrayNoInit<FScriptDelegate> WriteDelegates;
    TArrayNoInit<FScriptDelegate> ProfileDataChangedDelegates;

    /** Constructors */
    FProfileSettingsCache() {}
    FProfileSettingsCache(EEventParm)
    {
        appMemzero(this, sizeof(FProfileSettingsCache));
    }
};

// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.QueuedAvatarRequest: retail SDK size 32 (2012 PDB 32)
struct FQueuedAvatarRequest
{
    FLOAT CheckTime;
    INT NumberOfAttempts;
    FUniqueNetId PlayerNetId;
    INT Size;
    FScriptDelegate ReadOnlineAvatarCompleteDelegate;

    /** Constructors */
    FQueuedAvatarRequest() {}
    FQueuedAvatarRequest(EEventParm)
    {
        appMemzero(this, sizeof(FQueuedAvatarRequest));
    }
};

// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks.SteamPlayerClanData: retail SDK size 24 (2012 PDB 24)
struct FSteamPlayerClanData
{
    FStringNoInit ClanName;
    FStringNoInit ClanTag;

    /** Constructors */
    FSteamPlayerClanData() {}
    FSteamPlayerClanData(EEventParm)
    {
        appMemzero(this, sizeof(FSteamPlayerClanData));
    }
};

// OnlineSubsystemSteamworks.OnlineLobbyInterfaceSteamworks: retail sizeof 56, reflected span 56..56 (2012 PDB sizeof 56)
class UOnlineLobbyInterfaceSteamworks : public UObject
{
public:
    //## BEGIN PROPS OnlineLobbyInterfaceSteamworks
    //## END PROPS OnlineLobbyInterfaceSteamworks

    DECLARE_CLASS(UOnlineLobbyInterfaceSteamworks,UObject,0,OnlineSubsystemSteamworks)
    DECLARE_WITHIN(UOnlineSubsystemCommonImpl)
};

struct OnlineSubsystemSteamworks_eventOnReadCrossTitleProfileSettingsComplete_Parms
{
    BYTE LocalUserNum;
    INT TitleId;
    UBOOL bWasSuccessful;
    OnlineSubsystemSteamworks_eventOnReadCrossTitleProfileSettingsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnReadOnlineAvatarComplete_Parms
{
    FUniqueNetId PlayerNetId;
    class UTexture2D* Avatar;
    OnlineSubsystemSteamworks_eventOnReadOnlineAvatarComplete_Parms(EEventParm)
    : PlayerNetId(EC_EventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnReadAchievementsComplete_Parms
{
    INT TitleId;
    OnlineSubsystemSteamworks_eventOnReadAchievementsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnProfileDataChanged_Parms
{
    OnlineSubsystemSteamworks_eventOnProfileDataChanged_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnUnlockAchievementComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemSteamworks_eventOnUnlockAchievementComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnDeviceSelectionComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemSteamworks_eventOnDeviceSelectionComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnKeyboardInputComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemSteamworks_eventOnKeyboardInputComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnCreateOnlineAccountCompleted_Parms
{
    BYTE ErrorStatus;
    OnlineSubsystemSteamworks_eventOnCreateOnlineAccountCompleted_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnReadTitleFileComplete_Parms
{
    UBOOL bWasSuccessful;
    FString Filename;
    OnlineSubsystemSteamworks_eventOnReadTitleFileComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnStorageDeviceChange_Parms
{
    OnlineSubsystemSteamworks_eventOnStorageDeviceChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnConnectionStatusChange_Parms
{
    BYTE ConnectionStatus;
    OnlineSubsystemSteamworks_eventOnConnectionStatusChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnControllerChange_Parms
{
    INT ControllerId;
    UBOOL bIsConnected;
    OnlineSubsystemSteamworks_eventOnControllerChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnExternalUIChange_Parms
{
    UBOOL bIsOpening;
    OnlineSubsystemSteamworks_eventOnExternalUIChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnLinkStatusChange_Parms
{
    UBOOL bIsConnected;
    OnlineSubsystemSteamworks_eventOnLinkStatusChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventGetPlayerNicknameFromIndex_Parms
{
    INT UserIndex;
    FString ReturnValue;
    OnlineSubsystemSteamworks_eventGetPlayerNicknameFromIndex_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnReadFriendsComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemSteamworks_eventOnReadFriendsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnWritePlayerStorageComplete_Parms
{
    BYTE LocalUserNum;
    UBOOL bWasSuccessful;
    OnlineSubsystemSteamworks_eventOnWritePlayerStorageComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnReadPlayerStorageForNetIdComplete_Parms
{
    FUniqueNetId NetId;
    UBOOL bWasSuccessful;
    OnlineSubsystemSteamworks_eventOnReadPlayerStorageForNetIdComplete_Parms(EEventParm)
    : NetId(EC_EventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnReadPlayerStorageComplete_Parms
{
    BYTE LocalUserNum;
    UBOOL bWasSuccessful;
    OnlineSubsystemSteamworks_eventOnReadPlayerStorageComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnWriteProfileSettingsComplete_Parms
{
    BYTE LocalUserNum;
    UBOOL bWasSuccessful;
    OnlineSubsystemSteamworks_eventOnWriteProfileSettingsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnReadProfileSettingsComplete_Parms
{
    BYTE LocalUserNum;
    UBOOL bWasSuccessful;
    OnlineSubsystemSteamworks_eventOnReadProfileSettingsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnLoginStatusChange_Parms
{
    BYTE NewStatus;
    FUniqueNetId NewId;
    OnlineSubsystemSteamworks_eventOnLoginStatusChange_Parms(EEventParm)
    : NewId(EC_EventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnLogoutCompleted_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemSteamworks_eventOnLogoutCompleted_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnLoginFailed_Parms
{
    BYTE LocalUserNum;
    BYTE ErrorCode;
    OnlineSubsystemSteamworks_eventOnLoginFailed_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnFriendsChange_Parms
{
    OnlineSubsystemSteamworks_eventOnFriendsChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnMutingChange_Parms
{
    OnlineSubsystemSteamworks_eventOnMutingChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnLoginCancelled_Parms
{
    OnlineSubsystemSteamworks_eventOnLoginCancelled_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventOnLoginChange_Parms
{
    BYTE LocalUserNum;
    OnlineSubsystemSteamworks_eventOnLoginChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventExit_Parms
{
    OnlineSubsystemSteamworks_eventExit_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemSteamworks_eventInit_Parms
{
    UBOOL ReturnValue;
    OnlineSubsystemSteamworks_eventInit_Parms(EEventParm)
    {
    }
};
// OnlineSubsystemSteamworks.OnlineSubsystemSteamworks: retail sizeof 1132, reflected span 200..1132 (2012 PDB sizeof 1284)
class UOnlineSubsystemSteamworks : public UOnlineSubsystemCommonImpl
{
public:
    //## BEGIN PROPS OnlineSubsystemSteamworks
    FPointer CallbackBridge;
    BITFIELD bStoringAchievement:1;
    BITFIELD bClientStatsStorePending:1;
    BITFIELD bGSStatsStoresSuccess:1;
    BITFIELD bNeedsKeyboardTicking:1;
    BITFIELD bLastHasConnection:1;
    BITFIELD bIsStatsSessionOk:1;
    BITFIELD bHasSteamworksAccount:1;
    BITFIELD bShouldUseMcp:1;
    BITFIELD bDLCHasBeenInstalled:1;
    INT TotalGSStatsStoresPending;
    BYTE UserStatsReceivedState;
    BYTE LoggedInStatus;
    BYTE bWasKeyboardInputCanceled;
    BYTE CurrentNotificationPosition;
    FStringNoInit LocalProfileName;
    FStringNoInit LoggedInPlayerName;
    FUniqueNetId LoggedInPlayerId;
    INT LoggedInPlayerNum;
    FStringNoInit ProfileDataDirectory;
    FStringNoInit ProfileDataExtension;
    TArrayNoInit<FScriptDelegate> WriteProfileSettingsDelegates;
    class UOnlineProfileSettings* CachedProfile;
    TArrayNoInit<FScriptDelegate> LocalPlayerStorageReadDelegates;
    TArrayNoInit<FScriptDelegate> LocalPlayerStorageWriteDelegates;
    TArrayNoInit<FScriptDelegate> RemotePlayerStorageReadDelegates;
    TArrayNoInit<FScriptDelegate> ReadFriendsDelegates;
    TArrayNoInit<FScriptDelegate> FriendsChangeDelegates;
    TArrayNoInit<FScriptDelegate> MutingChangeDelegates;
    TArrayNoInit<FScriptDelegate> LoginChangeDelegates;
    TArrayNoInit<FScriptDelegate> LoginFailedDelegates;
    TArrayNoInit<FScriptDelegate> LogoutCompletedDelegates;
    TArrayNoInit<FScriptDelegate> AccountCreateDelegates;
    TArrayNoInit<FScriptDelegate> ConnectionStatusChangeDelegates;
    TArrayNoInit<FScriptDelegate> ControllerChangeDelegates;
    TArrayNoInit<FScriptDelegate> LinkStatusDelegates;
    TArrayNoInit<FScriptDelegate> ReadTitleFileCompleteDelegates;
    TArrayNoInit<FScriptDelegate> AchievementDelegates;
    TArrayNoInit<FScriptDelegate> AchievementReadDelegates;
    FLocalTalkerSteam CurrentLocalTalker;
    TArrayNoInit<FRemoteTalker> RemoteTalkers;
    INT GameID;
    class UOnlineStatsRead* CurrentStatsRead;
    TArrayNoInit<FPendingPlayerStats> PendingStats;
    FStringNoInit KeyboardResultsString;
    TArrayNoInit<FScriptDelegate> KeyboardInputDelegates;
    FProfileSettingsCache ProfileCache;
    class UOnlinePlayerStorage* PlayerStorageCache;
    FStringNoInit CachedFriendMessage;
    FDeviceIdCache DeviceCache;
    TArrayNoInit<FString> LocationUrlsForInvites;
    FStringNoInit LocationUrl;
    TArrayNoInit<FOnlineFriendMessage> CachedFriendMessages;
    TArrayNoInit<FOnlineStatusMapping> StatusMappings;
    FStringNoInit DefaultStatus;
    FStringNoInit GameInviteMessage;
    FControllerConnectionState ControllerStates[4];
    FLOAT ConnectionPresenceTimeInterval;
    FLOAT ConnectionPresenceElapsedTime;
    FStringNoInit EncryptedProductKey;
    TArrayNoInit<FUniqueNetId> MuteList;
    TArrayNoInit<FQueuedAvatarRequest> QueuedAvatarRequests;
    TArrayNoInit<FAchievementMappingInfo> AchievementMappings;
    TArrayNoInit<FAchievementProgressStat> PendingAchievementProgress;
    FPointer m_paEnumeratedDLCs;
    FScriptDelegate __OnLoginChange__Delegate;
    FScriptDelegate __OnLoginCancelled__Delegate;
    FScriptDelegate __OnMutingChange__Delegate;
    FScriptDelegate __OnFriendsChange__Delegate;
    FScriptDelegate __OnLoginFailed__Delegate;
    FScriptDelegate __OnLogoutCompleted__Delegate;
    FScriptDelegate __OnLoginStatusChange__Delegate;
    FScriptDelegate __OnReadProfileSettingsComplete__Delegate;
    FScriptDelegate __OnWriteProfileSettingsComplete__Delegate;
    FScriptDelegate __OnReadPlayerStorageComplete__Delegate;
    FScriptDelegate __OnReadPlayerStorageForNetIdComplete__Delegate;
    FScriptDelegate __OnWritePlayerStorageComplete__Delegate;
    FScriptDelegate __OnReadFriendsComplete__Delegate;
    FScriptDelegate __OnLinkStatusChange__Delegate;
    FScriptDelegate __OnExternalUIChange__Delegate;
    FScriptDelegate __OnControllerChange__Delegate;
    FScriptDelegate __OnConnectionStatusChange__Delegate;
    FScriptDelegate __OnStorageDeviceChange__Delegate;
    FScriptDelegate __OnReadTitleFileComplete__Delegate;
    FScriptDelegate __OnCreateOnlineAccountCompleted__Delegate;
    FScriptDelegate __OnKeyboardInputComplete__Delegate;
    FScriptDelegate __OnDeviceSelectionComplete__Delegate;
    FScriptDelegate __OnUnlockAchievementComplete__Delegate;
    FScriptDelegate __OnProfileDataChanged__Delegate;
    FScriptDelegate __OnReadAchievementsComplete__Delegate;
    FScriptDelegate __OnReadOnlineAvatarComplete__Delegate;
    FScriptDelegate __OnReadCrossTitleProfileSettingsComplete__Delegate;
    //## END PROPS OnlineSubsystemSteamworks

    void delegateOnReadCrossTitleProfileSettingsComplete(BYTE LocalUserNum,INT TitleId,UBOOL bWasSuccessful)
    {
        OnlineSubsystemSteamworks_eventOnReadCrossTitleProfileSettingsComplete_Parms Parms(EC_EventParm);
        Parms.LocalUserNum=LocalUserNum;
        Parms.TitleId=TitleId;
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnReadCrossTitleProfileSettingsComplete,&__OnReadCrossTitleProfileSettingsComplete__Delegate,&Parms);
    }
    void delegateOnReadOnlineAvatarComplete(FUniqueNetId PlayerNetId,class UTexture2D* Avatar)
    {
        OnlineSubsystemSteamworks_eventOnReadOnlineAvatarComplete_Parms Parms(EC_EventParm);
        Parms.PlayerNetId=PlayerNetId;
        Parms.Avatar=Avatar;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnReadOnlineAvatarComplete,&__OnReadOnlineAvatarComplete__Delegate,&Parms);
    }
    void delegateOnReadAchievementsComplete(INT TitleId)
    {
        OnlineSubsystemSteamworks_eventOnReadAchievementsComplete_Parms Parms(EC_EventParm);
        Parms.TitleId=TitleId;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnReadAchievementsComplete,&__OnReadAchievementsComplete__Delegate,&Parms);
    }
    void delegateOnProfileDataChanged()
    {
        OnlineSubsystemSteamworks_eventOnProfileDataChanged_Parms Parms(EC_EventParm);
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnProfileDataChanged,&__OnProfileDataChanged__Delegate,&Parms);
    }
    void delegateOnUnlockAchievementComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemSteamworks_eventOnUnlockAchievementComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnUnlockAchievementComplete,&__OnUnlockAchievementComplete__Delegate,&Parms);
    }
    void delegateOnDeviceSelectionComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemSteamworks_eventOnDeviceSelectionComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnDeviceSelectionComplete,&__OnDeviceSelectionComplete__Delegate,&Parms);
    }
    void delegateOnKeyboardInputComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemSteamworks_eventOnKeyboardInputComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnKeyboardInputComplete,&__OnKeyboardInputComplete__Delegate,&Parms);
    }
    void delegateOnCreateOnlineAccountCompleted(BYTE ErrorStatus)
    {
        OnlineSubsystemSteamworks_eventOnCreateOnlineAccountCompleted_Parms Parms(EC_EventParm);
        Parms.ErrorStatus=ErrorStatus;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnCreateOnlineAccountCompleted,&__OnCreateOnlineAccountCompleted__Delegate,&Parms);
    }
    void delegateOnReadTitleFileComplete(UBOOL bWasSuccessful,const FString& Filename)
    {
        OnlineSubsystemSteamworks_eventOnReadTitleFileComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        Parms.Filename=Filename;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnReadTitleFileComplete,&__OnReadTitleFileComplete__Delegate,&Parms);
    }
    void delegateOnStorageDeviceChange()
    {
        OnlineSubsystemSteamworks_eventOnStorageDeviceChange_Parms Parms(EC_EventParm);
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnStorageDeviceChange,&__OnStorageDeviceChange__Delegate,&Parms);
    }
    void delegateOnConnectionStatusChange(BYTE ConnectionStatus)
    {
        OnlineSubsystemSteamworks_eventOnConnectionStatusChange_Parms Parms(EC_EventParm);
        Parms.ConnectionStatus=ConnectionStatus;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnConnectionStatusChange,&__OnConnectionStatusChange__Delegate,&Parms);
    }
    void delegateOnControllerChange(INT ControllerId,UBOOL bIsConnected)
    {
        OnlineSubsystemSteamworks_eventOnControllerChange_Parms Parms(EC_EventParm);
        Parms.ControllerId=ControllerId;
        Parms.bIsConnected=bIsConnected ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnControllerChange,&__OnControllerChange__Delegate,&Parms);
    }
    void delegateOnExternalUIChange(UBOOL bIsOpening)
    {
        OnlineSubsystemSteamworks_eventOnExternalUIChange_Parms Parms(EC_EventParm);
        Parms.bIsOpening=bIsOpening ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnExternalUIChange,&__OnExternalUIChange__Delegate,&Parms);
    }
    void delegateOnLinkStatusChange(UBOOL bIsConnected)
    {
        OnlineSubsystemSteamworks_eventOnLinkStatusChange_Parms Parms(EC_EventParm);
        Parms.bIsConnected=bIsConnected ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnLinkStatusChange,&__OnLinkStatusChange__Delegate,&Parms);
    }
    FString eventGetPlayerNicknameFromIndex(INT UserIndex)
    {
        OnlineSubsystemSteamworks_eventGetPlayerNicknameFromIndex_Parms Parms(EC_EventParm);
        Parms.ReturnValue=TEXT("");
        Parms.UserIndex=UserIndex;
        ProcessEvent(FindFunctionChecked(ONLINESUBSYSTEMSTEAMWORKS_GetPlayerNicknameFromIndex),&Parms);
        return Parms.ReturnValue;
    }
    void delegateOnReadFriendsComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemSteamworks_eventOnReadFriendsComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnReadFriendsComplete,&__OnReadFriendsComplete__Delegate,&Parms);
    }
    void delegateOnWritePlayerStorageComplete(BYTE LocalUserNum,UBOOL bWasSuccessful)
    {
        OnlineSubsystemSteamworks_eventOnWritePlayerStorageComplete_Parms Parms(EC_EventParm);
        Parms.LocalUserNum=LocalUserNum;
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnWritePlayerStorageComplete,&__OnWritePlayerStorageComplete__Delegate,&Parms);
    }
    void delegateOnReadPlayerStorageForNetIdComplete(FUniqueNetId NetId,UBOOL bWasSuccessful)
    {
        OnlineSubsystemSteamworks_eventOnReadPlayerStorageForNetIdComplete_Parms Parms(EC_EventParm);
        Parms.NetId=NetId;
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnReadPlayerStorageForNetIdComplete,&__OnReadPlayerStorageForNetIdComplete__Delegate,&Parms);
    }
    void delegateOnReadPlayerStorageComplete(BYTE LocalUserNum,UBOOL bWasSuccessful)
    {
        OnlineSubsystemSteamworks_eventOnReadPlayerStorageComplete_Parms Parms(EC_EventParm);
        Parms.LocalUserNum=LocalUserNum;
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnReadPlayerStorageComplete,&__OnReadPlayerStorageComplete__Delegate,&Parms);
    }
    void delegateOnWriteProfileSettingsComplete(BYTE LocalUserNum,UBOOL bWasSuccessful)
    {
        OnlineSubsystemSteamworks_eventOnWriteProfileSettingsComplete_Parms Parms(EC_EventParm);
        Parms.LocalUserNum=LocalUserNum;
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnWriteProfileSettingsComplete,&__OnWriteProfileSettingsComplete__Delegate,&Parms);
    }
    void delegateOnReadProfileSettingsComplete(BYTE LocalUserNum,UBOOL bWasSuccessful)
    {
        OnlineSubsystemSteamworks_eventOnReadProfileSettingsComplete_Parms Parms(EC_EventParm);
        Parms.LocalUserNum=LocalUserNum;
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnReadProfileSettingsComplete,&__OnReadProfileSettingsComplete__Delegate,&Parms);
    }
    void delegateOnLoginStatusChange(BYTE NewStatus,FUniqueNetId NewId)
    {
        OnlineSubsystemSteamworks_eventOnLoginStatusChange_Parms Parms(EC_EventParm);
        Parms.NewStatus=NewStatus;
        Parms.NewId=NewId;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnLoginStatusChange,&__OnLoginStatusChange__Delegate,&Parms);
    }
    void delegateOnLogoutCompleted(UBOOL bWasSuccessful)
    {
        OnlineSubsystemSteamworks_eventOnLogoutCompleted_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : FALSE;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnLogoutCompleted,&__OnLogoutCompleted__Delegate,&Parms);
    }
    void delegateOnLoginFailed(BYTE LocalUserNum,BYTE ErrorCode)
    {
        OnlineSubsystemSteamworks_eventOnLoginFailed_Parms Parms(EC_EventParm);
        Parms.LocalUserNum=LocalUserNum;
        Parms.ErrorCode=ErrorCode;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnLoginFailed,&__OnLoginFailed__Delegate,&Parms);
    }
    void delegateOnFriendsChange()
    {
        OnlineSubsystemSteamworks_eventOnFriendsChange_Parms Parms(EC_EventParm);
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnFriendsChange,&__OnFriendsChange__Delegate,&Parms);
    }
    void delegateOnMutingChange()
    {
        OnlineSubsystemSteamworks_eventOnMutingChange_Parms Parms(EC_EventParm);
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnMutingChange,&__OnMutingChange__Delegate,&Parms);
    }
    void delegateOnLoginCancelled()
    {
        OnlineSubsystemSteamworks_eventOnLoginCancelled_Parms Parms(EC_EventParm);
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnLoginCancelled,&__OnLoginCancelled__Delegate,&Parms);
    }
    void delegateOnLoginChange(BYTE LocalUserNum)
    {
        OnlineSubsystemSteamworks_eventOnLoginChange_Parms Parms(EC_EventParm);
        Parms.LocalUserNum=LocalUserNum;
        ProcessDelegate(ONLINESUBSYSTEMSTEAMWORKS_OnLoginChange,&__OnLoginChange__Delegate,&Parms);
    }
    void eventExit()
    {
        OnlineSubsystemSteamworks_eventExit_Parms Parms(EC_EventParm);
        ProcessEvent(FindFunctionChecked(ONLINESUBSYSTEMSTEAMWORKS_Exit),&Parms);
    }
    UBOOL eventInit()
    {
        OnlineSubsystemSteamworks_eventInit_Parms Parms(EC_EventParm);
        Parms.ReturnValue=FALSE;
        ProcessEvent(FindFunctionChecked(ONLINESUBSYSTEMSTEAMWORKS_Init),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_FUNCTION(execInt64ToUniqueNetId);
    DECLARE_FUNCTION(execUniqueNetIdToInt64);
    DECLARE_FUNCTION(execShowProfileUI);
    DECLARE_FUNCTION(execUniqueNetIdToPlayerName);
    DECLARE_FUNCTION(execDisplayAchievementProgress);
    DECLARE_FUNCTION(execEnumerateFilesOnRemoteStorage);
    DECLARE_FUNCTION(execDeleteFileFromRemoteStorage);
    DECLARE_FUNCTION(execReadBytesFromRemoteStorage);
    DECLARE_FUNCTION(execReadStringFromRemoteStorage);
    DECLARE_FUNCTION(execWriteBytesToRemoteStorage);
    DECLARE_FUNCTION(execWriteStringToRemoteStorage);
    DECLARE_FUNCTION(execGetSteamClanData);
    DECLARE_FUNCTION(execReadOnlineAvatar);
    DECLARE_FUNCTION(execShowCustomPlayersUI);
    DECLARE_FUNCTION(execGetAchievements);
    DECLARE_FUNCTION(execReadAchievements);
    DECLARE_FUNCTION(execShowPlayersUI);
    DECLARE_FUNCTION(execShowFriendsInviteUI);
    DECLARE_FUNCTION(execShowFriendsUI);
    DECLARE_FUNCTION(execUnlockGamerPicture);
    DECLARE_FUNCTION(execUnlockAchievement);
    DECLARE_FUNCTION(execIsDeviceValid);
    DECLARE_FUNCTION(execGetDeviceSelectionResults);
    DECLARE_FUNCTION(execShowDeviceSelectionUI);
    DECLARE_FUNCTION(execShowMembershipMarketplaceUI);
    DECLARE_FUNCTION(execShowContentMarketplaceUI);
    DECLARE_FUNCTION(execShowInviteUI);
    DECLARE_FUNCTION(execShowAchievementsUI);
    DECLARE_FUNCTION(execShowMessagesUI);
    DECLARE_FUNCTION(execShowGamerCardUI);
    DECLARE_FUNCTION(execShowFeedbackUI);
    DECLARE_FUNCTION(execShowKeyboardUI);
    DECLARE_FUNCTION(execSetOnlineStatus);
    DECLARE_FUNCTION(execCreateOnlineAccount);
    DECLARE_FUNCTION(execGetTitleFileContents);
    DECLARE_FUNCTION(execReadTitleFile);
    DECLARE_FUNCTION(execGetNATType);
    DECLARE_FUNCTION(execIsControllerConnected);
    DECLARE_FUNCTION(execSetNetworkNotificationPosition);
    DECLARE_FUNCTION(execHasLinkConnection);
    DECLARE_FUNCTION(execGetFriendsList);
    DECLARE_FUNCTION(execReadFriendsList);
    DECLARE_FUNCTION(execWriteProfileSettingsCompleted);
    DECLARE_FUNCTION(execWriteProfileSettings);
    DECLARE_FUNCTION(execReadProfileSettingsCompleted);
    DECLARE_FUNCTION(execReadProfileSettings);
    DECLARE_FUNCTION(execAreAnyFriends);
    DECLARE_FUNCTION(execIsFriend);
    DECLARE_FUNCTION(execGetLoginStatus);
    DECLARE_FUNCTION(execLogout);
    DECLARE_FUNCTION(execAutoLogin);
    DECLARE_FUNCTION(execLogin);
    DECLARE_FUNCTION(execShowLoginUI);
    DECLARE_FUNCTION(execExit);
    DECLARE_FUNCTION(execInit);
#include "CppText/UOnlineSubsystemSteamworks.h"
    DECLARE_CLASS(UOnlineSubsystemSteamworks,UOnlineSubsystemCommonImpl,0|CLASS_Config,OnlineSubsystemSteamworks)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_ONLINESUBSYSTEMSTEAMWORKS_CLASSES
#endif // !NAMES_ONLY

AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execInt64ToUniqueNetId);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execUniqueNetIdToInt64);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowProfileUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execUniqueNetIdToPlayerName);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execDisplayAchievementProgress);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execEnumerateFilesOnRemoteStorage);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execDeleteFileFromRemoteStorage);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execReadBytesFromRemoteStorage);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execReadStringFromRemoteStorage);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execWriteBytesToRemoteStorage);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execWriteStringToRemoteStorage);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execGetSteamClanData);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execReadOnlineAvatar);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowCustomPlayersUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execGetAchievements);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execReadAchievements);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowPlayersUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowFriendsInviteUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowFriendsUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execUnlockGamerPicture);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execUnlockAchievement);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execIsDeviceValid);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execGetDeviceSelectionResults);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowDeviceSelectionUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowMembershipMarketplaceUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowContentMarketplaceUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowInviteUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowAchievementsUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowMessagesUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowGamerCardUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowFeedbackUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowKeyboardUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execSetOnlineStatus);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execCreateOnlineAccount);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execGetTitleFileContents);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execReadTitleFile);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execGetNATType);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execIsControllerConnected);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execSetNetworkNotificationPosition);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execHasLinkConnection);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execGetFriendsList);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execReadFriendsList);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execWriteProfileSettingsCompleted);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execWriteProfileSettings);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execReadProfileSettingsCompleted);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execReadProfileSettings);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execAreAnyFriends);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execIsFriend);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execGetLoginStatus);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execLogout);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execAutoLogin);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execLogin);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execShowLoginUI);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execExit);
AUTOGENERATE_FUNCTION(UOnlineSubsystemSteamworks,-1,execInit);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef ONLINESUBSYSTEMSTEAMWORKS_NATIVE_DEFS
#define ONLINESUBSYSTEMSTEAMWORKS_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_ONLINESUBSYSTEMSTEAMWORKS \
	UOnlineLobbyInterfaceSteamworks::StaticClass(); \
	UOnlineSubsystemSteamworks::StaticClass(); \
	GNativeLookupFuncs.Set(FName("OnlineSubsystemSteamworks"), GOnlineSubsystemSteamworksUOnlineSubsystemSteamworksNatives); \

#endif // ONLINESUBSYSTEMSTEAMWORKS_NATIVE_DEFS

#ifdef NATIVES_ONLY
FNativeFunctionLookup GOnlineSubsystemSteamworksUOnlineSubsystemSteamworksNatives[] = 
{ 
	MAP_NATIVE(UOnlineSubsystemSteamworks, execInt64ToUniqueNetId)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execUniqueNetIdToInt64)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowProfileUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execUniqueNetIdToPlayerName)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execDisplayAchievementProgress)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execEnumerateFilesOnRemoteStorage)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execDeleteFileFromRemoteStorage)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execReadBytesFromRemoteStorage)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execReadStringFromRemoteStorage)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execWriteBytesToRemoteStorage)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execWriteStringToRemoteStorage)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execGetSteamClanData)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execReadOnlineAvatar)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowCustomPlayersUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execGetAchievements)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execReadAchievements)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowPlayersUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowFriendsInviteUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowFriendsUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execUnlockGamerPicture)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execUnlockAchievement)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execIsDeviceValid)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execGetDeviceSelectionResults)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowDeviceSelectionUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowMembershipMarketplaceUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowContentMarketplaceUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowInviteUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowAchievementsUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowMessagesUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowGamerCardUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowFeedbackUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowKeyboardUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execSetOnlineStatus)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execCreateOnlineAccount)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execGetTitleFileContents)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execReadTitleFile)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execGetNATType)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execIsControllerConnected)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execSetNetworkNotificationPosition)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execHasLinkConnection)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execGetFriendsList)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execReadFriendsList)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execWriteProfileSettingsCompleted)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execWriteProfileSettings)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execReadProfileSettingsCompleted)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execReadProfileSettings)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execAreAnyFriends)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execIsFriend)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execGetLoginStatus)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execLogout)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execAutoLogin)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execLogin)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execShowLoginUI)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execExit)
	MAP_NATIVE(UOnlineSubsystemSteamworks, execInit)
	{NULL, NULL}
};

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UOnlineLobbyInterfaceSteamworks)
VERIFY_CLASS_OFFSET_NODIE(UOnlineSubsystemSteamworks,OnlineSubsystemSteamworks,CallbackBridge)
VERIFY_CLASS_OFFSET_NODIE(UOnlineSubsystemSteamworks,OnlineSubsystemSteamworks,__OnReadCrossTitleProfileSettingsComplete__Delegate)
VERIFY_CLASS_SIZE_NODIE(UOnlineSubsystemSteamworks)
#endif // VERIFY_CLASS_SIZES

#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
