// GFxUI/src/gfxuiinteraction.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (61):
//   0x5b6e50  public: static void __cdecl UGFxAction_CloseMovie::InitializePrivateStaticClassUGFxAction_CloseMovie(void)
//   0x5b6e70  public: static void __cdecl UGFxAction_GetVariable::InitializePrivateStaticClassUGFxAction_GetVariable(void)
//   0x5b6e90  public: static void __cdecl UGFxAction_Invoke::InitializePrivateStaticClassUGFxAction_Invoke(void)
//   0x5b6eb0  public: static void __cdecl UGFxAction_OpenMovie::InitializePrivateStaticClassUGFxAction_OpenMovie(void)
//   0x5b6ed0  public: static void __cdecl UGFxAction_SetCaptureKeys::InitializePrivateStaticClassUGFxAction_SetCaptureKeys(void)
//   0x5b6ef0  public: static void __cdecl UGFxAction_SetVariable::InitializePrivateStaticClassUGFxAction_SetVariable(void)
//   0x5b6f10  public: static void __cdecl UGFxInteraction::InitializePrivateStaticClassUGFxInteraction(void)
//   0x5b6f30  public: static void __cdecl UGFxEvent_FSCommand::InitializePrivateStaticClassUGFxEvent_FSCommand(void)
//   0x5b6f50  public: virtual void __thiscall UGFxInteraction::BeginDestroy(void)
//   0x5b6f70  public: virtual unsigned int __thiscall UGFxInteraction::IsReadyForFinishDestroy(void)
//   0x5b6f90  public: virtual int __thiscall UGFxEngine::GetResourceSize(void)
//   0x5b6fa0  public: virtual void __thiscall UGFxEvent_FSCommand::FinishDestroy(void)
//   0x5b9aa0  public: static class UClass * __cdecl UGFxFSCmdHandler_Kismet::GetPrivateStaticClassUGFxFSCmdHandler_Kismet(wchar_t const *)
//   0x5b9b30  public: static class UClass * __cdecl UGFxInteraction::GetPrivateStaticClassUGFxInteraction(wchar_t const *)
//   0x5b9bc0  public: static void __cdecl UGFxEngine::DumpGFXMemoryStats(class FOutputDevice &)
//   0x5bff50  public: static class UClass * __cdecl UGFxInteraction::StaticClassNoInline(void)
//   0x5bff80  public: virtual void __thiscall UGFxInteraction::SetRenderViewport(class FViewport *)
//   0x5bffa0  public: virtual void __thiscall UGFxInteraction::Tick(float)
//   0x5bffd0  public: virtual void __thiscall UGFxInteraction::Send(enum ECallbackEventType, class FViewport *, unsigned int)
//   0x5c0000  public: unsigned int __thiscall UGFxEngine::AddGCReferenceFor(class UObject const * const, int)
//   0x5c00f0  public: unsigned int __thiscall UGFxEngine::RemoveGCReferenceFor(class UObject const * const)
//   0x5c01b0  void __cdecl RefreshIsUsingGamepad(int, unsigned int)
//   0x5c0260  SeqVarToASValue
//   0x5c03e0  ASValueToSeqVar
//   0x5caf20  public: static void __cdecl UGFxFSCmdHandler_Kismet::InitializePrivateStaticClassUGFxFSCmdHandler_Kismet(void)
//   0x5caf40  public: virtual class UGFxMoviePlayer * __thiscall UGFxInteraction::GetFocusMovie(int)
//   0x5caf80  public: virtual unsigned int __thiscall UGFxFSCmdHandler_Kismet::FSCommand(class UGFxMoviePlayer *, class UGFxEvent_FSCommand *, class FString const &, class FString const &)
//   0x5cf3e0  public: static class UClass * __cdecl UGFxFSCmdHandler_Kismet::StaticClassNoInline(void)
//   0x5d22b0  public: virtual void __thiscall UGFxInteraction::CloseAllMoviePlayers(void)
//   0x5d22d0  public: virtual unsigned int __thiscall UGFxInteraction::InputKey(int, class FName, enum EInputEvent, float, unsigned int)
//   0x5d2390  public: virtual unsigned int __thiscall UGFxInteraction::InputChar(int, wchar_t)
//   0x5d23c0  public: virtual unsigned int __thiscall UGFxEvent_FSCommand::RegisterEvent(void)
//   0x5d4ef0  public: virtual void __thiscall UGFxInteraction::FinishDestroy(void)
//   0x5d4f30  public: virtual void __thiscall UGFxInteraction::NotifyGameSessionEnded(void)
//   0x5d4f40  public: virtual unsigned int __thiscall UGFxInteraction::InputAxis(int, class FName, float, float, unsigned int)
//   0x5de6c0  public: static class UClass * __cdecl UGFxAction_CloseMovie::GetPrivateStaticClassUGFxAction_CloseMovie(wchar_t const *)
//   0x5de750  public: static class UClass * __cdecl UGFxAction_GetVariable::GetPrivateStaticClassUGFxAction_GetVariable(wchar_t const *)
//   0x5de7e0  public: static class UClass * __cdecl UGFxAction_Invoke::GetPrivateStaticClassUGFxAction_Invoke(wchar_t const *)
//   0x5de870  public: static class UClass * __cdecl UGFxAction_OpenMovie::GetPrivateStaticClassUGFxAction_OpenMovie(wchar_t const *)
//   0x5de900  public: static class UClass * __cdecl UGFxAction_SetCaptureKeys::GetPrivateStaticClassUGFxAction_SetCaptureKeys(wchar_t const *)
//   0x5de990  public: static class UClass * __cdecl UGFxAction_SetVariable::GetPrivateStaticClassUGFxAction_SetVariable(wchar_t const *)
//   0x5dea20  public: static class UClass * __cdecl UGFxEvent_FSCommand::GetPrivateStaticClassUGFxEvent_FSCommand(wchar_t const *)
//   0x5e1a10  public: static class UClass * __cdecl UGFxAction_CloseMovie::StaticClassNoInline(void)
//   0x5e1a40  public: static class UClass * __cdecl UGFxAction_GetVariable::StaticClassNoInline(void)
//   0x5e1a70  public: static class UClass * __cdecl UGFxAction_Invoke::StaticClassNoInline(void)
//   0x5e1aa0  public: static class UClass * __cdecl UGFxAction_OpenMovie::StaticClassNoInline(void)
//   0x5e1ad0  public: static class UClass * __cdecl UGFxAction_SetCaptureKeys::StaticClassNoInline(void)
//   0x5e1b00  public: static class UClass * __cdecl UGFxAction_SetVariable::StaticClassNoInline(void)
//   0x5e1b30  public: static class UClass * __cdecl UGFxEvent_FSCommand::StaticClassNoInline(void)
//   0x5e3530  public: virtual void __thiscall UGFxInteraction::Init(void)
//   0x5e3580  public: virtual void __thiscall UGFxInteraction::NotifyPlayerAdded(int, class ULocalPlayer *)
//   0x5e3590  public: virtual void __thiscall UGFxInteraction::NotifyPlayerRemoved(int, class ULocalPlayer *)
//   0x5e4af0  public: virtual unsigned int __thiscall UGFxInteraction::Exec(wchar_t const *, class FOutputDevice &)
//   0x5e51a0  public: virtual void __thiscall UGFxAction_OpenMovie::Activated(void)
//   0x5e5630  public: virtual void __thiscall UGFxAction_CloseMovie::Activated(void)
//   0x5e5760  public: void __thiscall UGFxAction_SetCaptureKeys::SetKeys(void)
//   0x5e58e0  public: void __thiscall UGFxAction_SetCaptureKeys::RemoveKeys(void)
//   0x5e5a50  public: virtual void __thiscall UGFxAction_GetVariable::Activated(void)
//   0x5e5d80  public: virtual void __thiscall UGFxAction_SetVariable::Activated(void)
//   0x5e6170  public: virtual void __thiscall UGFxAction_Invoke::Activated(void)
//   0x5e82d0  public: virtual void __thiscall UGFxAction_SetCaptureKeys::Activated(void)
