// GFxUI/src/gfxuimovie.cpp
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (141):
//   0x5b6fb0  public: static void __cdecl UGFxMoviePlayer::InitializePrivateStaticClassUGFxMoviePlayer(void)
//   0x5b6fd0  public: static void __cdecl UGFxFSCmdHandler::InitializePrivateStaticClassUGFxFSCmdHandler(void)
//   0x5b6ff0  public: static void __cdecl UGFxRawData::InitializePrivateStaticClassUGFxRawData(void)
//   0x5b7010  public: virtual void __thiscall UGFxMoviePlayer::Cleanup(void)
//   0x5b7030  public: virtual void __thiscall UGFxMoviePlayer::FinishDestroy(void)
//   0x5b7050  public: void __thiscall UGFxMoviePlayer::SetMovieCanReceiveFocus(unsigned int)
//   0x5b7070  public: void __thiscall UGFxMoviePlayer::SetMovieCanReceiveInput(unsigned int)
//   0x5b7090  public: virtual void __thiscall UGFxMoviePlayer::SetPause(unsigned int)
//   0x5b70b0  public: virtual void __thiscall UGFxMoviePlayer::SetTimingMode(unsigned char)
//   0x5b7100  public: virtual void __thiscall UGFxMoviePlayer::PostAdvance(float)
//   0x5b71b0  public: virtual void __thiscall UGFxObject::BeginDestroy(void)
//   0x5b71d0  GFxDisplayInfoToU
//   0x5b7350  UDisplayInfoToGFx
//   0x5b7440  public: struct FASDisplayInfo __thiscall UGFxObject::GetDisplayInfo(void)
//   0x5b74b0  public: class FMatrix __thiscall UGFxObject::GetDisplayMatrix(void)
//   0x5b7580  public: unsigned int __thiscall UGFxObject::GetPosition(float &, float &)
//   0x5b75f0  public: void __thiscall UGFxObject::SetDisplayInfo(struct FASDisplayInfo)
//   0x5b7650  public: void __thiscall UGFxObject::execSetDisplayMatrix(struct FFrame &, void * const)
//   0x5b9cf0  public: static class UClass * __cdecl UGFxFSCmdHandler::GetPrivateStaticClassUGFxFSCmdHandler(wchar_t const *)
//   0x5b9d80  public: void __thiscall UGFxMoviePlayer::SetViewport(int, int, int, int)
//   0x5b9e30  public: virtual void __thiscall UGFxMoviePlayer::Advance(float)
//   0x5b9e80  public: virtual void __thiscall UGFxObject::Clear(void)
//   0x5b9eb0  public: void __thiscall UGFxObject::SetPosition(float, float)
//   0x5b9f20  public: void __thiscall UGFxObject::execSetDisplayMatrix3D(struct FFrame &, void * const)
//   0x5b9fc0  public: void __thiscall UGFxObject::SetVisible(unsigned int)
//   0x5ba020  public: void __thiscall UGFxObject::SetElementObject(int, class UGFxObject *)
//   0x5ba0d0  public: unsigned int __thiscall UGFxObject::GetElementBool(int)
//   0x5ba1a0  public: float __thiscall UGFxObject::GetElementFloat(int)
//   0x5ba260  public: void __thiscall UGFxObject::SetElementFloat(int, float)
//   0x5ba2f0  public: void __thiscall UGFxObject::SetElementString(int, class FString const &)
//   0x5ba3c0  public: void __thiscall UGFxObject::SetElementVisible(int, unsigned int)
//   0x5ba4a0  public: void __thiscall UGFxObject::SetElementPosition(int, float, float)
//   0x5ba580  public: void __thiscall UGFxObject::SetElementColorTransform(int, struct FASColorTransform)
//   0x5ba680  public: struct FASDisplayInfo __thiscall UGFxObject::GetElementDisplayInfo(int)
//   0x5ba770  public: class FMatrix __thiscall UGFxObject::GetElementDisplayMatrix(int)
//   0x5ba8c0  public: void __thiscall UGFxObject::SetElementDisplayInfo(int, struct FASDisplayInfo)
//   0x5ba990  public: void __thiscall UGFxObject::SetElementDisplayMatrix(int, class FMatrix const &)
//   0x5baa80  public: void __thiscall UGFxObject::execSetElementDisplayMatrix(struct FFrame &, void * const)
//   0x5c0520  public: static class UClass * __cdecl UGFxFSCmdHandler::StaticClassNoInline(void)
//   0x5c0550  public: virtual struct FASValue __thiscall UGFxMoviePlayer::Invoke(class FString const &, class TArray<struct FASValue, class FDefaultAllocator> const &)
//   0x5c0930  public: class UGFxObject * __thiscall UGFxMoviePlayer::CreateValueAddRef(void const *, class UClass *)
//   0x5c0a00  public: virtual void __thiscall UGFxMoviePlayer::SetVariableObject(class FString const &, class UGFxObject *)
//   0x5c0b70  public: virtual struct FASValue __thiscall UGFxMoviePlayer::GetVariable(class FString const &)
//   0x5c0d30  public: virtual unsigned int __thiscall UGFxMoviePlayer::GetVariableBool(class FString const &)
//   0x5c0e60  public: virtual float __thiscall UGFxMoviePlayer::GetVariableNumber(class FString const &)
//   0x5c0f90  public: virtual class FString __thiscall UGFxMoviePlayer::GetVariableString(class FString const &)
//   0x5c1180  public: virtual void __thiscall UGFxMoviePlayer::SetVariable(class FString const &, struct FASValue)
//   0x5c1300  public: virtual void __thiscall UGFxMoviePlayer::SetVariableBool(class FString const &, unsigned int)
//   0x5c1420  public: virtual void __thiscall UGFxMoviePlayer::SetVariableNumber(class FString const &, float)
//   0x5c1540  public: virtual void __thiscall UGFxMoviePlayer::SetVariableString(class FString const &, class FString const &)
//   0x5c1690  public: virtual unsigned int __thiscall UGFxMoviePlayer::SetVariableArray(class FString const &, int, class TArray<struct FASValue, class FDefaultAllocator> const &)
//   0x5c1970  public: virtual unsigned int __thiscall UGFxMoviePlayer::SetVariableIntArray(class FString const &, int, class TArray<int, class FDefaultAllocator> const &)
//   0x5c1aa0  public: virtual unsigned int __thiscall UGFxMoviePlayer::SetVariableFloatArray(class FString const &, int, class TArray<float, class FDefaultAllocator> const &)
//   0x5c1bd0  public: virtual unsigned int __thiscall UGFxMoviePlayer::SetVariableStringArray(class FString const &, int, class TArray<class FString, class FDefaultAllocator> const &)
//   0x5c1d80  public: struct FASValue __thiscall UGFxObject::Invoke(class FString const &, class TArray<struct FASValue, class FDefaultAllocator> const &)
//   0x5c2210  public: void __thiscall UGFxObject::GotoAndPlay(class FString const &)
//   0x5c22e0  public: void __thiscall UGFxObject::GotoAndStop(class FString const &)
//   0x5c23b0  public: struct FASValue __thiscall UGFxObject::Get(class FString const &)
//   0x5c25c0  public: unsigned int __thiscall UGFxObject::GetBool(class FString const &)
//   0x5c2700  public: float __thiscall UGFxObject::GetFloat(class FString const &)
//   0x5c2840  public: class FString __thiscall UGFxObject::GetString(class FString const &)
//   0x5c2a50  public: class FString __thiscall UGFxObject::GetText(void)
//   0x5c2bb0  public: void __thiscall UGFxObject::Set(class FString const &, struct FASValue)
//   0x5c2d50  public: void __thiscall UGFxObject::SetObject(class FString const &, class UGFxObject *)
//   0x5c2f40  public: void __thiscall UGFxObject::SetBool(class FString const &, unsigned int)
//   0x5c3070  public: void __thiscall UGFxObject::SetFloat(class FString const &, float)
//   0x5c31a0  public: struct FASValue __thiscall UGFxObject::GetElement(int)
//   0x5c32f0  public: class FString __thiscall UGFxObject::GetElementString(int)
//   0x5c3460  public: void __thiscall UGFxObject::SetElement(int, struct FASValue)
//   0x5c3570  public: void __thiscall UGFxObject::SetElementBool(int, unsigned int)
//   0x5c3600  public: struct FASValue __thiscall UGFxObject::GetElementMember(int, class FString const &)
//   0x5c3830  public: unsigned int __thiscall UGFxObject::GetElementMemberBool(int, class FString const &)
//   0x5c39c0  public: float __thiscall UGFxObject::GetElementMemberFloat(int, class FString const &)
//   0x5c3b50  public: class FString __thiscall UGFxObject::GetElementMemberString(int, class FString const &)
//   0x5c3d20  public: void __thiscall UGFxObject::SetElementMember(int, class FString const &, struct FASValue)
//   0x5c3ee0  public: void __thiscall UGFxObject::SetElementMemberObject(int, class FString const &, class UGFxObject *)
//   0x5c4030  public: void __thiscall UGFxObject::SetElementMemberBool(int, class FString const &, unsigned int)
//   0x5c4190  public: void __thiscall UGFxObject::SetElementMemberFloat(int, class FString const &, float)
//   0x5c42e0  public: void __thiscall UGFxObject::SetElementMemberString(int, class FString const &, class FString const &)
//   0x5cb160  public: virtual void __thiscall FGFxSoundEventCallback::Call(struct GFxFunctionHandler::Params const &)
//   0x5cb2c0  public: virtual unsigned int __thiscall UGFxMoviePlayer::GetVariableIntArray(class FString const &, int, class TArray<int, class FDefaultAllocator> &)
//   0x5cb4a0  public: virtual unsigned int __thiscall UGFxMoviePlayer::GetVariableFloatArray(class FString const &, int, class TArray<float, class FDefaultAllocator> &)
//   0x5cb680  public: void __thiscall FOutputToGfxPolicy::OnBeginFont(class FString const &)
//   0x5cb730  public: void __thiscall FOutputToGfxPolicy::OnBeginColor(struct FLinearColor)
//   0x5cb7c0  public: __thiscall FGFxDelegateCallback::FGFxDelegateCallback(struct FScriptDelegate const &)
//   0x5cb840  public: virtual __thiscall FGFxDelegateCallback::~FGFxDelegateCallback(void)
//   0x5cb8e0  public: void __thiscall UGFxObject::SetFunction(class FString const &, class UObject *, class FName)
//   0x5cba60  public: void __thiscall UGFxObject::execActionScriptSetFunction(struct FFrame &, void * const)
//   0x5cbc30  public: void __thiscall UGFxObject::execActionScriptSetFunctionOn(struct FFrame &, void * const)
//   0x5cbe20  public: void __thiscall UGFxMoviePlayer::execActionScriptSetFunction(struct FFrame &, void * const)
//   0x5cf480  public: virtual unsigned int __thiscall FGFxCLIKObjectOnLoadEventCallback::CallEventHandler(class FName const &, class FName const &, class UGFxObject *, class UGFxObject *)
//   0x5cf550  public: virtual unsigned int __thiscall FGFxCLIKObjectOnUnloadEventCallback::CallEventHandler(class FName const &, class FName const &, class UGFxObject *, class UGFxObject *)
//   0x5cf5b0  public: virtual unsigned int __thiscall UGFxMoviePlayer::Start(unsigned int)
//   0x5cf600  public: virtual void __thiscall UGFxMoviePlayer::Close(unsigned int)
//   0x5cf740  public: virtual unsigned int __thiscall UGFxMoviePlayer::SetExternalTexture(class FString const &, class UTexture *)
//   0x5d35e0  public: static class UClass * __cdecl UGFxObject::GetPrivateStaticClassUGFxObject(wchar_t const *)
//   0x5d3670  public: virtual unsigned int __thiscall UGFxMoviePlayer::GetVariableArray(class FString const &, int, class TArray<struct FASValue, class FDefaultAllocator> &)
//   0x5d3930  public: virtual unsigned int __thiscall UGFxMoviePlayer::GetVariableStringArray(class FString const &, int, class TArray<class FString, class FDefaultAllocator> &)
//   0x5d5040  public: static class UClass * __cdecl UGFxRawData::GetPrivateStaticClassUGFxRawData(wchar_t const *)
//   0x5d50d0  public: static class UClass * __cdecl USwfMovie::GetPrivateStaticClassUSwfMovie(wchar_t const *)
//   0x5d5160  public: static class UClass * __cdecl UFlashMovie::GetPrivateStaticClassUFlashMovie(wchar_t const *)
//   0x5d51f0  public: void __thiscall UGFxObject::SetString(class FString const &, class FString const &, class UTranslationContext *)
//   0x5d5380  public: void __thiscall UGFxObject::SetText(class FString const &, class UTranslationContext *)
//   0x5d7310  public: static class UClass * __cdecl UGFxRawData::StaticClassNoInline(void)
//   0x5d7340  public: static void __cdecl USwfMovie::InitializePrivateStaticClassUSwfMovie(void)
//   0x5d90b0  public: static class UClass * __cdecl USwfMovie::StaticClassNoInline(void)
//   0x5d90e0  public: static void __cdecl UFlashMovie::InitializePrivateStaticClassUFlashMovie(void)
//   0x5d9100  public: void __thiscall UGFxMoviePlayer::AddCaptureKey(class FName)
//   0x5d91a0  public: void __thiscall UGFxMoviePlayer::ClearFocusIgnoreKeys(void)
//   0x5d91d0  public: void __thiscall UGFxMoviePlayer::AddFocusIgnoreKey(class FName)
//   0x5dae80  public: static class UClass * __cdecl UFlashMovie::StaticClassNoInline(void)
//   0x5daeb0  public: void __thiscall UGFxMoviePlayer::FlushPlayerInput(unsigned int)
//   0x5deab0  public: __thiscall UGFxMoviePlayer::UGFxMoviePlayer(void)
//   0x5deb80  public: virtual void __thiscall USwfMovie::PostLoad(void)
//   0x5e1b60  public: static class UClass * __cdecl UGFxMoviePlayer::GetPrivateStaticClassUGFxMoviePlayer(wchar_t const *)
//   0x5e30f0  public: static class UClass * __cdecl UGFxMoviePlayer::StaticClassNoInline(void)
//   0x5e3120  public: static void __cdecl UGFxObject::InitializePrivateStaticClassUGFxObject(void)
//   0x5e35c0  public: static class UClass * __cdecl UGFxObject::StaticClassNoInline(void)
//   0x5e35f0  public: unsigned int __thiscall UGFxMoviePlayer::Load(class FString const &, unsigned int)
//   0x5e3a30  public: virtual unsigned int __thiscall UGFxMoviePlayer::PreLoad(void)
//   0x5e6800  public: virtual void __thiscall FGFxCLIKObjectEventCallback::Call(struct GFxFunctionHandler::Params const &)
//   0x5e6aa0  public: virtual class UGFxObject * __thiscall UGFxMoviePlayer::GetVariableObject(class FString const &, class UClass *)
//   0x5e6c20  public: virtual class UGFxObject * __thiscall UGFxMoviePlayer::CreateObject(class FString const &, class UClass *)
//   0x5e6d70  public: virtual class UGFxObject * __thiscall UGFxMoviePlayer::CreateArray(void)
//   0x5e6e30  public: class UGFxObject * __thiscall UGFxObject::GetObjectW(class FString const &, class UClass *)
//   0x5e6fd0  public: class UGFxObject * __thiscall UGFxObject::CreateEmptyMovieClip(class FString const &, int, class UClass *)
//   0x5e7150  public: class UGFxObject * __thiscall UGFxObject::AttachMovie(class FString const &, class FString const &, int, class UClass *)
//   0x5e7370  public: class UGFxObject * __thiscall UGFxObject::GetElementObject(int, class UClass *)
//   0x5e7470  public: class UGFxObject * __thiscall UGFxObject::GetElementMemberObject(int, class FString const &, class UClass *)
//   0x5e7660  public: virtual void __thiscall FGFxDelegateCallback::Call(struct GFxFunctionHandler::Params const &)
//   0x5e7870  void __cdecl ExecuteActionScript<class GPtr<class GFxMovieView>>(class GPtr<class GFxMovieView>, class UGFxMoviePlayer *, class GFxValue &, struct FFrame &, void * const, enum ActionScriptReturnSignature)
//   0x5e7b30  void __cdecl ExecuteActionScript<class GFxValue *>(class GFxValue *, class UGFxMoviePlayer *, class GFxValue &, struct FFrame &, void * const, enum ActionScriptReturnSignature)
//   0x5e8350  public: void __thiscall UGFxMoviePlayer::execActionScriptVoid(struct FFrame &, void * const)
//   0x5e83f0  public: void __thiscall UGFxMoviePlayer::execActionScriptInt(struct FFrame &, void * const)
//   0x5e8490  public: void __thiscall UGFxMoviePlayer::execActionScriptString(struct FFrame &, void * const)
//   0x5e8530  public: void __thiscall UGFxMoviePlayer::execActionScriptObject(struct FFrame &, void * const)
//   0x5e85d0  public: void __thiscall UGFxObject::execActionScriptVoid(struct FFrame &, void * const)
//   0x5e8660  public: void __thiscall UGFxObject::execActionScriptFloat(struct FFrame &, void * const)
//   0x5e8700  public: void __thiscall UGFxObject::execActionScriptString(struct FFrame &, void * const)
//   0x5e87a0  public: void __thiscall UGFxObject::execActionScriptObject(struct FFrame &, void * const)
//   0x5e8830  public: void __thiscall UGFxObject::execActionScriptArray(struct FFrame &, void * const)
