/*=============================================================================
	DebugCameraController.h: Engine.DebugCameraController.
=============================================================================*/

#ifndef _INC_DEBUGCAMERACONTROLLER
#define _INC_DEBUGCAMERACONTROLLER

// DISHONORED(retail): Engine.DebugCameraController lives in Engine on APlayerController (script_classes_2013.json: super
// Engine.PlayerController, config Input, header group Controller; native_class_sizes.csv 1376 bytes, super APlayerController,
// 2013 StaticClassNoInline rva 0xdce70). The reference tree had it in GameFramework on AGamePlayerController.
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

class ADebugCameraController : public APlayerController
{
public:
    //## BEGIN PROPS DebugCameraController
    // DISHONORED(layout): retail SDK span 1320..1368, retail sizeof 1376 (16-byte AActor alignment); regenerated by sdk_props.py
    FName PrimaryKey;  // DISHONORED(layout): retail SDK @1320, 2012 PDB @1320
    FName SecondaryKey;  // DISHONORED(layout): retail SDK @1328, 2012 PDB @1328
    FName UnselectKey;  // DISHONORED(layout): retail SDK @1336, 2012 PDB @1336
    BITFIELD bShowSelectedInfo:1;  // DISHONORED(layout): retail SDK @1344, 2012 PDB @1344
    BITFIELD bIsFrozenRendering:1;  // DISHONORED(layout): retail SDK @1344, 2012 PDB @1344
    class APlayerController* OryginalControllerRef;  // DISHONORED(layout): retail SDK @1348, 2012 PDB @1348
    class UPlayer* OryginalPlayer;  // DISHONORED(layout): retail SDK @1352, 2012 PDB @1352
    class UDrawFrustumComponent* DrawFrustum;  // DISHONORED(layout): retail SDK @1356, 2012 PDB @1356
    class AActor* SelectedActor;  // DISHONORED(layout): retail SDK @1360, 2012 PDB @1360
    class UPrimitiveComponent* SelectedComponent;  // DISHONORED(layout): retail SDK @1364, 2012 PDB @1364
    //## END PROPS DebugCameraController

    virtual void PrimarySelect(FVector HitLoc,FVector HitNormal,struct FTraceHitInfo HitInfo);
    virtual void SecondarySelect(FVector HitLoc,FVector HitNormal,struct FTraceHitInfo HitInfo);
    virtual void Unselect();
    virtual FString ConsoleCommand(const FString& Command,UBOOL bWriteToLog=TRUE);
    DECLARE_FUNCTION(execPrimarySelect)
    {
        P_GET_STRUCT(FVector,HitLoc);
        P_GET_STRUCT(FVector,HitNormal);
        P_GET_STRUCT(struct FTraceHitInfo,HitInfo);
        P_FINISH;
        this->PrimarySelect(HitLoc,HitNormal,HitInfo);
    }
    DECLARE_FUNCTION(execSecondarySelect)
    {
        P_GET_STRUCT(FVector,HitLoc);
        P_GET_STRUCT(FVector,HitNormal);
        P_GET_STRUCT(struct FTraceHitInfo,HitInfo);
        P_FINISH;
        this->SecondarySelect(HitLoc,HitNormal,HitInfo);
    }
    DECLARE_FUNCTION(execUnselect)
    {
        P_FINISH;
        this->Unselect();
    }
    DECLARE_CLASS(ADebugCameraController,APlayerController,0|CLASS_Config,Engine)
    static const TCHAR* StaticConfigName() {return TEXT("Input");}

    virtual void UpdateHiddenComponents(const FVector& ViewLocation,TSet<UPrimitiveComponent*>& HiddenComponents);
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS

extern FNativeFunctionLookup GEngineADebugCameraControllerNatives[];

#endif
