#pragma once
// Engine/inc/enginearkppclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (39):
//   0x1eb4c0  public: static class UClass * __cdecl UArkPpNodeController::StaticClass(void)
//   0x1eb4e0  public: static class UClass * __cdecl UArkPpNode::StaticClass(void)
//   0x1eb500  public: static class UClass * __cdecl UArkPpNodeAA::StaticClass(void)
//   0x1eb520  public: static class UClass * __cdecl UArkPpNodeBlur::StaticClass(void)
//   0x1eb540  public: static class UClass * __cdecl UArkPpNodeCommonTarget::StaticClass(void)
//   0x1eb560  public: static class UClass * __cdecl UArkPpNodeDof::StaticClass(void)
//   0x1eb580  public: static class UClass * __cdecl UArkPpNodeKuwa::StaticClass(void)
//   0x1eb5a0  public: static class UClass * __cdecl UArkPpNodeMaterial::StaticClass(void)
//   0x1eb5c0  public: static class UClass * __cdecl UArkPpNodeSceneColor::StaticClass(void)
//   0x1eb5e0  public: static class UClass * __cdecl UArkPpNodeSwitch::StaticClass(void)
//   0x1eb600  public: static class UClass * __cdecl UArkPpNodeTarget::StaticClass(void)
//   0x549c00  protected: virtual __thiscall UArkPpNodeController::~UArkPpNodeController(void)
//   0x54b7e0  public: static void __cdecl UArkPpNodeController::InternalConstructor(void *)
//   0x5590d0  protected: virtual __thiscall UArkPpNode::~UArkPpNode(void)
//   0x559170  public: virtual class UArkPpNode * __thiscall UArkPpNodeAA::GetInput(unsigned int)
//   0x559180  protected: virtual __thiscall UArkPpNodeAA::~UArkPpNodeAA(void)
//   0x559210  protected: virtual __thiscall UArkPpNodeBlur::~UArkPpNodeBlur(void)
//   0x5592a0  protected: virtual __thiscall UArkPpNodeCommonTarget::~UArkPpNodeCommonTarget(void)
//   0x559330  public: virtual class UArkPpNode * __thiscall UArkPpNodeDof::GetInput(unsigned int)
//   0x559340  protected: virtual __thiscall UArkPpNodeDof::~UArkPpNodeDof(void)
//   0x5593d0  public: virtual class UArkPpNode * __thiscall UArkPpNodeKuwa::GetInput(unsigned int)
//   0x5593f0  protected: virtual __thiscall UArkPpNodeKuwa::~UArkPpNodeKuwa(void)
//   0x559480  protected: virtual __thiscall UArkPpNodeSceneColor::~UArkPpNodeSceneColor(void)
//   0x559510  public: virtual class UArkPpNode * __thiscall UArkPpNodeSwitch::GetInput(unsigned int)
//   0x559540  protected: virtual __thiscall UArkPpNodeSwitch::~UArkPpNodeSwitch(void)
//   0x5595e0  protected: virtual __thiscall UArkPpNodeTarget::~UArkPpNodeTarget(void)
//   0x55d500  public: static void __cdecl UArkPpNode::InternalConstructor(void *)
//   0x55d520  public: static void __cdecl UArkPpNodeAA::InternalConstructor(void *)
//   0x55d540  public: static void __cdecl UArkPpNodeBlur::InternalConstructor(void *)
//   0x55d560  public: static void __cdecl UArkPpNodeCommonTarget::InternalConstructor(void *)
//   0x55d580  public: static void __cdecl UArkPpNodeDof::InternalConstructor(void *)
//   0x55d5a0  public: static void __cdecl UArkPpNodeKuwa::InternalConstructor(void *)
//   0x55d5c0  public: static void __cdecl UArkPpNodeSceneColor::InternalConstructor(void *)
//   0x55d5e0  public: static void __cdecl UArkPpNodeSwitch::InternalConstructor(void *)
//   0x55d600  public: static void __cdecl UArkPpNodeTarget::InternalConstructor(void *)
//   0x55f260  public: virtual unsigned int __thiscall UArkPpNodeMaterial::NumInputs(void)const
//   0x55f270  public: virtual class UArkPpNode * __thiscall UArkPpNodeMaterial::GetInput(unsigned int)
//   0x55f2d0  protected: virtual __thiscall UArkPpNodeMaterial::~UArkPpNodeMaterial(void)
//   0x561060  public: static void __cdecl UArkPpNodeMaterial::InternalConstructor(void *)
