/*===========================================================================
    EngineArkaneClasses.h - Arkane's own Engine-package native classes.

    DISHONORED(port): these classes belong to the retail Engine package (native_class_sizes.csv package_2013 = Engine) but have no
    counterpart in the reference tree, so agent T's generator emitted them into DishonoredGame's shim header
    (DishonoredGameEngineShims.h) and DishonoredGame registered them. They are Engine's: Engine.upk's exports use them
    (145 AkEvent and 45 AkBank objects in Startup.upk alone) and their Serialize/PostLoad run while Engine packages load.
    Layouts are the retail SDK dump (retail_sdk_layout.json), copied verbatim from the generated shim blocks; sizes are asserted below.
    Bodies: Engine/Src/akevent.cpp, akbank.cpp, arkcomponentcontainer.cpp (the retail source files of the 2012 PDB) and
    Engine/Src/UnWorld.cpp (IMPLEMENT_CLASS(UAudioSystem), which the 2012 PDB attributes to engine/src/unworld.cpp).
    The matinee half of the same move (UMatineeData, the Arkane interp tracks) is in EngineInterpolationClasses.h.
===========================================================================*/
#ifndef NAMES_ONLY
#ifndef INCLUDED_ENGINE_ARKANE_CLASSES
#define INCLUDED_ENGINE_ARKANE_CLASSES 1

#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

// the DECLARE_CLASS family of the script classes, like every generated *Classes.h of the module
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

class UAkAudioDevice;

// Engine.AkBank: retail sizeof 64, reflected span 56..64 (2012 PDB sizeof 64)
class UAkBank : public UObject
{
public:
    //## BEGIN PROPS AkBank
    INT m_AkPackageID;
    BITFIELD AutoLoad:1;
    BITFIELD GenerateDefinition:1;
    BITFIELD AutoGenerated:1;
    //## END PROPS AkBank


    // DISHONORED(port): akbank.cpp. 2013 rvas: PostLoad 0xcdac0, BeginDestroy 0xc7830, Load 0xc7210, Unload 0xc7680
    virtual void PostLoad();
    virtual void BeginDestroy();
    UBOOL Load();
    void Unload();
    DECLARE_CLASS(UAkBank,UObject,0,Engine)
};

// Engine.AkBaseSoundObject: retail sizeof 56, reflected span 56..56 (2012 PDB sizeof 56)
class UAkBaseSoundObject : public UObject
{
public:
    //## BEGIN PROPS AkBaseSoundObject
    //## END PROPS AkBaseSoundObject

    DECLARE_ABSTRACT_CLASS(UAkBaseSoundObject,UObject,0,Engine)
};

// Engine.AkEvent: retail sizeof 68, reflected span 56..68 (2012 PDB sizeof 68)
class UAkEvent : public UAkBaseSoundObject
{
public:
    //## BEGIN PROPS AkEvent
    class UAkBank* RequiredBank;
    FLOAT m_fMaxRadius;
    INT m_akID;
    //## END PROPS AkEvent


    // DISHONORED(port): akevent.cpp. 2013 rvas: PostLoad 0xcdb10, PostRename 0xc78e0 (thunk to ComputeAkID), ComputeAkID 0xc7840,
    // FixRequiredBank 0xc78e0, ComputeMaxRadius 0xc7aa0, GetMaxRadius 0xcdb40, IsAudible 0xb0bd0
    virtual void PostLoad();
    virtual void PostRename();
    void ComputeAkID();
    void FixRequiredBank();
    void ComputeMaxRadius();
    FLOAT GetMaxRadius();
    virtual UBOOL IsAudible( const FVector& SourceLocation, const FVector& ListenerLocation, AActor* SourceActor, UBOOL& bIsOccluded, UBOOL bCheckOcclusion );
    DECLARE_CLASS(UAkEvent,UAkBaseSoundObject,0,Engine)
};

// Engine.ArkComponentContainer: retail sizeof 96, reflected span 81..96 (2012 PDB sizeof 96)
class UArkComponentContainer : public UActorComponent
{
public:
    //## BEGIN PROPS ArkComponentContainer
    TArrayNoInit<FPointer> m_Components;
    //## END PROPS ArkComponentContainer


    // DISHONORED(port): arkcomponentcontainer.cpp. 2013 rvas: Serialize 0x5364b0, BeginDestroy 0x538a80,
    // AddReferencedObjects 0x536460, RemoveAllComponents 0x538990
    virtual void Serialize( FArchive& Ar );
    virtual void BeginDestroy();
    virtual void AddReferencedObjects( TArray<UObject*>& ObjectArray );
    void RemoveAllComponents();
    DECLARE_CLASS(UArkComponentContainer,UActorComponent,0,Engine)
};

// Engine.AudioSystem: retail sizeof 56, reflected span 56..56 (2012 PDB sizeof 56)
class UAudioSystem : public UObject
{
public:
    //## BEGIN PROPS AudioSystem
    //## END PROPS AudioSystem


    // DISHONORED(retail): the eight UAudioSystem virtuals in 2013 vtable order (vftable rva 0xc5d2d8, slots 73..80 after the 73 UObject
    // slots; UDishonoredAudioSystem's table 0xd5c4b0 overrides every one of them: Init 0x7a3120, the listener-cell getter 0x83c770,
    // GetCellAtPoint 0x792d10, Update 0x7b3520, RegisterAmbientSound 0x793460, UnregisterAmbientSound 0x7a3ea0,
    // SuspendUpdate 0x7873d0, ResumeUpdate 0x7873e0). UWorld::Init constructs the class named by [DishonoredMods] AudioSystemClass
    // and calls Init through slot 73.
    /** slot 73 */
    virtual void Init() {}
    /** slot 74: the cell the listener is in (UDishonoredAudioSystem::m_pListenerCell) */
    virtual class AVolume* GetListenerCell() const { return NULL; }
    /** slot 75 */
    virtual class AVolume* GetCellAtPoint( const FVector& Point, class AVolume* LastCell ) const { return NULL; }
    /** slot 76: retail Update(UAkAudioDevice*, TSet<UAkComponent*>&); the second parameter stays opaque in Engine (AkAudio types) */
    virtual void Update( class UAkAudioDevice* AudioDevice, void* ActiveComponents ) {}
    /** slots 77, 78: retail takes an AAkAmbientSound* (AkAudio) */
    virtual void RegisterAmbientSound( AActor* AmbientSound ) {}
    virtual void UnregisterAmbientSound( AActor* AmbientSound ) {}
    /** slots 79, 80 */
    virtual void SuspendUpdate() {}
    virtual void ResumeUpdate() {}
    DECLARE_ABSTRACT_CLASS(UAudioSystem,UObject,0,Engine)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

static_assert(sizeof(UAkBank) == 64, "UAkBank: retail sizeof 64");
static_assert(sizeof(UAkBaseSoundObject) == 56, "UAkBaseSoundObject: retail sizeof 56");
static_assert(sizeof(UAkEvent) == 68, "UAkEvent: retail sizeof 68");
static_assert(sizeof(UAudioSystem) == 56, "UAudioSystem: retail sizeof 56");
static_assert(STRUCT_OFFSET(UAkBank, m_AkPackageID) == 56, "UAkBank::m_AkPackageID: retail SDK @56");
static_assert(STRUCT_OFFSET(UAkEvent, RequiredBank) == 56, "UAkEvent::RequiredBank: retail SDK @56");
static_assert(STRUCT_OFFSET(UAkEvent, m_fMaxRadius) == 60, "UAkEvent::m_fMaxRadius: retail SDK @60");
static_assert(STRUCT_OFFSET(UAkEvent, m_akID) == 64, "UAkEvent::m_akID: retail SDK @64");

#endif // !INCLUDED_ENGINE_ARKANE_CLASSES
#endif // !NAMES_ONLY

#define AUTO_INITIALIZE_REGISTRANTS_ENGINE_ARKANE \
	UAudioSystem::StaticClass(); \
	UAkBaseSoundObject::StaticClass(); \
	UAkEvent::StaticClass(); \
	UAkBank::StaticClass(); \
	UArkComponentContainer::StaticClass(); \

