#pragma once
// Engine/inc/enginesoireeclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (88):
//   0x1eb060  public: static class UClass * __cdecl UAnimNotify_SoireeAccent::StaticClass(void)
//   0x1eb080  public: static class UClass * __cdecl UAnimNotify_SoireeApex::StaticClass(void)
//   0x1eb0a0  public: static class UClass * __cdecl UAnimNotify_SoireeEnd::StaticClass(void)
//   0x1eb0c0  public: static class UClass * __cdecl UAnimNotify_SoireeIn::StaticClass(void)
//   0x1eb0e0  public: static class UClass * __cdecl UAnimNotify_SoireeLoop::StaticClass(void)
//   0x1eb100  public: static class UClass * __cdecl UAnimNotify_SoireeOut::StaticClass(void)
//   0x1eb120  public: static class UClass * __cdecl UInterpGroupPlayer::StaticClass(void)
//   0x1eb140  public: static class UClass * __cdecl UInterpGroupInstPlayer::StaticClass(void)
//   0x1eb160  public: static class UClass * __cdecl UInterpTrackAIControl::StaticClass(void)
//   0x1eb180  public: static class UClass * __cdecl UInterpTrackAttachment::StaticClass(void)
//   0x1eb1a0  public: static class UClass * __cdecl UInterpTrackFaceTo::StaticClass(void)
//   0x1eb1c0  public: static class UClass * __cdecl UInterpTrackLocomotion::StaticClass(void)
//   0x1eb1e0  public: static class UClass * __cdecl UInterpTrackLookAt::StaticClass(void)
//   0x1eb200  public: static class UClass * __cdecl UInterpTrackStretchAnimControl::StaticClass(void)
//   0x1eb220  public: static class UClass * __cdecl UInterpTrackSoireeControl::StaticClass(void)
//   0x1eb240  public: static class UClass * __cdecl UInterpTrackInstAIControl::StaticClass(void)
//   0x1eb260  public: static class UClass * __cdecl UInterpTrackInstAttachment::StaticClass(void)
//   0x1eb280  public: static class UClass * __cdecl UInterpTrackInstFaceTo::StaticClass(void)
//   0x1eb2a0  public: static class UClass * __cdecl UInterpTrackInstLocomotion::StaticClass(void)
//   0x1eb2c0  public: static class UClass * __cdecl UInterpTrackInstLookAt::StaticClass(void)
//   0x1eb2e0  public: static class UClass * __cdecl UInterpTrackInstSoireeControl::StaticClass(void)
//   0x1eb300  public: static class UClass * __cdecl UInterpTrackInstStretchAnimControl::StaticClass(void)
//   0x1eb320  public: static class UClass * __cdecl UInterpTrackKeyProperties::StaticClass(void)
//   0x1eb340  public: static class UClass * __cdecl UInterpTrackAIControlKeyProperties::StaticClass(void)
//   0x1eb360  public: static class UClass * __cdecl UInterpTrackLocomotionKeyProperties::StaticClass(void)
//   0x1eb380  public: static class UClass * __cdecl UInterpTrackAIControlBodyIntentionKeyProperties::StaticClass(void)
//   0x1eb3a0  public: static class UClass * __cdecl UInterpTrackAIControlNPCAimKeyProperties::StaticClass(void)
//   0x1eb3c0  public: static class UClass * __cdecl UInterpTrackAIControlNPCFireKeyProperties::StaticClass(void)
//   0x1eb3e0  public: static class UClass * __cdecl UInterpTrackAkEventKeyProperties::StaticClass(void)
//   0x1eb400  public: static class UClass * __cdecl UInterpTrackAttachmentKeyProperties::StaticClass(void)
//   0x1eb420  public: static class UClass * __cdecl UInterpTrackFaceToKeyProperties::StaticClass(void)
//   0x1eb440  public: static class UClass * __cdecl UInterpTrackLookAtKeyProperties::StaticClass(void)
//   0x1eb460  public: static class UClass * __cdecl UInterpTrackSoireeControlKeyProperties::StaticClass(void)
//   0x1eb480  public: static class UClass * __cdecl UInterpTrackStretchAnimKeyProperties::StaticClass(void)
//   0x53acd0  protected: virtual __thiscall UAnimNotify_SoireeEnd::~UAnimNotify_SoireeEnd(void)
//   0x53ad60  protected: virtual __thiscall UInterpTrackInstAIControl::~UInterpTrackInstAIControl(void)
//   0x53adf0  protected: virtual __thiscall UInterpTrackInstAttachment::~UInterpTrackInstAttachment(void)
//   0x53ae80  protected: virtual __thiscall UInterpTrackInstFaceTo::~UInterpTrackInstFaceTo(void)
//   0x53af10  protected: virtual __thiscall UInterpTrackInstLocomotion::~UInterpTrackInstLocomotion(void)
//   0x53afa0  protected: virtual __thiscall UInterpTrackInstLookAt::~UInterpTrackInstLookAt(void)
//   0x53b030  protected: virtual __thiscall UInterpTrackInstStretchAnimControl::~UInterpTrackInstStretchAnimControl(void)
//   0x53b0c0  protected: virtual __thiscall UInterpTrackAIControlKeyProperties::~UInterpTrackAIControlKeyProperties(void)
//   0x53b150  protected: virtual __thiscall UInterpTrackLocomotionKeyProperties::~UInterpTrackLocomotionKeyProperties(void)
//   0x53b1e0  protected: virtual __thiscall UInterpTrackAIControlBodyIntentionKeyProperties::~UInterpTrackAIControlBodyIntentionKeyProperties(void)
//   0x53b270  protected: virtual __thiscall UInterpTrackAIControlNPCAimKeyProperties::~UInterpTrackAIControlNPCAimKeyProperties(void)
//   0x53b300  protected: virtual __thiscall UInterpTrackAIControlNPCFireKeyProperties::~UInterpTrackAIControlNPCFireKeyProperties(void)
//   0x53b390  protected: virtual __thiscall UInterpTrackAttachmentKeyProperties::~UInterpTrackAttachmentKeyProperties(void)
//   0x53b420  protected: virtual __thiscall UInterpTrackFaceToKeyProperties::~UInterpTrackFaceToKeyProperties(void)
//   0x53b4b0  protected: virtual __thiscall UInterpTrackSoireeControlKeyProperties::~UInterpTrackSoireeControlKeyProperties(void)
//   0x53b540  protected: virtual __thiscall UInterpTrackStretchAnimKeyProperties::~UInterpTrackStretchAnimKeyProperties(void)
//   0x53c3c0  public: static void __cdecl UAnimNotify_SoireeEnd::InternalConstructor(void *)
//   0x53c3e0  public: static void __cdecl UInterpTrackInstAIControl::InternalConstructor(void *)
//   0x53c400  public: static void __cdecl UInterpTrackInstAttachment::InternalConstructor(void *)
//   0x53c420  public: static void __cdecl UInterpTrackInstFaceTo::InternalConstructor(void *)
//   0x53c440  public: static void __cdecl UInterpTrackInstLocomotion::InternalConstructor(void *)
//   0x53c460  public: static void __cdecl UInterpTrackInstLookAt::InternalConstructor(void *)
//   0x53c480  public: static void __cdecl UInterpTrackInstStretchAnimControl::InternalConstructor(void *)
//   0x53c4a0  public: static void __cdecl UInterpTrackAIControlKeyProperties::InternalConstructor(void *)
//   0x53c4c0  public: static void __cdecl UInterpTrackLocomotionKeyProperties::InternalConstructor(void *)
//   0x53c4e0  public: static void __cdecl UInterpTrackAIControlBodyIntentionKeyProperties::InternalConstructor(void *)
//   0x53c500  public: static void __cdecl UInterpTrackAIControlNPCAimKeyProperties::InternalConstructor(void *)
//   0x53c520  public: static void __cdecl UInterpTrackAIControlNPCFireKeyProperties::InternalConstructor(void *)
//   0x53c540  public: static void __cdecl UInterpTrackAttachmentKeyProperties::InternalConstructor(void *)
//   0x53c560  public: static void __cdecl UInterpTrackFaceToKeyProperties::InternalConstructor(void *)
//   0x53c580  public: static void __cdecl UInterpTrackSoireeControlKeyProperties::InternalConstructor(void *)
//   0x53c5a0  public: static void __cdecl UInterpTrackStretchAnimKeyProperties::InternalConstructor(void *)
//   0x5418d0  protected: virtual __thiscall UInterpGroupPlayer::~UInterpGroupPlayer(void)
//   0x5444f0  public: static void __cdecl UInterpGroupPlayer::InternalConstructor(void *)
//   0x544520  protected: virtual __thiscall UInterpGroupInstPlayer::~UInterpGroupInstPlayer(void)
//   0x5445b0  protected: virtual __thiscall UInterpTrackInstSoireeControl::~UInterpTrackInstSoireeControl(void)
//   0x5469f0  public: static void __cdecl UInterpGroupInstPlayer::InternalConstructor(void *)
//   0x546a10  public: static void __cdecl UInterpTrackInstSoireeControl::InternalConstructor(void *)
//   0x5485e0  protected: virtual __thiscall UInterpTrackAIControl::~UInterpTrackAIControl(void)
//   0x548690  protected: virtual __thiscall UInterpTrackAttachment::~UInterpTrackAttachment(void)
//   0x548740  protected: virtual __thiscall UInterpTrackFaceTo::~UInterpTrackFaceTo(void)
//   0x5487f0  protected: virtual __thiscall UInterpTrackLocomotion::~UInterpTrackLocomotion(void)
//   0x5488b0  protected: virtual __thiscall UInterpTrackLookAt::~UInterpTrackLookAt(void)
//   0x548960  protected: virtual __thiscall UInterpTrackStretchAnimControl::~UInterpTrackStretchAnimControl(void)
//   0x548a10  protected: virtual __thiscall UInterpTrackSoireeControl::~UInterpTrackSoireeControl(void)
//   0x548c00  public: static void __cdecl UInterpTrackAIControl::InternalConstructor(void *)
//   0x548c40  public: static void __cdecl UInterpTrackAttachment::InternalConstructor(void *)
//   0x548c80  public: static void __cdecl UInterpTrackFaceTo::InternalConstructor(void *)
//   0x548cc0  public: static void __cdecl UInterpTrackLocomotion::InternalConstructor(void *)
//   0x548d00  public: static void __cdecl UInterpTrackLookAt::InternalConstructor(void *)
//   0x548d40  public: static void __cdecl UInterpTrackStretchAnimControl::InternalConstructor(void *)
//   0x548d80  public: static void __cdecl UInterpTrackSoireeControl::InternalConstructor(void *)
//   0x5f4ce0  protected: virtual __thiscall UInterpTrackAkEventKeyProperties::~UInterpTrackAkEventKeyProperties(void)
//   0x5f5cf0  public: static void __cdecl UInterpTrackAkEventKeyProperties::InternalConstructor(void *)
