// AkAudioLayouts.h - compile-time layout checks of the retail (2013) AkAudio classes and script structs:
// sizeof = retail descriptor (native_class_sizes.csv) / retail struct size, member offsets = the offsets the retail
// UStruct::Link computed (CodeRed SDK dump). Generated by resources/tools/symbols/gen_classes_header.py --sdk.
// `pending` lines are known mismatches listed in <Module>Layouts.pending.txt (base classes not converged yet, ...).
// DISHONORED_SDK_LAYOUT_CHECKS (root CMakeLists.txt, per module target) turns them on independently of the Core/Engine PDB asserts.
#pragma once
#if DISHONORED_LAYOUT_CHECKS || DISHONORED_SDK_LAYOUT_CHECKS
#include <cstddef>

static_assert(sizeof(AAkAmbientSound) == 608, "AAkAmbientSound: retail sizeof 608");
static_assert(offsetof(AAkAmbientSound, PlayEvent) == 592, "AAkAmbientSound::PlayEvent: retail offset 592");
static_assert(offsetof(AAkAmbientSound, m_bEnded) == 596, "AAkAmbientSound::m_bEnded: retail offset 596");
static_assert(sizeof(AAkAmbientSoundMovable) == 608, "AAkAmbientSoundMovable: retail sizeof 608");
static_assert(sizeof(FAkEventTrackKey) == 12, "FAkEventTrackKey: retail sizeof 12");
static_assert(offsetof(FAkEventTrackKey, Time) == 0, "FAkEventTrackKey::Time: retail offset 0");
static_assert(offsetof(FAkEventTrackKey, Event) == 4, "FAkEventTrackKey::Event: retail offset 4");
static_assert(offsetof(FAkEventTrackKey, Properties) == 8, "FAkEventTrackKey::Properties: retail offset 8");
static_assert(sizeof(FAkPlayingRadius) == 8, "FAkPlayingRadius: retail sizeof 8");
static_assert(offsetof(FAkPlayingRadius, m_PlayingID) == 0, "FAkPlayingRadius::m_PlayingID: retail offset 0");
static_assert(offsetof(FAkPlayingRadius, m_Radius) == 4, "FAkPlayingRadius::m_Radius: retail offset 4");
static_assert(sizeof(UActorFactoryAkAmbientSound) == 92, "UActorFactoryAkAmbientSound: retail sizeof 92");
static_assert(offsetof(UActorFactoryAkAmbientSound, AmbientEvent) == 88, "UActorFactoryAkAmbientSound::AmbientEvent: retail offset 88");
static_assert(sizeof(UAkAudioDevice) == 136, "UAkAudioDevice: retail sizeof 136");
static_assert(sizeof(UAkComponent) == 108, "UAkComponent: retail sizeof 108");
static_assert(offsetof(UAkComponent, BoneName) == 84, "UAkComponent::BoneName: retail offset 84");
static_assert(offsetof(UAkComponent, m_PlayingRadii) == 96, "UAkComponent::m_PlayingRadii: retail offset 96");
static_assert(sizeof(UInterpTrackAkEvent) == 136, "UInterpTrackAkEvent: retail sizeof 136");
static_assert(offsetof(UInterpTrackAkEvent, AkEvents) == 124, "UInterpTrackAkEvent::AkEvents: retail offset 124");
static_assert(sizeof(UInterpTrackAkRTPC) == 156, "UInterpTrackAkRTPC: retail sizeof 156");
static_assert(offsetof(UInterpTrackAkRTPC, Param) == 144, "UInterpTrackAkRTPC::Param: retail offset 144");
static_assert(sizeof(UInterpTrackInstAkEvent) == 84, "UInterpTrackInstAkEvent: retail sizeof 84");
static_assert(offsetof(UInterpTrackInstAkEvent, m_lStartedAkEvent) == 64, "UInterpTrackInstAkEvent::m_lStartedAkEvent: retail offset 64");
static_assert(offsetof(UInterpTrackInstAkEvent, LastUpdatePosition) == 76, "UInterpTrackInstAkEvent::LastUpdatePosition: retail offset 76");
static_assert(sizeof(UInterpTrackInstAkRTPC) == 64, "UInterpTrackInstAkRTPC: retail sizeof 64");
static_assert(sizeof(USeqAct_AkClearBanks) == 248, "USeqAct_AkClearBanks: retail sizeof 248");
static_assert(sizeof(USeqAct_AkLoadBank) == 276, "USeqAct_AkLoadBank: retail sizeof 276");
static_assert(offsetof(USeqAct_AkLoadBank, Bank) == 268, "USeqAct_AkLoadBank::Bank: retail offset 268");
static_assert(offsetof(USeqAct_AkLoadBank, Signal) == 272, "USeqAct_AkLoadBank::Signal: retail offset 272");
static_assert(sizeof(USeqAct_AkPostEvent) == 280, "USeqAct_AkPostEvent: retail sizeof 280");
static_assert(offsetof(USeqAct_AkPostEvent, Signal) == 264, "USeqAct_AkPostEvent::Signal: retail offset 264");
static_assert(offsetof(USeqAct_AkPostEvent, m_pAudioSystem) == 268, "USeqAct_AkPostEvent::m_pAudioSystem: retail offset 268");
static_assert(offsetof(USeqAct_AkPostEvent, Event) == 276, "USeqAct_AkPostEvent::Event: retail offset 276");
static_assert(sizeof(USeqAct_AkPostTrigger) == 260, "USeqAct_AkPostTrigger: retail sizeof 260");
static_assert(offsetof(USeqAct_AkPostTrigger, Trigger) == 248, "USeqAct_AkPostTrigger::Trigger: retail offset 248");
static_assert(sizeof(USeqAct_AkSetRTPCValue) == 284, "USeqAct_AkSetRTPCValue: retail sizeof 284");
static_assert(offsetof(USeqAct_AkSetRTPCValue, Param) == 264, "USeqAct_AkSetRTPCValue::Param: retail offset 264");
static_assert(offsetof(USeqAct_AkSetRTPCValue, Value) == 276, "USeqAct_AkSetRTPCValue::Value: retail offset 276");
static_assert(sizeof(USeqAct_AkSetState) == 272, "USeqAct_AkSetState: retail sizeof 272");
static_assert(offsetof(USeqAct_AkSetState, StateGroup) == 248, "USeqAct_AkSetState::StateGroup: retail offset 248");
static_assert(offsetof(USeqAct_AkSetState, State) == 260, "USeqAct_AkSetState::State: retail offset 260");
static_assert(sizeof(USeqAct_AkSetSwitch) == 272, "USeqAct_AkSetSwitch: retail sizeof 272");
static_assert(offsetof(USeqAct_AkSetSwitch, SwitchGroup) == 248, "USeqAct_AkSetSwitch::SwitchGroup: retail offset 248");
static_assert(offsetof(USeqAct_AkSetSwitch, Switch) == 260, "USeqAct_AkSetSwitch::Switch: retail offset 260");
static_assert(sizeof(USeqAct_AkStartAmbientSound) == 248, "USeqAct_AkStartAmbientSound: retail sizeof 248");
static_assert(sizeof(USeqAct_AkStopAll) == 248, "USeqAct_AkStopAll: retail sizeof 248");
#endif // DISHONORED_LAYOUT_CHECKS || DISHONORED_SDK_LAYOUT_CHECKS
