#pragma once
// AkAudio/inc/akaudioclasses.h
// Stub created by resources/tools/import_reference.py: this file exists in Dishonored's
// build but not in the reference engine tree. Rewrite it from the decompile (Phase 3).
// PDB functions attributed to this file (32):
//   0x5f6490  protected: virtual __thiscall UActorFactoryAkAmbientSound::~UActorFactoryAkAmbientSound(void)
//   0x5f6e50  public: static void __cdecl UActorFactoryAkAmbientSound::InternalConstructor(void *)
//   0x5f6e70  protected: virtual __thiscall UInterpTrackInstAkEvent::~UInterpTrackInstAkEvent(void)
//   0x5f7840  protected: virtual __thiscall UAkComponent::~UAkComponent(void)
//   0x5f78e0  public: static void __cdecl UInterpTrackInstAkEvent::InternalConstructor(void *)
//   0x5f7be0  protected: virtual __thiscall AAkAmbientSound::~AAkAmbientSound(void)
//   0x5f7c70  protected: virtual __thiscall AAkAmbientSoundMovable::~AAkAmbientSoundMovable(void)
//   0x5f7d00  public: static void __cdecl UAkComponent::InternalConstructor(void *)
//   0x5f7f70  public: static void __cdecl AAkAmbientSound::InternalConstructor(void *)
//   0x5f7fa0  public: static void __cdecl AAkAmbientSoundMovable::InternalConstructor(void *)
//   0x5f8480  protected: virtual __thiscall UInterpTrackAkEvent::~UInterpTrackAkEvent(void)
//   0x5f8530  protected: virtual __thiscall UInterpTrackAkRTPC::~UInterpTrackAkRTPC(void)
//   0x5f8ac0  public: static void __cdecl UInterpTrackAkEvent::InternalConstructor(void *)
//   0x5f8b00  public: static void __cdecl UInterpTrackAkRTPC::InternalConstructor(void *)
//   0x5f9490  protected: virtual __thiscall USeqAct_AkClearBanks::~USeqAct_AkClearBanks(void)
//   0x5f9520  protected: virtual __thiscall USeqAct_AkLoadBank::~USeqAct_AkLoadBank(void)
//   0x5f95b0  protected: virtual __thiscall USeqAct_AkPostEvent::~USeqAct_AkPostEvent(void)
//   0x5f9640  protected: virtual __thiscall USeqAct_AkPostTrigger::~USeqAct_AkPostTrigger(void)
//   0x5f96e0  protected: virtual __thiscall USeqAct_AkSetRTPCValue::~USeqAct_AkSetRTPCValue(void)
//   0x5f9780  protected: virtual __thiscall USeqAct_AkSetState::~USeqAct_AkSetState(void)
//   0x5f9830  protected: virtual __thiscall USeqAct_AkSetSwitch::~USeqAct_AkSetSwitch(void)
//   0x5f98e0  protected: virtual __thiscall USeqAct_AkStartAmbientSound::~USeqAct_AkStartAmbientSound(void)
//   0x5f9970  protected: virtual __thiscall USeqAct_AkStopAll::~USeqAct_AkStopAll(void)
//   0x5fa4d0  public: static void __cdecl USeqAct_AkClearBanks::InternalConstructor(void *)
//   0x5fa4f0  public: static void __cdecl USeqAct_AkLoadBank::InternalConstructor(void *)
//   0x5fa510  public: static void __cdecl USeqAct_AkPostEvent::InternalConstructor(void *)
//   0x5fa530  public: static void __cdecl USeqAct_AkPostTrigger::InternalConstructor(void *)
//   0x5fa550  public: static void __cdecl USeqAct_AkSetRTPCValue::InternalConstructor(void *)
//   0x5fa570  public: static void __cdecl USeqAct_AkSetState::InternalConstructor(void *)
//   0x5fa590  public: static void __cdecl USeqAct_AkSetSwitch::InternalConstructor(void *)
//   0x5fa5b0  public: static void __cdecl USeqAct_AkStartAmbientSound::InternalConstructor(void *)
//   0x5fa5d0  public: static void __cdecl USeqAct_AkStopAll::InternalConstructor(void *)
