"""Write docs/binaries.md: size, SHA-256 and PDB GUID/age for every exe/dll/pdb in both game trees."""
import hashlib
import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TREES = [REPO.parent / "Dishonored_Latest2026" / "Binaries", REPO.parent / "Dishonored_Debug2012" / "Binaries"]
EXTENSIONS = {".exe", ".dll", ".pdb"}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def pe_rsds(path: Path) -> str:
    data = path.read_bytes()
    if data[:2] != b"MZ":
        return ""
    i = data.find(b"RSDS")
    if i == -1:
        return ""
    guid = data[i + 4 : i + 20].hex()
    age = struct.unpack_from("<I", data, i + 20)[0]
    return f"{guid}/{age}"


def pdb_guid(path: Path) -> str:
    data = path.read_bytes()
    return "(see matching exe)" if data[:24].startswith(b"Microsoft C/C++ MSF 7.00") else ""


def main() -> int:
    rows = []
    for tree in TREES:
        for path in sorted(tree.rglob("*")):
            if path.suffix.lower() not in EXTENSIONS or "Redist" in path.parts:
                continue
            rel = path.relative_to(REPO.parent).as_posix()
            ident = pe_rsds(path) if path.suffix.lower() != ".pdb" else pdb_guid(path)
            rows.append((rel, path.stat().st_size, sha256(path), ident))
            print(rel, file=sys.stderr)
    out = REPO / "docs" / "binaries.md"
    with out.open("w", encoding="utf-8") as f:
        f.write("# Binary manifest\n\nGenerated by `tools/hash_binaries.py`. Redist folders excluded.\n\n")
        f.write("| Path | Size | SHA-256 | PDB GUID/age |\n|---|---:|---|---|\n")
        for rel, size, digest, ident in rows:
            f.write(f"| `{rel}` | {size:,} | `{digest}` | `{ident}` |\n")
    print(f"{len(rows)} files -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
