"""P2.6: dump FPackageFileSummary fields of UE3 cooked packages (file version >= 767 layout).

Usage: python resources/tools/pdb/read_package_summary.py <pkg.upk> [...]  [--md resources/docs/symbols/package_summary.md]

Field order follows `operator<<(FArchive&, FPackageFileSummary&)` in the reference UnLinker.cpp:
Tag, FileVersion/LicenseeVersion, TotalHeaderSize, FolderName, PackageFlags, Name/Export/Import
counts+offsets, DependsOffset, ImportExportGuidsOffset/ImportGuidsCount/ExportGuidsCount (>=623),
ThumbnailTableOffset (>=584), Guid, Generations, EngineVersion, CookedContentVersion,
CompressionFlags, CompressedChunks, PackageSource, AdditionalPackagesToCook (>=516),
TextureAllocations (>=767).
"""
import argparse
import struct
import sys
from pathlib import Path

PACKAGE_FILE_TAG = 0x9E2A83C1
PACKAGE_FILE_TAG_SWAPPED = 0xC1832A9E


class Reader:
    def __init__(self, data: bytes):
        self.d = data
        self.o = 0

    def u32(self):
        v = struct.unpack_from("<I", self.d, self.o)[0]
        self.o += 4
        return v

    def i32(self):
        v = struct.unpack_from("<i", self.d, self.o)[0]
        self.o += 4
        return v

    def u16(self):
        v = struct.unpack_from("<H", self.d, self.o)[0]
        self.o += 2
        return v

    def fstring(self):
        n = self.i32()
        if n == 0:
            return ""
        if n < 0:
            s = self.d[self.o : self.o - n * 2].decode("utf-16le", "replace")
            self.o += -n * 2
        else:
            s = self.d[self.o : self.o + n].decode("latin-1")
            self.o += n
        return s.rstrip("\0")

    def guid(self):
        g = self.d[self.o : self.o + 16].hex()
        self.o += 16
        return g


def read_summary(path: Path) -> dict:
    r = Reader(path.read_bytes()[:65536])
    s = {"file": path.name, "tree": path.parts[-4] if len(path.parts) >= 4 else ""}
    tag = r.u32()
    if tag not in (PACKAGE_FILE_TAG, PACKAGE_FILE_TAG_SWAPPED):
        raise ValueError(f"{path}: bad tag 0x{tag:08x}")
    s["tag"] = f"0x{tag:08x}"
    s["file_version"] = r.u16()
    s["licensee_version"] = r.u16()
    v = s["file_version"]
    s["total_header_size"] = r.i32()
    s["folder_name"] = r.fstring()
    s["package_flags"] = f"0x{r.u32():08x}"
    s["name_count"], s["name_offset"] = r.i32(), r.i32()
    s["export_count"], s["export_offset"] = r.i32(), r.i32()
    s["import_count"], s["import_offset"] = r.i32(), r.i32()
    s["depends_offset"] = r.i32()
    if v >= 623:
        s["import_export_guids_offset"], s["import_guids_count"], s["export_guids_count"] = r.i32(), r.i32(), r.i32()
    if v >= 584:
        s["thumbnail_table_offset"] = r.i32()
    s["guid"] = r.guid()
    gen_count = r.i32()
    s["generations"] = [(r.i32(), r.i32(), r.i32()) for _ in range(gen_count)]
    s["engine_version"] = r.i32()
    s["cooked_content_version"] = r.i32()
    s["cooked_content_version_split"] = f"{s['cooked_content_version'] & 0xFFFF} | licensee {(s['cooked_content_version'] >> 16) & 0xFFFF}"
    s["compression_flags"] = f"0x{r.u32():08x}"
    chunk_count = r.i32()
    s["compressed_chunks"] = chunk_count
    r.o += chunk_count * 16
    s["package_source"] = f"0x{r.u32():08x}"
    if v >= 516:
        n = r.i32()
        s["additional_packages_to_cook"] = [r.fstring() for _ in range(n)]
    if v >= 767:
        n = r.i32()
        s["texture_allocation_types"] = n
    s["summary_size"] = r.o
    return s


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("packages", nargs="+")
    ap.add_argument("--md", default=None)
    args = ap.parse_args(argv[1:])
    rows = [read_summary(Path(p)) for p in args.packages]
    keys = ["tree", "file", "file_version", "licensee_version", "engine_version", "cooked_content_version_split", "package_flags", "compression_flags", "compressed_chunks", "name_count", "export_count", "import_count", "total_header_size", "folder_name", "generations", "package_source", "additional_packages_to_cook", "texture_allocation_types", "summary_size", "guid"]
    for s in rows:
        print(" | ".join(f"{k}={s.get(k)}" for k in keys[:11]))
    if args.md:
        out = Path(args.md)
        with out.open("w", encoding="utf-8") as f:
            f.write("# Package summaries\n\nGenerated by `resources/tools/pdb/read_package_summary.py`. These values pin `UnObjVer.cpp` (P2.6).\n\n")
            f.write("| " + " | ".join(keys) + " |\n|" + "---|" * len(keys) + "\n")
            for s in rows:
                f.write("| " + " | ".join(str(s.get(k, "")).replace("|", "\\|") for k in keys) + " |\n")
        print(f"-> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
